#This file was automatically generated by oml2-scaffold V2.12.0pre.79-58cf-dirty
 #for infrastructure_monitoring version 1.0.0.
 
require "oml4r"

# Define Measurement Point(s)
#-----------------------------------------------------------------------#

class USED_MEMORY_MP < OML4R::MPBase
 name :used_memory
 param :used_memory, {:type => :double, :relation => "{omn-monitoring-data:SimpleMeasurement|omn-monitoring:isMeasurementOf|omn-monitoring-metric:UsedMemory}{omn-monitoring-metric:UsedMemory|omn-monitoring:isMeasurementMetricOf|omn-domain-pc:PC}{omn-monitoring-metric:UsedMemory|omn-monitoring-data:hasMeasurementData|omn-monitoring-data:MeasurementData}{omn-monitoring-data:MeasurementData|omn-monitoring-data:hasMeasurementDataValue|%value%}{omn-monitoring-data:MeasurementData|omn-monitoring:hasUnit|omn-monitoring-unit:Byte}{omn-monitoring-unit:Byte|omn-monitoring-unit:hasPrefix|omn-monitoring-unit:giga}"}
 param :timestamp, {:type => :datetime, :relation => "{omn-monitoring-data:MeasurementData|omn-monitoring-data:hasTimestamp|%value%}"}
 param :physicalresource, {:type => :string, :relation => "{omn-domain-pc:PC|rdfs:label|%value%}"}
 param :virtualresource, {:type => :string, :relation => "{omn-domain-pc:VM|rdfs:label|%value%}{omn-domain-pc:VM|omn-lifecycle:childOf|omn-domain-pc:PC}"}
end

class TOTAL_MEMORY_MP < OML4R::MPBase
 name :total_memory
 param :total_memory, {:type => :double, :relation => "{omn-monitoring-data:SimpleMeasurement|omn-monitoring:isMeasurementOf|omn-monitoring-metric:TotalMemory}{omn-monitoring-metric:TotalMemory|omn-monitoring:isMeasurementMetricOf|omn-domain-pc:PC}{omn-monitoring-metric:TotalMemory|omn-monitoring-data:hasMeasurementData|omn-monitoring-data:MeasurementData}{omn-monitoring-data:MeasurementData|omn-monitoring-data:hasMeasurementDataValue|%value%}{omn-monitoring-data:MeasurementData|omn-monitoring:hasUnit|omn-monitoring-unit:Byte}{omn-monitoring-unit:Byte|omn-monitoring-unit:hasPrefix|omn-monitoring-unit:giga}"}
 param :timestamp, {:type => :datetime, :relation => "{omn-monitoring-data:MeasurementData|omn-monitoring-data:hasTimestamp|%value%}"}
 param :physicalresource, {:type => :string, :relation => "{omn-domain-pc:PC|rdfs:label|%value%}"}
 param :virtualresource, {:type => :string, :relation => "{omn-domain-pc:VM|rdfs:label|%value%}{omn-domain-pc:VM|omn-lifecycle:childOf|omn-domain-pc:PC}"}
end

class AVAILABLE_MEMORY_MP < OML4R::MPBase
 name :available_memory
 param :available_memory, {:type => :double, :relation => "{omn-monitoring-data:SimpleMeasurement|omn-monitoring:isMeasurementOf|omn-monitoring-metric:AvailableMemory}{omn-monitoring-metric:AvailableMemory|omn-monitoring:isMeasurementMetricOf|omn-domain-pc:PC}{omn-monitoring-metric:AvailableMemory|omn-monitoring-data:hasMeasurementData|omn-monitoring-data:MeasurementData}{omn-monitoring-data:MeasurementData|omn-monitoring-data:hasMeasurementDataValue|%value%}{omn-monitoring-data:MeasurementData|omn-monitoring:hasUnit|omn-monitoring-unit:Byte}{omn-monitoring-unit:Byte|omn-monitoring-unit:hasPrefix|omn-monitoring-unit:giga}"}
 param :timestamp, {:type => :datetime, :relation => "{omn-monitoring-data:MeasurementData|omn-monitoring-data:hasTimestamp|%value%}"}
 param :physicalresource, {:type => :string, :relation => "{omn-domain-pc:PC|rdfs:label|%value%}"}
 param :virtualresource, {:type => :string, :relation => "{omn-domain-pc:VM|rdfs:label|%value%}{omn-domain-pc:VM|omn-lifecycle:childOf|omn-domain-pc:PC}"}
end

class USED_BANDWIDTH_MP < OML4R::MPBase
 name :used_bandwidth
 param :used_bandwidth, {:type => :double, :relation => "{omn-monitoring-data:SimpleMeasurement|omn-monitoring:isMeasurementOf|omn-monitoring-metric:UsedBandwidth}{omn-monitoring-metric:UsedBandwidth|omn-monitoring:isMeasurementMetricOf|omn-domain-pc:PC}{omn-monitoring-metric:UsedBandwidth|omn-monitoring-data:hasMeasurementData|omn-monitoring-data:MeasurementData}{omn-monitoring-data:MeasurementData|omn-monitoring-data:hasMeasurementDataValue|%value%}{omn-monitoring-data:MeasurementData|omn-monitoring:hasUnit|omn-monitoring-unit:bitpersecond}{omn-monitoring-unit:bitpersecond|omn-monitoring-unit:hasPrefix|omn-monitoring-unit:mega}"}
 param :timestamp, {:type => :datetime, :relation => "{omn-monitoring-data:MeasurementData|omn-monitoring-data:hasTimestamp|%value%}"}
 param :physicalresource, {:type => :string, :relation => "{omn-domain-pc:PC|rdfs:label|%value%}"}
 param :virtualresource, {:type => :string, :relation => "{omn-domain-pc:VM|rdfs:label|%value%}{omn-domain-pc:VM|omn-lifecycle:childOf|omn-domain-pc:PC}"}
end

class AVAILABILITY_MP < OML4R::MPBase
 name :availability
 param :availability, {:type => :double, :relation => "{omn-monitoring-data:SimpleMeasurement|omn-monitoring:isMeasurementOf|omn-monitoring-metric:Availability}{omn-monitoring-metric:Availability|omn-monitoring:isMeasurementMetricOf|omn-domain-pc:PC}{omn-monitoring-metric:Availability|omn-monitoring-data:hasMeasurementData|omn-monitoring-data:MeasurementData}{omn-monitoring-data:MeasurementData|omn-monitoring-data:hasMeasurementDataValue|%value%}"}
 param :timestamp, {:type => :datetime, :relation => "{omn-monitoring-data:MeasurementData|omn-monitoring-data:hasTimestamp|%value%}"}
 param :physicalresource, {:type => :string, :relation => "{omn-domain-pc:PC|rdfs:label|%value%}"}
 param :virtualresource, {:type => :string, :relation => "{omn-domain-pc:VM|rdfs:label|%value%}{omn-domain-pc:VM|omn-lifecycle:childOf|omn-domain-pc:PC}"}
end

class CPU_LOAD_MP < OML4R::MPBase
 name :cpu_load
 param :cpu_load, {:type => :double, :relation => "{omn-monitoring-data:SimpleMeasurement|omn-monitoring:isMeasurementOf|omn-monitoring-metric:CPULoad}{omn-monitoring-metric:CPULoad|omn-monitoring:isMeasurementMetricOf|omn-domain-pc:PC}{omn-monitoring-metric:CPULoad|omn-monitoring-data:hasMeasurementData|omn-monitoring-data:MeasurementData}{omn-monitoring-data:MeasurementData|omn-monitoring-data:hasMeasurementDataValue|%value%}"}
 param :timestamp, {:type => :datetime, :relation => "{omn-monitoring-data:MeasurementData|omn-monitoring-data:hasTimestamp|%value%}"}
 param :physicalresource, {:type => :string, :relation => "{omn-domain-pc:PC|rdfs:label|%value%}"}
 param :virtualresource, {:type => :string, :relation => "{omn-domain-pc:VM|rdfs:label|%value%}{omn-domain-pc:VM|omn-lifecycle:childOf|omn-domain-pc:PC}"}
end


#-----------------------------------------------------------------------#

#write code here

