/*
 * This file was automatically generated by oml2-scaffold V2.12.0pre.79-58cf-dirty
 * for infrastructure_monitoring version 1.0.0.
 * Please do not edit.
 */

#ifndef INFRASTRUCTURE_MONITORING_OPTS_H
#define INFRASTRUCTURE_MONITORING_OPTS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  char* pm;
  char* vm;
  char* link;
  double used_memory;
  char* used_memory_timestamp;
  double total_memory;
  char* total_memory_timestamp;
  double available_memory;
  char* available_memory_timestamp;
  double free_memory;
  char* free_memory_timestamp;
  double catched_memory;
  char* catched_memory_timestamp;
  double buffers_memory;
  char* buffers_memory_timestamp;
  double used_swap;
  char* used_swap_timestamp;
  double used_bandwidth;
  char* used_bandwidth_timestamp;
  double cpu_idle;
  char* cpu_idle_timestamp;
  double cpu_nice;
  char* cpu_nice_timestamp;
  double cpu_iowait;
  char* cpu_iowait_timestamp;
  int availability;
  char* availability_timestamp;
  double cpu_load;
  char* cpu_load_timestamp;
  double free_swap;
  char* free_swap_timestamp;
  double cpu_user;
  char* cpu_user_timestamp;
  double total_swap;
  char* total_swap_timestamp;
  double cpu_system;
  char* cpu_system_timestamp;
  double disk_ioread;
  char* disk_ioread_timestamp;
  double free_disk_space;
  char* free_disk_space_timestamp;
  double used_disk_space;
  char* used_disk_space_timestamp;
  double packet_loss;
  char* packet_loss_timestamp;
  double delay;
  char* delay_timestamp;

} opts_t;

#ifndef USE_OPTS

opts_t* g_opts;

#else

static opts_t g_opts_storage = {"", "", "", 0., "", 0., "", 0., "", 0., "", 0., "", 0., "", 0., "", 0., "", 0., "", 0., "", 0., "", 0, "", 0., "", 0., "", 0., "", 0., "", 0., "", 0., "", 0., "", 0., "", 0., "", 0., ""};
opts_t* g_opts = &g_opts_storage;

/* Only the file containing the main() function should come through here */

#include <popt.h>

struct poptOption options[] = {
  POPT_AUTOHELP
  { "pm-uri", 0, POPT_ARG_STRING, &g_opts_storage.pm, 0, "URI of monitored physical host"},
  { "vm-uri", 0, POPT_ARG_STRING, &g_opts_storage.vm, 0, "URI of virtual host"},
  { "link-uri", 0, POPT_ARG_STRING, &g_opts_storage.link, 0, "URI of a Link between two nodes"},
  { "used-memory", 0, POPT_ARG_DOUBLE, &g_opts_storage.used_memory, 0, "Check used memory"},
  { "used-memory-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.used_memory_timestamp, 0, "Time of checking"},
  { "total-memory", 0, POPT_ARG_DOUBLE, &g_opts_storage.total_memory, 0, "Check total memory"},
  { "total-memory-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.total_memory_timestamp, 0, "Time of checking"},
  { "available-memory", 0, POPT_ARG_DOUBLE, &g_opts_storage.available_memory, 0, "Check available memory"},
  { "available-memory-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.available_memory_timestamp, 0, "Time of checking"},
  { "free-memory", 0, POPT_ARG_DOUBLE, &g_opts_storage.free_memory, 0, "Check free memory"},
  { "free-memory-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.free_memory_timestamp, 0, "Time of checking"},
  { "catched-memory", 0, POPT_ARG_DOUBLE, &g_opts_storage.catched_memory, 0, "Check catched memory"},
  { "catched-memory-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.catched_memory_timestamp, 0, "Time of checking"},
  { "buffers-memory", 0, POPT_ARG_DOUBLE, &g_opts_storage.buffers_memory, 0, "Check buffers memory"},
  { "buffers-memory-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.buffers_memory_timestamp, 0, "Time of checking"},
  { "used-swap", 0, POPT_ARG_DOUBLE, &g_opts_storage.used_swap, 0, "Check used swap space"},
  { "used-swap-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.used_swap_timestamp, 0, "Time of checking"},
  { "used-bandwidth", 0, POPT_ARG_DOUBLE, &g_opts_storage.used_bandwidth, 0, "Check used bandwidth"},
  { "used-bandwidth-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.used_bandwidth_timestamp, 0, "Time of checking"},
  { "cpu-idle", 0, POPT_ARG_DOUBLE, &g_opts_storage.cpu_idle, 0, "Check CPU Idle"},
  { "cpu-idle-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.cpu_idle_timestamp, 0, "Time of checking"},
  { "cpu-nice", 0, POPT_ARG_DOUBLE, &g_opts_storage.cpu_nice, 0, "Check CPU Nice"},
  { "cpu-nice-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.cpu_nice_timestamp, 0, "Time of checking"},
  { "cpu-iowait", 0, POPT_ARG_DOUBLE, &g_opts_storage.cpu_iowait, 0, "Check CPU IOwait"},
  { "cpu-iowait-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.cpu_iowait_timestamp, 0, "Time of checking"},
  { "availability", 0, POPT_ARG_INT, &g_opts_storage.availability, 0, "Check if a VM is available"},
  { "availability-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.availability_timestamp, 0, "Time of checking"},
  { "cpu-load", 0, POPT_ARG_DOUBLE, &g_opts_storage.cpu_load, 0, "Check CPU Load"},
  { "cpu-load-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.cpu_load_timestamp, 0, "Time of checking"},
  { "free-swap", 0, POPT_ARG_DOUBLE, &g_opts_storage.free_swap, 0, "Check Free Swap"},
  { "free-swap-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.free_swap_timestamp, 0, "Time of checking"},
  { "cpu-user", 0, POPT_ARG_DOUBLE, &g_opts_storage.cpu_user, 0, "Check CPU User"},
  { "cpu-user-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.cpu_user_timestamp, 0, "Time of checking"},
  { "total-swap", 0, POPT_ARG_DOUBLE, &g_opts_storage.total_swap, 0, "Check Total Swap"},
  { "total-swap-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.total_swap_timestamp, 0, "Time of checking"},
  { "cpu-system", 0, POPT_ARG_DOUBLE, &g_opts_storage.cpu_system, 0, "Check CPU System"},
  { "cpu-system-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.cpu_system_timestamp, 0, "Time of checking"},
  { "disk-ioread", 0, POPT_ARG_DOUBLE, &g_opts_storage.disk_ioread, 0, "Check Disk IO read"},
  { "disk-ioread-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.disk_ioread_timestamp, 0, "Time of checking"},
  { "free-disk-space", 0, POPT_ARG_DOUBLE, &g_opts_storage.free_disk_space, 0, "Check Free Disk Space"},
  { "free-disk-space-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.free_disk_space_timestamp, 0, "Time of checking"},
  { "used-disk-space", 0, POPT_ARG_DOUBLE, &g_opts_storage.used_disk_space, 0, "Check Used Disk Space"},
  { "used-disk-space-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.used_disk_space_timestamp, 0, "Time of checking"},
  { "packet-loss", 0, POPT_ARG_DOUBLE, &g_opts_storage.packet_loss, 0, "Check Packet Loss"},
  { "packet-loss-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.packet_loss_timestamp, 0, "Time of checking"},
  { "delay", 0, POPT_ARG_DOUBLE, &g_opts_storage.delay, 0, "Check Delay"},
  { "delay-timestamp", 0, POPT_ARG_STRING, &g_opts_storage.delay_timestamp, 0, "Time of checking"},

  { NULL, 0, 0, NULL, 0 }
};

#endif /* USE_OPTS */

#ifdef __cplusplus
}
#endif

#endif /* INFRASTRUCTURE_MONITORING_OPTS_H */
