/*
 * This file was automatically generated by oml2-scaffold V2.12.0pre.79-58cf-dirty
 * for /home/ubuntu/soml/example/liboml2/generator version 1.0.0.
 * Please do not edit.
 */

#ifndef /HOME/UBUNTU/SOML/EXAMPLE/LIBOML2/GENERATOR_OPTS_H
#define /HOME/UBUNTU/SOML/EXAMPLE/LIBOML2/GENERATOR_OPTS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  int loop;
  int delay;
  unsigned int varuint32;
  int varint64;
  unsigned int varuint64;
  int varboolean;
  double vardouble;
  int varint32;
  int varlong;
  char* varstring;

} opts_t;

#ifndef USE_OPTS

opts_t* g_opts;

#else

static opts_t g_opts_storage = {0, 0, 0, 0, 0, 0, 0., 0, 0, ""};
opts_t* g_opts = &g_opts_storage;

/* Only the file containing the main() function should come through here */

#include <popt.h>

struct poptOption options[] = {
  POPT_AUTOHELP
  { "loop", 'l', POPT_ARG_NONE, &g_opts_storage.loop, 'l', "Create periodic result"},
  { "delay", 'd', POPT_ARG_INT, &g_opts_storage.delay, 'd', "Delay between consecutive measurements", "seconds"},
  { "uint32", 0, POPT_ARG_INT, &g_opts_storage.varuint32, 0, "Command line option of type uint32"},
  { "int64", 0, POPT_ARG_INT, &g_opts_storage.varint64, 0, "Command line option of type int64"},
  { "uint64", 0, POPT_ARG_INT, &g_opts_storage.varuint64, 0, "Command line option of type uint64"},
  { "boolean", 0, POPT_ARG_NONE, &g_opts_storage.varboolean, 0, "Command line option of type boolean"},
  { "double", 0, POPT_ARG_DOUBLE, &g_opts_storage.vardouble, 0, "Command line option of type double"},
  { "int32", 0, POPT_ARG_INT, &g_opts_storage.varint32, 0, "Command line option of type int32"},
  { "long", 0, POPT_ARG_LONG, &g_opts_storage.varlong, 0, "Command line option of type long"},
  { "string", 0, POPT_ARG_STRING, &g_opts_storage.varstring, 0, "Command line option of type string"},

  { NULL, 0, 0, NULL, 0 }
};

#endif /* USE_OPTS */

#ifdef __cplusplus
}
#endif

#endif /* /HOME/UBUNTU/SOML/EXAMPLE/LIBOML2/GENERATOR_OPTS_H */
