oml2: api.c File Reference
api.c File Reference
Implement the user-visible API of OML.
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <assert.h>
#include <sys/time.h>
#include "oml2/oml_filter.h"
#include "oml2/omlc.h"
#include "ocomm/o_log.h"
#include "oml_value.h"
#include "validate.h"
#include "mem.h"
#include "client.h"
#include "buffered_writer.h"
Functions
void omlc_process (OmlMP *mp, OmlValueU *values)
int omlc_inject (OmlMP *mp, OmlValueU *values)
int omlc_inject_metadata (OmlMP *mp, const char *key, const OmlValueU *value, OmlValueT type, const char *fname)
Variables
OmlMP * schema0
Detailed Description
Implement the user-visible API of OML.
Definition in file api.c.
Function Documentation
int omlc_inject (OmlMP * mp, OmlValueU * values)
Inject a measurement sample into a Measurement Point.
Parameters
mp pointer to OmlMP into which the new sample is being injected
values an array of OmlValueU to be processed
Returns
0 on success, <0 otherwise
The values' types is assumed to be the same as what was passed to omlc_add_mp Type information is stored in (stored in mp->param_defs[].param_types)
Traverse the list of MSs attached to this MP and, for each MS, the list of filters to apply to the sample. Input the relevant field of the MP to each filter, the call omlc_ms_process() to determine whether a new sample has to be output on that MS.
The content of values is deep-copied into the MSs' storage, so values can be directly freed/reused when inject returns.
This function might call omlc_inject_client_instr which in turns calls omlc_inject. We make sure not to loop.
See Also
omlc_add_mp, omlc_ms_process, oml_value_set, omlc_inject_client_instr
Definition at line 149 of file api.c.
References OmlWriter::bufferedWriter, bw_nlost_reset(), OmlClient::client_instr, OmlMStream::dropped, OmlMStream::filters, OmlFilter::index, OmlFilter::input, OmlClient::instr_interval, OmlClient::instr_time, LOGDEBUG, logerror(), logwarn(), mp_lock(), mp_unlock(), OmlMP::name, OmlFilter::next, OmlMStream::next, OmlMStream::nwriters, oml_value_init(), oml_value_reset(), oml_value_set(), omlc_instance, OmlMP::param_defs, OmlMPDef::param_types, OmlClient::start_time, OmlMP::streams, OmlMStream::table_name, OmlMStream::writers, OmlMStream::written, xmaxbytes(), xmembytes(), xmemfreed(), and xmemnew().
Referenced by main(), omlc_inject_metadata(), omlc_process(), run(), and START_TEST().
{
  OmlMStream* ms;
  OmlValue v;
  int i;
  if (NULL == omlc_instance || omlc_instance->start_time <= 0) {
    logerror("Cannot inject samples prior to calling omlc_init and omlc_start\n");
    return -1;
  }
  if (mp == NULL || values == NULL) {
    return -1;
  }
  LOGDEBUG("Injecting data into MP '%s'\n", mp->name);
  oml_value_init(&v);
  if (mp_lock(mp) == -1) {
    logwarn("Cannot lock MP '%s' for injection\n", mp->name);
    return -1;
  }
  uint64_t written = 0;
  uint64_t dropped = 0;
  for (ms = mp->streams; ms; ms = ms->next) {
    LOGDEBUG("Filtering MP '%s' data into MS '%s'\n", mp->name, ms->table_name);
    OmlFilter* f = ms->filters;
    for (; f != NULL; f = f->next) {
      /* FIXME:  Should validate this indexing */
      oml_value_set(&v, &values[f->index], mp->param_defs[f->index].param_types);
      f->input(f, &v);
    }
    omlc_ms_process(ms);
    written += ms->written;
    dropped += ms->dropped;
    for (i=0; i<ms->nwriters; i++) {
      dropped += bw_nlost_reset(ms->writers[i]->bufferedWriter);
    }
  }
  mp_unlock(mp);
  oml_value_reset(&v);
  /* do we need to send client instrumentation? */
  if(mp != omlc_instance->client_instr && omlc_instance->instr_interval) {
    time_t now;
    time(&now);
    if(omlc_instance->instr_time + omlc_instance->instr_interval <= now) {
      omlc_instance->instr_time = now; /* Make sure we don't loop */
      omlc_inject_client_instr(written, dropped, xmemnew(), xmemfreed(), xmembytes(), xmaxbytes());
    }
  }
  return 0;
}
int omlc_inject_metadata (OmlMP * mp, const char * key, const OmlValueU * value, OmlValueT type, const char * fname)
Inject metadata (key/value) for a specific MP.
Parameters
mp pointer to the OmlMP to which the metadata relates
key base name for the key (keys are unique)
value OmlValueU containing the value for the given key
type OmlValueT of value, currently only OML_STRING_VALUE is valid
fname optional field name to which this metadata relates
Returns
0 on success, -1 otherwise
See Also
omlc_add_mp
Definition at line 218 of file api.c.
References OmlClient::app_name, find_mp_field(), logdebug(), logerror(), logwarn(), mstring_buf(), mstring_create(), mstring_delete(), mstring_set(), mstring_sprintf(), OmlMP::name, OML_STRING_VALUE, omlc_copy_string, omlc_inject(), omlc_instance, omlc_reset_string, omlc_set_string, omlc_zero_array, OmlClient::start_time, and validate_name().
Referenced by main(), omlc_add_mp(), run(), and START_TEST().
{
  int ret = -1;
  OmlValueU v[3];
  omlc_zero_array(v, 3);
  MString *subject = mstring_create();
  if (NULL == omlc_instance || omlc_instance->start_time <= 0) {
    logerror("Cannot inject metadata prior to calling omlc_init and omlc_start\n");
  } else if (!key || !value) {
    logwarn("Trying to inject metadata with missing key and/or value\n");
  } else if (! validate_name(key)) {
    logerror("%s is an invalid metadata key name\n", key);
  } else if (type != OML_STRING_VALUE) {
    logwarn("Currently, only OML_STRING_VALUE are valid as metadata value\n");
  } else {
    mstring_set (subject, ".");
    if(NULL == mp) {
      logdebug("%s: supplied MP is NULL, assuming experiment metadata\n",
          __FUNCTION__);
    } else {
      /* XXX: At the moment, MS are named as APPNAME_MPNAME.
       * Be consistent with it here, until #1055 is addressed */
      mstring_sprintf(subject, "%s_%s", omlc_instance->app_name, mp->name);
      if (fname) {
        if (find_mp_field(fname, mp) < 0) {
          logwarn("Field %s not found in MP %s, not reporting\n", fname, mp->name);
        } else {
          mstring_sprintf(subject, ".%s", fname);
        }
      }
    }
    omlc_set_string(v[0], mstring_buf(subject));
    omlc_set_string(v[1], key);
    omlc_copy_string(v[2], *value);
    omlc_inject(schema0, v);
    omlc_reset_string(v[0]);
    omlc_reset_string(v[1]);
    omlc_reset_string(v[2]);
    mstring_delete(subject);
    ret = 0;
  }
  return ret;
}
void omlc_process (OmlMP * mp, OmlValueU * values)
DEPRECATED
See Also
omlc_inject
Definition at line 120 of file api.c.
References logwarn(), and omlc_inject().
{
  logwarn("'omlc_process' is deprecated, use 'omlc_inject' instead\n");
  omlc_inject(mp, values);
}
Variable Documentation
OmlMP* schema0
Definition at line 50 of file init.c.