oml2: base64.c File Reference
base64.c File Reference
Source code for converting to/from BASE64 format (used for binary marshalling of blobs.
#include "base64.h"
#include <assert.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <sys/types.h>
Functions
size_t base64_size_string (size_t blob_sz)
size_t base64_encode_blob (size_t blob_sz, const void *blob, char *s)
ssize_t base64_validate_string (const char *s)
size_t base64_size_blob (size_t s_sz)
ssize_t base64_decode_string (size_t s_sz, const char *s, size_t blob_sz, void *blob)
Detailed Description
Source code for converting to/from BASE64 format (used for binary marshalling of blobs.
See Also
omspbin).
Definition in file base64.c.
Function Documentation
ssize_t base64_decode_string (size_t s_sz, const char * s, size_t blob_sz, void * blob)
Decode a BASE64-encoded string into a blob.
You must call base64_validate_string(const char*) on the string before calling this function (it will tell you the correct value for s_sz and ensures the string is valid).
Parameters
s_sz The size of the unpadded BASE64-encoded string.
s A pointer to the BASE64-encoded string.
blob_sz The size of the output buffer.
blob A pointer to the blob.
Returns
The blob size or -1 if an error occurred.
Definition at line 155 of file base64.c.
Referenced by START_TEST().
{
  uint32_t x;
  size_t i, j;
  uint8_t *p, *begin;
  static const int8_t DECODE[] = {
    -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, 62, -1, -1, -1, 63,
    52, 53, 54, 55, 56, 57, 58, 59,
    60, 61, -1, -1, -1, -1, -1, -1,
    -1,  0, 1,   2,  3, 4,   5,  6,
     7,  8, 9, 10, 11, 12, 13, 14,
    15, 16, 17, 18, 19, 20, 21, 22,
    23, 24, 25, -1, -1, -1, -1, -1,
    -1, 26, 27, 28, 29, 30, 31, 32,
    33, 34, 35, 36, 37, 38, 39, 40,
    41, 42, 43, 44, 45, 46, 47, 48,
    49, 50, 51, -1, -1, -1, -1, -1,
  };
  assert(s_sz == 0 || s);
  assert(blob_sz == 0 || blob);
  p = begin = blob;
  for(i = 0; i < s_sz; i += 4) {
    x = 0;
    for(j = i; j < i + 4 &&  j < s_sz; j++) {
      char c = s[j];
      if(!(0 <= c && c < sizeof(DECODE))) {
        return -1;
      } else if(-1 == DECODE[(int)c]) {
        return -1;
      }
      x <<= 6;
      x |=  DECODE[(int)c];
    }
    switch(j % 4) {
    case 0:
      *p++ = x >> 16;
      *p++ = x >> 8;
      *p++ = x;
      break;
    case 3:
      *p++ = x >> 10;
      *p++ = x >> 2;
      break;
    case 2:
      *p++ = x >> 4;
      break;
    case 1:
      return -1;
    }
  }
  return p - begin;
}
size_t base64_encode_blob (size_t blob_sz, const void * blob, char * s)
Encode a blob as a string using BASE64 encoding.
Note that the output string buffer must be large enough to hold the BASE64-encoded string plus the NUL terminator. You should determine the exact size for the buffer by calling the base64_size_string(size_t) function.
Parameters
blob_sz The size of the input blob.
blob A pointer to the input blob.
s A non-NULL pointer to the output string buffer.
Returns
The size of the encoded string.
Definition at line 58 of file base64.c.
Referenced by START_TEST().
{
  size_t i;
  uint32_t x;
  char *begin = s;
  const uint8_t *p;
  assert(0 == blob_sz || blob);
  assert(s);
  p = blob;
  begin = s;
  for(i = 0; i < blob_sz; i += 3) {
    switch(blob_sz - i) {
    case 1:
      x = p[i] << 16;
      *s++ = BASE64[x >> 18 & 0x3f];
      *s++ = BASE64[x >> 12 & 0x3f];
      *s++ = '=';
      *s++ = '=';
      break;
    case 2:
      x = p[i] << 16 | p[i+1] << 8;
      *s++ = BASE64[x >> 18 & 0x3f];
      *s++ = BASE64[x >> 12 & 0x3f];
      *s++ = BASE64[x >> 6 & 0x3f];
      *s++ = '=';
      break;
    default:
      x = p[i] << 16 | p[i+1] << 8 | p[i+2];
      *s++ = BASE64[x >> 18 & 0x3f];
      *s++ = BASE64[x >> 12 & 0x3f];
      *s++ = BASE64[x >> 6 & 0x3f];
      *s++ = BASE64[x & 0x3f];
      break;
    }
  }
  *s = '\0';
  return s - begin;
}
size_t base64_size_blob (size_t s_sz)
Returns the size of a blob which is encoded using BASE64.
This function takes the unpadded string size (as returned by base64_validate_string(const char*). The size is given by the equation size = in_sz * 3 / 4.
Parameters
s_sz The size of the BASE64-encoded string.
Returns
The size of the blob.
Definition at line 136 of file base64.c.
Referenced by START_TEST().
{
  return s_sz * 3 / 4;
}
size_t base64_size_string (size_t blob_sz)
Return the exact size of the string buffer needed to hold a BASE64-encoded blob of blob_sz bytes.
The string size is given by the equation size = 4 * ⌈ blob_sz / 3 ⌉ for the buffer size 1 extra byte added for the terminating NUL.
Parameters
blob_sz The size of the blob to encode.
Returns
The size of the BASE64 string buffer to hold the blob.
Definition at line 39 of file base64.c.
Referenced by START_TEST().
{
  return 4 * ((blob_sz + 2) / 3) + 1;
}
ssize_t base64_validate_string (const char * s)
Validate a BASE64-encoded string.
A properly formed string will have a length which is a multiple of 4 bytes and all characters will be drawn from the BASE64 character set. Note that the empty string is considered to be a valid BASE64 string.
Parameters
s A non-NULL pointer to the BASE64-encoded string.
Returns
If valid the length of the string minus any padding; otherwise -1.
Definition at line 109 of file base64.c.
Referenced by START_TEST().
{
  size_t s_sz;
  assert(s);
  s_sz = strlen(s);
  if(s_sz % 4 == 0) {
    size_t n = strspn(s, BASE64);
    if((s_sz == n) ||
      (s_sz - 1 == n && '=' == s[n]) ||
      (s_sz - 2 == n && '=' == s[n] && '=' == s[n+1])) {
      return n;
    }
  }
  return -1;
}