oml2: bin_writer.c File Reference
bin_writer.c File Reference
An implementation of the OmlWriter interface functions (see oml2/oml_writer.h) that writes messages using the OML binary protocol OMSP Binary Marshalling.
#include <stdlib.h>
#include <string.h>
#include "oml2/omlc.h"
#include "oml2/oml_writer.h"
#include "oml2/oml_filter.h"
#include "ocomm/o_socket.h"
#include "ocomm/o_log.h"
#include "client.h"
#include "marshal.h"
#include "mbuf.h"
#include "buffered_writer.h"
#include "assert.h"
Data Structures
struct OmlBinWriter
Macros
#define DEF_PROTOCOL "tcp"
#define DEF_PORT 3003
Typedefs
typedef struct OmlBinWriter OmlBinWriter
Functions
OmlWriter * bin_writer_new (OmlOutStream *out_stream)
Detailed Description
An implementation of the OmlWriter interface functions (see oml2/oml_writer.h) that writes messages using the OML binary protocol OMSP Binary Marshalling.
Definition in file bin_writer.c.
Macro Definition Documentation
#define DEF_PORT 3003
Definition at line 30 of file bin_writer.c.
#define DEF_PROTOCOL "tcp"
Definition at line 29 of file bin_writer.c.
Typedef Documentation
typedef struct OmlBinWriter OmlBinWriter
An OmlWriter using the binary marshalling functions OMSP Binary Marshalling
Function Documentation
OmlWriter* bin_writer_new (OmlOutStream * out_stream)
Create a new OmlBinWriter
Parameters
out_stream OmlOutStream into which the data should be written
Returns
a pointer to the new OmlBinWriter cast as an OmlWriter
See Also
BufferedWriter
Definition at line 91 of file bin_writer.c.
References bw_create(), OmlClient::max_queue, OMB_DATA_P, oml_malloc(), and omlc_instance.
Referenced by create_writer().
{
  assert(out_stream != NULL);
  OmlBinWriter* self = (OmlBinWriter *)oml_malloc(sizeof(OmlBinWriter));
  memset(self, 0, sizeof(OmlBinWriter));
  self->bufferedWriter = bw_create(out_stream,
      omlc_instance->max_queue, 0);
  self->out_stream = out_stream;
  self->meta = owb_meta;
  self->header_done = owb_header_done;
  self->row_start = owb_row_start;
  self->row_end = owb_row_end;
  self->out = owb_row_cols;
  self->close = owb_close;
  self->msgtype = OMB_DATA_P; // Short packets.
  return (OmlWriter*)self;
}