oml2: binary.h File Reference
binary.h File Reference
#include <stdint.h>
#include "oml2/omlc.h"
#include "mbuf.h"
#include "schema.h"
#include "message.h"
Functions
int bin_find_sync (MBuffer *mbuf)
size_t bin_value_size (MBuffer *mbuf, OmlValue *value)
int bin_read_msg_start (struct oml_message *msg, MBuffer *mbuf)
int bin_read_msg_values (struct oml_message *msg, MBuffer *mbuf, struct schema *schema, OmlValue *values)
Function Documentation
int bin_find_sync (MBuffer * mbuf)
Find the next sync bytes in an MBuffer, and advance read pointer accordingly if found.
The previous message is also consumed.
Parameters
mbuf MBuffer to look into
Returns
(>=0) offset if found, -1 otherwise (including if there is not enough data in the buffer)
See Also
find_sync, mbuf_read_skip, mbuf_consume_message
Definition at line 48 of file binary.c.
References find_sync(), mbuf_consume_message(), mbuf_rd_remaining(), mbuf_rdptr(), and mbuf_read_skip().
Referenced by bin_read_msg_start(), and START_TEST().
{
  int len, offset = -1;
  uint8_t *buf, *sync_pos;
  len = mbuf_rd_remaining (mbuf);
  if (len < 2) {
    /* Optimisation: get out early */
    return -1;
  }
  buf = mbuf_rdptr (mbuf);
  sync_pos = find_sync(buf, len);
  if (sync_pos) {
    offset = sync_pos - buf;
    mbuf_read_skip (mbuf, offset);
    mbuf_consume_message(mbuf);
  }
  return offset;
}
int bin_read_msg_start (struct oml_message * msg, MBuffer * mbuf)
Definition at line 104 of file binary.c.
References bin_find_sync(), count, oml_message::count, oml_message::length, mbuf_begin_read(), mbuf_rd_remaining(), mbuf_read(), mbuf_read_skip(), MSG_BINARY, OMB_DATA_P, OMB_LDATA_P, OML_DOUBLE_VALUE, OML_INT32_VALUE, oml_value_get_value, oml_value_init(), oml_value_reset(), oml_value_set_type(), omlc_get_double, omlc_get_int32, oml_message::seqno, oml_message::stream, oml_message::timestamp, and oml_message::type.
Referenced by proxy_message_loop(), and START_TEST().
{
  OmlValue value;
  oml_value_init(&value);
  if (msg == NULL || mbuf == NULL)
    return -1;
  /* First, find the sync position */
  int sync_pos = bin_find_sync (mbuf);
  if (sync_pos == -1)
    return -1;
  mbuf_begin_read (mbuf);
  if (mbuf_rd_remaining (mbuf) < 3) {
    return 0; // Not enough data to determine packet type
  }
  mbuf_read_skip (mbuf, 2); // Skip the sync bytes
  uint8_t packet_type;
  uint16_t msglen16;
  uint32_t length;
  uint32_t header_length;
  mbuf_read (mbuf, &packet_type, 1);
  switch (packet_type) {
  case OMB_DATA_P:
    // FIXME:  Return type (maybe not enough bytes)
    mbuf_read (mbuf, (uint8_t*)&msglen16, 2);
    msglen16 = ntohs (msglen16);
    length = (uint32_t)msglen16;
    header_length = 5;
    break;
  case OMB_LDATA_P:
    mbuf_read (mbuf, (uint8_t*)&length, 4);
    length = ntohl (length);
    header_length = 7;
    break;
  default:
    return -1; // Unknown packet type
  }
  if (mbuf_rd_remaining (mbuf) < length)
    return 0; /* Not enough bytes for the full message */
  // Now get the count and index
  uint8_t count;
  uint8_t stream;
  mbuf_read (mbuf, &count, 1);
  mbuf_read (mbuf, &stream, 1);
  msg->type = MSG_BINARY;
  msg->stream = stream;
  msg->length = length + header_length;
  msg->count = count;
  oml_value_set_type(&value, OML_INT32_VALUE);
  // FIXME: check for error (e.g. type mismatch)
  bin_read_value (mbuf, &value);
  msg->seqno = omlc_get_int32(*oml_value_get_value(&value));
  oml_value_set_type(&value, OML_DOUBLE_VALUE);
  // FIXME: check for error (e.g. type mismatch)
  bin_read_value (mbuf, &value);
  msg->timestamp = omlc_get_double(*oml_value_get_value(&value));
  oml_value_reset(&value);
  return msg->length;
}
int bin_read_msg_values (struct oml_message * msg, MBuffer * mbuf, struct schema * schema, OmlValue * values)
Definition at line 182 of file binary.c.
References oml_message::count, mbuf_consume_message(), and schema::nfields.
Referenced by START_TEST().
{
  int i = 0;
  if (msg->count != schema->nfields)
    return -1;
  for (i = 0; i < schema->nfields; i++) {
    int bytes;
    bytes = bin_read_value (mbuf, &values[i]);
    if (bytes == -1)
      return -1;
  }
  mbuf_consume_message (mbuf);
  return 0;
}
size_t bin_value_size (MBuffer * mbuf, OmlValue * value)