oml2: buffered_writer.h File Reference
buffered_writer.h File Reference
#include "oml2/oml_out_stream.h"
#include "oml2/oml_writer.h"
#include "mbuf.h"
Typedefs
typedef void * BufferedWriterHdl
Functions
BufferedWriterHdl bw_create (OmlOutStream *outStream, long queueCapacity, long chainSize)
void bw_close (BufferedWriterHdl instance)
int bw_push (BufferedWriterHdl instance, uint8_t *data, size_t size)
int _bw_push (BufferedWriterHdl instance, uint8_t *data, size_t size)
int bw_push_meta (BufferedWriterHdl instance, uint8_t *data, size_t size)
int _bw_push_meta (BufferedWriterHdl instance, uint8_t *data, size_t size)
int bw_msgcount_add (BufferedWriterHdl instance, int nmessages)
int bw_msgcount_reset (BufferedWriterHdl instance)
int bw_nlost_reset (BufferedWriterHdl instance)
MBuffer * bw_get_write_buf (BufferedWriterHdl instance, int exclusive)
void bw_unlock_buf (BufferedWriterHdl instance)
Typedef Documentation
typedef void* BufferedWriterHdl
Definition at line 21 of file buffered_writer.h.
Function Documentation
int _bw_push (BufferedWriterHdl instance, uint8_t * data, size_t size)
Add some data to the end of the queue (lock must be held).
This function is the same as bw_push except it assumes that the lock is already acquired.
Add some data to the end of the queue.This function tries to acquire the lock on the BufferedWriter, and releases it when done.
Parameters
instance BufferedWriter handle
data Pointer to data to add
size size of data
Returns
1 if success, 0 otherwise
See Also
_bw_push
See Also
bw_push
Definition at line 232 of file buffered_writer.c.
References BufferChunk::mbuf, mbuf_wr_remaining(), and mbuf_write().
Referenced by bw_push().
{
  BufferedWriter* self = (BufferedWriter*)instance;
  if (!self->active) { return 0; }
  BufferChunk* chunk = self->writerChunk;
  if (chunk == NULL) { return 0; }
  if (mbuf_wr_remaining(chunk->mbuf) < size) {
    chunk = getNextWriteChunk(self, chunk);
  }
  if (mbuf_write(chunk->mbuf, data, size) < 0) {
    return 0;
  }
  pthread_cond_signal(&self->semaphore);
  return 1;
}
int _bw_push_meta (BufferedWriterHdl instance, uint8_t * data, size_t size)
Add some data to the end of the header buffer (lock must be held).
This function is the same as bw_push_meta except it assumes that the lock is already acquired.
Add some data to the end of the header buffer.This function tries to acquire the lock on the BufferedWriter, and releases it when done.
Parameters
instance BufferedWriter handle
data Pointer to data to add
size size of data
Returns
1 if success, 0 otherwise
See Also
_bw_push_meta
See Also
bw_push_meta
Definition at line 288 of file buffered_writer.c.
References mbuf_write().
Referenced by bw_push_meta().
{
  BufferedWriter* self = (BufferedWriter*)instance;
  int result = 0;
  if (!self->active) { return 0; }
  if (mbuf_write(self->meta_buf, data, size) > 0) {
    result = 1;
    /* XXX: There is no point in signalling the semaphore as the
     * writer will not be able to do anything with the new data.
     *
     * Also, it puts everything in a deadlock otherwise */
    /* pthread_cond_signal(&self->semaphore); */
  }
  return result;
}
void bw_close (BufferedWriterHdl instance)
Close an output stream and destroy the objects.
Parameters
instance handle (i.e., pointer) to a BufferedWriter
Definition at line 165 of file buffered_writer.c.
References BufferedWriter::active, logdebug(), logerror(), loginfo(), logwarn(), oml_free(), oml_lock(), and oml_unlock().
{
  int *retval;
  BufferedWriter *self = (BufferedWriter*)instance;
  if(!self) { return; }
  if (oml_lock (&self->lock, __FUNCTION__)) { return; }
  self->active = 0;
  loginfo ("%s: Waiting for buffered queue thread to drain...\n", self->outStream->dest);
  pthread_cond_signal (&self->semaphore);
  oml_unlock (&self->lock, __FUNCTION__);
  if(pthread_join (self->readerThread, (void**)&retval)) {
    logwarn ("%s: Cannot join buffered queue reader thread: %s\n",
        self->outStream->dest, strerror(errno));
  } else {
    if (1 == *retval) {
      logdebug ("%s: Buffered queue fully drained\n", self->outStream->dest);
    } else {
      logerror ("%s: Buffered queue did not fully drain\n",
          self->outStream->dest, *retval);
    }
  }
  self->outStream->close(self->outStream);
  destroyBufferChain(self);
  oml_free(self);
}
BufferedWriterHdl bw_create (OmlOutStream * outStream, long queueCapacity, long chunkSize)
Create a BufferedWriter instance
Parameters
outStream opaque OmlOutStream handler
queueCapacity maximal size [B] of the internal queue queueCapaity/chunkSize will be used (at least 2)
chunkSize size [B] of buffer space allocated at a time, set to 0 for default (DEF_CHAIN_BUFFER_SIZE)
Returns
an instance pointer if successful, NULL otherwise
See Also
DEF_CHAIN_BUFFER_SIZE
Definition at line 108 of file buffered_writer.c.
References DEF_CHAIN_BUFFER_SIZE, logdebug(), mbuf_create(), oml_free(), and oml_malloc().
Referenced by bin_writer_new(), and text_writer_new().
{
  long nchunks;
  BufferedWriter* self = NULL;
  assert(outStream>=0);
  assert(queueCapacity>=0);
  assert(chunkSize>=0);
  if((self = (BufferedWriter*)oml_malloc(sizeof(BufferedWriter)))) {
    memset(self, 0, sizeof(BufferedWriter));
    self->outStream = outStream;
    /* This forces a 'connected' INFO message upon first connection */
    self->backoff = 1;
    self->bufSize = chunkSize > 0 ? chunkSize : DEF_CHAIN_BUFFER_SIZE;
    nchunks = queueCapacity / self->bufSize;
    self->unallocatedBuffers = (nchunks > 2) ? nchunks : 2; /* at least two chunks */
    logdebug ("%s: Buffer size %dB (%d chunks of %dB)\n",
        self->outStream->dest,
        self->unallocatedBuffers*self->bufSize,
        self->unallocatedBuffers, self->bufSize);
    if(NULL == (self->writerChunk = self->firstChunk = createBufferChunk(self))) {
      oml_free(self);
      self = NULL;
    } else if(NULL == (self->meta_buf = mbuf_create())) {
      destroyBufferChain(self);
      oml_free(self);
      self = NULL;
    } else {
      /* Initialize mutex and condition variable objects */
      pthread_cond_init(&self->semaphore, NULL);
      pthread_mutex_init(&self->lock, NULL);
      /* Initialize and set thread detached attribute */
      pthread_attr_t tattr;
      pthread_attr_init(&tattr);
      pthread_attr_setdetachstate(&tattr, PTHREAD_CREATE_JOINABLE);
      self->active = 1;
      pthread_create(&self->readerThread, &tattr, threadStart, (void*)self);
    }
  }
  return (BufferedWriterHdl)self;
}
MBuffer* bw_get_write_buf (BufferedWriterHdl instance, int exclusive)
Return an MBuffer with (optional) exclusive write access
If exclusive access is required, the caller is in charge of releasing the lock with bw_unlock_buf.
Parameters
instance BufferedWriter handle
exclusive indicate whether the entire BufferedWriter should be locked
Returns
an MBuffer instance if success to write in, NULL otherwise
See Also
bw_unlock_buf
Definition at line 365 of file buffered_writer.c.
References BufferChunk::mbuf, mbuf_write_offset(), oml_lock(), oml_unlock(), and BufferChunk::targetBufSize.
{
  BufferedWriter* self = (BufferedWriter*)instance;
  if (oml_lock(&self->lock, __FUNCTION__)) { return 0; }
  if (!self->active) { return 0; }
  BufferChunk* chunk = self->writerChunk;
  if (chunk == NULL) { return 0; }
  MBuffer* mbuf = chunk->mbuf;
  if (mbuf_write_offset(mbuf) >= chunk->targetBufSize) {
    chunk = getNextWriteChunk(self, chunk);
    mbuf = chunk->mbuf;
  }
  if (! exclusive) {
    oml_unlock(&self->lock, __FUNCTION__);
  }
  return mbuf;
}
int bw_msgcount_add (BufferedWriterHdl instance, int nmessages)
Count the addition (or deletion) of a full message in the current BufferChunk.
Parameters
instance BufferedWriter handle
nmessages number of messages to count (can be negative)
Returns
the (new) current number of messages in the current writer BufferChunk
See Also
bw_msgcount_reset, bw_nlost_reset
Definition at line 316 of file buffered_writer.c.
References BufferChunk::nmessages, and BufferedWriter::writerChunk.
{
  BufferedWriter* self = (BufferedWriter*)instance;
  self->writerChunk->nmessages += 1;
  return self->writerChunk->nmessages;
}
int bw_msgcount_reset (BufferedWriterHdl instance)
Reset the message count in the current BufferChunk and return its previous value.
Parameters
instance BufferedWriter handle
Returns
the number of messages in the current writer BufferChunk before resetting
See Also
bw_msgcount_add, bw_nlost_reset
Definition at line 331 of file buffered_writer.c.
References BufferChunk::nmessages, and BufferedWriter::writerChunk.
{
  BufferedWriter* self = (BufferedWriter*)instance;
  int n = self->writerChunk->nmessages;
  self->writerChunk->nmessages = 0;
  return n;
}
int bw_nlost_reset (BufferedWriterHdl instance)
Reset the number of messages lost by the BufferedWriter and return its previous value.
Parameters
instance BufferedWriter handle
Returns
the number of lost messages in the BufferedWriter before resetting
See Also
bw_msgcount_add, bw_msgcount_reset
Definition at line 347 of file buffered_writer.c.
References BufferedWriter::nlost.
Referenced by omlc_inject().
{
  BufferedWriter* self = (BufferedWriter*)instance;
  int n = self->nlost;
  self->nlost = 0;
  return n;
}
int bw_push (BufferedWriterHdl instance, uint8_t * data, size_t size)
Add some data to the end of the queue.
This function tries to acquire the lock on the BufferedWriter, and releases it when done.
Parameters
instance BufferedWriter handle
data Pointer to data to add
size size of data
Returns
1 if success, 0 otherwise
See Also
_bw_push
Definition at line 211 of file buffered_writer.c.
References _bw_push(), oml_lock(), and oml_unlock().
{
  int result = 0;
  BufferedWriter* self = (BufferedWriter*)instance;
  if (oml_lock(&self->lock, __FUNCTION__) == 0) {
    result =_bw_push(instance, data, size);
    oml_unlock(&self->lock, __FUNCTION__);
  }
  return result;
}
int bw_push_meta (BufferedWriterHdl instance, uint8_t * data, size_t size)
Add some data to the end of the header buffer.
This function tries to acquire the lock on the BufferedWriter, and releases it when done.
Parameters
instance BufferedWriter handle
data Pointer to data to add
size size of data
Returns
1 if success, 0 otherwise
See Also
_bw_push_meta
Definition at line 266 of file buffered_writer.c.
References _bw_push_meta(), oml_lock(), and oml_unlock().
{
  int result = 0;
  BufferedWriter* self = (BufferedWriter*)instance;
  if (oml_lock(&self->lock, __FUNCTION__) == 0) {
    result = _bw_push_meta(instance, data, size);
    oml_unlock(&self->lock, __FUNCTION__);
  }
  return result;
}
void bw_unlock_buf (BufferedWriterHdl instance)
Return and unlock MBuffer
Parameters
instance BufferedWriter handle for which a buffer was previously obtained through bw_get_write_buf
See Also
bw_get_write_buf
Definition at line 392 of file buffered_writer.c.
References oml_unlock().
{
  BufferedWriter* self = (BufferedWriter*)instance;
  pthread_cond_signal(&self->semaphore); /* assume we locked for a reason */
  oml_unlock(&self->lock, __FUNCTION__);
}