oml2: cbuf.c File Reference
cbuf.c File Reference
A FIFO implementation used by the proxy that uses a circular list of pages to manage the memory.
#include <stdlib.h>
#include <string.h>
#include "mem.h"
#include "cbuf.h"
Macros
#define CBUFFER_DEFAULT_SIZE 1024
Functions
CBuffer * cbuf_create (int default_size)
void cbuf_destroy (CBuffer *cbuf)
int cbuf_add_page (CBuffer *cbuf, int size)
int cbuf_write (CBuffer *cbuf, char *buf, size_t size)
void cbuf_write_cursor (CBuffer *cbuf, struct cbuffer_cursor *cursor)
int cbuf_read_cursor (CBuffer *cbuf, struct cbuffer_cursor *cursor, size_t n)
char * cbuf_cursor_pointer (struct cbuffer_cursor *cursor)
size_t cbuf_cursor_page_remaining (struct cbuffer_cursor *cursor)
int cbuf_advance_cursor (struct cbuffer_cursor *cursor, size_t n)
int cbuf_consume_cursor (struct cbuffer_cursor *cursor, size_t n)
Detailed Description
A FIFO implementation used by the proxy that uses a circular list of pages to manage the memory.
It always writes in the tail buffer and always reads from the read buffer; tail->next points back to the start of the buffer:
*  +------------------------------------------+
*  V                                          |
* [X] -> [X] -> ... [X] -> ... -> [X] -> [X] -+
*                    ^                    ^
*                    |_ read              |_ tail
*
When the tail buffer fills up, add a new one after tail, link the new tail to the head, and keep writing.
To remove a buffer from the head, link the tail to the next one.
Could also implement this as a circular chain where beyond a certain size the chain does not expand, by having an empty flag on the nodes and allowing the tail to process, rather than inserting new nodes at the tail.
Definition in file cbuf.c.
Macro Definition Documentation
#define CBUFFER_DEFAULT_SIZE 1024
Definition at line 40 of file cbuf.c.
Referenced by cbuf_create().
Function Documentation
int cbuf_add_page (CBuffer * cbuf, int size)
Definition at line 87 of file cbuf.c.
References cbuffer_page::buf, cbuffer_page::empty, cbuffer_page::fill, cbuffer_page::next, oml_free(), oml_malloc(), _cbuffer::page_size, cbuffer_page::read, _cbuffer::read, cbuffer_page::size, and _cbuffer::tail.
Referenced by cbuf_create(), and cbuf_write().
{
  struct cbuffer_page *page;
  if (cbuf == NULL)
    return -1;
  if (size <= 0)
    size = cbuf->page_size;
  page = oml_malloc (sizeof (struct cbuffer_page));
  if (page == NULL)
    return -1;
  page->buf = oml_malloc (size);
  if (page->buf == NULL) {
    oml_free (page);
    return -1;
  }
  page->empty = 1;
  page->fill = 0;
  page->size = size;
  page->read = 0;
  page->next = NULL;
  if (cbuf->tail == NULL) {
    cbuf->tail = page;
    cbuf->read = page;
    cbuf->tail->next = cbuf->tail;
  } else {
    struct cbuffer_page *head = cbuf->tail->next;
    cbuf->tail->next = page;
    cbuf->tail = page;
    cbuf->tail->next = head;
  }
  return 0;
}
int cbuf_advance_cursor (struct cbuffer_cursor * cursor, size_t n)
Definition at line 220 of file cbuf.c.
References cbuf_cursor_page_remaining(), count, cbuffer_page::fill, cbuffer_cursor::index, cbuffer_page::next, and cbuffer_cursor::page.
Referenced by client_send_thread().
{
  int count = 0;
  do {
    size_t page_remaining = cbuf_cursor_page_remaining (cursor);
    size_t to_consume = n < page_remaining ? n : page_remaining;
    count += to_consume;
    cursor->index += to_consume;
    n -= to_consume;
    /* If we've read to the end of this page, skip to the next page */
    if (cursor->index == cursor->page->fill) {
      /* Advance to the next page */
      cursor->page = cursor->page->next;
      cursor->index = 0;
    }
  } while (n > 0);
  return count;
}
int cbuf_consume_cursor (struct cbuffer_cursor * cursor, size_t n)
a
Definition at line 245 of file cbuf.c.
References cbuf_cursor_page_remaining(), count, cbuffer_page::empty, cbuffer_page::fill, cbuffer_cursor::index, cbuffer_page::next, cbuffer_cursor::page, and cbuffer_page::read.
Referenced by client_send_thread(), and main().
{
  int count = 0;
  do {
    size_t page_remaining = cbuf_cursor_page_remaining (cursor);
    size_t to_consume = n < page_remaining ? n : page_remaining;
    count += to_consume;
    cursor->index += to_consume;
    n -= to_consume;
    /* If we've read to the end of this page, skip to the next page */
    if (cursor->index == cursor->page->fill) {
      /* Reset the current page to empty */
      cursor->page->empty = 1;
      cursor->page->read = 0;
      cursor->page->fill = 0;
      /* Advance to the next page */
      cursor->page = cursor->page->next;
      cursor->index = 0;
    }
  } while (n > 0);
  cursor->page->read = cursor->index;
  //  cbuf->read = cursor->page; /* Not sure about this */
  return count;
}
CBuffer* cbuf_create (int default_size)
Definition at line 43 of file cbuf.c.
References cbuf_add_page(), CBUFFER_DEFAULT_SIZE, oml_free(), oml_malloc(), and _cbuffer::page_size.
Referenced by client_new(), and START_TEST().
{
  CBuffer *cbuf = NULL;
  if (default_size <= 0)
    default_size = CBUFFER_DEFAULT_SIZE;
  cbuf = oml_malloc (sizeof (CBuffer));
  if (cbuf == NULL)
    return NULL;
  cbuf->page_size = default_size;
  if (cbuf_add_page (cbuf, -1) == -1) {
    oml_free (cbuf);
    return NULL;
  }
  return cbuf;
}
size_t cbuf_cursor_page_remaining (struct cbuffer_cursor * cursor)
Get the number of bytes remaining on the page following the cursor.
Definition at line 210 of file cbuf.c.
References cbuffer_page::fill, cbuffer_cursor::index, and cbuffer_cursor::page.
Referenced by cbuf_advance_cursor(), cbuf_consume_cursor(), client_send_thread(), and main().
{
  return cursor->page->fill - cursor->index;
}
char* cbuf_cursor_pointer (struct cbuffer_cursor * cursor)
Definition at line 200 of file cbuf.c.
References cbuffer_page::buf, cbuffer_cursor::index, and cbuffer_cursor::page.
Referenced by client_send_thread(), and main().
{
  return cursor->page->buf + cursor->index;
}
void cbuf_destroy (CBuffer * cbuf)
Definition at line 65 of file cbuf.c.
References cbuffer_page::buf, cbuffer_page::next, oml_free(), and _cbuffer::tail.
Referenced by client_free().
{
  if (cbuf == NULL)
    return;
  if (cbuf->tail != NULL) {
    struct cbuffer_page *head, *current, *next;
    current = cbuf->tail;
    head = cbuf->tail->next;
    do {
      if (current->buf)
        oml_free (current->buf);
      next = current->next;
      oml_free (current);
      current = next;
    } while (current != NULL && current != head);
  }
  oml_free (cbuf);
}
int cbuf_read_cursor (CBuffer * cbuf, struct cbuffer_cursor * cursor, size_t n)
Get a cursor pointing to the current read position in the buffer chain. Returns the number of bytes between the cursor position and the end of the page the cursor points to.
Definition at line 183 of file cbuf.c.
References cbuffer_page::fill, cbuffer_cursor::index, cbuffer_cursor::page, cbuffer_page::read, and _cbuffer::read.
{
  if (cbuf == NULL || cursor == NULL)
    return -1;
  cursor->page = cbuf->read;
  cursor->index = cursor->page->read;
  size_t remainder = cursor->page->fill - cursor->index;
  if (remainder < n)
    return remainder;
  else
    return n;
}
int cbuf_write (CBuffer * cbuf, char * buf, size_t size)
Definition at line 129 of file cbuf.c.
References cbuffer_page::buf, cbuf_add_page(), count, cbuffer_page::empty, cbuffer_page::fill, cbuffer_page::next, cbuffer_page::size, and _cbuffer::tail.
Referenced by START_TEST(), and store_received_message().
{
  int count = 0;
  if (cbuf == NULL || buf == NULL)
    return -1;
  do {
    struct cbuffer_page *page = cbuf->tail;
    size_t remain = (page->size - page->fill);
    size_t to_write = size < remain ? size : remain;
    memcpy (&page->buf[page->fill], buf + count, to_write);
    page->empty = 0;
    page->fill += to_write;
    count += to_write;
    if (size > to_write) {
      if (page->next->empty) {
        cbuf->tail = page->next;
      } else {
        if (cbuf_add_page (cbuf, -1) == -1) {
          break;
        }
      }
    }
    size -= to_write;
  } while (size > 0);
  return count;
}
void cbuf_write_cursor (CBuffer * cbuf, struct cbuffer_cursor * cursor)
Get a cursor pointing to the current write position in the buffer chain.
Definition at line 167 of file cbuf.c.
References cbuffer_page::fill, cbuffer_cursor::index, cbuffer_cursor::page, and _cbuffer::tail.
Referenced by store_received_message().
{
  if (cbuf == NULL || cursor == NULL)
    return;
  cursor->page = cbuf->tail;
  cursor->index = cursor->page->fill;
}