oml2: check_util.h File Reference
check_util.h File Reference
#include "oml2/omlc.h"
#include "oml2/oml_filter.h"
Data Structures
struct TestVector
struct TestData
Macros
#define LENGTH(a) ((sizeof(a))/(sizeof((a)[0])))
#define MAKEOMLCMDLINE(argc, argv, collect)
Functions
OmlValueU * make_vector (void *v, OmlValueT type, int n)
TestVector * make_test_vector (void *v, OmlValueT type, int n)
int vector_type_check (OmlValue *values, OmlValueT type, int n)
int vector_values_check (OmlValue *values, OmlValueU *expected, OmlValueT type, int n)
void run_filter_test (TestData *test_data, OmlFilter *f)
Macro Definition Documentation
#define LENGTH (a) ((sizeof(a))/(sizeof((a)[0])))
Definition at line 19 of file check_util.h.
#define MAKEOMLCMDLINE (argc, argv, collect)
Value:
const char* argv[] = {                      \
    __FUNCTION__,                             \
    "--oml-id", __FUNCTION__,                 \
    "--oml-domain", __FILE__,                 \
    "--oml-collect", collect,                 \
    "--oml-log-level", "2"};                  \
  int argc = 9;
Definition at line 21 of file check_util.h.
Referenced by START_TEST().
Function Documentation
TestVector* make_test_vector (void * v, OmlValueT type, int n)
Definition at line 84 of file check_util.c.
References TestVector::length, make_vector(), TestVector::type, type, and TestVector::vector.
Referenced by START_TEST().
{
  TestVector* result = (TestVector*)malloc (sizeof (TestVector));
  if (result)
    {
      OmlValueU* oml_v = make_vector (v, type, n);
      if (oml_v)
        {
          memset (result, 0, sizeof (TestVector));
          result->length = n;
          result->type = type;
          result->vector = oml_v;
          return result;
        }
      else
        {
          free (result);
          return NULL;
        }
    }
  else
    return NULL;
}
OmlValueU* make_vector (void * v, OmlValueT type, int n)
Definition at line 37 of file check_util.c.
References OML_DOUBLE_VALUE, OML_INT32_VALUE, OML_INT64_VALUE, OML_LONG_VALUE, OML_UINT32_VALUE, OML_UINT64_VALUE, omlc_set_double, omlc_set_int32, omlc_set_int64, omlc_set_long, omlc_set_uint32, omlc_set_uint64, and omlc_zero_array.
Referenced by make_test_vector().
{
  OmlValueU* result = (OmlValueU*)malloc (n * sizeof (OmlValueU));
  if (result)
    {
      int i = 0;
      omlc_zero_array(result, n);
      switch (type)
        {
        case OML_LONG_VALUE:
          for (i = 0; i < n; i++)
            omlc_set_long(result[i], ((long*)v)[i]);
          break;
        case OML_DOUBLE_VALUE:
          for (i = 0; i < n; i++)
            omlc_set_double(result[i], ((double*)v)[i]);
          break;
        case OML_INT32_VALUE:
          for (i = 0; i < n; i++)
            omlc_set_int32(result[i], ((int32_t*)v)[i]);
          break;
        case OML_UINT32_VALUE:
          for (i = 0; i < n; i++)
            omlc_set_uint32(result[i], ((uint32_t*)v)[i]);
          break;
        case OML_INT64_VALUE:
          for (i = 0; i < n; i++)
            omlc_set_int64(result[i], ((int64_t*)v)[i]);
          break;
        case OML_UINT64_VALUE:
          for (i = 0; i < n; i++)
            omlc_set_uint64(result[i], ((uint64_t*)v)[i]);
          break;
        default:
          // Can't do non-numeric types yet
          return NULL;
        }
      return result;
    }
  else
    return NULL;
}
void run_filter_test (TestData * test_data, OmlFilter * f)
Definition at line 235 of file check_util.c.
References count, TestData::count, _omlTestWriter::count, input, OmlFilter::input, TestData::inputs, TestVector::length, OmlFilter::name, OmlFilter::newwindow, oml_value_init(), oml_value_reset(), oml_value_set_type(), _omlTestWriter::out, OmlFilter::output, TestData::outputs, TestVector::type, OmlValue::value, _omlTestWriter::values, TestVector::vector, vector_type_check(), vector_values_check(), vector_values_stringify(), and vector_values_ut_stringify().
Referenced by START_TEST().
{
  int i = 0, j = 0;
  int count = 0;
  OmlTestWriter w;
  OmlValue v;
  oml_value_init(&v);
  w.out = test_writer_out;
  for (i = 0; i < test_data->count; i++) {
    TestVector* input = test_data->inputs[i];
    TestVector* output = test_data->outputs[i];
    oml_value_set_type(&v, input->type);
    for (j = 0; j < input->length; j++, count++)
    {
      int res;
      /* XXX: is this really legal? */
      v.value = input->vector[j];
      res = f->input(f, &v);
      fail_unless (res == 0);
    }
    f->output (f, (OmlWriter*)&w);
    f->newwindow (f);
    fail_unless (w.count == output->length);
    fail_unless (vector_type_check (w.values, output->type, output->length));
    fail_unless (vector_values_check (w.values, output->vector, output->type, output->length),
        "Output mismatch in test vector %d [%s] for filter '%s': expected [%s] but got [%s]",
        i,
        vector_values_ut_stringify(input->vector, input->type, input->length),
        f->name,
        vector_values_ut_stringify(output->vector, output->type, output->length),
        vector_values_stringify(w.values, w.count));
  }
  /* Ask for data when nothing more has happened*/
  f->output (f, (OmlWriter*)&w);
  fail_unless (w.count == test_data->outputs[0]->length,
      "Filter with empty window didn't return the right amount of data items (%d instead of %d)",
      w.count, test_data->outputs[0]->length);
  oml_value_reset(&v);
}
int vector_type_check (OmlValue * values, OmlValueT type, int n)
Definition at line 110 of file check_util.c.
References oml_value_get_type.
Referenced by run_filter_test().
{
  int i = 0;
  for (i = 0; i < n; i++)
      if (oml_value_get_type(&values[i]) != type)
        return 0;
  return 1;
}
int vector_values_check (OmlValue * values, OmlValueU * expected, OmlValueT type, int n)
Definition at line 120 of file check_util.c.
References OML_DOUBLE_VALUE, OML_INT32_VALUE, OML_INT64_VALUE, OML_LONG_VALUE, OML_STRING_VALUE, OML_UINT32_VALUE, OML_UINT64_VALUE, oml_value_get_value, omlc_get_double, omlc_get_int32, omlc_get_int64, omlc_get_long, omlc_get_string_length, omlc_get_string_ptr, omlc_get_uint32, and omlc_get_uint64.
Referenced by run_filter_test().
{
  double epsilon = 1e-9;
  int i = 0;
  for (i = 0; i < n; i++) {
      switch (type) {
        case OML_LONG_VALUE:
          if (omlc_get_long(*oml_value_get_value(&values[i])) != omlc_get_long(expected[i]))
            return 0;
          break;
        case OML_DOUBLE_VALUE:
          if (fabs(omlc_get_double(*oml_value_get_value(&values[i])) - omlc_get_double(expected[i])) > epsilon)
            return 0;
          break;
        case OML_STRING_VALUE:
          if (omlc_get_string_length(*oml_value_get_value(&values[i])) != omlc_get_string_length(expected[i]))
            return 0;
          if (strcmp (omlc_get_string_ptr(*oml_value_get_value(&values[i])), omlc_get_string_ptr(expected[i])) != 0)
            return 0;
          break;
        case OML_INT32_VALUE:
          if (omlc_get_int32(*oml_value_get_value(&values[i])) != omlc_get_int32(expected[i]))
            return 0;
          break;
        case OML_UINT32_VALUE:
          if (omlc_get_uint32(*oml_value_get_value(&values[i])) != omlc_get_uint32(expected[i]))
            return 0;
          break;
        case OML_INT64_VALUE:
          if (omlc_get_int64(*oml_value_get_value(&values[i])) != omlc_get_int64(expected[i]))
            return 0;
          break;
        case OML_UINT64_VALUE:
          if (omlc_get_uint64(*oml_value_get_value(&values[i])) != omlc_get_uint64(expected[i]))
            return 0;
          break;
        default:
          return 0; // Fail on unknown value types
        }
    }
  return 1;
}