oml2: check_liboml2_api.c File Reference
check_liboml2_api.c File Reference
Test the user-visible OML API.
#include <string.h>
#include <check.h>
#include "ocomm/o_log.h"
#include "oml2/omlc.h"
#include "check_util.h"
#include "oml_util.h"
#include "oml_value.h"
#include "validate.h"
#include "client.h"
Data Structures
struct Name
Functions
START_TEST (test_api_app_name_spaces)
END_TEST START_TEST (test_api_validate_name)
END_TEST START_TEST (test_api_name_spaces)
START_TEST (test_api_basic)
END_TEST START_TEST (test_api_metadata)
END_TEST Suite * api_suite (void)
Variables
END_TEST OmlMPDef mpdef []
OmlMP * mp
Detailed Description
Test the user-visible OML API.
Definition in file check_liboml2_api.c.
Function Documentation
END_TEST Suite* api_suite (void)
Definition at line 228 of file check_liboml2_api.c.
References LENGTH.
Referenced by main().
{
  Suite* s = suite_create("API");
  TCase* tc_api_names = tcase_create("ApiNames");
  tcase_add_loop_test (tc_api_names, test_api_app_name_spaces, 0, LENGTH(names_vector));
  tcase_add_loop_test (tc_api_names, test_api_validate_name, 0, LENGTH(names_vector));
  tcase_add_loop_test (tc_api_names, test_api_name_spaces, 0, LENGTH(names_vector));
  suite_add_tcase (s, tc_api_names);
  TCase* tc_api_func = tcase_create("ApiFunctions");
  tcase_add_test(tc_api_func, test_api_basic);
  tcase_add_test(tc_api_func, test_api_metadata);
  suite_add_tcase (s, tc_api_func);
  return s;
}
START_TEST (test_api_app_name_spaces)
Definition at line 84 of file check_liboml2_api.c.
References name, omlc_close(), omlc_init(), and omlc_instance.
{
  int res;
  res = omlc_init (names_vector[_i].name, 0, NULL, NULL);
  if (names_vector[_i].is_valid_app_name)
    {
      fail_if (res != 0, "Valid app name '%s' was rejected\n", names_vector[_i]);
      fail_if (omlc_instance == NULL);
    }
  else
    {
      fail_if (res != -1, "Invalid app name '%s' was incorrectly accepted\n", names_vector[_i]);
      fail_unless (omlc_instance == NULL);
    }
  omlc_close();
}
END_TEST START_TEST (test_api_validate_name)
Definition at line 102 of file check_liboml2_api.c.
References name, and validate_name().
{
  int res = validate_name (names_vector[_i].name);
  if (names_vector[_i].is_valid_name) {
    fail_if (res == 0, "MP name '%s' incorrectly marked as invalid\n", names_vector[_i].name);
  } else {
    fail_unless (res == 0, "MP name '%s' incorrectly marked as valid\n", names_vector[_i].name);
  }
}
END_TEST START_TEST (test_api_name_spaces)
Definition at line 113 of file check_liboml2_api.c.
References Name::is_valid_name, Name::name, name, OML_INT32_VALUE, omlc_add_mp(), and omlc_instance.
{
  OmlMPDef def [] =
    {
      { "field1", OML_INT32_VALUE, NULL },
      { NULL, (OmlValueT)0, NULL }
    };
  OmlClient dummy;
  memset(&dummy, 0, sizeof(OmlClient));
  omlc_instance = &dummy;
  const char* name = names_vector[_i].name;
  int is_valid = names_vector[_i].is_valid_name;
  OmlMP* res = omlc_add_mp (name, def);
  if (is_valid)
    fail_if (res == NULL, "omlc_add_mp () failed to create MP for valid name '%s'\n", name);
  else
    fail_unless (res == NULL, "omlc_add_mp() created an MP for invalid name '%s'\n", name);
}
START_TEST (test_api_basic)
Definition at line 143 of file check_liboml2_api.c.
References logdebug(), MAKEOMLCMDLINE, o_set_log_level(), omlc_add_mp(), omlc_close(), omlc_init(), omlc_inject(), omlc_set_string, omlc_start(), and omlc_zero.
{
  OmlMP *mp1, *mp2;
  OmlValueU value;
  o_set_log_level (2);
  logdebug("%s\n", __FUNCTION__);
  MAKEOMLCMDLINE(argc, argv, "file:test_api_basic");
  omlc_zero(value);
  omlc_set_string(value, "1337");
  fail_if(omlc_init("app", &argc, argv, NULL), "Error initialising OML");
  mp1 = omlc_add_mp("MP1", mpdef);
  fail_if(mp1 == NULL, "Failed to add MP1 before omlc_start");
  fail_unless(omlc_inject(mp1, &value),
      "omlc_inject() succeeded before omlc_start was called");
  fail_if(omlc_start(), "Error starting OML");
  fail_if(omlc_inject(mp1, &value),
      "omlc_inject() failed after omlc_start was called");
  mp2 = omlc_add_mp("MP2", mpdef);
  fail_if(mp2 == NULL, "Failed to add MP2 after omlc_start");
  fail_if(omlc_inject(mp2, &value),
      "omlc_inject() failed for second MP");
  fail_if(omlc_close(), "Error closing OML");
}
END_TEST START_TEST (test_api_metadata)
Definition at line 177 of file check_liboml2_api.c.
References logdebug(), MAKEOMLCMDLINE, mp, o_set_log_level(), OML_BLOB_VALUE, OML_INPUT_VALUE, OML_STRING_VALUE, omlc_add_mp(), omlc_close(), omlc_init(), omlc_inject_metadata(), omlc_reset_string, omlc_set_string, omlc_start(), omlc_zero, and type.
{
  OmlMP *mp;
  OmlValueU value;
  OmlValueT type = OML_STRING_VALUE;
  omlc_zero(value);
  omlc_set_string(value, "1337");
  o_set_log_level (2);
  logdebug("%s\n", __FUNCTION__);
  MAKEOMLCMDLINE(argc, argv, "file:test_api_metadata");
  fail_if(omlc_init("app", &argc, argv, NULL), "Error initialising OML");
  mp = omlc_add_mp("MP", mpdef);
  fail_if(mp == NULL, "Failed to add MP");
  fail_unless(-1 == omlc_inject_metadata(NULL, "k", &value, type, NULL),
      "omlc_inject_metadata accepted to work before omlc_start()");
  fail_if(omlc_start(), "Error starting OML");
  /* Test argument validation */
  fail_if(-1 == omlc_inject_metadata(NULL, "k", &value, type, NULL),
      "omlc_inject_metadata refused a NULL MP");
  fail_unless(-1 == omlc_inject_metadata(mp, NULL, &value, type, NULL),
      "omlc_inject_metadata accepted a NULL key");
  fail_unless(-1 == omlc_inject_metadata(mp, "k", NULL, type, NULL),
      "omlc_inject_metadata accepted a NULL value");
  omlc_set_string(value, "value");
  fail_unless(0 == omlc_inject_metadata(mp, "k", &value, type, NULL),
      "omlc_inject_metadata refused valid metadata");
  fail_unless(0 == omlc_inject_metadata(mp, "k", &value, type, "label"),
      "omlc_inject_metadata refused metadata for an existing field");
  for (type = OML_INPUT_VALUE; type <= OML_BLOB_VALUE; type++) {
    if (type != OML_STRING_VALUE) {
      fail_unless(-1 == omlc_inject_metadata(NULL, "k", &value, type, NULL),
          "omlc_inject_metadata accepted a non-string value type");
    }
  }
  omlc_reset_string(value);
  fail_if(omlc_close(), "Error closing OML");
}
Variable Documentation
OmlMP* mp
Definition at line 141 of file check_liboml2_api.c.
Referenced by create_mstream(), find_mp(), omlc_add_mp(), read_mp(), and START_TEST().
END_TEST OmlMPDef mpdef[]
Initial value:
 {
  { "label", OML_STRING_VALUE, NULL },
  { NULL, (OmlValueT)0, NULL }
}
Definition at line 137 of file check_liboml2_api.c.