oml2: check_liboml2.c File Reference
check_liboml2.c File Reference
#include <stdlib.h>
#include <check.h>
#include "ocomm/o_log.h"
#include "check_liboml2_suites.h"
Functions
int main (void)
Function Documentation
int main (void)
Definition at line 17 of file check_liboml2.c.
References api_suite(), bswap_suite(), cbuf_suite(), config_suite(), filters_suite(), log_suite(), mbuf_suite(), o_set_log_file(), omlvalue_suite(), and writers_suite().
{
  int number_failed = 0;
  o_set_log_file ("check_liboml2_oml.log");
  SRunner* sr = srunner_create (omlvalue_suite());
  srunner_add_suite (sr, bswap_suite ());
  srunner_add_suite (sr, mbuf_suite ());
  srunner_add_suite (sr, cbuf_suite ());
  srunner_add_suite (sr, writers_suite ());
  srunner_add_suite (sr, filters_suite ());
  srunner_add_suite (sr, api_suite ());
  srunner_add_suite (sr, config_suite ());
  /* The log_suite has to be last, lest it messes up logging for suites
   * following it */
  srunner_add_suite (sr, log_suite ());
  srunner_run_all (sr, CK_ENV);
  number_failed += srunner_ntests_failed (sr);
  srunner_free (sr);
  return (number_failed == 0) ? EXIT_SUCCESS : EXIT_FAILURE;
}