oml2: check_libshared_headers.c File Reference
check_libshared_headers.c File Reference
#include <stdio.h>
#include <check.h>
#include <arpa/inet.h>
#include "headers.h"
#include "text.h"
#include "binary.h"
#include "oml_util.h"
#include "oml_value.h"
Functions
START_TEST (test_tag_from_string)
END_TEST START_TEST (test_header_from_string)
END_TEST START_TEST (test_header_from_string_short)
END_TEST START_TEST (test_schema_field_from_meta)
END_TEST START_TEST (test_text_read)
END_TEST START_TEST (test_bin_read)
END_TEST Suite * headers_suite (void)
Function Documentation
END_TEST Suite* headers_suite (void)
Definition at line 290 of file check_libshared_headers.c.
References LENGTH.
Referenced by main().
{
  Suite *s = suite_create ("Headers");
  /* Headers test cases */
  TCase *tc_tag_from_string = tcase_create ("HeadersTagFromString");
  TCase *tc_header_from_string = tcase_create ("HeadersHeaderFromString");
  /* Add tests to test case "HeadersTagFromString" */
  tcase_add_loop_test (tc_tag_from_string, test_tag_from_string,
                       0, LENGTH (vector_header_names));
  tcase_add_loop_test (tc_header_from_string, test_header_from_string,
                       0, LENGTH (vector_headers));
  tcase_add_loop_test (tc_header_from_string, test_header_from_string_short,
                       0, LENGTH (vector_headers));
  tcase_add_loop_test (tc_header_from_string, test_schema_field_from_meta,
            0, LENGTH (meta_types));
  tcase_add_test (tc_header_from_string, test_text_read);
  tcase_add_test (tc_header_from_string, test_bin_read);
  suite_add_tcase (s, tc_tag_from_string);
  suite_add_tcase (s, tc_header_from_string);
  return s;
}
START_TEST (test_tag_from_string)
Definition at line 126 of file check_libshared_headers.c.
References expected, name, and tag_from_string().
{
  const char *name = vector_header_names[_i].name;
  size_t len = name ? strlen (name) : 1;
  enum HeaderTag expected = vector_header_names[_i].tag;
  enum HeaderTag actual = tag_from_string (name, len);
  fail_unless (actual == expected);
}
END_TEST START_TEST (test_header_from_string)
Definition at line 137 of file check_libshared_headers.c.
References expected, header, header_from_string(), input, is_null, header::tag, and header::value.
{
  struct header *header;
  const char *input = vector_headers[_i].input;
  const struct header *expected = &vector_headers[_i].header;
  const int is_null = vector_headers[_i].is_null;
  size_t len = input ? strlen (input) : 0;
  header = header_from_string(input, len);
  fail_if (!is_null && header == NULL);
  fail_if (is_null  && header != NULL);
  if (!is_null) {
    fail_unless (header->tag == expected->tag, "Incorrect tag, expected '%d', but got '%d'", expected->tag, header->tag);
    fail_unless (strcmp (header->value, expected->value) == 0, "Incorrect header, expected '%s', but got '%s'", expected->value, header->value);
  }
}
END_TEST START_TEST (test_header_from_string_short)
Definition at line 157 of file check_libshared_headers.c.
References expected, header, header_from_string(), input, is_null, header::tag, and header::value.
{
  struct header *header;
  const char *input = vector_headers[_i].input;
  const struct header *expected = &vector_headers[_i].header;
  const int is_null = vector_headers[_i].is_null_short;
  size_t len = input ? strlen (input) : 0;
  /* Adjust so we don't read the whole string, but only if the string
     is long enough */
  if (len > 2)
    len -= 2;
  header = header_from_string(input, len);
  fail_if (!is_null && header == NULL);
  fail_if (is_null  && header != NULL);
  if (!is_null) {
    size_t check_len = strlen (expected->value);
    if (check_len > 2)
      check_len -= 2;
    fail_unless (header->tag == expected->tag);
    fail_unless (header->value && strlen (header->value) == check_len);
    fail_unless (strncmp (header->value, expected->value, check_len) == 0);
  }
}
END_TEST START_TEST (test_schema_field_from_meta)
Definition at line 186 of file check_libshared_headers.c.
References expected, schema_field::name, schema_field_from_meta(), schema_field::type, and type.
{
  const char *type= meta_types[_i].type;
  const  OmlValueT expected = meta_types[_i].expected;
  int len = strlen(type) * 2 + 2;
  char *meta = malloc(len);
  struct schema_field f;
  int ret;
  snprintf(meta, len, "%s:%s", type, type);
  ret = schema_field_from_meta (meta, len, &f);
  fail_if(ret != 0,
      "Could not convert type %s", type);
  fail_if(f.type != expected,
      "Mismatch for type %s: expected %d, got %d", type, expected, f.type);
  fail_if(strcmp(f.name, type),
      "Field name mismatch: expected %s, got %s", type, f.name);
}
END_TEST START_TEST (test_text_read)
Definition at line 206 of file check_libshared_headers.c.
References oml_message::count, oml_message::length, mbuf_create(), mbuf_write(), oml_value_array_init(), oml_value_array_reset(), schema_from_meta(), oml_message::seqno, oml_message::stream, text_read_msg_start(), text_read_msg_values(), and oml_message::timestamp.
{
  uint8_t buf [] = "0.123456\t1\t42\tabde\t3.1416\t111\nbleftover text for next line";
  char meta [] = "1 mympstrm label:string pi:double fighter:uint32";
  MBuffer *mbuf = mbuf_create();
  struct oml_message msg;
  struct schema *schema = schema_from_meta (meta);
  OmlValue values[3];
  oml_value_array_init(values, 3);
  bzero(&msg, sizeof(msg));
  mbuf_write (mbuf, buf, sizeof(buf));
  int result = text_read_msg_start (&msg, mbuf);
  fprintf (stderr, "STRM: %d\n", msg.stream);
  fprintf (stderr, "SEQN: %u\n", msg.seqno);
  fprintf (stderr, "TS  : %f\n", msg.timestamp);
  fprintf (stderr, "LEN : %d\n", msg.length);
  fprintf (stderr, "COUNT: %d\n", msg.count);
  result = text_read_msg_values (&msg, mbuf, schema, values);
  result *= 42;
  oml_value_array_reset(values, 3);
}
END_TEST START_TEST (test_bin_read)
Definition at line 237 of file check_libshared_headers.c.
References bin_read_msg_start(), bin_read_msg_values(), oml_message::count, oml_message::length, mbuf_create(), mbuf_write(), oml_value_array_init(), oml_value_array_reset(), oml_value_to_s(), schema_from_meta(), oml_message::seqno, oml_message::stream, and oml_message::timestamp.
{
  /* DATA_P, count=1, stream=3, { LONG_T 42 } */
  uint8_t buf [] = { 0xAA, 0xAA, 0x01, 0x00, 0x00,
                     0x3, 0x1, // count = 1, stream = 3
                     0x01, 0x00, 0x00, 0x00, 0x32, // LONG_T 50
                     0x02, 0x54, 0x00, 0x00, 0x00, 0x05, // DOUBLE_T 42.0
                     0x01, 0x00, 0x10, 0xF4, 0x47, // LONG_T 1111111
                     0x02, 0x54, 0x00, 0x00, 0x00, 0x05, // DOUBLE_T 42.0
                     0x04, 0x03, 'A',  'B',  'C' // STRING_T "ABC"
  };
  char meta [] = "3 mympstrm id:long hitchhiker:double sesame:string";
  MBuffer *mbuf = mbuf_create ();
  struct oml_message msg;
  struct schema *schema = schema_from_meta (meta);
  OmlValue values [3];
  int result;
  oml_value_array_init(values, 3);
  bzero(&msg, sizeof(msg));
  int size = sizeof (buf) - 5;
  uint16_t nv = htons (size);
  memcpy (buf + 3, &nv, 2);
  mbuf_write (mbuf, buf, sizeof (buf));
  result = bin_read_msg_start (&msg, mbuf);
  fail_unless(result > 0, "Unable to start reading binary message");
  fprintf (stderr, "---\n");
  fprintf (stderr, "STRM: %d\n", msg.stream);
  fprintf (stderr, "SEQN: %u\n", msg.seqno);
  fprintf (stderr, "TS  : %f\n", msg.timestamp);
  fprintf (stderr, "LEN : %d\n", msg.length);
  fprintf (stderr, "COUNT: %d\n", msg.count);
  result = bin_read_msg_values (&msg, mbuf, schema, values);
  int i = 0;
  for (i = 0; i < 3; i++) {
    char s[64];
    oml_value_to_s (&values[i], s, 64);
    fprintf (stderr, "%s\n", s);
  }
  oml_value_array_reset(values, 3);
}
Variable Documentation
OmlValueT expected
Definition at line 98 of file check_libshared_headers.c.
Referenced by START_TEST().
struct header header
Definition at line 71 of file check_libshared_headers.c.
Referenced by header_from_string(), proxy_message_loop(), read_header(), and START_TEST().
static int input
Definition at line 70 of file check_libshared_headers.c.
Referenced by omlf_register_filter(), omlf_register_filter_stddev(), run_filter_test(), and START_TEST().
int is_null
Definition at line 72 of file check_libshared_headers.c.
Referenced by START_TEST().
int is_null_short
Definition at line 73 of file check_libshared_headers.c.
const char* name
Definition at line 15 of file check_libshared_headers.c.
enum HeaderTag tag
Definition at line 16 of file check_libshared_headers.c.
char* type
Definition at line 97 of file check_libshared_headers.c.