oml2: check_liboml2_suites.h File Reference
check_liboml2_suites.h File Reference
#include <check.h>
Functions
Suite * api_suite (void)
Suite * bswap_suite (void)
Suite * cbuf_suite (void)
Suite * config_suite (void)
Suite * filters_suite (void)
Suite * log_suite (void)
Suite * mbuf_suite (void)
Suite * omlvalue_suite (void)
Suite * writers_suite (void)
Function Documentation
Suite* api_suite (void)
Definition at line 228 of file check_liboml2_api.c.
References LENGTH.
Referenced by main().
{
  Suite* s = suite_create("API");
  TCase* tc_api_names = tcase_create("ApiNames");
  tcase_add_loop_test (tc_api_names, test_api_app_name_spaces, 0, LENGTH(names_vector));
  tcase_add_loop_test (tc_api_names, test_api_validate_name, 0, LENGTH(names_vector));
  tcase_add_loop_test (tc_api_names, test_api_name_spaces, 0, LENGTH(names_vector));
  suite_add_tcase (s, tc_api_names);
  TCase* tc_api_func = tcase_create("ApiFunctions");
  tcase_add_test(tc_api_func, test_api_basic);
  tcase_add_test(tc_api_func, test_api_metadata);
  suite_add_tcase (s, tc_api_func);
  return s;
}
Suite* bswap_suite (void)
Definition at line 104 of file check_liboml2_bswap.c.
Referenced by main().
{
  Suite *s = suite_create("Bswap");
  /* Bswap test cases */
  TCase *tc_bswap = tcase_create ("Bswap");
  /* Add tests to the test case "Bswap" */
  tcase_add_test (tc_bswap, test_bswap_16);
  tcase_add_test (tc_bswap, test_bswap_32);
  tcase_add_test (tc_bswap, test_bswap_64);
  suite_add_tcase (s, tc_bswap);
  return s;
}
Suite* cbuf_suite (void)
Definition at line 639 of file check_liboml2_cbuf.c.
Referenced by main().
{
  Suite* s = suite_create ("Cbuf");
  /* Cbuf test cases */
  TCase* tc_cbuf = tcase_create ("Cbuf");
  /* Add tests to "Mbuf" */
  tcase_add_test (tc_cbuf, test_cbuf_create);
  suite_add_tcase (s, tc_cbuf);
  return s;
}
Suite* config_suite (void)
Definition at line 225 of file check_liboml2_config.c.
Referenced by main().
{
  Suite* s = suite_create ("Config");
  TCase* tc_config = tcase_create ("Config");
  tcase_add_test (tc_config, test_config_metadata);
  tcase_add_test (tc_config, test_config_empty_collect);
  tcase_add_test (tc_config, test_config_multi_collect);
  suite_add_tcase (s, tc_config);
  return s;
}
Suite* filters_suite (void)
Definition at line 441 of file check_liboml2_filters.c.
References filter_setup(), and filter_teardown().
Referenced by main().
{
  Suite* s = suite_create ("Filters");
  /* Filter test cases */
  TCase* tc_filter = tcase_create ("FilterCore");
  TCase* tc_filter_avg = tcase_create ("FilterAverage");
  TCase* tc_filter_first = tcase_create ("FilterFirst");
  //  TCase* tc_filter_hist = tcase_create ("FilterHistogram");
  TCase* tc_filter_stddev = tcase_create ("FilterStddev");
  TCase* tc_filter_sum = tcase_create ("FilterSum");
  TCase* tc_filter_delta= tcase_create ("FilterDelta");
  /* Setup fixtures */
  tcase_add_checked_fixture (tc_filter,       filter_setup, filter_teardown);
  tcase_add_checked_fixture (tc_filter_avg,   filter_setup, filter_teardown);
  tcase_add_checked_fixture (tc_filter_first, filter_setup, filter_teardown);
  //tcase_add_checked_fixture (tc_filter_hist,  filter_setup, filter_teardown);
  tcase_add_checked_fixture (tc_filter_stddev,filter_setup, filter_teardown);
  tcase_add_checked_fixture (tc_filter_sum,filter_setup, filter_teardown);
  tcase_add_checked_fixture (tc_filter_delta,filter_setup, filter_teardown);
  /* Add tests to test case "FilterCore" */
  tcase_add_test (tc_filter, test_filter_create);
  /* Add tests to test case "FilterAverage" */
  tcase_add_test (tc_filter_avg, test_filter_avg_create);
  tcase_add_test (tc_filter_avg, test_filter_avg_output);
  /* Add tests to test case "FilterFirst" */
  tcase_add_test (tc_filter_first, test_filter_first_create);
  /* Add tests to test case "FilterHistogram" */
  //tcase_add_test (tc_filter_hist, test_filter_hist_create);
  /* Add tests to test case "FilterStddev" */
  tcase_add_test (tc_filter_stddev, test_filter_stddev_create);
  tcase_add_test (tc_filter_stddev, test_filter_stddev_0);
  tcase_add_test (tc_filter_stddev, test_filter_stddev_1);
  /* Add tests to test case "FilterSum" */
  tcase_add_test (tc_filter_sum, test_filter_sum_create);
  tcase_add_test (tc_filter_sum, test_filter_sum_output);
  /* Add tests to test case "FilterDelta" */
  tcase_add_test (tc_filter_delta, test_filter_delta_create);
  tcase_add_test (tc_filter_delta, test_filter_delta_output);
  /* Add the test cases to this test suite */
  suite_add_tcase (s, tc_filter);
  suite_add_tcase (s, tc_filter_avg);
  suite_add_tcase (s, tc_filter_first);
  //suite_add_tcase (s, tc_filter_hist);
  suite_add_tcase (s, tc_filter_stddev);
  suite_add_tcase (s, tc_filter_sum);
  suite_add_tcase (s, tc_filter_delta);
  return s;
}
Suite* log_suite (void)
Definition at line 67 of file check_liboml2_log.c.
Referenced by main().
{
  Suite* s = suite_create ("Log");
  TCase* tc_log = tcase_create ("Log");
  tcase_set_timeout(tc_log, 0);
  tcase_add_test (tc_log, test_log_rate);
  suite_add_tcase (s, tc_log);
  return s;
}
Suite* mbuf_suite (void)
Definition at line 620 of file check_liboml2_mbuf.c.
Referenced by main().
{
  Suite* s = suite_create ("Mbuf");
  /* Mbuf test cases */
  TCase* tc_mbuf = tcase_create ("Mbuf");
  /* Add tests to "Mbuf" */
  tcase_add_test (tc_mbuf, test_mbuf_create);
  tcase_add_test (tc_mbuf, test_mbuf_buffer);
  tcase_add_test (tc_mbuf, test_mbuf_length);
  tcase_add_test (tc_mbuf, test_mbuf_resize);
  tcase_add_test (tc_mbuf, test_mbuf_resize_contents);
  tcase_add_test (tc_mbuf, test_mbuf_write);
  tcase_add_test (tc_mbuf, test_mbuf_write_null);
  tcase_add_test (tc_mbuf, test_mbuf_read);
  tcase_add_test (tc_mbuf, test_mbuf_read_null);
  tcase_add_test (tc_mbuf, test_mbuf_begin_read);
  tcase_add_test (tc_mbuf, test_mbuf_begin_write);
  tcase_add_test (tc_mbuf, test_mbuf_reset_read);
  tcase_add_test (tc_mbuf, test_mbuf_reset_write);
  tcase_add_test (tc_mbuf, test_mbuf_consume_message);
  tcase_add_test (tc_mbuf, test_mbuf_repack);
  tcase_add_test (tc_mbuf, test_mbuf_repack_message);
  suite_add_tcase (s, tc_mbuf);
  return s;
}
Suite* omlvalue_suite (void)
Definition at line 428 of file check_liboml2_omlvalue.c.
References LENGTH.
Referenced by main().
{
  Suite* s = suite_create ("OmlValue");
  TCase* tc_omlvalue = tcase_create ("OmlValue");
  tcase_add_test (tc_omlvalue, test_stringU);
  tcase_add_test (tc_omlvalue, test_blobU);
  tcase_add_test (tc_omlvalue, test_intrinsic);
  tcase_add_test (tc_omlvalue, test_string);
  tcase_add_test (tc_omlvalue, test_blob);
  tcase_add_loop_test (tc_omlvalue, test_bool_loop, 0, LENGTH(booltest));
  suite_add_tcase (s, tc_omlvalue);
  return s;
}
Suite* writers_suite (void)
Definition at line 117 of file check_liboml2_writers.c.
Referenced by main().
{
  Suite* s = suite_create ("Writers");
  /* Test cases */
  /*TCase* tc_bw = tcase_create ("BfWr");*/
  TCase* tc_fw = tcase_create ("FileWr");
  /* Add tests */
  /*tcase_add_test (tc_bw, test_bw_create);*/
  tcase_add_test (tc_fw, test_fw_create_buffered);
  /*suite_add_tcase (s, tc_bw);*/
  suite_add_tcase (s, tc_fw);
  return s;
}