oml2: check_liboml2_cbuf.c File Reference
check_liboml2_cbuf.c File Reference
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <check.h>
#include "cbuf.h"
#include "check_util.h"
Macros
#define _GNU_SOURCE /* For NAN, strncasecmp */
Functions
START_TEST (test_cbuf_create)
END_TEST Suite * cbuf_suite (void)
Macro Definition Documentation
#define _GNU_SOURCE /* For NAN, strncasecmp */
Definition at line 24 of file check_liboml2_cbuf.c.
Function Documentation
END_TEST Suite* cbuf_suite (void)
Definition at line 639 of file check_liboml2_cbuf.c.
Referenced by main().
{
  Suite* s = suite_create ("Cbuf");
  /* Cbuf test cases */
  TCase* tc_cbuf = tcase_create ("Cbuf");
  /* Add tests to "Mbuf" */
  tcase_add_test (tc_cbuf, test_cbuf_create);
  suite_add_tcase (s, tc_cbuf);
  return s;
}
START_TEST (test_cbuf_create)
Definition at line 623 of file check_liboml2_cbuf.c.
References cbuf_create(), and cbuf_write().
{
  CBuffer *cbuf = cbuf_create (-1);
  char * test_string = "abcdefg";
  size_t len = strlen (test_string);
  int i = 0;
  for (i = 0; i < 1000; i++) {
    cbuf_write (cbuf, "abcdefg", len);
  }
}