oml2: check_server.h File Reference
check_server.h File Reference
#include "ocomm/o_eventloop.h"
#include "client_handler.h"
Functions
ClientHandler * check_server_prepare_client_handler (const char *name, SockEvtSource *source)
void check_server_destroy_client_handler (ClientHandler *ch)
Function Documentation
void check_server_destroy_client_handler (ClientHandler * ch)
Free the fake test ClientHandler.
Parameters
ch ClientHandler
See Also
client_handler_new
Definition at line 69 of file check_server.c.
References _clientHandler::mbuf, mbuf_destroy(), and oml_free().
Referenced by START_TEST().
{
  mbuf_destroy(ch->mbuf);
  oml_free(ch);
}
ClientHandler* check_server_prepare_client_handler (const char * name, SockEvtSource * source)
Create a fake test ClientHandler almost as server/client_handler.h:client_handler_new() would.
Parameters
name identifier for this ClientHandler
Returns
a working ClientHandler (or fail the test)
See Also
client_handler_new
Definition at line 46 of file check_server.c.
References C_HEADER, C_TEXT_DATA, _clientHandler::content, _clientHandler::event, MAX_STRING_SIZE, _clientHandler::mbuf, mbuf_create(), _clientHandler::name, oml_malloc(), _clientHandler::socket, and _clientHandler::state.
Referenced by START_TEST().
{
  ClientHandler* ch;
  ch = (ClientHandler*) oml_malloc(sizeof(ClientHandler));
  fail_if(ch == NULL, "Problem allocating ClientHandler");
  ch->state = C_HEADER;
  ch->content = C_TEXT_DATA;
  ch->mbuf = mbuf_create ();
  ch->socket = NULL;
  ch->event = source;
  strncpy (ch->name, name, MAX_STRING_SIZE);
  return ch;
}