oml2: check_liboml2_writers.c File Reference
check_liboml2_writers.c File Reference
#include <math.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <check.h>
#include "mbuf.h"
#include "client.h"
#include "oml_util.h"
Data Structures
struct _omlFileOutStream
Macros
#define _GNU_SOURCE /* For NAN */
#define FN "test_fw_create_buffered"
Typedefs
typedef struct _omlFileOutStream OmlFileOutStream
Functions
START_TEST (test_fw_create_buffered)
END_TEST Suite * writers_suite (void)
Macro Definition Documentation
#define _GNU_SOURCE /* For NAN */
Definition at line 24 of file check_liboml2_writers.c.
#define FN "test_fw_create_buffered"
Definition at line 63 of file check_liboml2_writers.c.
Referenced by START_TEST().
Typedef Documentation
typedef struct _omlFileOutStream OmlFileOutStream
Function Documentation
START_TEST (test_fw_create_buffered)
Definition at line 65 of file check_liboml2_writers.c.
References OmlFileOutStream::f, file_stream_get_buffered(), file_stream_new(), file_stream_set_buffered(), FN, OmlFileOutStream::write, and OmlOutStream::write.
{
  char buf[] = "aaa\n";
  char buf2[10];
  int len;
  FILE *f;
  OmlOutStream *os;
  OmlFileOutStream *fs;
  /* Remove stray file */
  unlink(FN);
  os = file_stream_new(FN);
  fs = (OmlFileOutStream*) os;
  fail_if(fs->f==NULL);
  fail_if(fs->write==NULL);
  /* Not set nor used at the moment
   *fail_if(fs->close==NULL); */
  /* The OmlFileOutStream is buffered by default */
  fail_unless(file_stream_get_buffered(os));
  fail_unless(os->write(NULL, (uint8_t*)buf, 0, NULL, 0)==-1);
  /* Buffered operation */
  fail_unless(os->write(os, (uint8_t*)buf, sizeof(buf), NULL, 0)==sizeof(buf));
  f = fopen(FN, "r");
  /* Nothing should be read at this time */
  len = fread(buf2, sizeof(char), sizeof(buf2), f);
  fail_unless(len==0, "Read %d bytes from " FN ", expected %d", len, 0);
  fclose(f);
  /* Unuffered operation */
  file_stream_set_buffered(os, 0);
  fail_if(file_stream_get_buffered(os));
  fail_unless(os->write(os, (uint8_t*)buf, sizeof(buf), NULL, 0)==sizeof(buf));
  f = fopen(FN, "r");
  /* Nothing should be read at this time */
  len=fread(buf2, sizeof(char), sizeof(buf2), f);
  fail_unless(len==2*sizeof(buf), "Read %d bytes from " FN ", expected %d", len, 2*sizeof(buf)-2);
  fclose(f);
  /* Final check */
  file_stream_set_buffered(os, 1);
  fail_unless(file_stream_get_buffered(os));
}
END_TEST Suite* writers_suite (void)
Definition at line 117 of file check_liboml2_writers.c.
Referenced by main().
{
  Suite* s = suite_create ("Writers");
  /* Test cases */
  /*TCase* tc_bw = tcase_create ("BfWr");*/
  TCase* tc_fw = tcase_create ("FileWr");
  /* Add tests */
  /*tcase_add_test (tc_bw, test_bw_create);*/
  tcase_add_test (tc_fw, test_fw_create_buffered);
  /*suite_add_tcase (s, tc_bw);*/
  suite_add_tcase (s, tc_fw);
  return s;
}