oml2: check_libshared_suites.h File Reference
check_libshared_suites.h File Reference
#include <check.h>
Functions
Suite * base64_suite (void)
Suite * string_utils_suite (void)
Suite * json_suite (void)
Suite * mstring_suite (void)
Suite * util_suite (void)
Suite * headers_suite (void)
Suite * marshal_suite (void)
Function Documentation
Suite* base64_suite (void)
Definition at line 98 of file check_libshared_base64.c.
Referenced by main().
{
  Suite *s = suite_create("base64");
  TCase *tc_core = tcase_create("base64");
  tcase_add_test(tc_core, test_base64_string_size);
  tcase_add_test(tc_core, zero_length_inputs);
  tcase_add_test(tc_core, test_round_trip);
  suite_add_tcase(s, tc_core);
  return s;
}
Suite* headers_suite (void)
Definition at line 290 of file check_libshared_headers.c.
References LENGTH.
Referenced by main().
{
  Suite *s = suite_create ("Headers");
  /* Headers test cases */
  TCase *tc_tag_from_string = tcase_create ("HeadersTagFromString");
  TCase *tc_header_from_string = tcase_create ("HeadersHeaderFromString");
  /* Add tests to test case "HeadersTagFromString" */
  tcase_add_loop_test (tc_tag_from_string, test_tag_from_string,
                       0, LENGTH (vector_header_names));
  tcase_add_loop_test (tc_header_from_string, test_header_from_string,
                       0, LENGTH (vector_headers));
  tcase_add_loop_test (tc_header_from_string, test_header_from_string_short,
                       0, LENGTH (vector_headers));
  tcase_add_loop_test (tc_header_from_string, test_schema_field_from_meta,
            0, LENGTH (meta_types));
  tcase_add_test (tc_header_from_string, test_text_read);
  tcase_add_test (tc_header_from_string, test_bin_read);
  suite_add_tcase (s, tc_tag_from_string);
  suite_add_tcase (s, tc_header_from_string);
  return s;
}
Suite* json_suite (void)
Definition at line 141 of file check_libshared_json.c.
Referenced by main().
{
  Suite *s = suite_create("json");
  TCase *tc_core = tcase_create("json_tests");
  tcase_add_test(tc_core, null_valued_vector_double_null_output);
  tcase_add_test(tc_core, zero_sized_vector_double_null_output);
  tcase_add_test(tc_core, single_elt_vector_double_null_output);
  tcase_add_test(tc_core, null_valued_vector_double_tiny_output);
  tcase_add_test(tc_core, zero_sized_vector_double_tiny_output);
  tcase_add_test(tc_core, single_elt_vector_double_tiny_output);
  tcase_add_test(tc_core, vector_double_test_precision);
  suite_add_tcase(s, tc_core);
  return s;
}
Suite* marshal_suite (void)
Definition at line 1811 of file check_libshared_marshal.c.
References LENGTH.
Referenced by main().
{
  Suite* s = suite_create ("Marshal");
  /* Marshalling test cases */
  TCase* tc_marshal = tcase_create ("Marshal");
  /* Add tests to "Marshal" */
  tcase_add_test (tc_marshal, test_marshal_init);
  tcase_add_loop_test (tc_marshal, test_marshal_value_long,   0, LENGTH (long_values));
  tcase_add_loop_test (tc_marshal, test_marshal_value_int32,  0, LENGTH (int32_values));
  tcase_add_loop_test (tc_marshal, test_marshal_value_uint32, 0, LENGTH (int32_values));
  tcase_add_loop_test (tc_marshal, test_marshal_value_int64,  0, LENGTH (int64_values));
  tcase_add_loop_test (tc_marshal, test_marshal_value_uint64, 0, LENGTH (int64_values));
  tcase_add_loop_test (tc_marshal, test_marshal_value_double, 0, LENGTH (double_values));
  tcase_add_loop_test (tc_marshal, test_marshal_value_string, 0, LENGTH (string_values));
  tcase_add_loop_test (tc_marshal, test_marshal_guid,         0, LENGTH (guid_values));
  tcase_add_loop_test (tc_marshal, test_marshal_bool,         0, LENGTH (bool_values));
  tcase_add_test (tc_marshal, test_marshal_unmarshal_long);
  tcase_add_test (tc_marshal, test_marshal_unmarshal_int32);
  tcase_add_test (tc_marshal, test_marshal_unmarshal_uint32);
  tcase_add_test (tc_marshal, test_marshal_unmarshal_int64);
  tcase_add_test (tc_marshal, test_marshal_unmarshal_uint64);
  tcase_add_test (tc_marshal, test_marshal_unmarshal_double);
  tcase_add_test (tc_marshal, test_marshal_unmarshal_string);
  tcase_add_test (tc_marshal, test_marshal_unmarshal_guid);
  tcase_add_test (tc_marshal, test_marshal_unmarshal_bool);
  tcase_add_test (tc_marshal, test_marshal_unmarshal_vector_double);
  tcase_add_test (tc_marshal, test_marshal_unmarshal_vector_int32);
  tcase_add_test (tc_marshal, test_marshal_unmarshal_vector_int64);
  tcase_add_test (tc_marshal, test_marshal_unmarshal_vector_bool);
  /* Do the full marshalling/unmarshalling test, types above should also be tested there */
  tcase_add_test (tc_marshal, test_marshal_full);
  suite_add_tcase (s, tc_marshal);
  return s;
}
Suite* mstring_suite (void)
Definition at line 71 of file check_libshared_mstring.c.
Referenced by main().
{
  Suite* s = suite_create ("MString");
  TCase* tc_mstring = tcase_create ("MString");
  tcase_add_test (tc_mstring, test_mstring);
  suite_add_tcase (s, tc_mstring);
  return s;
}
Suite* string_utils_suite (void)
Definition at line 112 of file check_libshared_string_utils.c.
Referenced by main().
{
  Suite *s = suite_create("string_utils");
  TCase *tc_core = tcase_create("string_utils");
  tcase_add_test(tc_core, test_round_trip);
  suite_add_tcase(s, tc_core);
  return s;
}
Suite* util_suite (void)
Definition at line 166 of file check_libshared_util.c.
References LENGTH.
Referenced by main().
{
  Suite* s = suite_create ("Util");
  TCase* tc_util = tcase_create ("Util");
  tcase_add_test (tc_util, test_util_uri);
  tcase_add_test (tc_util, test_util_find);
  tcase_add_loop_test (tc_util, test_util_parse_uri, 0, LENGTH(test_uris));
  suite_add_tcase (s, tc_util);
  return s;
}