oml2: client.h File Reference
client.h File Reference
Defines various structures and functions used by various parts.
#include <stdio.h>
#include <time.h>
#include <oml2/omlc.h>
#include <oml2/oml_filter.h>
#include <oml2/oml_writer.h>
#include <oml2/oml_out_stream.h>
#include <mstring.h>
Data Structures
struct OmlClient
Macros
#define COLLECTION_URI_MAX_LENGTH 64
#define xstr(s) str(s)
#define str(s) #s
#define DEF_PORT 3003
#define DEF_PORT_STRING xstr(DEF_PORT)
Typedefs
typedef struct OmlClient OmlClient
Functions
OmlMP * find_mp (const char *name)
int find_mp_field (const char *name, OmlMP *mp)
OmlMStream * find_mstream (const char *name)
OmlMStream * find_mstream_in_mp (const char *name, OmlMP *mp)
OmlMStream * oml_mp_get_default_ms (OmlMP *mp)
int oml_ms_add_writer (OmlMStream *ms, OmlWriter *w)
MString * mp_fields_summary (OmlMP *mp)
OmlMP * destroy_mp (OmlMP *mp)
OmlMStream * create_mstream (const char *name, OmlMP *mp, OmlWriter *writer, double sample_interval, int sample_thres)
OmlMStream * destroy_ms (OmlMStream *ms)
void create_default_filters (OmlMP *mp, OmlMStream *ms)
OmlFilter * create_default_filter (OmlMPDef *def, OmlMStream *ms, int index)
void filter_engine_start (OmlMStream *mp)
int filter_process (OmlMStream *mp)
int mp_lock (OmlMP *mp)
void mp_unlock (OmlMP *mp)
int oml_lock (pthread_mutex_t *mutexP, const char *mutexName)
void oml_unlock (pthread_mutex_t *mutexP, const char *mutexName)
void oml_lock_persistent (pthread_mutex_t *mutexP, const char *mutexName)
OmlWriter * text_writer_new (OmlOutStream *out_stream)
OmlWriter * bin_writer_new (OmlOutStream *out_stream)
OmlOutStream * file_stream_new (const char *file)
int file_stream_set_buffered (OmlOutStream *hdl, int buffered)
int file_stream_get_buffered (OmlOutStream *hdl)
OmlOutStream * net_stream_new (const char *transport, const char *hostname, const char *port)
const char * validate_app_name (const char *name)
Variables
OmlClient * omlc_instance
Detailed Description
Defines various structures and functions used by various parts.
Definition in file client.h.
Macro Definition Documentation
#define COLLECTION_URI_MAX_LENGTH 64
Definition at line 26 of file client.h.
Referenced by omlc_init().
#define DEF_PORT 3003
Definition at line 30 of file client.h.
#define DEF_PORT_STRING xstr(DEF_PORT)
Definition at line 31 of file client.h.
Referenced by create_writer().
#define str (s) #s
Definition at line 29 of file client.h.
#define xstr (s) str(s)
Definition at line 28 of file client.h.
Typedef Documentation
typedef struct OmlClient OmlClient
Internal data structure holding OML parameters
Function Documentation
OmlWriter* bin_writer_new (OmlOutStream * out_stream)
Create a new OmlBinWriter
Parameters
out_stream OmlOutStream into which the data should be written
Returns
a pointer to the new OmlBinWriter cast as an OmlWriter
See Also
BufferedWriter
Definition at line 91 of file bin_writer.c.
References bw_create(), OmlClient::max_queue, OMB_DATA_P, oml_malloc(), and omlc_instance.
Referenced by create_writer().
{
  assert(out_stream != NULL);
  OmlBinWriter* self = (OmlBinWriter *)oml_malloc(sizeof(OmlBinWriter));
  memset(self, 0, sizeof(OmlBinWriter));
  self->bufferedWriter = bw_create(out_stream,
      omlc_instance->max_queue, 0);
  self->out_stream = out_stream;
  self->meta = owb_meta;
  self->header_done = owb_header_done;
  self->row_start = owb_row_start;
  self->row_end = owb_row_end;
  self->out = owb_row_cols;
  self->close = owb_close;
  self->msgtype = OMB_DATA_P; // Short packets.
  return (OmlWriter*)self;
}
OmlFilter* create_default_filter (OmlMPDef * def, OmlMStream * ms, int index)
Create a new filter for the measurement associated with the stream
Parameters
def OmlMPDef of the MP for which to create a filter
ms OmlMStream in which the filter outputs its samples
index index of the field to filter within this MP
Returns
a new filter
Definition at line 1224 of file init.c.
References create_filter(), OmlMPDef::name, name, omlc_is_numeric_type, OmlMPDef::param_types, OmlMPDef::relations, OmlMStream::sample_interval, OmlMStream::sample_thres, and type.
Referenced by create_default_filters().
{
  const char* name = def->name;
  OmlValueT type = def->param_types;
  OMLSemDef * concepts = def->relations;
  int multiple_samples = ms->sample_thres > 1 || ms->sample_interval > 0;
  char* fname;
  if (multiple_samples && omlc_is_numeric_type (type)) {
    fname = "avg";
  } else {
    fname = "first";
  }
  OmlFilter* f = create_filter(fname, name, type, concepts, index);
  return f;
}
void create_default_filters (OmlMP * mp, OmlMStream * ms)
Create the default filters
Parameters
mp OmlMP to add filters to
ns OmlMStream associated to mp
Definition at line 1187 of file init.c.
References create_default_filter(), logdebug(), logerror(), OmlMP::name, OmlFilter::next, OmlMP::param_count, OmlMP::param_defs, and OmlMStream::table_name.
Referenced by oml_mp_get_default_ms().
{
  int j;
  if(!mp || !ms) {
    return;
  }
  int param_count = mp->param_count;
  logdebug("Creating default filters on MP '%s' to MS '%s'\n",
      mp->name, ms->table_name);
  OmlFilter* prev = NULL;
  for (j = 0; j < param_count; j++) {
    OmlMPDef def = mp->param_defs[j];
    OmlFilter* f = create_default_filter(&def, ms, j);
    if (f) {
      if (prev == NULL) {
        ms->firstFilter = f;
      } else {
        prev->next = f;
      }
      prev = f;
    } else {
      logerror("Unable to create default filter for MP %s.\n", mp->name);
    }
  }
}
OmlMStream* create_mstream (const char * name, OmlMP * mp, OmlWriter * writer, double sample_interval, int sample_thres)
Create a new stream of measurement samples from the inputs to a given MP.
If a stream by that name already exists, it is used instead.
Parameters
sample_interval the sample interval for the filter
sample_thres the threshold for the filter
mp the measurement point
writer the destination for the stream output samples
Returns
the new measurement stream, or NULL if an error occurred.
Definition at line 963 of file init.c.
References OmlClient::app_name, OmlClient::client_instr, find_mstream(), logdebug(), logerror(), loginfo(), mp, OmlMStream::mp, mstring_buf(), mstring_cat(), mstring_create(), mstring_delete(), mstring_set(), OmlMP::mutex, OmlMP::mutexP, OmlMP::name, OmlMStream::next, oml_free(), oml_malloc(), oml_ms_add_writer(), OmlMStream::sample_interval, OmlMStream::sample_thres, OmlMP::streams, and OmlMStream::table_name.
Referenced by oml_mp_get_default_ms().
{
  char *stream_name = NULL;
  int new = 1;
  MString *namestr;
  OmlMStream *ms;
  if (!mp) {
    return NULL;
  }
  namestr = mstring_create();
  /* If name is not specified, create one by concatenating the application and
   * MP names.
   *
   * XXX: We probably should not do it for any MP, as an MP should be
   * application-agnostic. This is not the case at the moment, and we don't
   * want to confuse legacy post-processing scripts. See #1055.
   *
   * However, schema 0 is new, so let's do the right thing here.
   *
   */
  namestr = mstring_create();
  if ((mp != schema0) && (mp != omlc_instance->client_instr)) {
    mstring_set (namestr, omlc_instance->app_name);
    mstring_cat (namestr, "_");
  }
  if (name) {
    mstring_cat (namestr, name);
  } else {
    mstring_cat (namestr, mp->name);
  }
  stream_name = mstring_buf (namestr);
  if ((ms=find_mstream (stream_name))) {
    loginfo("MS '%s' already exists, assuming identical parameters for a new destination; use the 'name' attribute of the <stream /> element to change\n", stream_name);
    new = 0;
  } else {
    logdebug("MS '%s' does not exist, creating...\n", stream_name);
    ms = (OmlMStream*)oml_malloc(sizeof(OmlMStream));
    if(!ms) {
      logerror("Cannot allocate memory for MS %s\n", name);
      return NULL;
    }
    memset(ms, 0, sizeof(OmlMStream));
    ;
    strncpy (ms->table_name, stream_name, sizeof(ms->table_name));
    ms->table_name[sizeof(ms->table_name)-1] = '\0';
    ms->sample_interval = sample_interval;
    ms->sample_thres = sample_thres;
    ms->mp = mp;
    if (ms->sample_interval > 0) {
      if (mp->mutexP == NULL) {
        mp->mutexP = &mp->mutex;
        pthread_mutex_init(mp->mutexP, NULL);
      }
      ms->sample_thres = 0;
    }
  }
  mstring_delete (namestr);
  if(!writer) {
    logdebug("NULL writer for MS %s; it might get added later (using a configuration file?)\n", name?name:mp->name);
  } else if (oml_ms_add_writer(ms, writer))  {
    logerror("Cannot add %s's writer\n", name);
    if(new) {
      oml_free(ms);
    }
    return NULL;
  }
  if (new) {
    ms->next = mp->streams;
    mp->streams = ms;
  }
  return ms;
}
OmlMP* destroy_mp (OmlMP * mp)
Destroy MP
This function is designed so it can be used in a while loop to clean up the entire linked list:
while((mp=destroy_mp(mp)));
Parameters
mp pointer to the OmlMP to free
Returns
mp->next (can be NULL)
Definition at line 493 of file init.c.
References OmlMP::active, destroy_ms(), destroy_sem_concepts(), logdebug(), mp_lock(), mp_unlock(), OmlMP::name, OmlMP::next, OmlMP::param_defs, OmlMPDef::relations, and OmlMP::streams.
Referenced by omlc_close().
{
  OmlMP *next;
  OmlMStream *ms;
  if(!mp) {
    return NULL;
  }
  logdebug("Destroying MP %s at %p\n", mp->name, mp);
  next = mp->next;
  if (!mp_lock(mp)) {
    mp->active = 0;
    ms = mp->streams;
    while (destroy_sem_concepts(mp->param_defs->relations));
    while( (ms=destroy_ms(ms)) );
    mp_unlock(mp);
  }
  return next;
}
OmlMStream* destroy_ms (OmlMStream * ms)
Destroy a Measurement Stream, and deep free allocated memory (filters.
This function is designed so it can be used in a while loop to clean up the entire linked list:
while((ms=destroy_ms(ms)));
Parameters
ms pointer to the OmlMStream to free
Returns
ms->next (can be NULL)
Definition at line 1088 of file init.c.
References destroy_filter(), filter_process(), OmlMStream::filters, logdebug(), loginfo(), OmlMStream::next, oml_free(), OmlMStream::sample_size, OmlMStream::table_name, and OmlMStream::writers.
Referenced by destroy_mp().
{
  OmlMStream *next;
  OmlFilter *ft;
  if(!ms) {
    return NULL;
  }
  logdebug("Destroying MS %s at %p\n", ms->table_name, ms);
  next = ms->next;
  if (ms->sample_size > 0) {
    loginfo("Reporting last (partial) sample for MS %s\n", ms->table_name);
    filter_process(ms);
  }
  ft = ms->filters;
  while( (ft = destroy_filter(ft)) );
  oml_free(ms->writers);
  oml_free(ms);
  return next;
}
int file_stream_get_buffered (OmlOutStream * hdl)
Get the buffering startegy of an OmlOutStream
Returns 0 if fflush(3) is used after each write, 1 otherwise.
Parameters
hdl the OmlOutStream
Returns
0 if unbuffered, 1 if buffered, -1 on failure (hdl was NULL)
Definition at line 190 of file file_stream.c.
References OmlOutStream::write.
Referenced by START_TEST().
{
  OmlFileOutStream* self = (OmlFileOutStream*)hdl;
  if (self == NULL) return -1;
  return (hdl->write==file_stream_write);
}
OmlOutStream* file_stream_new (const char * file)
Create a new out stream for writing into a local file.
Parameters
file destination file (oml_strndup()'d locally)
Returns
a new OmlOutStream instance
See Also
oml_strndup
Definition at line 59 of file file_stream.c.
References logerror(), loginfo(), oml_malloc(), and oml_strndup().
Referenced by create_writer(), and START_TEST().
{
  OmlFileOutStream* self = (OmlFileOutStream *)oml_malloc(sizeof(OmlFileOutStream));
  memset(self, 0, sizeof(OmlFileOutStream));
  loginfo ("File_stream: opening local storage file '%s'\n", file);
  if (strcmp(file, "stdout") == 0 || strcmp(file, "-") == 0) {
    self->f = stdout;
  } else {
    if ((self->f = fopen(file, "a+")) == NULL) {
      logerror ("Can't open local storage file '%s'\n", file);
      return 0;
    }
  }
  self->write = file_stream_write;
  self->close = file_stream_close;
  self->dest = (char*)oml_strndup (file, strlen (file));
  self->header_written = 0;
  return (OmlOutStream*)self;
}
int file_stream_set_buffered (OmlOutStream * hdl, int buffered)
Set the buffering startegy of an OmlOutStream
Tell whether fflush(3) should be used after each write.
Parameters
hdl the OmlOutStream
buffered if 0, unbuffered operation is used, otherwise buffered operation is
Returns
0 on success, -1 on failure (+hdl+ was NULL)
Definition at line 168 of file file_stream.c.
References file_stream_write_flush(), and OmlOutStream::write.
Referenced by create_writer(), and START_TEST().
{
  OmlFileOutStream* self = (OmlFileOutStream*)hdl;
  if (self == NULL) return -1;
  if(buffered)
    hdl->write=file_stream_write;
  else
    hdl->write=file_stream_write_flush;
  return 0;
}
void filter_engine_start (OmlMStream * ms)
Start the filtering engine on the given MS
Parameters
ms pointer to OmlMStream to start filtering on
Definition at line 50 of file filter.c.
References OmlMStream::filter_thread, logdebug(), and OmlMStream::table_name.
Referenced by oml_mp_get_default_ms().
{
  logdebug ("Starting filtering thread for MS '%s'\n", ms->table_name);
  pthread_create(&ms->filter_thread, NULL, thread_start, (void*)ms);
}
int filter_process (OmlMStream * ms)
Run filters associated to an MS.
Get the writer associated to the MS, and generate and write initial metadata (seqno and time). Then, instruct all the filters, in sequence, to write their filtered sample to this writer before finalising the write.
Parameters
ms MS to generate output for
Returns
0 if success, -1 otherwise
See Also
OmlWriter, oml_writer_row_start, oml_writer_out, oml_writer_row_end
Definition at line 103 of file filter.c.
References OmlMStream::dropped, logerror(), logwarn(), OmlFilter::newwindow, OmlFilter::next, OmlMStream::nwriters, OmlFilter::output, OmlWriter::row_end, OmlWriter::row_start, OmlMStream::sample_size, OmlMStream::seq_no, OmlClient::start_time, OmlMStream::table_name, OmlMStream::writers, and OmlMStream::written.
Referenced by destroy_ms().
{
  struct timeval tv;
  double now;
  int i;
  OmlFilter *f;
  OmlWriter *writer;
  /* Get the time as soon as possible */
  gettimeofday(&tv, NULL);
  if (ms == NULL || omlc_instance == NULL || ms->writers == NULL) {
    logerror("Could not process filters because of null measurement stream, instance or writers array\n");
    return -1;
  }
  now = tv.tv_sec - omlc_instance->start_time + 0.000001 * tv.tv_usec;
  ms->seq_no++;
  for (i=0; i<ms->nwriters; i++) {
    writer = ms->writers[i];
    if (writer == NULL) {
      logwarn("%s: Sending data NULL writer (at %d)\n", ms->table_name, i);
    } else {
      /* Be aware that row_start is obtaining a lock on the writer
       * which is released in row_end. Always ensure that row_end is
       * called, even if there is a problem somewhere along the way.
       * \see oml_writer_row_start, oml_writer_out, oml_writer_row_end
       */
      if(writer->row_start(writer, ms, now) == 1)
        ms->written++;
      else
        ms->dropped++;
      f = ms->firstFilter;
      for (; f != NULL; f = f->next) {
        f->output(f, writer);
      }
      writer->row_end(writer, ms);
    }
  }
  f = ms->firstFilter;
  for (; f != NULL; f = f->next) {
    f->newwindow(f);
  }
  ms->sample_size = 0;
  return 0;
}
OmlMP* find_mp (const char * name)
Find a named measurement point.
Parameters
name The name of the measurement point to search for.
Returns
the measurement point, or NULL if not found.
Definition at line 850 of file init.c.
References mp, OmlClient::mpoints, OmlMP::name, and OmlMP::next.
{
  OmlMP *mp = omlc_instance->mpoints;
  while (mp && strcmp (name, mp->name))
    mp = mp->next;
  return mp;
}
int find_mp_field (const char * name, OmlMP * mp)
a named field of an MP.
Parameters
name name of the field to look up
mp OmlMP to look for the field
If either parameter is NULL, act as if the field wasn't found.
Returns
a valid index into the OmlMP's param_defs array, or -1 if not found
Definition at line 867 of file init.c.
References logdebug(), OmlMPDef::name, OmlMP::name, OmlMP::param_count, and OmlMP::param_defs.
Referenced by omlc_inject_metadata().
{
  size_t i;
  if (NULL == name || NULL == mp) { return -1; }
  size_t len = mp->param_count;
  OmlMPDef *fields = mp->param_defs;
  for (i = 0; i < len; i++) {
    logdebug("Searching MP %s for field '%s', found '%s'\n",
        mp->name, name, fields[i].name);
    if (strcmp (name, fields[i].name) == 0) {
      return i;
    }
  }
  return -1;
}
OmlMStream* find_mstream (const char * name)
Find a measurement stream by name. All measurement streams must be named uniquely.
Parameters
name the name of the measurement stream to search for.
Returns
a pointer to the measurement stream or NULL if not found.
Definition at line 938 of file init.c.
References find_mstream_in_mp(), OmlClient::mpoints, and OmlMP::next.
Referenced by create_mstream().
{
  OmlMP *mp = omlc_instance->mpoints;
  OmlMStream *ms = NULL;
  while (mp) {
    ms = find_mstream_in_mp (name, mp);
    if (ms)
      break;
    mp = mp->next;
  }
  return ms;
}
OmlMStream* find_mstream_in_mp (const char * name, OmlMP * mp)
Find a named MStream among the streams attached to an MP.
Parameters
name name of the stream to search for
mp MP in which to search for the stream
Returns
a pointer to the OmlMStream if found, or NULL if not (or name is NULL)
Definition at line 915 of file init.c.
References OmlMStream::next, OmlMP::streams, and OmlMStream::table_name.
Referenced by find_mstream().
{
  OmlMStream *ms = mp->streams;
  if (!name)
    return NULL;
  while (ms) {
    if (ms && ms->table_name && strcmp (name, ms->table_name) == 0)
      break;
    ms = ms->next;
  }
  return ms;
}
MString* mp_fields_summary (OmlMP * mp)
Create an MString containing a comma-separated list of the fields of the MP.
Parameters
mp OmlMP to summarize
Returns
the fields summary for mp. The caller is repsonsible for calling mstring_delete() to deallocate the returned MString.
Definition at line 889 of file init.c.
References mstring_cat(), mstring_create(), mstring_set(), name, OmlMP::param_count, and OmlMP::param_defs.
{
  int i;
  OmlMPDef *fields = mp->param_defs;
  MString *s = mstring_create();
  mstring_set (s, "'");
  if (!s) return NULL;
  for (i = 0; i < mp->param_count; i++) {
    mstring_cat (s, fields[i].name);
    if (i < mp->param_count - 1)
      mstring_cat (s, "', '");
  }
  mstring_cat (s, "'");
  return s;
}
int mp_lock (OmlMP * mp)
Lock a measurement point mutex
Parameters
mp OmlMP to lock
Returns
0 if successful, -1 otherwise
See Also
mp_unlock, oml_lock
Definition at line 30 of file misc.c.
References OmlMP::mutexP, OmlMP::name, and oml_lock().
Referenced by destroy_mp(), and omlc_inject().
{
  return oml_lock(mp->mutexP, mp->name);
}
void mp_unlock (OmlMP * mp)
Unlock a measurement point mutex
Parameters
mp OmlMP to unlock
See Also
mp_lock, oml_unlock
Definition at line 40 of file misc.c.
References OmlMP::mutexP, OmlMP::name, and oml_unlock().
Referenced by destroy_mp(), and omlc_inject().
{
  oml_unlock(mp->mutexP, mp->name);
}
OmlOutStream* net_stream_new (const char * transport, const char * hostname, const char * service)
Create a new out stream for sending over the network
Parameters
transport string representing the protocol used to establish the connection (oml_strndup()'d locally)
hostname string representing the host to connect to (oml_strndup()'d locally)
service symbolic name or port number of the service to connect to (oml_strndup()'d locally)
Returns
a new OmlOutStream instance
See Also
oml_strndup
Definition at line 80 of file net_stream.c.
References logdebug(), mstring_buf(), mstring_create(), mstring_delete(), mstring_len(), mstring_sprintf(), oml_malloc(), oml_strndup(), and socket_set_non_blocking_mode().
Referenced by create_writer().
{
  MString *dest;
  assert(transport != NULL && hostname != NULL && service != NULL);
  OmlNetOutStream* self = (OmlNetOutStream *)oml_malloc(sizeof(OmlNetOutStream));
  memset(self, 0, sizeof(OmlNetOutStream));
  dest = mstring_create();
  mstring_sprintf(dest, "%s:%s:%s", transport, hostname, service);
  self->dest = (char*)oml_strndup (mstring_buf(dest), mstring_len(dest));
  mstring_delete(dest);
  self->protocol = (char*)oml_strndup (transport, strlen (transport));
  self->host = (char*)oml_strndup (hostname, strlen (hostname));
  self->service = (char*)oml_strndup (service, strlen (service));
  logdebug("%s: Created OmlNetOutStream\n", self->dest);
  socket_set_non_blocking_mode(0);
  /* // Now see if we can connect to server */
  /* if (! open_socket(self)) { */
  /*   free(self); */
  /*   return NULL; */
  /* } */
  self->write = net_stream_write;
  self->close = net_stream_close;
  return (OmlOutStream*)self;
}
int oml_lock (pthread_mutex_t * mutexP, const char * mutexName)
Lock a mutex
Parameters
mutexP pointer to mutex lock
mutexName name of mutex; used for error reporting only
Returns
0 if successful, -1 otherwise
See Also
oml_unlock
Definition at line 52 of file misc.c.
References logwarn().
Referenced by bw_close(), bw_get_write_buf(), bw_push(), bw_push_meta(), mp_lock(), and oml_lock_persistent().
{
  if (mutexP) {
    if (pthread_mutex_lock(mutexP)) {
      logwarn("%s: Couldn't get mutex lock (%s)\n",
          mutexName, strerror(errno));
      return -1;
    }
  }
  return 0;
}
void oml_lock_persistent (pthread_mutex_t * mutexP, const char * mutexName)
Try to obtain a lock on the BufferedWriter until it succeeds
Parameters
mutexP pointer to mutex to unlock
mutexName name of mutex; used for error reporting only
See Also
oml_lock, oml_unlock
Definition at line 86 of file misc.c.
References logwarn(), and oml_lock().
{
  while (oml_lock(mutexP, mutexName)) {
    logwarn("Cannot get lock in %s; will try again soon.\n", mutexName);
    sleep(1);
  }
}
OmlMStream* oml_mp_get_default_ms (OmlMP * mp)
Get or create a default MS for the given MP, reporting all fields, using the OML instance's default samples and intervals and writing to its default writer.
Parameters
mp OmlMP for which to set the filter configuration
Returns
the OmlMstream if successful, NULL otherwise
Definition at line 1153 of file init.c.
References create_default_filters(), create_mstream(), OmlMP::default_ms, OmlClient::default_writer, filter_engine_start(), logdebug(), logerror(), OmlMP::name, OmlClient::sample_count, OmlClient::sample_interval, and OmlMP::streams.
Referenced by omlc_add_mp().
{
  if(NULL == omlc_instance || NULL == mp) {
    return NULL;
  }
  logdebug("Getting default MS for MP %s\n", mp->name);
  if (!mp->default_ms) {
    if(!mp->streams) {
      create_mstream (NULL, mp,
          omlc_instance->default_writer,
          omlc_instance->sample_interval,
          omlc_instance->sample_count );
      if (NULL == mp->streams) {
        logerror("Error creating MS %s\n", mp->name);
        return NULL;
      }
      create_default_filters(mp, mp->streams);
      if (omlc_instance->sample_interval > 0) {
        filter_engine_start(mp->streams);
      }
    }
    mp->default_ms = mp->streams;
  }
  return mp->default_ms;
}
int oml_ms_add_writer (OmlMStream * ms, OmlWriter * w)
Add a new writer to an existing MS
Parameters
ms MStream to add w to
w writer to add to MS
Returns
0 on success, -1 on error (previous writers are preserved)
Definition at line 1052 of file init.c.
References logerror(), OmlMStream::nwriters, oml_realloc(), OmlMStream::table_name, and OmlMStream::writers.
Referenced by create_mstream().
{
  int n;
  OmlWriter **writers;
  if(!ms || !w) {
    logerror("%s: ms (%p) or w (%p) are invalid", __FUNCTION__, ms, w);
    return -1;
  }
  n = ms->nwriters + 1;
  writers = (OmlWriter **)oml_realloc(ms->writers, n*sizeof(OmlWriter*));
  if (!writers) {
    logerror("Cannot (re)allocate memory for %s's writers array\n", ms->table_name);
    return -1;
  }
  writers[n-1] = w;
  ms->writers = writers;
  ms->nwriters = n;
  return 0;
}
void oml_unlock (pthread_mutex_t * mutexP, const char * mutexName)
Unock a mutex
Parameters
mutexP pointer to mutex to unlock
mutexName name of mutex; used for error reporting only
See Also
oml_lock
Definition at line 70 of file misc.c.
References logwarn().
Referenced by bw_close(), bw_get_write_buf(), bw_push(), bw_push_meta(), bw_unlock_buf(), and mp_unlock().
{
  if (mutexP) {
    if (pthread_mutex_unlock(mutexP)) {
      logwarn("%s: Couldn't unlock mutex (%s)\n",
          mutexName, strerror(errno));
    }
  }
}
OmlWriter* text_writer_new (OmlOutStream * out_stream)
Create a new OmlTextWriter
Parameters
out_stream OmlOutStream into which the data should be written
Returns
a pointer to the new OmlTextWriter cast as an OmlWriter
See Also
BufferedWriter
Definition at line 83 of file text_writer.c.
References bw_create(), OmlClient::max_queue, oml_malloc(), and omlc_instance.
Referenced by create_writer().
{
  assert(out_stream != NULL);
  OmlTextWriter* self = (OmlTextWriter *)oml_malloc(sizeof(OmlTextWriter));
  memset(self, 0, sizeof(OmlTextWriter));
  self->bufferedWriter = bw_create(out_stream, omlc_instance->max_queue, 0);
  self->out_stream = out_stream;
  self->meta = owt_meta;
  self->header_done = owt_header_done;
  self->row_start = owt_row_start;
  self->row_end = owt_row_end;
  self->out = owt_row_cols;
  self->close = owt_close;
  return (OmlWriter*)self;
}
const char* validate_app_name (const char * name)
Validate the name of the application.
If the application name contains a '/', it is truncated to the sub-string following the final '/'. If the application name contains any characters other than alphanumeric characters or an underscore, it is declared invalid. The first character must not be a digit. Whitespace is not allowed. An empty string is also not allowed.
Parameters
name the name of the application.
Returns
If the application name is valid, a pointer to the application name, possibly truncated, is returned. If the application name is not valid, returns NULL. If the returned pointer is not NULL, it may be different from name.
Definition at line 1473 of file init.c.
References validate_name().
Referenced by omlc_init().
{
  size_t len = strlen (name);
  const char* p = name + len - 1;
  while (p >= name) {
    if (*p == '/')
      break;
    p--;
  }
  /* Either 1 character before name, or '/': need to move forward 1 character */
  p++;
  if (validate_name (p))
    return p;
  else
    return NULL;
}
Variable Documentation
OmlClient* omlc_instance
Global OmlClient instance
Definition at line 40 of file init.c.
Referenced by bin_writer_new(), omlc_inject(), omlc_inject_metadata(), parse_config(), START_TEST(), and text_writer_new().