oml2: client_handler.h File Reference
client_handler.h File Reference
#include <time.h>
#include <ocomm/o_socket.h>
#include <ocomm/o_eventloop.h>
#include <oml2/oml_writer.h>
#include <mbuf.h>
#include "database.h"
Data Structures
struct _clientHandler
Macros
#define MAX_PROTOCOL_VERSION OML_PROTOCOL_VERSION
#define MIN_PROTOCOL_VERSION 1
#define DEF_NUM_VALUES 30
#define MAX_STRING_SIZE 64
Typedefs
typedef enum _cstate CState
typedef struct _clientHandler ClientHandler
Enumerations
enum _cstate {
C_HEADER, C_BINARY_DATA, C_TEXT_DATA, C_PROTOCOL_ERROR,
C_BINARY_SKIP
}
Functions
ClientHandler * client_handler_new (Socket *new_sock)
void client_handler_free (ClientHandler *self)
Macro Definition Documentation
#define DEF_NUM_VALUES 30
Definition at line 45 of file client_handler.h.
Referenced by client_realloc_tables().
#define MAX_PROTOCOL_VERSION OML_PROTOCOL_VERSION
Definition at line 34 of file client_handler.h.
Referenced by main().
#define MAX_STRING_SIZE 64
Definition at line 46 of file client_handler.h.
Referenced by check_server_prepare_client_handler(), client_handler_new(), and client_handler_update_name().
#define MIN_PROTOCOL_VERSION 1
Definition at line 35 of file client_handler.h.
Referenced by main().
Typedef Documentation
typedef struct _clientHandler ClientHandler
typedef enum _cstate CState
Enumeration Type Documentation
enum _cstate
Enumerator:
C_HEADER
C_BINARY_DATA
C_TEXT_DATA
C_PROTOCOL_ERROR
C_BINARY_SKIP
Definition at line 37 of file client_handler.h.
                     {
  C_HEADER,       // processing header info
  C_BINARY_DATA,  // data is of binary format
  C_TEXT_DATA,    // data in binary format
  C_PROTOCOL_ERROR,// a protocol error occurred --> kick the client
  C_BINARY_SKIP,  // somehow invalid binary message, we need to resync
} CState;
Function Documentation
void client_handler_free (ClientHandler * self)
Definition at line 227 of file client_handler.c.
References database_release(), eventloop_socket_release(), mbuf_destroy(), oml_free(), oml_value_reset(), and socket_free().
{
  if (self->event)
    eventloop_socket_release (self->event);
  if (self->database)
    database_release (self->database);
  if (self->socket)
    socket_free (self->socket);
  if (self->tables)
    oml_free (self->tables);
  if (self->seqno_offsets)
    oml_free (self->seqno_offsets);
  mbuf_destroy (self->mbuf);
  int i, j;
  for (i = 0; i < self->table_count; i++) {
    for (j = 0; j < self->values_vector_counts[i]; j++) {
      oml_value_reset(&self->values_vectors[i][j]);
    }
    oml_free (self->values_vectors[i]);
  }
  oml_free (self->values_vectors);
  oml_free (self->values_vector_counts);
  if (self->sender_name)
    oml_free (self->sender_name);
  if (self->app_name)
    oml_free (self->app_name);
  oml_free (self);
  //  oml_memreport ();
}
ClientHandler* client_handler_new (Socket * new_sock)
Create a client handler and associates it with a Socket object.
Parameters
new_sock Socket object created by accept()ing the connection
Returns
a pointer to the newly created ClientHandler
See Also
on_client_connect()
on_connect()
Definition at line 206 of file client_handler.c.
References C_HEADER, C_TEXT_DATA, client_callback(), eventloop_on_read_in_channel(), MAX_STRING_SIZE, mbuf_create(), oml_malloc(), and status_callback().
{
  ClientHandler* self = oml_malloc(sizeof(ClientHandler));
  if (!self) return NULL;
  memset(self, 0, sizeof(*self));
  self->state = C_HEADER;
  self->content = C_TEXT_DATA;
  self->mbuf = mbuf_create ();
  self->socket = new_sock;
  self->event = eventloop_on_read_in_channel(new_sock, client_callback,
      status_callback, (void*)self);
  strncpy (self->name, self->event->name, MAX_STRING_SIZE);
  const char *event = "Connect";
  const char *message = "";
  client_event_report(self, event, message);
  return self;
}