oml2: client_handler.c File Reference
client_handler.c File Reference
The client handler receives callbacks from the eventloop and processes messages in either OML's text or binary formats.
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "oml2/oml_writer.h"
#include "ocomm/o_log.h"
#include "ocomm/o_socket.h"
#include "ocomm/o_eventloop.h"
#include "mem.h"
#include "monitoring_server.h"
#include "mbuf.h"
#include "oml_value.h"
#include "oml_util.h"
#include "validate.h"
#include "marshal.h"
#include "binary.h"
#include "schema.h"
#include "client_handler.h"
Macros
#define DEF_TABLE_COUNT 10
Functions
void client_callback (SockEvtSource *source, void *handle, void *buf, int buf_size)
const char * client_state_to_s (CState state)
int client_realloc_tables (ClientHandler *self, int ntables)
int client_realloc_values (ClientHandler *self, int idx, int nvalues)
ClientHandler * client_handler_new (Socket *new_sock)
void client_handler_free (ClientHandler *self)
void client_handler_update_name (ClientHandler *self)
void process_schema (ClientHandler *self, char *value)
Detailed Description
The client handler receives callbacks from the eventloop and processes messages in either OML's text or binary formats.
Definition in file client_handler.c.
Macro Definition Documentation
#define DEF_TABLE_COUNT 10
Definition at line 36 of file client_handler.c.
Function Documentation
void client_callback (SockEvtSource * source, void * handle, void * buf, int buf_size)
Callback function called when the socket receive some data
Parameters
source the socket event
handle the client handler
buf data received from the socket
bufsize the size of the data set from the socket
Definition at line 81 of file oml2-proxy-server.c.
References C_PROTOCOL_ERROR, eventloop_socket_remove(), logerror(), mbuf_repack_message(), _sockEvtSource::name, proxy_message_loop(), and socket_close().
{
  (void)source;
  Client* self = (Client*)handle;
  //  logdebug ("'%s': received %d octets of data\n", source->name, buf_size);
  //  logdebug ("'%s': %s\n", source->name, to_octets (buf, buf_size));
  proxy_message_loop (source->name, self, buf, buf_size);
  mbuf_repack_message (self->mbuf);
  if (self->state == C_PROTOCOL_ERROR) {
    socket_close (self->recv_socket);
    logerror("'%s': protocol error, proxy server will disconnect upstream client\n", source->name);
    eventloop_socket_remove (self->recv_event);  // Note:  this free()'s source!
    self->recv_event = NULL;
  }
  fwrite (buf, sizeof (char), buf_size, self->file);
  pthread_mutex_lock (&self->mutex);
  pthread_cond_signal (&self->condvar);
  pthread_mutex_unlock (&self->mutex);
}
void client_handler_free (ClientHandler * self)
Definition at line 227 of file client_handler.c.
References database_release(), eventloop_socket_release(), mbuf_destroy(), oml_free(), oml_value_reset(), and socket_free().
{
  if (self->event)
    eventloop_socket_release (self->event);
  if (self->database)
    database_release (self->database);
  if (self->socket)
    socket_free (self->socket);
  if (self->tables)
    oml_free (self->tables);
  if (self->seqno_offsets)
    oml_free (self->seqno_offsets);
  mbuf_destroy (self->mbuf);
  int i, j;
  for (i = 0; i < self->table_count; i++) {
    for (j = 0; j < self->values_vector_counts[i]; j++) {
      oml_value_reset(&self->values_vectors[i][j]);
    }
    oml_free (self->values_vectors[i]);
  }
  oml_free (self->values_vectors);
  oml_free (self->values_vector_counts);
  if (self->sender_name)
    oml_free (self->sender_name);
  if (self->app_name)
    oml_free (self->app_name);
  oml_free (self);
  //  oml_memreport ();
}
ClientHandler* client_handler_new (Socket * new_sock)
Create a client handler and associates it with a Socket object.
Parameters
new_sock Socket object created by accept()ing the connection
Returns
a pointer to the newly created ClientHandler
See Also
on_client_connect()
on_connect()
Definition at line 206 of file client_handler.c.
References C_HEADER, C_TEXT_DATA, client_callback(), eventloop_on_read_in_channel(), MAX_STRING_SIZE, mbuf_create(), oml_malloc(), and status_callback().
{
  ClientHandler* self = oml_malloc(sizeof(ClientHandler));
  if (!self) return NULL;
  memset(self, 0, sizeof(*self));
  self->state = C_HEADER;
  self->content = C_TEXT_DATA;
  self->mbuf = mbuf_create ();
  self->socket = new_sock;
  self->event = eventloop_on_read_in_channel(new_sock, client_callback,
      status_callback, (void*)self);
  strncpy (self->name, self->event->name, MAX_STRING_SIZE);
  const char *event = "Connect";
  const char *message = "";
  client_event_report(self, event, message);
  return self;
}
void client_handler_update_name (ClientHandler * self)
Definition at line 258 of file client_handler.c.
References logerror(), logwarn(), and MAX_STRING_SIZE.
{
  if (self->database && self->sender_name && self->app_name) {
    snprintf(self->name, MAX_STRING_SIZE, "%s:%s:%s", self->database->name, self->sender_name, self->app_name);
    self->name[MAX_STRING_SIZE-1] = 0;
  } else if (self->event) {
    logwarn("%s: Some identification fields (domain, sender-id or app-name) were missing in the headers\n", self->event->name);
  } else {
    logerror("Unitialised fields in ClientHandler after end of headers; this is probably a bug\n");
  }
}
int client_realloc_tables (ClientHandler * self, int ntables)
Allocate data structures for the ClientHandler's tables.
(Re)Allocate the following:
self->tables – the DbTables themselves
self->seq_no_offsets – the seq_no offet of each table
self->values_vectors – values vectors – one for each table
self->values_vector_counts – size of each of the values_vectors
There should be at least ntables of each of these. For the size of each of the values_vectors[i], see client_realloc_values().
If reallocating, only grow the structures: a call to client_realloc_tables(ch, n) then client_realloc_tables(ch, m) with m<n is safe and won't lose any data. self->table_count is set to ntables at the end of this, as long as there are not already enough tables to accomodate ntables.
Parameters
self the ClientHandler
ntables the maximal number of tables to handle
Returns
0 on success, -1 otherwise
Definition at line 106 of file client_handler.c.
References DEF_NUM_VALUES, logdebug(), oml_calloc(), oml_realloc(), and oml_value_array_init().
Referenced by process_schema().
{
  if (!self || ntables <= 0) {
    return -1;
  }
  if (ntables > self->table_count) {
    int error = 0;
    DbTable **new_tables = oml_realloc (self->tables, ntables*sizeof(DbTable*));
    int *new_so = oml_realloc (self->seqno_offsets, ntables*sizeof(int));
    OmlValue **new_vv = oml_realloc (self->values_vectors, ntables*sizeof(OmlValue*));
    int *new_vv_counts = oml_realloc (self->values_vector_counts, ntables * sizeof (int));
    if (!new_tables || !new_so || !new_vv || !new_vv_counts) {
      logdebug ("%s: Failed to allocate memory for %d more client tables (current %d)\n",
          self->name, (ntables - self->table_count), self->table_count);
      // Don't free anything because whatever got successfully oml_realloc'd is still ok
      error = -1;
    }
    /* Keep whatever succeeded */
    if (new_tables) {
      self->tables = new_tables;
      /* Initialise all new tables to NULL so we know they are not allocated yet */
      memset(&self->tables[self->table_count], 0, (ntables - self->table_count) * sizeof(DbTable*));
    }
    if (new_so) self->seqno_offsets = new_so;
    if (new_vv) self->values_vectors = new_vv;
    if (new_vv_counts) self->values_vector_counts = new_vv_counts;
    /* If the values vectors succeeded, we need to create the new ones */
    if (new_vv && new_vv_counts) {
      int i = 0;
      for (i = self->table_count; i < ntables; i++) {
        self->values_vectors[i] = oml_calloc (DEF_NUM_VALUES, sizeof (OmlValue));
        if (self->values_vectors[i]) {
          self->values_vector_counts[i] = DEF_NUM_VALUES;
          oml_value_array_init(self->values_vectors[i], self->values_vector_counts[i]);
        } else {
          self->values_vector_counts[i] = -1;
          logdebug ("%s: Could not allocate memory for values vector for table index %d\n", self->name, i);
          error = -1;
        }
      }
    }
    if (!error)
      self->table_count = ntables;
    return error;
  }
  return 0;
}
int client_realloc_values (ClientHandler * self, int idx, int nvalues)
(Re)allocate the values vector for the table with the given index, so that it is expanded (never reduced) to hold nvalues elements.
Parameters
self ClientHandler holding the vectors
idx index of the vector to reallocate
nvalues number of values to allow in that vector
Returns
0 on success, -1 otherwise
See Also
client_realloc_tables
Definition at line 170 of file client_handler.c.
References logwarn(), oml_realloc(), and oml_value_array_init().
Referenced by process_schema().
{
  int curnvalues;
  if (!self || idx < 0 || idx > self->table_count || nvalues <= 0)
    return -1;
  curnvalues = self->values_vector_counts[idx];
  if (nvalues > curnvalues) {
    OmlValue *new_values = oml_realloc (self->values_vectors[idx],
        nvalues * sizeof (OmlValue));
    if (!new_values) {
      logwarn("%s: Could not reallocate memory for values for table %d\n",
          self->name, idx);
      return -1;
    }
    oml_value_array_init(&new_values[curnvalues], nvalues - curnvalues);
    self->values_vectors[idx] = new_values;
    self->values_vector_counts[idx] = nvalues;
  }
  return 0;
}
const char* client_state_to_s (CState state)
Definition at line 46 of file client_handler.c.
{
  static const char *states [] = {
    "C_HEADER",
    "C_BINARY_DATA",
    "C_TEXT_DATA",
    "C_PROTOCOL_ERROR"
  };
  return states[state];
}
void process_schema (ClientHandler * self, char * value)
Process schema from string.
Parameters
self pointer to ClientHandler processing the schema
value schema to process
Returns
1 if successful, 0 otherwise
Definition at line 299 of file client_handler.c.
References C_PROTOCOL_ERROR, client_realloc_tables(), client_realloc_values(), database_find_or_create_table(), schema::index, logerror(), loginfo(), logwarn(), schema::name, schema::nfields, DbTable::schema, schema_free(), and schema_from_meta().
{
  struct schema *schema = schema_from_meta (value);
  if (!schema) {
    logerror ("%s: Failure parsing schema '%s'; disconnecting client.\n", self->name, value);
    self->state = C_PROTOCOL_ERROR;
    return;
  }
  char *invalid = NULL;
  if (!validate_schema_names (schema, &invalid)) {
    logerror ("%s: Invalid name '%s' in schema '%s'\n", self->name, invalid, value);
    self->state = C_PROTOCOL_ERROR;
    schema_free (schema);
    return;
  }
  int idx = schema->index;
  loginfo("%s: New MS schema %s\n", self->name, value); /* Value contains the index */
  DbTable* table = database_find_or_create_table(self->database, schema);
  if (table == NULL) {
    logerror("%s: Can't find table '%s' or client schema '%s' doesn't match any of the existing tables.\n",
        self->name, schema->name, value);
    self->state = C_PROTOCOL_ERROR;
    schema_free (schema);
    return;
  }
  schema_free (schema);
  if (client_realloc_tables (self, idx + 1) == -1) {
    logerror ("%s: Failed to allocate memory for table index %d '%s'\n",
        self->name, idx, schema->name);
    return;
  }
  if (self->tables[idx] != NULL) {
    logwarn("%s: Replacing existing MS schema %s with new schema %s\n",
        self->name, self->tables[idx]->schema->name, value);
  }
  self->tables[idx] = table;
  /* Reallocate the values vector if this schema has more columns than can fit already. */
  if (client_realloc_values (self, idx, table->schema->nfields) == -1) {
    logwarn ("%s: Could not allocate values vector of size %d for table index %d '%s'\n",
        self->name, table->schema->nfields, idx, schema->name);
  }
}