oml2: database.h File Reference
database.h File Reference
Interface that storage backend need to implement to be usable by the server.
#include "oml2/omlc.h"
#include "mstring.h"
#include "table_descr.h"
#include "schema.h"
Data Structures
struct DbTable
struct Database
struct db_typemap
Macros
#define DEFAULT_DB_BACKEND "sqlite"
#define MAX_DB_NAME_SIZE 64
#define MAX_TABLE_NAME_SIZE 64
#define MAX_COL_NAME_SIZE 64
#define MAX_TABLE_RENAME 10
Typedefs
typedef struct DbTable DbTable
typedef struct Database Database
typedef OmlValueT(* db_adapter_type_to_oml)(const char *type)
typedef const char *(* db_adapter_oml_to_type)(OmlValueT type)
typedef int(* db_adapter_stmt)(Database *db, const char *stmt)
typedef int(* db_adapter_create)(Database *db)
typedef void(* db_adapter_release)(Database *db)
typedef int(* db_adapter_table_create)(Database *db, DbTable *table, int shallow)
typedef int(* db_adapter_table_create_meta)(Database *db, const char *name)
typedef int(* db_adapter_table_free)(Database *db, DbTable *table)
typedef char *(* db_adapter_prepared_var)(Database *db, unsigned int order)
typedef MString *(* db_adapter_prepare)(Database *db, DbTable *table)
typedef int(* db_adapter_insert)(Database *db, DbTable *table, int sender_id, int seq_no, double time_stamp, OmlValue *values, int value_count)
typedef char *(* db_adapter_get_metadata)(Database *db, const char *key)
typedef int(* db_adapter_set_metadata)(Database *db, const char *key, const char *value)
typedef char *(* db_adapter_get_uri)(Database *db, char *uri, size_t size)
typedef int(* db_add_sender_id)(Database *db, const char *sender_id)
typedef TableDescr *(* db_adapter_get_table_list)(Database *db, int *num_tables)
typedef struct db_typemap db_typemap
Functions
int database_setup_backend (const char *backend)
db_adapter_create database_create_function (const char *backend)
Database * database_find (const char *name)
int database_init (Database *self)
void database_release (Database *database)
void database_cleanup ()
DbTable * database_find_table (Database *database, const char *name)
DbTable * database_find_or_create_table (Database *database, struct schema *schema)
DbTable * database_create_table (Database *database, const struct schema *schema)
void database_table_free (Database *database, DbTable *table)
MString * database_make_sql_insert (Database *db, DbTable *table)
Detailed Description
Interface that storage backend need to implement to be usable by the server.
Definition in file database.h.
Macro Definition Documentation
#define DEFAULT_DB_BACKEND "sqlite"
Definition at line 21 of file database.h.
#define MAX_COL_NAME_SIZE 64
Definition at line 25 of file database.h.
#define MAX_DB_NAME_SIZE 64
Definition at line 23 of file database.h.
Referenced by database_find().
#define MAX_TABLE_NAME_SIZE 64
Definition at line 24 of file database.h.
#define MAX_TABLE_RENAME 10
Limit on the number of times the server tries to generate a table name for a different schema.
XXX: If this is changed, make sure enough memory is allocated in database_find_or_create_table() to hold the new table name in the schema structure.
Definition at line 35 of file database.h.
Referenced by database_find_or_create_table().
Typedef Documentation
typedef struct Database Database
Definition at line 40 of file database.h.
typedef int(* db_adapter_create)(Database *db)
Create a database adapter structures
Parameters
db basic Database structure to associate with the database
Returns
0 if successful, -1 otherwise
Definition at line 73 of file database.h.
typedef char*(* db_adapter_get_metadata)(Database *db, const char *key)
Get data from the metadata table
The returned string should be oml_free'd by the caller when no longer needed.
Parameters
key key to lookup
Returns
an oml_malloc'd string containing the current value for that key
See Also
oml_malloc, oml_free
Definition at line 140 of file database.h.
typedef TableDescr*(* db_adapter_get_table_list)(Database *db, int *num_tables)
Get a list of tables
The list of tables should also include _experiment_metadata and _senders, even though they might not be defined with a schema string.
The caller should oml_free the returned values when no longer needed.
Parameters
db Database to list tables of
[out] num_tables pointer to an integer where the number of tables will be written, set to -1 on error
Returns
a linked list of TableDescr of length *num_tables, or NULL
See Also
table_descr_new, table_descr_list_free
Definition at line 184 of file database.h.
typedef char*(* db_adapter_get_uri)(Database *db, char *uri, size_t size)
Get a URI to this database
Parameters
db Database object
[out] uri output string buffer
size length of uri
Returns
uri on success, NULL otherwise (e.g., uri buffer too small)
Definition at line 157 of file database.h.
typedef int(* db_adapter_insert)(Database *db, DbTable *table, int sender_id, int seq_no, double time_stamp, OmlValue *values, int value_count)
Insert value in the a table of a database
Parameters
db Database to write in
table DbTable to insert data in
sender_id sender ID
seq_no sequence number
time_stamp timestamp of the receiving data
values OmlValue array to insert
value_count number of values
Returns
0 if successful, -1 otherwise
Definition at line 129 of file database.h.
typedef const char*(* db_adapter_oml_to_type)(OmlValueT type)
Mapping from OML to native types.
Parameters
type string describing the SQLite3 type
Returns
the corresponding OmlValueT or OML_UNKNOWN_VALUE if unknown
Definition at line 54 of file database.h.
typedef MString*(* db_adapter_prepare)(Database *db, DbTable *table)
Definition at line 116 of file database.h.
typedef char*(* db_adapter_prepared_var)(Database *db, unsigned int order)
Return a string suitable to represent an unbound variable in a prepared statement.
Parameters
db pointer to Database
order
Returns
an oml_malloc'd string to be freed by the caller, or NULL on error
Definition at line 114 of file database.h.
typedef void(* db_adapter_release)(Database *db)
Release the database.
This is called when the last active client leaves.
Parameters
db Database to release
Definition at line 81 of file database.h.
typedef int(* db_adapter_set_metadata)(Database *db, const char *key, const char *value)
Set data in the metadata table
Parameters
key key to lookup
value a string to set for that key
Returns
0 on success, -1 otherwise
Definition at line 148 of file database.h.
typedef int(* db_adapter_stmt)(Database *db, const char *stmt)
Execute an SQL statement with no data return.
This function executes a statement with the assumption that the result can be ignored; that is, it's not useful for SELECT statements.
Parameters
self the database handle.
stmt the SQL statement to execute.
Returns
0 if successful, -1 if the database reports an error.
Definition at line 66 of file database.h.
typedef int(* db_adapter_table_create)(Database *db, DbTable *table, int shallow)
Create the adapter data structures required to represent a database table.
Parameters
db Database to create the table adapter
table DbTable description of the table to create
shallow if 0, the table should be actively CREATEd in the database backend
Returns
0 on success, -1 on failure
Definition at line 90 of file database.h.
typedef int(* db_adapter_table_create_meta)(Database *db, const char *name)
Create a metadata table
Parameters
db pointer to Database
name name of the database table to create
Returns
0 on success, -1 otherwise
Definition at line 98 of file database.h.
typedef int(* db_adapter_table_free)(Database *db, DbTable *table)
Free an SQLite3 table
Parameters
database Database in which the table is
table DbTable structure to free
Returns
0 on success, <0 otherwise
Definition at line 106 of file database.h.
typedef OmlValueT(* db_adapter_type_to_oml)(const char *type)
Mapping from native to OML types.
Parameters
type string describing the SQLite3 type
Returns
the corresponding OmlValueT or OML_UNKNOWN_VALUE if unknown
Definition at line 47 of file database.h.
typedef int(* db_add_sender_id)(Database *db, const char *sender_id)
Add a new sender to the database, returning its index.
If a sender with the given id already exists, its pre-existing index should be returned. Otherwise, a new sender is added to the table with a new sender id, unique to this experiment.
Parameters
db the Database to which the sender id is being added.
sender_id the sender ID
Returns
the index of the new sender
Definition at line 169 of file database.h.
typedef struct db_typemap db_typemap
A typemapping between OML types and their representation in the database backend
typedef struct DbTable DbTable
Definition at line 39 of file database.h.
Function Documentation
void database_cleanup ()
Close all open databases
Useful when exiting.
Definition at line 318 of file database.c.
References database_release(), logdebug(), and Database::next.
{
  Database *next, *db = first_db;
  logdebug("Cleaning up databases\n");
  while (db) {
    next = db->next;
    database_release(db);
    db = next;
  }
}
db_adapter_create database_create_function (const char * backend)
Get the database-creation function for the selected backend.
Parameters
backend name of the selected backed
Returns
the backend's db_adapter_create function
Definition at line 196 of file database.c.
References LENGTH, and name.
Referenced by database_find(), and database_setup_backend().
{
  size_t i = 0;
  for (i = 0; i < LENGTH (backends); i++)
    if (!strncmp (backend, backends[i].name, strlen (backends[i].name)))
      return backends[i].fn;
  return NULL;
}
DbTable* database_create_table (Database * database, const struct schema * schema)
Create the adapter structure for a table.
Create a new table in the database, with given schema. Register the table with the database, so that database_find_table () will find it. Return a pointer to the table, or NULL on error.
The schema is deep copied, so the caller can safely free the schema.
Note: this function does NOT issue the SQL required to create the table in the actual storage backend.
Parameters
database Database to add the DbTable to
schema schema structure for that tables
Returns
an oml_malloc'd DbTable (already added to database), or NULL on error
See Also
database_find_table, schema_copy, database_release
Definition at line 365 of file database.c.
References Database::first_table, DbTable::next, oml_free(), oml_malloc(), DbTable::schema, and schema_copy().
Referenced by database_find_or_create_table(), database_init(), and dba_table_create_from_schema().
{
  DbTable *table = oml_malloc (sizeof (DbTable));
  if (!table)
    return NULL;
  table->schema = schema_copy (schema);
  if (!table->schema) {
    oml_free (table);
    return NULL;
  }
  table->next = database->first_table;
  database->first_table = table;
  return table;
}
Database* database_find (const char * name)
Find a database instance for name.
If no database with this name exists, a new one is created.
Parameters
name name of the database to find
Returns
a pointer to the database
Definition at line 214 of file database.c.
References database_create_function(), database_init(), database_release(), dbbackend, HOOK_CMD_DBCREATED, HOOK_CMD_DBOPENED, logdebug(), loginfo(), MAX_DB_NAME_SIZE, Database::name, Database::next, oml_free(), oml_malloc(), and Database::ref_count.
Referenced by START_TEST().
{
  Database* db = first_db;
  while (db != NULL) {
    if (!strcmp(name, db->name)) {
      loginfo ("%s: Database already open (%d client%s)\n",
                name, db->ref_count, db->ref_count>1?"s":"");
      db->ref_count++;
      return db;
    }
    db = db->next;
  }
  // need to create a new one
  Database *self = oml_malloc(sizeof(Database));
  logdebug("%s: Creating or opening database\n", name);
  strncpy(self->name, name, MAX_DB_NAME_SIZE);
  self->ref_count = 1;
  self->create = database_create_function (dbbackend);
  if (self->create (self)) {
    oml_free(self);
    return NULL;
  }
  if (database_init (self) == -1) {
    database_release(self);
    oml_free (self);
    return NULL;
  }
  char *start_time_str = self->get_metadata (self, "start_time");
  if (start_time_str == NULL) {
    /* No start time: this is probably a new database */
    database_hook_send_event(self, HOOK_CMD_DBCREATED);
  } else {
    database_hook_send_event(self, HOOK_CMD_DBOPENED);
    self->start_time = strtol (start_time_str, NULL, 0);
    oml_free (start_time_str);
    logdebug("%s: Retrieved start-time = %lu\n", name, self->start_time);
  }
  // hook this one into the list of active databases
  self->next = first_db;
  first_db = self;
  return self;
}
DbTable* database_find_or_create_table (Database * database, struct schema * schema)
Search a Database's registered DbTables for one matchng the given schema.
If none is found, the table is created. If one is found, but the schema differs, try to append a number to the name (up to MAX_TABLE_RENAME), create that table, and update the schema.
If the table search/creation is successful, the returned DbTable is already added to the list of the Database.
Parameters
database Database to search
schema schema structure for the table to add
Returns
a newly created DbTable for that table, or NULL on error
See Also
MAX_TABLE_RENAME, database_create_table
Definition at line 396 of file database.c.
References database_create_table(), database_find_table(), database_table_free(), Database::first_table, logdebug(), logerror(), logwarn(), MAX_TABLE_RENAME, schema::name, Database::name, DbTable::next, oml_free(), oml_realloc(), oml_strndup(), DbTable::schema, schema_copy(), schema_diff(), schema_free(), and Database::table_create.
Referenced by process_schema().
{
  if (database == NULL) return NULL;
  if (schema == NULL) return NULL;
  DbTable *table = NULL;
  struct schema *s = schema_copy(schema);
  int i = 1;
  int diff = 0, tnlen;
  tnlen = strlen(schema->name);
  do {
    table = database_find_table (database, s->name);
    if (table) {
      diff = schema_diff (s, table->schema);
      if (!diff) {
        schema_free(s);
        return table;
      } else if (diff == -1) {
        logerror ("%s: Schema error table '%s'\n", database->name, s->name);
        logdebug (" One of the server schema %p or the client schema %p is probably NULL\n", s, table->schema);
      } else if (diff > 0) {
        logdebug ("%s: Schema differ for table '%s', at or after column %d\n",
            database->name, s->name, diff);
      }
      if (i == 1) {
        /* First time we need to increase the size */
        /* Add space for 2 characters and null byte, that is up to '_9', with MAX_TABLE_RENAME = 10 */
        s->name = oml_realloc(s->name, tnlen + 3);
        strncpy(s->name, schema->name, tnlen);
      }
      snprintf(&s->name[tnlen], 3, "_%d", ++i);
    }
  } while(table && diff && (i < MAX_TABLE_RENAME));
  if (table && diff) {
    logerror ("%s: Too many (>%d) tables named '%s_x', giving up. Please use the rename attribute of <mp /> tags.\n",
      database->name, MAX_TABLE_RENAME, schema->name);
    schema_free(s);
    return NULL;
  }
  if(i>1) {
    /* We had to change the table name*/
    logwarn("%s: Creating table '%s' for new stream '%s' with incompatible schema\n", database->name, s->name, schema->name);
    oml_free(schema->name);
    schema->name = oml_strndup(s->name, tnlen+3);
  }
  schema_free(s);
  /* No table by that name exists, so we create it */
  table = database_create_table (database, schema);
  if (!table)
    return NULL;
  if (database->table_create (database, table, 0)) {
    logerror ("%s: Couldn't create table '%s'\n", database->name, schema->name);
    /* Unlink the table from the experiment's list */
    DbTable* t = database->first_table;
    if (t == table)
      database->first_table = t->next;
    else {
      while (t && t->next != table)
        t = t->next;
      if (t && t->next)
        t->next = t->next->next;
    }
    database_table_free (database, table);
    return NULL;
  }
  return table;
}
DbTable* database_find_table (Database * database, const char * name)
Definition at line 335 of file database.c.
References Database::first_table, schema::name, DbTable::next, and DbTable::schema.
Referenced by database_find_or_create_table().
{
  DbTable *table = database->first_table;
  while (table) {
    if (!strcmp (table->schema->name, name))
      return table;
    table = table->next;
  }
  return NULL;
}
int database_init (Database * database)
Initialise adapters for a new database
If the database already has tables, initialise the adapters.
Parameters
database main Database object
Returns
0 on success, -1 otherwise
See Also
database_create_table, db_adapter_table_create
Definition at line 517 of file database.c.
References database_create_table(), database_table_free(), Database::get_table_list, LENGTH, logdebug(), logerror(), logwarn(), Database::name, TableDescr::next, schema_copy(), Database::semantic, Database::table_create, Database::table_create_meta, table_descr_have_table(), and table_descr_list_free().
Referenced by database_find().
{
  int num_tables;
  TableDescr* tables = database->get_table_list (database, &num_tables);
  if (!database->semantic)
  {
    TableDescr* td = tables;
    if (num_tables == -1)
      return -1;
    logdebug("%s: Got table list with %d tables in it\n", database->name, num_tables);
    int i = 0;
    for (i = 0; i < num_tables; i++, td = td->next) {
      if (td->schema) {
        struct schema *schema = schema_copy (td->schema);
        DbTable *table = database_create_table (database, schema);
        if (!table) {
          logwarn ("%s: Failed to create table '%s'\n",
                   database->name, td->name);
          continue;
        }
        /* Create the required table data structures, but don't do SQL CREATE TABLE */
        if (database->table_create (database, table, 1) == -1) {
          logwarn ("%s: Failed to create adapter structures for table '%s'\n",
                   database->name, td->name);
          database_table_free (database, table);
        }
      }
    }
    /* Create default tables if they are not already present in the 'tables' list */
    const char *meta_tables [] = { "_senders", "_experiment_metadata" };
    size_t j;
    for (j = 0; j < LENGTH(meta_tables); j++) {
      if (!table_descr_have_table (tables, meta_tables[j])) {
        if (database->table_create_meta (database, meta_tables[j])) {
          table_descr_list_free (tables);
          logerror("%s: Could not create default table %s\n",
              database->name, meta_tables[j]);
          return -1;
        }
      }
    }
    table_descr_list_free (tables);
  }
  return 0;
}
MString* database_make_sql_insert (Database * db, DbTable * table)
Prepare an INSERT statement for a given table
The returned value is to be destroyed by the caller.
Parameters
db Database
table DbTable adapter for the target SQLite3 table
Returns
an MString containing the prepared statement, or NULL on error
See Also
mstring_create, mstring_delete
Definition at line 502 of file database.c.
{
    return db->prepare(db,table);
}
void database_release (Database * self)
One client no longer uses this database. If this was the last client checking out, close database.
Parameters
self the database to release
See Also
db_adapter_release
Definition at line 270 of file database.c.
References database_table_free(), HOOK_CMD_DBCLOSED, logerror(), loginfo(), DbTable::next, Database::next, and oml_free().
Referenced by client_handler_free(), database_cleanup(), database_find(), and START_TEST().
{
  if (self == NULL) {
    logerror("NONE: Trying to release a NULL database.\n");
    return;
  }
  if (--self->ref_count > 0) return; // still in use
  // unlink DB
  Database* db_p = first_db;
  Database* prev_p = NULL;
  while (db_p != NULL && db_p != self) {
    prev_p = db_p;
    db_p = db_p->next;
  }
  if (db_p == NULL) {
    logerror("%s:  Trying to release an unknown database\n", self->name);
    return;
  }
  if (prev_p == NULL)
    first_db = self->next; // was first
  else
    prev_p->next = self->next;
  // no longer needed
  DbTable* t_p = self->first_table;
  while (t_p != NULL) {
    DbTable* t = t_p->next;
    /* Release the backend storage for this table */
    self->table_free (self, t_p);
    /* Release the table */
    database_table_free(self, t_p);
    t_p = t;
  }
  loginfo ("%s: Closing database\n", self->name);
  self->release (self);
  database_hook_send_event(self, HOOK_CMD_DBCLOSED);
  oml_free(self);
}
int database_setup_backend (const char * backend)
Setup the selected database backend.
Must be called after dropping privileges.
Parameters
backend name of the selected backend
Returns
0 on success, -1 otherwise
See Also
sq3_backend_setup, psql_backend_setup
Definition at line 131 of file database.c.
References database_create_function(), fuseki_backend_setup(), logdebug(), logerror(), psql_backend_setup(), sq3_backend_setup(), and virtuoso_backend_setup().
Referenced by main().
{
  logdebug ("Database backend: '%s'\n", backend);
  if (!database_create_function (backend)) {
    logerror ("Unknown database backend '%s' (valid backends: %s)\n",
         backend, database_valid_backends ());
    return -1;
  }
  if (!strcmp (backend, "sqlite")) {
    if(sq3_backend_setup ()) return -1;
#if HAVE_LIBPQ
  } else if (!strcmp (backend, "postgresql")) {
    if(psql_backend_setup ()) return -1;
#endif
  } else if (!strcmp (backend, "fuseki")) {
    if(fuseki_backend_setup ()) return -1;
  } else if (!strcmp (backend, "virtuoso")) {
    if(virtuoso_backend_setup ()) return -1;
  }
  return 0;
}
void database_table_free (Database * database, DbTable * table)
Definition at line 479 of file database.c.
References logdebug(), logwarn(), schema::name, Database::name, oml_free(), DbTable::schema, and schema_free().
Referenced by database_find_or_create_table(), database_init(), and database_release().
{
  if (database && table) {
    logdebug("%s: Freeing table '%s'\n", database->name, table->schema->name);
    schema_free (table->schema);
    oml_free(table);
  } else {
    logwarn("%s: Tried to free a NULL table (or database was NULL).\n",
            (database ? database->name : "NONE"));
  }
}