oml2: database_adapter.c File Reference
database_adapter.c File Reference
#include <string.h>
#include "oml_util.h"
#include "schema.h"
#include "database.h"
#include "database_adapter.h"
Functions
int dba_table_create_from_meta (Database *db, const char *meta)
int dba_table_create_from_schema (Database *db, const struct schema *schema)
int dba_table_create_meta (Database *db, const char *name)
int dba_begin_transaction (Database *db)
int dba_end_transaction (Database *db)
int dba_reopen_transaction (Database *db)
Function Documentation
int dba_begin_transaction (Database * db)
Open a transaction with the database server.
Parameters
db Database to work with
Returns
the success value of running the statement
See Also
db_adapter_stmt
Definition at line 145 of file database_adapter.c.
References Database::semantic, sql, and Database::stmt.
Referenced by dba_reopen_transaction(), fuseki_create_database(), psql_create_database(), sq3_create_database(), and virtuoso_create_database().
{
  if (!db->semantic)
  {
    const char sql[] = "BEGIN TRANSACTION;";
    return db->stmt (db, sql);
  }
  else return 0;
}
int dba_end_transaction (Database * db)
Close the current transaction with the database server.
Parameters
db Database to work with
Returns
the success value of running the statement
See Also
db_adapter_stmt
Definition at line 161 of file database_adapter.c.
References Database::semantic, sql, and Database::stmt.
Referenced by dba_reopen_transaction().
{
  if (!db->semantic)
  {
    const char sql[] = "END TRANSACTION;";
    return db->stmt (db, sql);
  }
  else return 0;
}
int dba_reopen_transaction (Database * db)
Close the current transaction and start a new one.
Parameters
db Database to work with
Returns
0 on success, -1 otherwise
See Also
dba_begin_transaction, dba_end_transaction, db_adapter_stmt
Definition at line 177 of file database_adapter.c.
References dba_begin_transaction(), and dba_end_transaction().
{
  if (dba_end_transaction (db)) { return -1; }
  if (dba_begin_transaction (db)) { return -1; }
  return 0;
}
int dba_table_create_from_meta (Database * db, const char * meta)
Create a table in the specified database following the given schema string
Parameters
db Database to create table in
meta schema string (from metadata) to generate table from
Returns
0 on success, -1 otherwise
Definition at line 42 of file database_adapter.c.
References dba_table_create_from_schema(), schema_free(), and schema_from_meta().
Referenced by dba_table_create_meta().
{
  int ret;
  struct schema* s = NULL;
  s = schema_from_meta(meta);
  if (!s) {
    return -1;
  }
  ret = dba_table_create_from_schema(db, s);
  schema_free(s);
  return ret;
}
int dba_table_create_from_schema (Database * db, const struct schema * schema)
Create a table in the specified database following the given schema
Parameters
db Database to create table in
meta schema to generate table from
Returns
0 on success, -1 otherwise
Definition at line 66 of file database_adapter.c.
References Database::backend_name, database_create_table(), schema::index, logerror(), mstring_buf(), mstring_create(), mstring_delete(), mstring_sprintf(), schema::name, Database::name, Database::o2t, oml_free(), schema_copy(), schema_free(), schema_to_meta(), schema_to_sql(), Database::set_metadata, Database::stmt, and Database::table_create.
Referenced by dba_table_create_from_meta().
{
  DbTable *table;
  MString *create = NULL, *meta_skey = NULL;;
  char *meta_svalue = NULL;
  struct schema *schema_meta;
  create = schema_to_sql (schema, db->o2t);
  if (!create) {
    logerror("%s:%s: Failed to build SQL CREATE TABLE statement string for schema '%s'\n",
        db->backend_name, db->name, schema_to_meta(schema));
    goto fail_exit;
  }
  if (db->stmt(db, mstring_buf(create))) {
    goto fail_exit;
  }
  /* FIXME: Create prepared insertion statement here. See #1056. */
  if(!(table = database_create_table(db, schema))) {
    logerror("%s:%s: Failed to register generic adapter for newly created table for schema '%s'\n",
        db->backend_name, db->name, schema_to_meta(schema));
    goto fail_exit;
  } else if (db->table_create(db, table, 1)) { /* XXX: table_create calls us when shallow=0 */
    logerror("%s:%s: Failed to register specific adapter for newly created table for schema '%s'\n",
        db->backend_name, db->name, schema_to_meta(schema));
    goto fail_exit;
  }
  /* The schema index is irrelevant in the metadata, temporarily drop it */
  schema_meta = schema_copy(schema);
  schema_meta->index = -1;
  meta_skey = mstring_create ();
  mstring_sprintf (meta_skey, "table_%s", schema->name);
  meta_svalue = schema_to_meta (schema);
  db->set_metadata (db, mstring_buf (meta_skey), meta_svalue);
  oml_free(meta_svalue);
  mstring_delete(meta_skey);
  schema_free(schema_meta);
  if (create) { mstring_delete(create); }
  return 0;
fail_exit:
  if (create) { mstring_delete(create); }
  return -1;
}
int dba_table_create_meta (Database * db, const char * name)
Create the metadata tables using this backend's SQL wrapper
See Also
db_adapter_table_create_meta
Definition at line 116 of file database_adapter.c.
References Database::backend_name, dba_table_create_from_meta(), LENGTH, logdebug(), logwarn(), Database::name, sql, and Database::stmt.
Referenced by fuseki_create_database(), psql_create_database(), sq3_create_database(), and virtuoso_create_database().
{
  int i = 0;
  for (i = 0; i < LENGTH (meta_tables); i++) {
    if (strcmp (meta_tables[i].name, name) == 0) {
      if (meta_tables[i].sql) {
        logdebug("%s:%s: Creating default table %s from SQL '%s'\n",
            db->backend_name, db->name,
            name, meta_tables[i].sql);
        return db->stmt (db, meta_tables[i].sql);
      } else if (meta_tables[i].schema) {
        logdebug("%s:%s: Creating default table %s from schema '%s'\n",
            db->backend_name, db->name,
            name, meta_tables[i].schema);
        return dba_table_create_from_meta(db, meta_tables[i].schema);
      } else {
        logwarn ("%s:%s: Default definition found for %s, but it is not complete\n", name);
      }
    }
  }
  return -1;
}
Variable Documentation
const char* name
Definition at line 22 of file database_adapter.c.
const char* schema
Definition at line 24 of file database_adapter.c.
Referenced by schema_from_meta(), schema_from_sql(), schema_new(), and table_descr_new().
const char* sql
Definition at line 23 of file database_adapter.c.
Referenced by dba_begin_transaction(), dba_end_transaction(), and dba_table_create_meta().