oml2: delta_filter.c File Reference
delta_filter.c File Reference
Implements a filter which returns the difference between the previously reported and current sample values. While it's at it, it also reports the current (i.e. last) value.
#include <stdlib.h>
#include <string.h>
#include "oml2/omlc.h"
#include "oml2/oml_filter.h"
#include "ocomm/o_log.h"
#include "oml_value.h"
#include "delta_filter.h"
Macros
#define FILTER_NAME "delta"
Typedefs
typedef struct
OmlDeltaFilterInstanceData InstanceData
Functions
void * omlf_delta_new (OmlValueT type, OmlValue *result)
void omlf_register_filter_delta (void)
Detailed Description
Implements a filter which returns the difference between the previously reported and current sample values. While it's at it, it also reports the current (i.e. last) value.
Definition in file delta_filter.c.
Macro Definition Documentation
#define FILTER_NAME "delta"
Definition at line 25 of file delta_filter.c.
Referenced by omlf_delta_new(), and omlf_register_filter_delta().
Typedef Documentation
typedef struct OmlDeltaFilterInstanceData InstanceData
Definition at line 27 of file delta_filter.c.
Function Documentation
void* omlf_delta_new (OmlValueT type, OmlValue * result)
Definition at line 39 of file delta_filter.c.
References FILTER_NAME, logerror(), oml_malloc(), omlc_is_numeric_type, and OmlDeltaFilterInstanceData::result.
Referenced by omlf_register_filter_delta().
  {
  if (! omlc_is_numeric_type (type)) {
    logerror ("%s filter: Can only handle numeric parameters\n", FILTER_NAME);
    return NULL;
  }
  InstanceData* self = (InstanceData *)oml_malloc(sizeof(InstanceData));
  if (self) {
    memset(self, 0, sizeof(InstanceData));
    self->previous = 0.;
    self->current = 0.;
    self->sample_count = 0;
    self->result = result;
  } else {
    logerror ("%s filter: Could not allocate %d bytes for instance data\n",
        FILTER_NAME,
        sizeof(InstanceData));
    return NULL;
  }
  return self;
}
void omlf_register_filter_delta (void)
Definition at line 68 of file delta_filter.c.
References FILTER_NAME, OML_DOUBLE_VALUE, omlf_delta_new(), and omlf_register_filter().
Referenced by register_builtin_filters().
{
  OmlFilterDef def [] =
    {
      { "delta", OML_DOUBLE_VALUE },
      { "last", OML_DOUBLE_VALUE },
      { NULL, 0 }
    };
  omlf_register_filter (FILTER_NAME,
            omlf_delta_new,
            NULL,
            sample,
            process,
            newwindow,
            NULL,
            def);
}