oml2: factory.c File Reference
factory.c File Reference
Implements the functions to create and manage filters.
#include <string.h>
#include <stdlib.h>
#include "oml2/omlc.h"
#include "ocomm/o_log.h"
#include "mem.h"
#include "oml_value.h"
#include "factory.h"
Data Structures
struct FilterType
Typedefs
typedef struct FilterType FilterType
Functions
const char * next_filter_name (void)
OmlFilter * create_filter (const char *filter_type, const char *instance_name, OmlValueT type, OMLSemDef *concepts, int index)
OmlFilter * destroy_filter (OmlFilter *f)
int omlf_register_filter (const char *filter_name, oml_filter_create create, oml_filter_set set, oml_filter_input input, oml_filter_output output, oml_filter_newwindow newwindow, oml_filter_meta meta, OmlFilterDef *filter_def)
void omlf_register_filter_average (void)
void omlf_register_filter_first (void)
void omlf_register_filter_last (void)
void omlf_register_filter_histogram (void)
void omlf_register_filter_stddev (void)
void omlf_register_filter_sum (void)
void omlf_register_filter_delta (void)
void register_builtin_filters ()
void unregister_filters ()
Detailed Description
Implements the functions to create and manage filters.
Definition in file factory.c.
Typedef Documentation
typedef struct FilterType FilterType
Function Documentation
OmlFilter* create_filter (const char * filter_type, const char * instance_name, OmlValueT type, OMLSemDef * concepts, int index)
Create an instance of a filter of type 'fname'.
Definition at line 91 of file factory.c.
References OmlFilter::concepts, FilterType::create, FilterType::definition, OmlFilter::definition, OmlFilter::index, FilterType::input, OmlFilter::input, OmlFilter::input_type, OmlFilter::instance_data, logerror(), FilterType::meta, OmlFilter::meta, FilterType::name, OmlFilter::name, FilterType::newwindow, OmlFilter::newwindow, FilterType::next, oml_malloc(), FilterType::output, OmlFilter::output, FilterType::output_count, OmlFilter::output_count, OmlFilter::result, FilterType::set, OmlFilter::set, and type.
Referenced by create_default_filter(), and START_TEST().
  {
  FilterType* ft = filter_types;
  for (; ft != NULL; ft = ft->next) {
    if (strcmp (filter_type, ft->name) == 0) break;
  }
  if (ft == NULL) {
    logerror ("Unknown filter '%s'.\n", filter_type);
    return NULL;  // nothing found
  }
  OmlFilter * f = (OmlFilter*)oml_malloc(sizeof(OmlFilter));
  memset(f, 0, sizeof(OmlFilter));
  strncpy (f->name, instance_name, sizeof(f->name));
  if (f->name[sizeof(f->name)-1] != '\0')
    f->name[sizeof(f->name)-1] = '\0';
  f->index = index;
  f->concepts = concepts;
  f->set = ft->set;
  f->input_type = type;
  f->input = ft->input;
  f->output = ft->output;
  f->newwindow = ft->newwindow;
  f->meta = ft->meta;
  f->definition = ft->definition;   /* FIXME:  Copy and substitute OML_INPUT_VALUE types */
  f->output_count = ft->output_count;
  f->result = create_filter_result_vector (f->definition, type, ft->output_count);
  f->instance_data = ft->create(type, f->result);
  return f;
}
OmlFilter* destroy_filter (OmlFilter * f)
Destroy a filter and free its memory.
This function is designed so it can be used in a while loop to clean up the entire linked list:
while((f=destroy_ms(f)));
Parameters
f pointer to the filter to destroy
Returns
f->next (can be NULL)
Definition at line 139 of file factory.c.
References OmlFilter::instance_data, logdebug(), OmlFilter::name, FilterType::next, OmlFilter::next, oml_free(), oml_value_array_reset(), OmlFilter::output_count, and OmlFilter::result.
Referenced by destroy_ms(), and START_TEST().
{
  OmlFilter *next;
  if (!f)
    return NULL;
  logdebug("Destroying filter %s at %p\n", f->name, f);
  next = f->next;
  if(f->result) {
    oml_value_array_reset(f->result, f->output_count);
    oml_free(f->result);
  }
  if(f->instance_data)
    oml_free(f->instance_data);
  oml_free(f);
  return next;
}
const char* next_filter_name (void)
Definition at line 41 of file factory.c.
References FilterType::name, name, and FilterType::next.
{
  static FilterType* ft = NULL;
  static int done = 1;
  const char* name;
  if (ft == NULL && done)
    {
      done = 0;
      ft = filter_types;
    }
  else if (ft == NULL)
    {
      done = 1;
      return NULL;
    }
  name = ft->name;
  ft = ft->next;
  return name;
}
int omlf_register_filter (const char * filter_name, oml_filter_create create, oml_filter_set set, oml_filter_input input, oml_filter_output output, oml_filter_newwindow newwindow, oml_filter_meta meta, OmlFilterDef * filter_def)
Register an instance of a filter of type filter_name.
Definition at line 210 of file factory.c.
References FilterType::create, FilterType::definition, FilterType::input, input, logerror(), FilterType::meta, FilterType::name, OmlFilterDef::name, FilterType::newwindow, FilterType::next, oml_malloc(), FilterType::output, FilterType::output_count, FilterType::set, and OmlFilterDef::type.
Referenced by omlf_register_filter_average(), omlf_register_filter_delta(), omlf_register_filter_first(), omlf_register_filter_histogram(), omlf_register_filter_last(), omlf_register_filter_stddev(), and omlf_register_filter_sum().
{
  if (create == NULL || input == NULL || output == NULL) {
    logerror ("Filter %s needs a create function, an input function, and an output function (one of them was null).\n", filter_name);
    return -1;
  }
  if (filter_def == NULL) {
    logerror ("Filter %s needs a filter definition (got a null definition).\n", filter_name);
    return -1;
  }
  FilterType* ft = (FilterType*)oml_malloc(sizeof(FilterType));
  ft->name = filter_name;
  ft->create = create;
  ft->set = set;
  ft->input = input;
  ft->output = output;
  ft->newwindow = newwindow;
  ft->output_count = 0;
  OmlFilterDef* dp = filter_def;
  for (; !(dp->name == NULL && dp->type == 0); dp++)
    ft->output_count++;
  ft->definition = copy_filter_definition (filter_def, ft->output_count);
  if (set == NULL)
      ft->set = default_filter_set;
  if (meta == NULL)
    ft->meta = default_filter_meta;
  else
    ft->meta = meta;
  ft->next = filter_types;
  filter_types = ft;
  return 0;
}
void omlf_register_filter_average (void)
Definition at line 67 of file average_filter.c.
References FILTER_NAME, OML_DOUBLE_VALUE, omlf_average_new(), and omlf_register_filter().
Referenced by register_builtin_filters().
{
  OmlFilterDef def [] =
    {
      { "avg", OML_DOUBLE_VALUE },
      { "min", OML_DOUBLE_VALUE },
      { "max", OML_DOUBLE_VALUE },
      { NULL, 0 }
    };
  omlf_register_filter (FILTER_NAME,
                        omlf_average_new,
                        NULL,
                        sample,
                        process,
                        newwindow,
                        NULL,
                        def);
}
void omlf_register_filter_delta (void)
Definition at line 68 of file delta_filter.c.
References FILTER_NAME, OML_DOUBLE_VALUE, omlf_delta_new(), and omlf_register_filter().
Referenced by register_builtin_filters().
{
  OmlFilterDef def [] =
    {
      { "delta", OML_DOUBLE_VALUE },
      { "last", OML_DOUBLE_VALUE },
      { NULL, 0 }
    };
  omlf_register_filter (FILTER_NAME,
            omlf_delta_new,
            NULL,
            sample,
            process,
            newwindow,
            NULL,
            def);
}
void omlf_register_filter_first (void)
Definition at line 64 of file first_filter.c.
References FILTER_NAME, OML_INPUT_VALUE, omlf_first_new(), and omlf_register_filter().
Referenced by register_builtin_filters().
{
  OmlFilterDef def [] =
    {
      { "first", OML_INPUT_VALUE },
      { NULL, 0 }
    };
  omlf_register_filter (FILTER_NAME,
            omlf_first_new,
            NULL,
            sample,
            process,
            newwindow,
            meta,
            def);
}
void omlf_register_filter_histogram (void)
Definition at line 78 of file histogram_filter.c.
References FILTER_NAME, OML_DOUBLE_VALUE, omlf_histogram_new(), and omlf_register_filter().
{
  OmlFilterDef def [] =
    {
      { "avg", OML_DOUBLE_VALUE },
      { "min", OML_DOUBLE_VALUE },
      { "max", OML_DOUBLE_VALUE },
      { NULL, 0 }
    };
  omlf_register_filter (FILTER_NAME,
            omlf_histogram_new,
            NULL,
            sample,
            process,
            newwindow,
            NULL,
            def);
}
void omlf_register_filter_last (void)
Definition at line 59 of file last_filter.c.
References FILTER_NAME, OML_INPUT_VALUE, omlf_last_new(), and omlf_register_filter().
Referenced by register_builtin_filters().
{
  OmlFilterDef def [] =
    {
      { "last", OML_INPUT_VALUE },
      { NULL, 0 }
    };
  omlf_register_filter (FILTER_NAME,
            omlf_last_new,
            NULL,
            sample,
            process,
            newwindow,
            NULL,
            def);
}
void omlf_register_filter_stddev (void)
Definition at line 90 of file stddev_filter.c.
References FILTER_NAME, input, OML_DOUBLE_VALUE, omlf_register_filter(), and omlf_stddev_new().
Referenced by register_builtin_filters().
{
  OmlFilterDef def [] =
    {
      { "stddev", OML_DOUBLE_VALUE },
      { "variance", OML_DOUBLE_VALUE },
      { NULL, 0 }
    };
  omlf_register_filter (FILTER_NAME,
                        omlf_stddev_new,
                        NULL,
                        input,
                        output,
                        newwindow,
                        NULL,
                        def);
}
void omlf_register_filter_sum (void)
Definition at line 65 of file sum_filter.c.
References FILTER_NAME, OML_DOUBLE_VALUE, omlf_register_filter(), and omlf_sum_new().
Referenced by register_builtin_filters().
{
  OmlFilterDef def [] =
    {
      { "sum", OML_DOUBLE_VALUE },
      { NULL, 0 }
    };
  omlf_register_filter (FILTER_NAME,
                        omlf_sum_new,
                        NULL,
                        sample,
                        process,
                        newwindow,
                        NULL,
                        def);
}
void register_builtin_filters (void)
Register all built-in filters.
Definition at line 270 of file factory.c.
References omlf_register_filter_average(), omlf_register_filter_delta(), omlf_register_filter_first(), omlf_register_filter_last(), omlf_register_filter_stddev(), and omlf_register_filter_sum().
Referenced by filter_setup(), and omlc_init().
{
  omlf_register_filter_average ();
  omlf_register_filter_first ();
  omlf_register_filter_last ();
  //  omlf_register_filter_histogram ();
  omlf_register_filter_stddev ();
  omlf_register_filter_sum ();
  omlf_register_filter_delta ();
}
void unregister_filters (void)
Unregister all built-in filters.
Definition at line 283 of file factory.c.
References FilterType::definition, logdebug(), FilterType::next, and oml_free().
Referenced by omlc_close().
{
  FilterType* ft = filter_types;
  logdebug("Unregistering filters\n");
  while(ft) {
    filter_types = ft->next;
    oml_free(ft->definition);
    oml_free(ft);
    ft = filter_types;
  };
}