oml2: factory.h File Reference
factory.h File Reference
#include <oml2/oml_filter.h>
Functions
const char * next_filter_name (void)
void register_builtin_filters (void)
void unregister_filters (void)
OmlFilter * create_filter (const char *filter_type, const char *instance_name, OmlValueT type, OMLSemDef *concepts, int index)
OmlFilter * destroy_filter (OmlFilter *f)
Function Documentation
OmlFilter* create_filter (const char * filter_type, const char * instance_name, OmlValueT type, OMLSemDef * concepts, int index)
Create an instance of a filter of type 'fname'.
Definition at line 91 of file factory.c.
References OmlFilter::concepts, FilterType::create, FilterType::definition, OmlFilter::definition, OmlFilter::index, FilterType::input, OmlFilter::input, OmlFilter::input_type, OmlFilter::instance_data, logerror(), FilterType::meta, OmlFilter::meta, FilterType::name, OmlFilter::name, FilterType::newwindow, OmlFilter::newwindow, FilterType::next, oml_malloc(), FilterType::output, OmlFilter::output, FilterType::output_count, OmlFilter::output_count, OmlFilter::result, FilterType::set, OmlFilter::set, and type.
Referenced by create_default_filter(), and START_TEST().
  {
  FilterType* ft = filter_types;
  for (; ft != NULL; ft = ft->next) {
    if (strcmp (filter_type, ft->name) == 0) break;
  }
  if (ft == NULL) {
    logerror ("Unknown filter '%s'.\n", filter_type);
    return NULL;  // nothing found
  }
  OmlFilter * f = (OmlFilter*)oml_malloc(sizeof(OmlFilter));
  memset(f, 0, sizeof(OmlFilter));
  strncpy (f->name, instance_name, sizeof(f->name));
  if (f->name[sizeof(f->name)-1] != '\0')
    f->name[sizeof(f->name)-1] = '\0';
  f->index = index;
  f->concepts = concepts;
  f->set = ft->set;
  f->input_type = type;
  f->input = ft->input;
  f->output = ft->output;
  f->newwindow = ft->newwindow;
  f->meta = ft->meta;
  f->definition = ft->definition;   /* FIXME:  Copy and substitute OML_INPUT_VALUE types */
  f->output_count = ft->output_count;
  f->result = create_filter_result_vector (f->definition, type, ft->output_count);
  f->instance_data = ft->create(type, f->result);
  return f;
}
OmlFilter* destroy_filter (OmlFilter * f)
Destroy a filter and free its memory.
This function is designed so it can be used in a while loop to clean up the entire linked list:
while((f=destroy_ms(f)));
Parameters
f pointer to the filter to destroy
Returns
f->next (can be NULL)
Definition at line 139 of file factory.c.
References OmlFilter::instance_data, logdebug(), OmlFilter::name, FilterType::next, OmlFilter::next, oml_free(), oml_value_array_reset(), OmlFilter::output_count, and OmlFilter::result.
Referenced by destroy_ms(), and START_TEST().
{
  OmlFilter *next;
  if (!f)
    return NULL;
  logdebug("Destroying filter %s at %p\n", f->name, f);
  next = f->next;
  if(f->result) {
    oml_value_array_reset(f->result, f->output_count);
    oml_free(f->result);
  }
  if(f->instance_data)
    oml_free(f->instance_data);
  oml_free(f);
  return next;
}
const char* next_filter_name (void)
Definition at line 41 of file factory.c.
References FilterType::name, name, and FilterType::next.
{
  static FilterType* ft = NULL;
  static int done = 1;
  const char* name;
  if (ft == NULL && done)
    {
      done = 0;
      ft = filter_types;
    }
  else if (ft == NULL)
    {
      done = 1;
      return NULL;
    }
  name = ft->name;
  ft = ft->next;
  return name;
}
void register_builtin_filters (void)
Register all built-in filters.
Definition at line 270 of file factory.c.
References omlf_register_filter_average(), omlf_register_filter_delta(), omlf_register_filter_first(), omlf_register_filter_last(), omlf_register_filter_stddev(), and omlf_register_filter_sum().
Referenced by filter_setup(), and omlc_init().
{
  omlf_register_filter_average ();
  omlf_register_filter_first ();
  omlf_register_filter_last ();
  //  omlf_register_filter_histogram ();
  omlf_register_filter_stddev ();
  omlf_register_filter_sum ();
  omlf_register_filter_delta ();
}
void unregister_filters (void)
Unregister all built-in filters.
Definition at line 283 of file factory.c.
References FilterType::definition, logdebug(), FilterType::next, and oml_free().
Referenced by omlc_close().
{
  FilterType* ft = filter_types;
  logdebug("Unregistering filters\n");
  while(ft) {
    filter_types = ft->next;
    oml_free(ft->definition);
    oml_free(ft);
    ft = filter_types;
  };
}