oml2: file_stream.c File Reference
file_stream.c File Reference
An OmlOutStream implementation that writer that writes measurement tuples to a file on the local filesystem.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "oml2/omlc.h"
#include "oml2/oml_out_stream.h"
#include "ocomm/o_log.h"
#include "mem.h"
#include "client.h"
Data Structures
struct OmlFileOutStream
Typedefs
typedef struct OmlFileOutStream OmlFileOutStream
Functions
OmlOutStream * file_stream_new (const char *file)
size_t file_stream_write_flush (OmlOutStream *hdl, uint8_t *buffer, size_t length, uint8_t *header, size_t header_length)
int file_stream_set_buffered (OmlOutStream *hdl, int buffered)
int file_stream_get_buffered (OmlOutStream *hdl)
Detailed Description
An OmlOutStream implementation that writer that writes measurement tuples to a file on the local filesystem.
Definition in file file_stream.c.
Typedef Documentation
typedef struct OmlFileOutStream OmlFileOutStream
Function Documentation
int file_stream_get_buffered (OmlOutStream * hdl)
Get the buffering startegy of an OmlOutStream
Returns 0 if fflush(3) is used after each write, 1 otherwise.
Parameters
hdl the OmlOutStream
Returns
0 if unbuffered, 1 if buffered, -1 on failure (hdl was NULL)
Definition at line 190 of file file_stream.c.
References OmlOutStream::write.
Referenced by START_TEST().
{
  OmlFileOutStream* self = (OmlFileOutStream*)hdl;
  if (self == NULL) return -1;
  return (hdl->write==file_stream_write);
}
OmlOutStream* file_stream_new (const char * file)
Create a new out stream for writing into a local file.
Parameters
file destination file (oml_strndup()'d locally)
Returns
a new OmlOutStream instance
See Also
oml_strndup
Definition at line 59 of file file_stream.c.
References logerror(), loginfo(), oml_malloc(), and oml_strndup().
Referenced by create_writer(), and START_TEST().
{
  OmlFileOutStream* self = (OmlFileOutStream *)oml_malloc(sizeof(OmlFileOutStream));
  memset(self, 0, sizeof(OmlFileOutStream));
  loginfo ("File_stream: opening local storage file '%s'\n", file);
  if (strcmp(file, "stdout") == 0 || strcmp(file, "-") == 0) {
    self->f = stdout;
  } else {
    if ((self->f = fopen(file, "a+")) == NULL) {
      logerror ("Can't open local storage file '%s'\n", file);
      return 0;
    }
  }
  self->write = file_stream_write;
  self->close = file_stream_close;
  self->dest = (char*)oml_strndup (file, strlen (file));
  self->header_written = 0;
  return (OmlOutStream*)self;
}
int file_stream_set_buffered (OmlOutStream * hdl, int buffered)
Set the buffering startegy of an OmlOutStream
Tell whether fflush(3) should be used after each write.
Parameters
hdl the OmlOutStream
buffered if 0, unbuffered operation is used, otherwise buffered operation is
Returns
0 on success, -1 on failure (+hdl+ was NULL)
Definition at line 168 of file file_stream.c.
References file_stream_write_flush(), and OmlOutStream::write.
Referenced by create_writer(), and START_TEST().
{
  OmlFileOutStream* self = (OmlFileOutStream*)hdl;
  if (self == NULL) return -1;
  if(buffered)
    hdl->write=file_stream_write;
  else
    hdl->write=file_stream_write_flush;
  return 0;
}
size_t file_stream_write_flush (OmlOutStream * hdl, uint8_t * buffer, size_t length, uint8_t * header, size_t header_length)
Write data to a file and flush it afterwards
Use fflush(3) after each right.
Parameters
hdl pointer to the OmlOutStream
buffer pointer to the buffer containing the data to write
length length of the buffer to write
header pointer to an optional buffer containing headers to be sent after (re)connecting
header_length length of the header to write; must be 0 if header is NULL
Returns
amount of data written, or -1 on error
Definition at line 145 of file file_stream.c.
References count.
Referenced by file_stream_set_buffered().
{
  OmlFileOutStream* self = (OmlFileOutStream*)hdl;
  if (!self) return -1;
  FILE* f = self->f;
  if (f == NULL) return -1;
  size_t count = file_stream_write(hdl, buffer, length, header, header_length);
  fflush(f);
  return count;
}