oml2: filter.c File Reference
filter.c File Reference
OML's client side filter engine.
#include <string.h>
#include <stdlib.h>
#include <pthread.h>
#include <errno.h>
#include <sys/time.h>
#include <time.h>
#include <unistd.h>
#include "oml2/omlc.h"
#include "oml2/oml_filter.h"
#include "oml2/oml_writer.h"
#include "ocomm/o_log.h"
#include "client.h"
Macros
#define _XOPEN_SOURCE 500 /* Or: #define _BSD_SOURCE; for useconds_t to be defined */
Functions
void filter_engine_start (OmlMStream *ms)
int filter_process (OmlMStream *ms)
Variables
OmlClient * omlc_instance
Detailed Description
OML's client side filter engine.
Definition in file filter.c.
Macro Definition Documentation
#define _XOPEN_SOURCE 500 /* Or: #define _BSD_SOURCE; for useconds_t to be defined */
Definition at line 33 of file filter.c.
Function Documentation
void filter_engine_start (OmlMStream * ms)
Start the filtering engine on the given MS
Parameters
ms pointer to OmlMStream to start filtering on
Definition at line 50 of file filter.c.
References OmlMStream::filter_thread, logdebug(), and OmlMStream::table_name.
Referenced by oml_mp_get_default_ms().
{
  logdebug ("Starting filtering thread for MS '%s'\n", ms->table_name);
  pthread_create(&ms->filter_thread, NULL, thread_start, (void*)ms);
}
int filter_process (OmlMStream * ms)
Run filters associated to an MS.
Get the writer associated to the MS, and generate and write initial metadata (seqno and time). Then, instruct all the filters, in sequence, to write their filtered sample to this writer before finalising the write.
Parameters
ms MS to generate output for
Returns
0 if success, -1 otherwise
See Also
OmlWriter, oml_writer_row_start, oml_writer_out, oml_writer_row_end
Definition at line 103 of file filter.c.
References OmlMStream::dropped, logerror(), logwarn(), OmlFilter::newwindow, OmlFilter::next, OmlMStream::nwriters, OmlFilter::output, OmlWriter::row_end, OmlWriter::row_start, OmlMStream::sample_size, OmlMStream::seq_no, OmlClient::start_time, OmlMStream::table_name, OmlMStream::writers, and OmlMStream::written.
Referenced by destroy_ms().
{
  struct timeval tv;
  double now;
  int i;
  OmlFilter *f;
  OmlWriter *writer;
  /* Get the time as soon as possible */
  gettimeofday(&tv, NULL);
  if (ms == NULL || omlc_instance == NULL || ms->writers == NULL) {
    logerror("Could not process filters because of null measurement stream, instance or writers array\n");
    return -1;
  }
  now = tv.tv_sec - omlc_instance->start_time + 0.000001 * tv.tv_usec;
  ms->seq_no++;
  for (i=0; i<ms->nwriters; i++) {
    writer = ms->writers[i];
    if (writer == NULL) {
      logwarn("%s: Sending data NULL writer (at %d)\n", ms->table_name, i);
    } else {
      /* Be aware that row_start is obtaining a lock on the writer
       * which is released in row_end. Always ensure that row_end is
       * called, even if there is a problem somewhere along the way.
       * \see oml_writer_row_start, oml_writer_out, oml_writer_row_end
       */
      if(writer->row_start(writer, ms, now) == 1)
        ms->written++;
      else
        ms->dropped++;
      f = ms->firstFilter;
      for (; f != NULL; f = f->next) {
        f->output(f, writer);
      }
      writer->row_end(writer, ms);
    }
  }
  f = ms->firstFilter;
  for (; f != NULL; f = f->next) {
    f->newwindow(f);
  }
  ms->sample_size = 0;
  return 0;
}
Variable Documentation
OmlClient* omlc_instance
Global OmlClient instance
Definition at line 40 of file init.c.