oml2: fuseki_adapter.c File Reference
fuseki_adapter.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include <string.h>
#include <inttypes.h>
#include <time.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include <curl/curl.h>
#include <assert.h>
#include <oml2/omlc.h>
#include <oml2/oml_filter.h>
#include <oml2/oml_writer.h>
#include "ocomm/o_log.h"
#include "mem.h"
#include "mstring.h"
#include "htonll.h"
#include "json.h"
#include "guid.h"
#include "oml_value.h"
#include "oml_util.h"
#include "schema.h"
#include "database.h"
#include "table_descr.h"
#include "database_adapter.h"
#include "fuseki_adapter.h"
Macros
#define HEADER_INSERT "prefix afn: <http://jena.hpl.hp.com/ARQ/function#> \ prefix fn: <http://www.w3.org/2005/xpath-functions#> \ prefix owl: <http://www.w3.org/2002/07/owl#> \ prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> \ prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> \ prefix time: <http://www.w3.org/2006/time#> \ prefix xsd: <http://www.w3.org/2001/XMLSchema#> \ prefix omn-monitoring-data: <http://open-multinet.info/ontology/omn-monitoring-data#> \ prefix omn-monitoring-genericconcepts: <http://open-multinet.info/ontology/omn-monitoring-genericconcepts#> \ prefix omn-monitoring-metric: <http://open-multinet.info/ontology/omn-monitoring-metric#> \ prefix omn-monitoring-tool: <http://open-multinet.info/ontology/omn-monitoring-tool#> \ prefix omn-monitoring-unit: <http://open-multinet.info/ontology/omn-monitoring-unit#> \ prefix omn-monitoring: <http://open-multinet.info/ontology/omn-monitoring#> \ prefix omn: <http://open-multinet.info/ontology/omn#> \ prefix omn-resource: <http://open-multinet.info/ontology/omn-resource#> \ prefix omn-lifecycle: <http://open-multinet.info/ontology/omn-lifecycle#> \ prefix omn-component: <http://open-multinet.info/ontology/omn-domain-pc#> \ prefix omn-federation: <http://open-multinet.info/ontology/omn-domain-pc#> \ prefix omn-policy: <http://open-multinet.info/ontology/omn-domain-pc#> \ prefix omn-service: <http://open-multinet.info/ontology/omn-domain-pc#> \ prefix omn-domain-pc: <http://open-multinet.info/ontology/omn-domain-pc#> "
#define MAXLINE 4096
#define MAXSUB 2000
#define REPLACE_SEQ "#?#value_seq#?#"
#define REPLACE_TS "#?#value_ts#?#"
#define REPLACE_TC "#?#value_tc#?#"
#define HASHSIZE 101
Functions
char * str_replace (const char *string, const char *substr, const char *replacement)
unsigned hash (char *s)
char * lookup (char *s)
char * lookup_char (char *s)
char * strdupp (char *s)
struct nlist * install (char *name, char *defn)
void init_list ()
void free_list ()
void handleValue (Database *db, int c, MString *insert, char *subject, char *predicate, char *pvar, int n)
int fuseki_backend_setup (void)
size_t logwrite (char *ptr, size_t size, size_t nmemb, void *userdata)
int fuseki_create_database (Database *db)
Variables
char * fus_host = DEFAULT_FUS_HOST
char * fus_port = DEFAULT_FUS_PORT
char * fus_namespace = DEFAULT_FUS_NAMESPACE
Macro Definition Documentation
#define HASHSIZE 101
Definition at line 134 of file fuseki_adapter.c.
Referenced by free_list(), and hash().
#define HEADER_INSERT "prefix afn: <http://jena.hpl.hp.com/ARQ/function#> \ prefix fn: <http://www.w3.org/2005/xpath-functions#> \ prefix owl: <http://www.w3.org/2002/07/owl#> \ prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> \ prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> \ prefix time: <http://www.w3.org/2006/time#> \ prefix xsd: <http://www.w3.org/2001/XMLSchema#> \ prefix omn-monitoring-data: <http://open-multinet.info/ontology/omn-monitoring-data#> \ prefix omn-monitoring-genericconcepts: <http://open-multinet.info/ontology/omn-monitoring-genericconcepts#> \ prefix omn-monitoring-metric: <http://open-multinet.info/ontology/omn-monitoring-metric#> \ prefix omn-monitoring-tool: <http://open-multinet.info/ontology/omn-monitoring-tool#> \ prefix omn-monitoring-unit: <http://open-multinet.info/ontology/omn-monitoring-unit#> \ prefix omn-monitoring: <http://open-multinet.info/ontology/omn-monitoring#> \ prefix omn: <http://open-multinet.info/ontology/omn#> \ prefix omn-resource: <http://open-multinet.info/ontology/omn-resource#> \ prefix omn-lifecycle: <http://open-multinet.info/ontology/omn-lifecycle#> \ prefix omn-component: <http://open-multinet.info/ontology/omn-domain-pc#> \ prefix omn-federation: <http://open-multinet.info/ontology/omn-domain-pc#> \ prefix omn-policy: <http://open-multinet.info/ontology/omn-domain-pc#> \ prefix omn-service: <http://open-multinet.info/ontology/omn-domain-pc#> \ prefix omn-domain-pc: <http://open-multinet.info/ontology/omn-domain-pc#> "
Definition at line 64 of file fuseki_adapter.c.
#define MAXLINE 4096
Definition at line 123 of file fuseki_adapter.c.
#define MAXSUB 2000
Definition at line 124 of file fuseki_adapter.c.
#define REPLACE_SEQ "#?#value_seq#?#"
Definition at line 126 of file fuseki_adapter.c.
#define REPLACE_TC "#?#value_tc#?#"
Definition at line 130 of file fuseki_adapter.c.
#define REPLACE_TS "#?#value_ts#?#"
Definition at line 128 of file fuseki_adapter.c.
Function Documentation
void free_list ()
Definition at line 201 of file fuseki_adapter.c.
References nlist::defn, HASHSIZE, and name.
{
    int i ;
    for (i = 0; i < HASHSIZE; i++) {
        free((void *) hashtab[i]->name);
        free((void *) hashtab[i]->defn);
    }
    //free(hashtab);
}
int fuseki_backend_setup (void)
This function generates a new socket that connects with fuseki backend and send some data
Returns
int - 0 (OK) -1 (KO)
Definition at line 224 of file fuseki_adapter.c.
{
    return 0; // OK = 0 || KO = -1
}
int fuseki_create_database (Database * db)
Create an SQLite3 database and adapter structures
See Also
db_adapter_create
Definition at line 242 of file fuseki_adapter.c.
References Database::add_sender_id, Database::backend_name, dba_begin_transaction(), dba_table_create_meta(), fus_host, fus_namespace, fus_port, Database::get_metadata, Database::get_table_list, Database::get_uri, Database::handle, Database::insert, loginfo(), logwrite(), mstring_buf(), mstring_create(), mstring_sprintf(), Database::o2t, oml_malloc(), Database::prepare, Database::prepared_var, Database::release, Database::semantic, Database::set_metadata, Database::stmt, Database::t2o, Database::table_create, Database::table_create_meta, and Database::table_free.
{
  MString* mstr = mstring_create ();
  CURL *curl;
  curl_global_init(CURL_GLOBAL_ALL);
  if (!(curl = curl_easy_init())) return -1;
  mstring_sprintf(mstr,"http://%s:%s/%s/update",fus_host, fus_port, fus_namespace);
  loginfo("%s\n",mstring_buf(mstr));
  curl_easy_setopt(curl, CURLOPT_URL, mstring_buf(mstr));
  curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, &logwrite);
  SemDB* self = oml_malloc(sizeof(SemDB));
  self->conn = curl;//conn;
  self->last_commit = time (NULL);
  db->semantic = 1;
  db->backend_name = backend_name;
  db->o2t = sem_oml_to_type;
  db->t2o = sem_type_to_oml;
  db->stmt = sem_stmt;
  db->table_create = sem_table_create;
  db->table_create_meta = dba_table_create_meta;
  db->table_free = sem_table_free;
  db->release = sem_release;
  db->prepared_var = sem_prepared_var;
  db->prepare = sem_prepare;
  db->insert = sem_insert;
  db->add_sender_id = sem_add_sender_id;
  db->set_metadata = sem_set_metadata;
  db->get_metadata = sem_get_metadata;
  db->get_uri = sem_get_uri;
  db->get_table_list = sem_get_table_list;
  db->handle = self;
  dba_begin_transaction (db);
  return 0;
}
void handleValue (Database * db, int c, MString * insert, char * subject, char * predicate, char * pvar, int n)
Definition at line 212 of file fuseki_adapter.c.
References mstring_sprintf(), and oml_free().
{
  pvar = sem_prepared_var(db,c);
  n += mstring_sprintf(insert,"\t\t%s %s %s .\n", subject, predicate, pvar);
  oml_free(pvar);
}
unsigned hash (char * s)
Definition at line 138 of file fuseki_adapter.c.
References HASHSIZE.
Referenced by install(), lookup(), and lookup_char().
{
    unsigned hashval;
    for (hashval = 0; *s != '\0'; s++)
      hashval = *s + 31 * hashval;
    return hashval % HASHSIZE;
}
void init_list ()
Definition at line 194 of file fuseki_adapter.c.
References install().
{
  struct nlist *list = hashtab ;
  list = install("omn-monitoring:Measurement","?measurement") ;
  list = install("omn-monitoring-data:MeasurementData","?data") ;
}
struct nlist* install (char * name, char * defn) read
Definition at line 176 of file fuseki_adapter.c.
References nlist::defn, hash(), lookup(), nlist::name, nlist::next, and strdupp().
Referenced by init_list().
{
    struct nlist *np;
    unsigned hashval;
    if ((np = lookup(name)) == NULL) { /* not found */
        np = (struct nlist *) malloc(sizeof(*np));
        if (np == NULL || (np->name = strdupp(name)) == NULL)
          return NULL;
        hashval = hash(name);
        np->next = hashtab[hashval];
        hashtab[hashval] = np;
    } else /* already there */
        free((void *) np->defn); /*free previous defn */
    if ((np->defn = strdupp(defn)) == NULL)
       return NULL;
    return np;
}
size_t logwrite (char * ptr, size_t size, size_t nmemb, void * userdata)
Definition at line 230 of file fuseki_adapter.c.
References logwarn().
{
   logwarn("Server response: %s\n",ptr);
   return size * nmemb;
}
char* lookup (char * s)
Definition at line 147 of file fuseki_adapter.c.
References hash(), nlist::name, and nlist::next.
Referenced by install().
{
    struct nlist *np;
    for (np = hashtab[hash(s)]; np != NULL; np = np->next)
        if (strcmp(s, np->name) == 0)
          return np; /* found */
    return NULL; /* not found */
}
char* lookup_char (char * s)
Definition at line 156 of file fuseki_adapter.c.
References nlist::defn, hash(), nlist::name, and nlist::next.
{
    struct nlist *np;
    for (np = hashtab[hash(s)]; np != NULL; np = np->next)
        if (strcmp(s, np->name) == 0)
          return np->defn; /* found */
    return NULL; /* not found */
}
char* str_replace (const char * string, const char * substr, const char * replacement)
char* strdupp (char * s)
Definition at line 166 of file fuseki_adapter.c.
Referenced by install().
{
    char *p;
    p = (char *) malloc(strlen(s)+1); /* +1 for \0 */
    if (p != NULL)
       strcpy(p, s);
    return p;
}
Variable Documentation
char* fus_host = DEFAULT_FUS_HOST
Definition at line 118 of file fuseki_adapter.c.
char* fus_namespace = DEFAULT_FUS_NAMESPACE
Definition at line 120 of file fuseki_adapter.c.
char* fus_port = DEFAULT_FUS_PORT
Definition at line 119 of file fuseki_adapter.c.