oml2: fuseki_adapter.h File Reference
fuseki_adapter.h File Reference
#include "../lib/ocomm/ocomm/o_socket.h"
#include "database.h"
#include <oml2/oml_out_stream.h>
#include <curl/curl.h>
Data Structures
struct SemDB
struct SemTable
struct nlist
Macros
#define DEFAULT_FUS_HOST "localhost"
#define DEFAULT_FUS_PORT "3030"
#define DEFAULT_FUS_NAMESPACE "ds"
Typedefs
typedef struct SemDB SemDB
typedef struct SemTable SemTable
Functions
int fuseki_backend_setup (void)
int fuseki_create_database (Database *db)
Macro Definition Documentation
#define DEFAULT_FUS_HOST "localhost"
Definition at line 21 of file fuseki_adapter.h.
#define DEFAULT_FUS_NAMESPACE "ds"
Definition at line 23 of file fuseki_adapter.h.
#define DEFAULT_FUS_PORT "3030"
Definition at line 22 of file fuseki_adapter.h.
Typedef Documentation
typedef struct SemDB SemDB
typedef struct SemTable SemTable
Function Documentation
int fuseki_backend_setup (void)
This function generates a new socket that connects with fuseki backend and send some data
Returns
int - 0 (OK) -1 (KO)
Definition at line 130 of file fuseki_adapter-new-yahya.c.
Referenced by database_setup_backend().
{
    return 0; // OK = 0 || KO = -1
}
int fuseki_create_database (Database * db)
Create an SQLite3 database and adapter structures
See Also
db_adapter_create
Definition at line 148 of file fuseki_adapter-new-yahya.c.
References Database::add_sender_id, Database::backend_name, dba_begin_transaction(), dba_table_create_meta(), fus_host, fus_namespace, fus_port, Database::get_metadata, Database::get_table_list, Database::get_uri, Database::handle, Database::insert, loginfo(), logwrite(), mstring_buf(), mstring_create(), mstring_sprintf(), Database::o2t, oml_malloc(), Database::prepare, Database::prepared_var, Database::release, Database::semantic, Database::set_metadata, Database::stmt, Database::t2o, Database::table_create, Database::table_create_meta, and Database::table_free.
{
  MString* mstr = mstring_create ();
  CURL *curl;
  curl_global_init(CURL_GLOBAL_ALL);
  if (!(curl = curl_easy_init())) return -1;
  mstring_sprintf(mstr,"http://%s:%s/%s/update",fus_host, fus_port, fus_namespace);
  loginfo("%s\n",mstring_buf(mstr));
  curl_easy_setopt(curl, CURLOPT_URL, mstring_buf(mstr));
  curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, &logwrite);
  SemDB* self = oml_malloc(sizeof(SemDB));
  self->conn = curl;//conn;
  self->last_commit = time (NULL);
  db->semantic = 1;
  db->backend_name = backend_name;
  db->o2t = sem_oml_to_type;
  db->t2o = sem_type_to_oml;
  db->stmt = sem_stmt;
  db->table_create = sem_table_create;
  db->table_create_meta = dba_table_create_meta;
  db->table_free = sem_table_free;
  db->release = sem_release;
  db->prepared_var = sem_prepared_var;
  db->prepare = sem_prepare;
  db->insert = sem_insert;
  db->add_sender_id = sem_add_sender_id;
  db->set_metadata = sem_set_metadata;
  db->get_metadata = sem_get_metadata;
  db->get_uri = sem_get_uri;
  db->get_table_list = sem_get_table_list;
  db->handle = self;
  dba_begin_transaction (db);
  return 0;
}