oml2: headers.h File Reference
headers.h File Reference
#include <stdlib.h>
Data Structures
struct header
Enumerations
enum HeaderTag {
H_NONE, H_PROTOCOL, H_DOMAIN, H_CONTENT,
H_APP_NAME, H_SENDER_ID, H_SCHEMA, H_START_TIME,
H_max
}
Functions
enum HeaderTag tag_from_string (const char *str, size_t n)
const char * tag_to_string (enum HeaderTag tag)
struct header * header_from_string (const char *str, size_t n)
Parse a protocol header line into a struct header.
void header_free (struct header *header)
Enumeration Type Documentation
enum HeaderTag
Enumerator:
H_NONE
H_PROTOCOL
H_DOMAIN
H_CONTENT
H_APP_NAME
H_SENDER_ID
H_SCHEMA
H_START_TIME
H_max
Definition at line 29 of file headers.h.
               {
  H_NONE,
  H_PROTOCOL,
  H_DOMAIN,
  H_CONTENT,
  H_APP_NAME,
  H_SENDER_ID,
  H_SCHEMA,
  H_START_TIME,
  H_max /* For calculating the max value for use in tables */
};
Function Documentation
void header_free (struct header * header)
Free the memory of a +struct header+ object.
Definition at line 338 of file headers.c.
References oml_free(), and header::value.
Referenced by client_free().
{
  if (header) {
    if (header->value)
      oml_free (header->value);
    oml_free (header);
  }
}
struct header* header_from_string (const char * str, size_t n) read
Parse a protocol header line into a struct header.
Each header consists of a tag, followed by a colon, followed by a value, terminated by a new line character '
'. This function parses such a header into the tag, converted from a string into an enum HeaderTag, and the value, which is kept as a string. They are returned as a newly allocated struct header object; the caller owns the memory and should deallocated it when it is no longer needed, using header_free().
Whitespace is not permitted at the start of the string, but is permitted before and after the colon ':'. This space is stripped from the value, but trailing space is not.
The string str should be null-terminated, but can be longer than +n+ characters. Characters after the n-th will be ignored. The +value+ part of the returned +struct header+ will not have any trailing whitespace removed.
If the tag part is not recognized, NULL is returned. If memory can't be allocated for the +struct header+, then NULL is returned instead. If there is no colon ':' in the first +n+ characters of +str+, then NULL is returned.
Parameters
str Input string to parse
n Number of characters of str to parse.
Returns
The header, or NULL if the header could not be parsed.
Definition at line 286 of file headers.c.
References find_white(), H_NONE, header, namelen, oml_free(), oml_malloc(), oml_strndup(), skip_white(), str, header::tag, tag, tag_from_string(), and header::value.
Referenced by read_header(), and START_TEST().
{
  if (!str) return NULL;
  const char *p = str;
  const char *q = memchr (p, ':', n);
  if (!q)
    return NULL;
  /* Strip trailing whitespace on the header name */
  p = find_white(p);
  int namelen;
  if (p < q)
    namelen = p - str;
  else
    namelen = q - str;
  enum HeaderTag tag = tag_from_string (str, namelen);
  if (tag == H_NONE)
    return NULL;
  /* Skip the ':' and strip leading whitespace on header value */
  if (*q)
    q = skip_white (++q);
  char * value = NULL;
  size_t valuelen = n - (q - str);
  struct header *header = NULL;
  if ((int)valuelen > 0) {
    value = oml_strndup (q, valuelen);
    if (!value)
      return NULL;
    header = oml_malloc (sizeof (struct header));
    if (!header) {
      oml_free (value);
      return NULL;
    }
    header->tag = tag;
    header->value = value;
    return header;
  }
  return NULL;
}
enum HeaderTag tag_from_string (const char * str, size_t n)
Convert a string header name into the tag for that header.
The +str+ should be a null terminated string. The parameter +n+ sets the bounds of the string to be considered for extracting the tag. All characters from the start to the n-th are considered part of the name, so any trailing whitespace should be after the n-th character.
The function takes +str+ and compares it against the list of known headers. If it finds a match, it converts the header to its corresponding tag; otherwise it returns H_NONE.
Parameters
str – string name to convert.
n – the number of bytes of str to consider
Returns
– the tag.
Definition at line 209 of file headers.c.
References H_NONE, name, and str.
Referenced by header_from_string(), and START_TEST().
{
  int i = 0;
  char first;
  char second;
  if (str == NULL || n <= 2)
    return H_NONE;
  first = *str;
  second = *(str+1);
  /* Premature optimization for fun and profit */
  for (; header_map[i].name != NULL; i++) {
    char h_first  = header_map[i].name[0];
    char h_second = header_map[i].name[1];
    size_t h_len = header_map[i].namelen;
    if (n < h_len)
      continue;
    if (first != 's') {
      /* We can fail on mismatched first char if it's not 's' */
      if ((first == h_first) &&
          (strncmp (str+1, header_map[i].name+1, n - 1) == 0))
        return header_map[i].tag;
    } else {
      /* If 's', we can fast-fail on the second char */
      if (first == h_first && second == h_second &&
          (strncmp (str+2, header_map[i].name+2, n - 2) == 0)) {
        return header_map[i].tag;
      }
    }
  }
  return H_NONE;
}
const char* tag_to_string (enum HeaderTag tag)
Definition at line 247 of file headers.c.
Referenced by client_send_header(), main(), and proxy_message_loop().
{
  int i = 0;
  for (i = 0; header_map[i].name != NULL; i++)
    if (header_map[i].tag == tag)
      return header_map[i].name;
  return NULL;
}