oml2: hook.h File Reference
hook.h File Reference
Macros
#define HOOK_BANNER "OML HOOK READY"
#define HOOK_CMD_EXIT "EXIT\n" /* No argument for this one */
#define HOOK_CMD_DBCREATED "DBCREATED"
#define HOOK_CMD_DBOPENED "DBOPENED"
#define HOOK_CMD_DBCLOSED "DBCLOSED"
Functions
void hook_setup (void)
void hook_cleanup (void)
int hook_enabled ()
ssize_t hook_write (const void *buf, size_t count)
ssize_t hook_read (void *buf, size_t count)
Variables
char * hook
int hookpipe []
Macro Definition Documentation
#define HOOK_BANNER "OML HOOK READY"
Definition at line 32 of file hook.h.
Referenced by hook_setup().
#define HOOK_CMD_DBCLOSED "DBCLOSED"
Definition at line 36 of file hook.h.
Referenced by database_release().
#define HOOK_CMD_DBCREATED "DBCREATED"
Definition at line 34 of file hook.h.
Referenced by database_find().
#define HOOK_CMD_DBOPENED "DBOPENED"
Definition at line 35 of file hook.h.
Referenced by database_find().
#define HOOK_CMD_EXIT "EXIT\n" /* No argument for this one */
Definition at line 33 of file hook.h.
Referenced by hook_cleanup().
Function Documentation
void hook_cleanup (void)
Terminate the event hook process
Definition at line 47 of file hook.c.
References hook, HOOK_CMD_EXIT, hook_write(), logdebug(), and logwarn().
Referenced by hook_setup(), and main().
{
  int i, ret;
  if (!hook) return;
  logdebug("hook: Cleaning up `%s'\n", hook);
  if(hook_write(HOOK_CMD_EXIT, (int)(sizeof(HOOK_CMD_EXIT) - 1)) == (int)(sizeof(HOOK_CMD_EXIT) - 1))
    return;
  logdebug("hook: Problem commanding `%s' to exit: %s\n", hook, strerror(errno));
  if(!kill(hookpid, SIGTERM))
    return;
  logdebug("hook: Cannot kill (TERM) process %d: %s\n", hookpid, strerror(errno));
  for (i=0; i<3; i++) {
    ret = kill(hookpid, SIGKILL);
    if(ret == ESRCH)
      return;
    logdebug("hook: Cannot kill (KILL) process %d: %s\n", hookpid, strerror(errno));
  }
  logwarn("hook: Could not kill process %d; giving up...", hookpid);
}
int hook_enabled (void)
Determine whether an event hook has been enabled
Returns
1 if hook enabled, 0 otherwise
Definition at line 157 of file hook.c.
                   {
 return hookpipe[0] >= 0 && hookpipe[1] >= 0;
}
ssize_t hook_read (void * buf, size_t count)
Read commands to the event hook.
This function reads whatever the event hook outputs on its +stdout+ It takes the same parameters as read(2), but skips the file descriptor.
This read is blocking, and should be used when knowingly.
Parameters
buf buffer into which +count+ bytes frome the event hook's +stdout+
count the number of bytes to read into +buf+
Returns
the same as read(2), and sets +errno+ accordingly
Definition at line 195 of file hook.c.
References logdebug().
Referenced by hook_setup().
{
  int n;
  if (-1 == hookpipe[0])
    return -1;
  n = read(hookpipe[0], buf, count);
  logdebug("hook: Read from fd %d: '%s'\n", hookpipe[0], buf);
  return n;
}
void hook_setup (void)
Initialise the event hook if specified.
This function creates two pipes, forks, redirects the child's stdin and stdout to/from these pipes, then executes the hook program
The hook program is expected to first print an identifying banner (
See Also
HOOK_BANNER), then wait for commands on stdin.
Though a reverse pipe is also created for the hook's stdout to be available to the main server process, it is not currently used for anything else than getting the banner. Also, a read(2) on it from the main process is blocking.
Definition at line 84 of file hook.c.
References hook, HOOK_BANNER, hook_cleanup(), hook_read(), logdebug(), loginfo(), and logwarn().
Referenced by main().
{
  int pto[2], pfrom[2];
  fd_set readfds;
  struct timeval timeout = { .tv_sec=5, .tv_usec=0, };
  char buf[sizeof(HOOK_BANNER)];
  if (!hook)
    return;
  if (pipe(pto) || pipe(pfrom)) {
    logwarn("hook: Cannot create pipes to `%s': %s\n", hook, strerror(errno));
    goto clean_pipes;
  }
  hookpid = fork();
  if (hookpid < 0) {
    logwarn("hook: Cannot fork for `%s': %s\n", hook, strerror(errno));
    hookpid = -1;
    goto clean_pipes;
  } else if (0 == hookpid) {            /* Child process */
    close(pto[1]);
    close(pfrom[0]);
    dup2(pto[0], STDIN_FILENO);
    dup2(pfrom[1], STDOUT_FILENO);
    execlp(hook, hook, NULL);
    logwarn("hook: Cannot execute `%s': %s\n", hook, strerror(errno));
    exit(1);
  } else {                              /* Parent process */
    close(pto[0]);
    close(pfrom[1]);
    hookpipe[0] = pfrom[0];
    hookpipe[1] = pto[1];
    /* Wait for banner or timeout */
    FD_ZERO(&readfds);
    FD_SET(hookpipe[0], &readfds);
    logdebug("hook: Waiting for `%s' to respond...\n", hook);
    if(select(hookpipe[0]+1, &readfds, NULL, NULL, &timeout) < 1) {
      logwarn("hook: `%s' (PID %d) not responding\n", hook, hookpid);
      hook_cleanup();
      goto clean_pipes;
    }
    /* Only hookpipe[0] was in readfds, so we know why we're here */
    if(hook_read(&buf, sizeof(buf)) <= 0) {
      logwarn("hook: Cannot get banner from `%s' (PID %d): %s\n", hook, hookpid, strerror(errno));
    } else if (strncmp(buf, HOOK_BANNER, sizeof(HOOK_BANNER)-1)) {  /* XXX: Ignore final '\n' instead of '\0' */
      buf[sizeof(buf)-1]=0;
      logwarn("hook: Incorrect banner from `%s' (PID %d): `%s'\n", hook, hookpid, buf);
      goto clean_pipes;
    }
    loginfo("hook: `%s' in place\n", hook);
  }
  return;
clean_pipes:
  logdebug("hook: Giving up on `%s'\n", hook);
  close(pto[0]);
  close(pfrom[0]);
  close(pto[1]);
  close(pfrom[1]);
  hook_clean_pipes();
}
ssize_t hook_write (const void * buf, size_t count)
Write commands to the event hook.
This function writes commands into the pipe connected to the event hook's stdin. It takes the same parameters as write(2), but skips the file descriptor.
Parameters
buf buffer from which +count+ bytes of data will be read out andwritten into event hook's +stdin+
count the number of bytes from +buf+ to write into the hook's +stdin+
Returns
the same as write(2), and sets +errno+ accordingly
Definition at line 172 of file hook.c.
References logdebug().
Referenced by hook_cleanup().
{
  int n;
  if (-1 == hookpipe[1])
    return -1;
  logdebug("hook: Sending command fd %d: '%s'\n", hookpipe[1], buf);
  n = write(hookpipe[1], buf, count);
  return n;
}
Variable Documentation
char* hook
Character string containing the name of the event hook program (or script) to instantiate.
Definition at line 27 of file hook.c.
Referenced by hook_cleanup(), and hook_setup().
int hookpipe[]