oml2: init.c File Reference
init.c File Reference
Implement the user-visible initialisation routines of the user-visible OML API.
#include <string.h>
#include <ctype.h>
#include <stdlib.h>
#include <errno.h>
#include <signal.h>
#include <sys/time.h>
#include <time.h>
#include "oml2/omlc.h"
#include "oml2/oml_filter.h"
#include "oml2/oml_writer.h"
#include "ocomm/o_log.h"
#include "mem.h"
#include "mstring.h"
#include "oml_value.h"
#include "validate.h"
#include "filter/factory.h"
#include "oml_util.h"
#include "client.h"
Macros
#define OMLC_COPYRIGHT "Copyright 2007-2014, NICTA"
#define DEF_LOG_LEVEL = O_LOG_INFO;
#define DEFAULT_SCHEMA_LENGTH 2048
Typedefs
typedef void(* sighandler)(int)
Functions
int parse_config (char *config_file)
int omlc_init (const char *application, int *pargc, const char **argv, o_log_fn custom_oml_log)
OMLSemDef * destroy_sem_concepts (OMLSemDef *sd)
OmlMP * omlc_add_mp (const char *mp_name, OmlMPDef *mp_def)
OMLSemDef * oml_sem_register_concepts (char ***concepts, int n)
OmlMP * destroy_mp (OmlMP *mp)
int omlc_start ()
int omlc_close (void)
OmlWriter * create_writer (const char *uri, enum StreamEncoding encoding)
OmlMP * find_mp (const char *name)
int find_mp_field (const char *name, OmlMP *mp)
MString * mp_fields_summary (OmlMP *mp)
OmlMStream * find_mstream_in_mp (const char *name, OmlMP *mp)
OmlMStream * find_mstream (const char *name)
OmlMStream * create_mstream (const char *name, OmlMP *mp, OmlWriter *writer, double sample_interval, int sample_thres)
int oml_ms_add_writer (OmlMStream *ms, OmlWriter *w)
OmlMStream * destroy_ms (OmlMStream *ms)
OmlMStream * oml_mp_get_default_ms (OmlMP *mp)
void create_default_filters (OmlMP *mp, OmlMStream *ms)
OmlFilter * create_default_filter (OmlMPDef *def, OmlMStream *ms, int index)
const char * validate_app_name (const char *name)
Variables
OmlClient * omlc_instance = NULL
OmlMP * schema0
Detailed Description
Implement the user-visible initialisation routines of the user-visible OML API.
Definition in file init.c.
Macro Definition Documentation
#define DEF_LOG_LEVEL = O_LOG_INFO;
Definition at line 42 of file init.c.
#define DEFAULT_SCHEMA_LENGTH 2048
Write the different schemas of the application
Parameters
ms the stream definition
index the index in the measurement points, used to initialias OmlMStream::index
Returns
0 if successful
Definition at line 1365 of file init.c.
#define OMLC_COPYRIGHT "Copyright 2007-2014, NICTA"
Definition at line 38 of file init.c.
Referenced by omlc_init().
Typedef Documentation
typedef void(* sighandler)(int)
A function pointer suitable for sigaction(3)
Definition at line 63 of file init.c.
Function Documentation
OmlFilter* create_default_filter (OmlMPDef * def, OmlMStream * ms, int index)
Create a new filter for the measurement associated with the stream
Parameters
def OmlMPDef of the MP for which to create a filter
ms OmlMStream in which the filter outputs its samples
index index of the field to filter within this MP
Returns
a new filter
Definition at line 1224 of file init.c.
References create_filter(), OmlMPDef::name, name, omlc_is_numeric_type, OmlMPDef::param_types, OmlMPDef::relations, OmlMStream::sample_interval, OmlMStream::sample_thres, and type.
Referenced by create_default_filters().
{
  const char* name = def->name;
  OmlValueT type = def->param_types;
  OMLSemDef * concepts = def->relations;
  int multiple_samples = ms->sample_thres > 1 || ms->sample_interval > 0;
  char* fname;
  if (multiple_samples && omlc_is_numeric_type (type)) {
    fname = "avg";
  } else {
    fname = "first";
  }
  OmlFilter* f = create_filter(fname, name, type, concepts, index);
  return f;
}
void create_default_filters (OmlMP * mp, OmlMStream * ms)
Create the default filters
Parameters
mp OmlMP to add filters to
ns OmlMStream associated to mp
Definition at line 1187 of file init.c.
References create_default_filter(), logdebug(), logerror(), OmlMP::name, OmlFilter::next, OmlMP::param_count, OmlMP::param_defs, and OmlMStream::table_name.
Referenced by oml_mp_get_default_ms().
{
  int j;
  if(!mp || !ms) {
    return;
  }
  int param_count = mp->param_count;
  logdebug("Creating default filters on MP '%s' to MS '%s'\n",
      mp->name, ms->table_name);
  OmlFilter* prev = NULL;
  for (j = 0; j < param_count; j++) {
    OmlMPDef def = mp->param_defs[j];
    OmlFilter* f = create_default_filter(&def, ms, j);
    if (f) {
      if (prev == NULL) {
        ms->firstFilter = f;
      } else {
        prev->next = f;
      }
      prev = f;
    } else {
      logerror("Unable to create default filter for MP %s.\n", mp->name);
    }
  }
}
OmlMStream* create_mstream (const char * name, OmlMP * mp, OmlWriter * writer, double sample_interval, int sample_thres)
Create a new stream of measurement samples from the inputs to a given MP.
If a stream by that name already exists, it is used instead.
Parameters
sample_interval the sample interval for the filter
sample_thres the threshold for the filter
mp the measurement point
writer the destination for the stream output samples
Returns
the new measurement stream, or NULL if an error occurred.
Definition at line 963 of file init.c.
References OmlClient::app_name, OmlClient::client_instr, find_mstream(), logdebug(), logerror(), loginfo(), mp, OmlMStream::mp, mstring_buf(), mstring_cat(), mstring_create(), mstring_delete(), mstring_set(), OmlMP::mutex, OmlMP::mutexP, OmlMP::name, OmlMStream::next, oml_free(), oml_malloc(), oml_ms_add_writer(), OmlMStream::sample_interval, OmlMStream::sample_thres, OmlMP::streams, and OmlMStream::table_name.
Referenced by oml_mp_get_default_ms().
{
  char *stream_name = NULL;
  int new = 1;
  MString *namestr;
  OmlMStream *ms;
  if (!mp) {
    return NULL;
  }
  namestr = mstring_create();
  /* If name is not specified, create one by concatenating the application and
   * MP names.
   *
   * XXX: We probably should not do it for any MP, as an MP should be
   * application-agnostic. This is not the case at the moment, and we don't
   * want to confuse legacy post-processing scripts. See #1055.
   *
   * However, schema 0 is new, so let's do the right thing here.
   *
   */
  namestr = mstring_create();
  if ((mp != schema0) && (mp != omlc_instance->client_instr)) {
    mstring_set (namestr, omlc_instance->app_name);
    mstring_cat (namestr, "_");
  }
  if (name) {
    mstring_cat (namestr, name);
  } else {
    mstring_cat (namestr, mp->name);
  }
  stream_name = mstring_buf (namestr);
  if ((ms=find_mstream (stream_name))) {
    loginfo("MS '%s' already exists, assuming identical parameters for a new destination; use the 'name' attribute of the <stream /> element to change\n", stream_name);
    new = 0;
  } else {
    logdebug("MS '%s' does not exist, creating...\n", stream_name);
    ms = (OmlMStream*)oml_malloc(sizeof(OmlMStream));
    if(!ms) {
      logerror("Cannot allocate memory for MS %s\n", name);
      return NULL;
    }
    memset(ms, 0, sizeof(OmlMStream));
    ;
    strncpy (ms->table_name, stream_name, sizeof(ms->table_name));
    ms->table_name[sizeof(ms->table_name)-1] = '\0';
    ms->sample_interval = sample_interval;
    ms->sample_thres = sample_thres;
    ms->mp = mp;
    if (ms->sample_interval > 0) {
      if (mp->mutexP == NULL) {
        mp->mutexP = &mp->mutex;
        pthread_mutex_init(mp->mutexP, NULL);
      }
      ms->sample_thres = 0;
    }
  }
  mstring_delete (namestr);
  if(!writer) {
    logdebug("NULL writer for MS %s; it might get added later (using a configuration file?)\n", name?name:mp->name);
  } else if (oml_ms_add_writer(ms, writer))  {
    logerror("Cannot add %s's writer\n", name);
    if(new) {
      oml_free(ms);
    }
    return NULL;
  }
  if (new) {
    ms->next = mp->streams;
    mp->streams = ms;
  }
  return ms;
}
OmlWriter* create_writer (const char * uri, enum StreamEncoding encoding)
Create either a file writer or a network writer
Parameters
uri collection URI
encoding StreamEncoding to use for the output, either SE_Text or SE_Binary
Returns
a pointer to the new OmlWriter, or NULL on error
Definition at line 741 of file init.c.
References bin_writer_new(), DEF_PORT_STRING, OmlClient::domain, file_stream_new(), file_stream_set_buffered(), OmlClient::first_writer, logerror(), net_stream_new(), OmlWriter::next, OmlClient::node_name, oml_free(), oml_strndup(), OML_URI_FILE_FLUSH, oml_uri_is_file, oml_uri_type(), parse_uri(), SE_Binary, SE_None, SE_Text, and text_writer_new().
{
  OmlURIType uri_type = oml_uri_type(uri);
  if (omlc_instance == NULL){
    logerror("No omlc_instance:  OML client was not initialized properly.\n");
    return NULL;
  }
  if (uri == NULL || strlen(uri) < 1) {
    logerror ("Missing or invalid collection URI definition (e.g., --oml-collect)\n");
    return NULL;
  }
  if (omlc_instance->node_name == NULL) {
    logerror ("Missing '--oml-id' flag \n");
    return NULL;
  }
  if (omlc_instance->domain == NULL) {
    logerror ("Missing '--oml-domain' flag \n");
    return NULL;
  }
  const char *transport = NULL;
  const char *path = NULL;
  const char *port = NULL;
  if (parse_uri (uri, &transport, &path, &port) == -1) {
    logerror ("Error parsing server destination URI '%s'; failed to create stream for this destination\n",
              uri);
    if (transport) oml_free ((void*)transport);
    if (path) oml_free ((void*)path);
    if (port) oml_free ((void*)port);
    return NULL;
  }
  const char *filepath = NULL;
  const char *hostname = NULL;
  if (oml_uri_is_file(uri_type)) {
    /* 'file://path/to/file' is equivalent to unix path '/path/to/file' */
    if (strncmp (path, "//", 2) == 0)
      filepath = &path[1];
    else
      filepath = path;
  } else if (transport) {
    if (strncmp (path, "//", 2) == 0)
      hostname = &path[2];
    else
      hostname = path;
  } else {
    hostname = path; /* If no transport specified, it must be tcp */
  }
  /* Default transport is tcp if not specified */
  if (!transport) {
    transport = oml_strndup ("tcp", strlen ("tcp"));
  }
  /* If not file transport, use the OML default port if unspecified */
  if (!port && !oml_uri_is_file(uri_type)) {
    port = oml_strndup (DEF_PORT_STRING, strlen (DEF_PORT_STRING));
  }
  OmlOutStream* out_stream;
  if (oml_uri_is_file(uri_type)) {
    out_stream = file_stream_new(filepath);
    if (encoding == SE_None) encoding = SE_Text; /* default encoding */
    if(OML_URI_FILE_FLUSH == uri_type) {
      file_stream_set_buffered(out_stream, 0);
    }
  } else {
    out_stream = net_stream_new(transport, hostname, port);
    if (encoding == SE_None) encoding = SE_Binary; /* default encoding */
  }
  if (out_stream == NULL) {
    logerror ("Failed to create stream for URI %s\n", uri);
    return NULL;
  }
  oml_free ((void*)transport);
  oml_free ((void*)path);
  oml_free ((void*)port);
  // Now create a write on top of the stream
  OmlWriter* writer = NULL;
  switch (encoding) {
  case SE_Text:   writer = text_writer_new (out_stream); break;
  case SE_Binary: writer = bin_writer_new (out_stream); break;
  case SE_None:
    logerror ("No encoding specified (this should never happen -- please report this as an OML bug)\n");
    // should cleanup streams
    return NULL;
  }
  if (writer == NULL) {
    logerror ("Failed to create writer for encoding '%s'.\n", encoding == SE_Binary ? "binary" : "text");
    return NULL;
  }
  writer->next = omlc_instance->first_writer;
  omlc_instance->first_writer = writer;
  return writer;
}
OmlMP* destroy_mp (OmlMP * mp)
Destroy MP
This function is designed so it can be used in a while loop to clean up the entire linked list:
while((mp=destroy_mp(mp)));
Parameters
mp pointer to the OmlMP to free
Returns
mp->next (can be NULL)
Definition at line 493 of file init.c.
References OmlMP::active, destroy_ms(), destroy_sem_concepts(), logdebug(), mp_lock(), mp_unlock(), OmlMP::name, OmlMP::next, OmlMP::param_defs, OmlMPDef::relations, and OmlMP::streams.
Referenced by omlc_close().
{
  OmlMP *next;
  OmlMStream *ms;
  if(!mp) {
    return NULL;
  }
  logdebug("Destroying MP %s at %p\n", mp->name, mp);
  next = mp->next;
  if (!mp_lock(mp)) {
    mp->active = 0;
    ms = mp->streams;
    while (destroy_sem_concepts(mp->param_defs->relations));
    while( (ms=destroy_ms(ms)) );
    mp_unlock(mp);
  }
  return next;
}
OmlMStream* destroy_ms (OmlMStream * ms)
Destroy a Measurement Stream, and deep free allocated memory (filters.
This function is designed so it can be used in a while loop to clean up the entire linked list:
while((ms=destroy_ms(ms)));
Parameters
ms pointer to the OmlMStream to free
Returns
ms->next (can be NULL)
Definition at line 1088 of file init.c.
References destroy_filter(), filter_process(), OmlMStream::filters, logdebug(), loginfo(), OmlMStream::next, oml_free(), OmlMStream::sample_size, OmlMStream::table_name, and OmlMStream::writers.
Referenced by destroy_mp().
{
  OmlMStream *next;
  OmlFilter *ft;
  if(!ms) {
    return NULL;
  }
  logdebug("Destroying MS %s at %p\n", ms->table_name, ms);
  next = ms->next;
  if (ms->sample_size > 0) {
    loginfo("Reporting last (partial) sample for MS %s\n", ms->table_name);
    filter_process(ms);
  }
  ft = ms->filters;
  while( (ft = destroy_filter(ft)) );
  oml_free(ms->writers);
  oml_free(ms);
  return next;
}
OMLSemDef* destroy_sem_concepts (OMLSemDef * sd)
Definition at line 321 of file init.c.
References OMLSemDef::next, OMLSemDef::object, oml_free(), OMLSemDef::predicate, and OMLSemDef::subject.
Referenced by destroy_mp(), and omlc_add_mp().
{
    OMLSemDef *sd_aux = NULL;
    if (sd)
    {
        if (sd->subject) oml_free(sd->subject);
        if (sd->predicate) oml_free(sd->predicate);
        if (sd->object) oml_free(sd->object);
        sd_aux = sd->next;
        oml_free(sd);
    }
    return sd_aux;
}
OmlMP* find_mp (const char * name)
Find a named measurement point.
Parameters
name The name of the measurement point to search for.
Returns
the measurement point, or NULL if not found.
Definition at line 850 of file init.c.
References mp, OmlClient::mpoints, OmlMP::name, and OmlMP::next.
{
  OmlMP *mp = omlc_instance->mpoints;
  while (mp && strcmp (name, mp->name))
    mp = mp->next;
  return mp;
}
int find_mp_field (const char * name, OmlMP * mp)
a named field of an MP.
Parameters
name name of the field to look up
mp OmlMP to look for the field
If either parameter is NULL, act as if the field wasn't found.
Returns
a valid index into the OmlMP's param_defs array, or -1 if not found
Definition at line 867 of file init.c.
References logdebug(), OmlMPDef::name, OmlMP::name, OmlMP::param_count, and OmlMP::param_defs.
Referenced by omlc_inject_metadata().
{
  size_t i;
  if (NULL == name || NULL == mp) { return -1; }
  size_t len = mp->param_count;
  OmlMPDef *fields = mp->param_defs;
  for (i = 0; i < len; i++) {
    logdebug("Searching MP %s for field '%s', found '%s'\n",
        mp->name, name, fields[i].name);
    if (strcmp (name, fields[i].name) == 0) {
      return i;
    }
  }
  return -1;
}
OmlMStream* find_mstream (const char * name)
Find a measurement stream by name. All measurement streams must be named uniquely.
Parameters
name the name of the measurement stream to search for.
Returns
a pointer to the measurement stream or NULL if not found.
Definition at line 938 of file init.c.
References find_mstream_in_mp(), OmlClient::mpoints, and OmlMP::next.
Referenced by create_mstream().
{
  OmlMP *mp = omlc_instance->mpoints;
  OmlMStream *ms = NULL;
  while (mp) {
    ms = find_mstream_in_mp (name, mp);
    if (ms)
      break;
    mp = mp->next;
  }
  return ms;
}
OmlMStream* find_mstream_in_mp (const char * name, OmlMP * mp)
Find a named MStream among the streams attached to an MP.
Parameters
name name of the stream to search for
mp MP in which to search for the stream
Returns
a pointer to the OmlMStream if found, or NULL if not (or name is NULL)
Definition at line 915 of file init.c.
References OmlMStream::next, OmlMP::streams, and OmlMStream::table_name.
Referenced by find_mstream().
{
  OmlMStream *ms = mp->streams;
  if (!name)
    return NULL;
  while (ms) {
    if (ms && ms->table_name && strcmp (name, ms->table_name) == 0)
      break;
    ms = ms->next;
  }
  return ms;
}
MString* mp_fields_summary (OmlMP * mp)
Create an MString containing a comma-separated list of the fields of the MP.
Parameters
mp OmlMP to summarize
Returns
the fields summary for mp. The caller is repsonsible for calling mstring_delete() to deallocate the returned MString.
Definition at line 889 of file init.c.
References mstring_cat(), mstring_create(), mstring_set(), name, OmlMP::param_count, and OmlMP::param_defs.
{
  int i;
  OmlMPDef *fields = mp->param_defs;
  MString *s = mstring_create();
  mstring_set (s, "'");
  if (!s) return NULL;
  for (i = 0; i < mp->param_count; i++) {
    mstring_cat (s, fields[i].name);
    if (i < mp->param_count - 1)
      mstring_cat (s, "', '");
  }
  mstring_cat (s, "'");
  return s;
}
OmlMStream* oml_mp_get_default_ms (OmlMP * mp)
Get or create a default MS for the given MP, reporting all fields, using the OML instance's default samples and intervals and writing to its default writer.
Parameters
mp OmlMP for which to set the filter configuration
Returns
the OmlMstream if successful, NULL otherwise
Definition at line 1153 of file init.c.
References create_default_filters(), create_mstream(), OmlMP::default_ms, OmlClient::default_writer, filter_engine_start(), logdebug(), logerror(), OmlMP::name, OmlClient::sample_count, OmlClient::sample_interval, and OmlMP::streams.
Referenced by omlc_add_mp().
{
  if(NULL == omlc_instance || NULL == mp) {
    return NULL;
  }
  logdebug("Getting default MS for MP %s\n", mp->name);
  if (!mp->default_ms) {
    if(!mp->streams) {
      create_mstream (NULL, mp,
          omlc_instance->default_writer,
          omlc_instance->sample_interval,
          omlc_instance->sample_count );
      if (NULL == mp->streams) {
        logerror("Error creating MS %s\n", mp->name);
        return NULL;
      }
      create_default_filters(mp, mp->streams);
      if (omlc_instance->sample_interval > 0) {
        filter_engine_start(mp->streams);
      }
    }
    mp->default_ms = mp->streams;
  }
  return mp->default_ms;
}
int oml_ms_add_writer (OmlMStream * ms, OmlWriter * w)
Add a new writer to an existing MS
Parameters
ms MStream to add w to
w writer to add to MS
Returns
0 on success, -1 on error (previous writers are preserved)
Definition at line 1052 of file init.c.
References logerror(), OmlMStream::nwriters, oml_realloc(), OmlMStream::table_name, and OmlMStream::writers.
Referenced by create_mstream().
{
  int n;
  OmlWriter **writers;
  if(!ms || !w) {
    logerror("%s: ms (%p) or w (%p) are invalid", __FUNCTION__, ms, w);
    return -1;
  }
  n = ms->nwriters + 1;
  writers = (OmlWriter **)oml_realloc(ms->writers, n*sizeof(OmlWriter*));
  if (!writers) {
    logerror("Cannot (re)allocate memory for %s's writers array\n", ms->table_name);
    return -1;
  }
  writers[n-1] = w;
  ms->writers = writers;
  ms->nwriters = n;
  return 0;
}
OMLSemDef* oml_sem_register_concepts (char *** concepts, int n)
Asign all concepts to the measurement Point
Parameters
concepts matrix of concepts
n number of triples
Returns
OMLSemDef* (can be NULL)
Author
Mario Poyato Pino mario.nosp@m..poy.nosp@m.ato@u.nosp@m.am.e.nosp@m.s
Definition at line 461 of file init.c.
References oml_malloc(), and xstrdup.
{
  int i=0;
  OMLSemDef *sd=NULL,*sd_last,*sd_aux;
  if (n>0) {
    sd = sd_last = sd_aux = (OMLSemDef*)oml_malloc(sizeof(OMLSemDef));
    while (i<n) {
      sd_aux->subject   = xstrdup(concepts[i][0]);
      sd_aux->predicate      = xstrdup(concepts[i][1]);
      sd_aux->object = xstrdup(concepts[i][2]);
      sd_aux->next      = NULL;
      if (++i<n) {
        sd_aux = (OMLSemDef*)oml_malloc(sizeof(OMLSemDef));
        sd_last->next = sd_aux;
        sd_last=sd_aux;
      }
    }
  }
  return sd;
}
OmlMP* omlc_add_mp (const char * mp_name, OmlMPDef * mp_def)
Register a measurement point.
This function should be called after omlc_init() and before omlc_start(). It can be called multiple times, once for each measurement point that the application needs to define.
The returned OmlMP must be the first argument in every omlc_inject() call for this specific measurement point.
XXX: The supplied name is not checked for existence.
The MP's input structure is defined by the mp_def parameter, it should be initialised as this example shows.
OmlMPDef mp_def[] =
{
  { "source", OML_UINT32_VALUE, NULL},
  { "destination", OML_UINT32_VALUE, NULL},
  { "length", OML_UINT32_VALUE, NULL},
  { "weight", OML_DOUBLE_VALUE, NULL},
  { "protocol", OML_STRING_VALUE, NULL},
  { NULL, (OmlValueT)0, NULL }
};
Parameters
mp_name The name of this MP. The name must not contain whitespace
mp_def Definition of this MP's input tuple, as an array of OmlMPDef objects
Returns
a new measurement point
See Also
omlc_init, omlc_start
Definition at line 365 of file init.c.
References OmlMP::active, OmlClient::app_name, destroy_sem_concepts(), OmlMStream::index, OmlClient::last_mpoint, logdebug(), logerror(), logwarn(), mp, mp_def, OmlClient::mpoints, mstring_buf(), mstring_create(), mstring_delete(), mstring_sprintf(), OmlMPDef::name, OmlMP::name, OmlMP::next, OmlClient::next_ms_idx, oml_free(), OML_LONG_VALUE, oml_malloc(), oml_mp_get_default_ms(), OML_STRING_VALUE, omlc_inject_metadata(), omlc_reset_string, omlc_set_string, omlc_zero, OmlMP::param_count, OmlMP::param_defs, OmlMPDef::param_types, OmlMPDef::relations, OmlClient::start_time, OmlMP::streams, and validate_name().
Referenced by main(), omlc_init(), and START_TEST().
{
  int pc = 0;
  char *schemastr;
  MString *meta;
  OmlValueU v;
  omlc_zero(v);
  if (omlc_instance == NULL) { return NULL; }
  if (!validate_name (mp_name)) {
    logerror("Illegal MP name '%s': missing or containing whitespaces or dashes; MP will not be created\n", mp_name);
    return NULL;
  }
  logdebug("Adding MP %s\n", mp_name);
  OmlMP* mp = (OmlMP*)oml_malloc(sizeof(OmlMP));
  memset(mp, 0, sizeof(OmlMP));
  mp->name = mp_name;
  mp->param_defs = mp_def;
  OmlMPDef* dp = mp_def;
  while (dp != NULL && dp->name != NULL) {
    if (dp->param_types == OML_LONG_VALUE) {
      logwarn("MP '%s', field '%s': OML_LONG_VALUE is deprecated, please use OML_INT32_VALUE instead; "
          "values outside of [INT_MIN, INT_MAX] will be clamped\n",
          mp->name, dp->name);
    }
    if (!validate_name (dp->name)) {
      logerror("Illegal field name '%s' in MP %s: missing or containing whitespaces or dashes; MP will not be created\n",
          dp->name, mp_name);
      while (destroy_sem_concepts(mp->param_defs->relations));
      oml_free (mp);
      return NULL;
    }
    pc++;
    dp++;
  }
  mp->param_count = pc;
  mp->active = 1;  // True if there is an attached MS.
  if(omlc_instance->start_time > 0) {
    /* omlc_start has already been called, declare MP through schema0 */
    meta = mstring_create();
    schemastr = schemastr_from_mpdef(mp_def);
    /* Unlike how we manage schema0, we do prepend the application name to the
     * MP name, even when declared after the start. This is mostly because that
     * concatenation happens anyway on the client side, when creating the
     * default filter configuration, and we don't want too many discrepancies
     * between the client and servers views at this stage. See #1055. */
    mstring_sprintf(meta, "%d %s_%s%s",
        omlc_instance->next_ms_idx, omlc_instance->app_name, mp_name, schemastr);
    oml_free(schemastr);
    logdebug("omlc_start already called, adding MP through schema 0: %s\n",
        mstring_buf(meta));
    omlc_set_string(v, mstring_buf(meta));
    omlc_inject_metadata(NULL, "schema", &v, OML_STRING_VALUE, NULL);
    omlc_reset_string(v);
    mstring_delete(meta);
    if (!oml_mp_get_default_ms(mp)) {
      logerror("Failed to create default MS for MP %s\n", mp_name);
      oml_free(mp);
      return NULL;
    }
    /* At this stage, we only have one stream set up, and we now its index */
    mp->streams->index = omlc_instance->next_ms_idx++;
  }
  if (NULL == omlc_instance->mpoints) {
    omlc_instance->mpoints = mp;
  } else {
    omlc_instance->last_mpoint->next = mp;
  }
  omlc_instance->last_mpoint = mp;
  return mp;
}
int omlc_close (void)
Terminate all open connections.
Once this function has been called, any futher calls to omlc_inject() will be ignored.
This call doesn't free all memory used by OML immediately. There may be a few threads which will take some time to finish while the remaining buffered data is sent.
Returns
0 on sucess, -1 otherwise
Definition at line 637 of file init.c.
References OmlWriter::close, destroy_mp(), OmlClient::first_writer, OmlClient::mpoints, O_LOG_DEBUG, oml_free(), oml_memreport(), and unregister_filters().
Referenced by main(), oml_cleanup(), omlc_init(), omlc_start(), and START_TEST().
{
  if (NULL == omlc_instance) {
    return 0; /* Already clear */
  } else {
    OmlWriter* w = omlc_instance->first_writer;
    OmlMP* mp = omlc_instance->mpoints;
    install_close_handler(SIG_DFL);
    while( (mp = destroy_mp(mp)) );
    if (w) {
      while( (w =  w->close(w)) );
    }
    unregister_filters ();
    oml_free(omlc_instance);
  }
  omlc_instance = NULL;
  oml_memreport(O_LOG_DEBUG);
  return 0;
}
int omlc_init (const char * application, int * pargc, const char ** argv, o_log_fn custom_oml_log)
Initialise the measurement library.
This functions parses the command line for –oml-* options and acts accordingly when they are found. A side effect of this function is that these options and their arguments are removed from argv, so the instrumented application doesn't see spurious OML option it can't make sense of.
Parameters
name name of the application
pargc argc of the command line of the application
argv argv of the command line of the application
custom_oml_log custom format-based logging function
Returns
0 on success, -1 on failure, 1 when OML is disabled.
See Also
omlc_add_mp, omlc_start, omlc_close
o_log_fn, o_set_log
Definition at line 96 of file init.c.
References OmlClient::app_name, OmlClient::client_instr, OmlClient::collection_uri, COLLECTION_URI_MAX_LENGTH, OmlClient::config_file, OmlClient::default_encoding, OmlClient::domain, OmlClient::instr_interval, OmlClient::instr_time, logerror(), loginfo(), logwarn(), OmlClient::max_queue, name, OmlClient::node_name, O_LOG_INFO, o_set_log(), o_set_log_file(), o_set_log_level(), oml_malloc(), OML_PROTOCOL_VERSION, omlc_add_mp(), omlc_close(), OMLC_COPYRIGHT, register_builtin_filters(), OmlClient::sample_count, OmlClient::sample_interval, SE_Binary, SE_None, SE_Text, validate_app_name(), and VERSION.
Referenced by main(), oml_setup(), and START_TEST().
{
  const char *app_name = validate_app_name (application);
  const char* name = NULL;
  const char* domain = NULL;
  const char* config_file = NULL;
  const char* local_data_file = NULL;
  const char* collection_uri = NULL;
  char *start = NULL, *end = NULL; /* For strtoX(3) */
  enum StreamEncoding default_encoding = SE_None;
  int sample_count = 0;
  double sample_interval = 0.0;
  int max_queue = 0;
  uint32_t instr_interval = 1;
  const char** arg = argv;
  if (!app_name) {
    logerror("Illegal application name '%s': missing or containing whitespaces or dashes\n", application);
    return -1;
  }
  omlc_instance = NULL;
  o_set_log_level(O_LOG_INFO);
  if (custom_oml_log)
    o_set_log (custom_oml_log);
  if (pargc && arg) {
    int i;
    for (i = *pargc; i > 0; i--, arg++) {
      if (strcmp(*arg, "--oml-id") == 0) {
        if (--i <= 0) {
          logerror("Missing argument for '--oml-id'\n");
          return -1;
        }
        name = *++arg;
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-domain") == 0) {
        if (--i <= 0) {
          logerror("Missing argument for '--oml-domain'\n");
          return -1;
        }
        domain = *++arg;
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-exp-id") == 0) {
        if (--i <= 0) {
          logerror("Missing argument for '--oml-exp-id'\n");
          return -1;
        }
        domain = *++arg;
        logwarn("Option --oml-exp-id is getting deprecated; please use '--oml-domain %s' instead\n", domain);
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-file") == 0) {
        if (--i <= 0) {
          logerror("Missing argument for '--oml-file'\n");
          return -1;
        }
        local_data_file = *++arg;
        logwarn("Option --oml-file is getting deprecated; please use '--oml-collect file:%s' instead\n", local_data_file);
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-collect") == 0) {
        if (--i <= 0) {
          logerror("Missing argument for '--oml-collect'\n");
          return -1;
        }
        collection_uri = (char*)*++arg;
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-config") == 0) {
        if (--i <= 0) {
          logerror("Missing argument for '--oml-config'\n");
          return -1;
        }
        config_file = *++arg;
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-samples") == 0) {
        if (--i <= 0) {
          logerror("Missing argument to '--oml-samples'\n");
          return -1;
        }
        sample_count = atoi(*++arg);
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-interval") == 0) {
        if (--i <= 0) {
          logerror("Missing argument to '--oml-interval'\n");
          return -1;
        }
        sample_interval = atof(*++arg);
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-log-file") == 0) {
        if (--i <= 0) {
          logerror("Missing argument to '--oml-log-file'\n");
          return -1;
        }
        o_set_log_file((char*)*++arg);
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-log-level") == 0) {
        if (--i <= 0) {
          logerror("Missing argument to '--oml-log-level'\n");
          return -1;
        }
        o_set_log_level(atoi(*++arg));
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-server") == 0) {
        if (--i <= 0) {
          logerror("Missing argument for '--oml-server'\n");
          return -1;
        }
        collection_uri = (char*)*++arg;
        logwarn("Option --oml-server is getting deprecated; please use '--oml-collect %s' instead\n", collection_uri);
        *pargc -= 2;
      } else if (strcmp (*arg, "--oml-text") == 0) {
        *pargc -= 1;
        default_encoding = SE_Text;
      } else if (strcmp (*arg, "--oml-binary") == 0) {
        *pargc -= 1;
        default_encoding = SE_Binary;
      } else if (strcmp(*arg, "--oml-bufsize") == 0) {
        if (--i <= 0) {
          logerror("Missing argument to '--oml-bufsize'\n");
          return -1;
        }
        max_queue = atoi(*++arg);
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-instr-interval") == 0) {
        start = (char *)*++arg; /* XXX: Drop arg's const */
        end = NULL;
        if (--i <= 0) {
          logerror("Missing argument to '--oml-instr-interval'\n");
          return -1;
        }
        instr_interval = strtoul(start, &end, 10);
        if(end == *arg || *end != '\0') {
          logwarn("Invalid argument to '--oml-instr-interval'\n");
          instr_interval = 0;
        }
        *pargc -= 2;
        if(0 == instr_interval) {
          loginfo("Client instrumentation disabled\n");
        }
      } else if (strcmp(*arg, "--oml-noop") == 0) {
        *pargc -= 1;
        omlc_close();
        return 1;
      } else if (strcmp(*arg, "--oml-help") == 0) {
        usage();
        *pargc -= 1;
        exit(0);
      } else if (strcmp(*arg, "--oml-list-filters") == 0) {
        print_filters();
        *pargc -= 1;
        exit(0);
      } else {
        *argv++ = *arg;
      }
    }
  }
  if (name == NULL) {
    name = getenv("OML_NAME");
  }
  if (domain == NULL) {
    if(!(domain = getenv("OML_DOMAIN"))) {
      if ((domain= getenv("OML_EXP_ID"))) {
        logwarn("Enviromnent variable OML_EXP_ID is getting deprecated; please use 'OML_DOMAIN=\"%s\"' instead\n",
            domain);
      }
    }
  }
  if (config_file == NULL) {
    config_file = getenv("OML_CONFIG");
  }
  if (local_data_file == NULL && collection_uri == NULL) {
    if(!(collection_uri = getenv("OML_COLLECT"))) {
      if ((collection_uri = getenv("OML_SERVER"))) {
        logwarn("Enviromnent variable OML_SERVER is getting deprecated; please use 'OML_COLLECT=\"%s\"' instead\n",
            collection_uri);
      }
    }
  }
  if(collection_uri == NULL) {
    collection_uri = default_uri(app_name, name, domain);
  }
  setup_features (getenv ("OML_FEATURES"));
  omlc_instance = oml_malloc(sizeof(OmlClient));
  memset(omlc_instance, 0, sizeof(OmlClient));
  omlc_instance->app_name = app_name;
  omlc_instance->node_name = name;
  omlc_instance->domain = domain;
  omlc_instance->sample_count = sample_count;
  omlc_instance->sample_interval = sample_interval;
  omlc_instance->default_encoding = default_encoding;
  omlc_instance->max_queue = max_queue;
  omlc_instance->instr_time = 0;
  omlc_instance->instr_interval = instr_interval;
  if (local_data_file != NULL) {
    // dump every sample into local_data_file
    if (local_data_file[0] == '-')
      local_data_file = "stdout";
    snprintf(omlc_instance->collection_uri, COLLECTION_URI_MAX_LENGTH, "file:%s", local_data_file);
  } else if (collection_uri != NULL) {
    strncpy(omlc_instance->collection_uri, collection_uri, COLLECTION_URI_MAX_LENGTH);
  }
  omlc_instance->config_file = config_file;
  register_builtin_filters ();
  schema0 = omlc_add_mp("_experiment_metadata", _experiment_metadata);
  omlc_instance->client_instr = omlc_add_mp("_client_instrumentation", _client_instrumentation);
  loginfo ("OML Client %s [OMSPv%d] %s\n",
           VERSION,
           OML_PROTOCOL_VERSION,
           OMLC_COPYRIGHT);
  return 0;
}
int omlc_start (void)
Get ready to start the measurement collection.
This function must be called after omlc_init and after any calls to omlc_add_mp(). It finalises the initialisation process and initialises filters on all measurement points, according to the current configuration (based on either command line options or the XML config file named by the –oml-config command line option).
It also registers a termination handler.
Once this function has been called, and if it succeeds, the application is free to start creating measurement samples by calling omlc_inject().
If this function fails, subsequent calls to omlc_inject() will result in undefined behaviour.
Returns
0 on success, -1 on failure
See Also
omlc_init, omlc_add_mp, omlc_close
install_close_handler, termination_handler
Definition at line 539 of file init.c.
References OmlClient::collection_uri, OmlClient::config_file, logerror(), omlc_close(), parse_config(), and OmlClient::start_time.
Referenced by main(), oml_setup(), and START_TEST().
{
  if (omlc_instance == NULL) { return -1; }
  struct timeval tv;
  gettimeofday(&tv, NULL);
  omlc_instance->start_time = tv.tv_sec;
  const char* config_file = omlc_instance->config_file;
  if (config_file) {
    if (parse_config((char*)config_file)) {
      logerror("Error while parsing configuration '%s'\n", config_file);
      omlc_close();
      return -1;
    }
  } else {
    if (omlc_instance->collection_uri == NULL) {
      logerror("Missing --oml-collect declaration.\n");
      omlc_close();
      return -2;
    }
    if (default_configuration()) {
      omlc_close();
      return -3;
    }
  }
  install_close_handler(termination_handler);
  if (write_meta() == -1) {
    return -1;
  }
  return 0;
}
int parse_config (char * configFile)
Parse the config file to configure liboml2.
Parameters
configFile the name of the config file
Returns
0 if successful <0 otherwise
Definition at line 223 of file parse_config.c.
References CT_COLLECT, CT_EXP, CT_NODE, CT_ROOT, OmlClient::domain, logdebug(), logerror(), OmlClient::node_name, and omlc_instance.
Referenced by omlc_start().
{
  xmlDocPtr doc;
  xmlNodePtr cur;
  logdebug("Using configuration file '%s'\n", configFile);
  if ((doc = xmlParseFile(configFile)) == NULL) {
    logerror("Config file '%s' not parsed successfully.\n",
      configFile);
    return -1;
  }
  if ((cur = xmlDocGetRootElement(doc)) == NULL) {
    logerror("Config file '%s' is empty.\n", configFile);
    xmlFreeDoc(doc);
    return -2;
  }
  if (!match_xml_elt (cur, CT_ROOT)) {
    logerror("Config file has incorrect root '%s', should be '%s'.\n",
             cur->name, canonical_name (CT_ROOT));
    xmlFreeDoc(doc);
    return -3;
  }
  if (omlc_instance->node_name == NULL) {
    omlc_instance->node_name = get_xml_attr(cur, CT_NODE);
  }
  if (omlc_instance->domain == NULL) {
    omlc_instance->domain = get_xml_attr(cur, CT_EXP);
  }
  cur = cur->xmlChildrenNode;
  while (cur != NULL) {
    if (match_xml_elt(cur, CT_COLLECT)) {
      if (parse_collector(cur)) {
        xmlFreeDoc(doc);
        return -4;
      }
    }
    cur = cur->next;
  }
  xmlFreeDoc(doc);
  return 0;
}
const char* validate_app_name (const char * name)
Validate the name of the application.
If the application name contains a '/', it is truncated to the sub-string following the final '/'. If the application name contains any characters other than alphanumeric characters or an underscore, it is declared invalid. The first character must not be a digit. Whitespace is not allowed. An empty string is also not allowed.
Parameters
name the name of the application.
Returns
If the application name is valid, a pointer to the application name, possibly truncated, is returned. If the application name is not valid, returns NULL. If the returned pointer is not NULL, it may be different from name.
Definition at line 1473 of file init.c.
References validate_name().
Referenced by omlc_init().
{
  size_t len = strlen (name);
  const char* p = name + len - 1;
  while (p >= name) {
    if (*p == '/')
      break;
    p--;
  }
  /* Either 1 character before name, or '/': need to move forward 1 character */
  p++;
  if (validate_name (p))
    return p;
  else
    return NULL;
}
Variable Documentation
void(* enable)(void)
Definition at line 1494 of file init.c.
const char* name
Definition at line 1493 of file init.c.
Referenced by create_default_filter(), database_create_function(), free_list(), mp_fields_summary(), next_filter_name(), oml_type_from_s(), oml_type_to_s(), omlc_init(), read_mp(), read_mp_def(), schema_from_sql(), schema_to_sql(), START_TEST(), table_descr_array_free(), tag_from_string(), and validate_name().
OmlClient* omlc_instance = NULL
Global OmlClient instance
Definition at line 40 of file init.c.
Referenced by bin_writer_new(), omlc_inject(), omlc_inject_metadata(), parse_config(), START_TEST(), and text_writer_new().
OmlMP* schema0
Definition at line 50 of file init.c.