oml2: last_filter.c File Reference
last_filter.c File Reference
Implements a filter which captures the last value presented.
#include <stdlib.h>
#include <string.h>
#include "oml2/omlc.h"
#include "oml2/oml_filter.h"
#include "ocomm/o_log.h"
#include "oml_value.h"
#include "last_filter.h"
Macros
#define FILTER_NAME "last"
Typedefs
typedef struct
OmlLastFilterInstanceData InstanceData
Functions
void * omlf_last_new (OmlValueT type, OmlValue *result)
void omlf_register_filter_last (void)
Detailed Description
Implements a filter which captures the last value presented.
Definition in file last_filter.c.
Macro Definition Documentation
#define FILTER_NAME "last"
Definition at line 23 of file last_filter.c.
Referenced by omlf_last_new(), and omlf_register_filter_last().
Typedef Documentation
typedef struct OmlLastFilterInstanceData InstanceData
Definition at line 25 of file last_filter.c.
Function Documentation
void* omlf_last_new (OmlValueT type, OmlValue * result)
Definition at line 37 of file last_filter.c.
References FILTER_NAME, logerror(), oml_malloc(), and OmlLastFilterInstanceData::result.
Referenced by omlf_register_filter_last().
  {
  InstanceData* self = (InstanceData *)oml_malloc(sizeof(InstanceData));
  if(self) {
    memset(self, 0, sizeof(InstanceData));
    self->result = result;
    self->sample_count = 0;
  } else {
    logerror ("%s filter: Could not allocate %d bytes for instance data\n",
        FILTER_NAME,
        sizeof(InstanceData));
    return NULL;
  }
  return self;
}
void omlf_register_filter_last (void)
Definition at line 59 of file last_filter.c.
References FILTER_NAME, OML_INPUT_VALUE, omlf_last_new(), and omlf_register_filter().
Referenced by register_builtin_filters().
{
  OmlFilterDef def [] =
    {
      { "last", OML_INPUT_VALUE },
      { NULL, 0 }
    };
  omlf_register_filter (FILTER_NAME,
            omlf_last_new,
            NULL,
            sample,
            process,
            newwindow,
            NULL,
            def);
}