oml2: mbuf.h File Reference
mbuf.h File Reference
#include <stdlib.h>
#include <stdint.h>
#include <stdarg.h>
Data Structures
struct MBuffer
Typedefs
typedef struct MBuffer MBuffer
Functions
MBuffer * mbuf_create (void)
MBuffer * mbuf_create2 (size_t buffer_length, size_t min_resize)
void mbuf_destroy (MBuffer *mbuf)
uint8_t * mbuf_buffer (MBuffer *mbuf)
uint8_t * mbuf_message (MBuffer *mbuf)
uint8_t * mbuf_rdptr (MBuffer *mbuf)
uint8_t * mbuf_wrptr (MBuffer *mbuf)
size_t mbuf_length (MBuffer *mbuf)
size_t mbuf_remaining (MBuffer *mbuf) __attribute__((deprecated))
size_t mbuf_rd_remaining (MBuffer *mbuf)
size_t mbuf_wr_remaining (MBuffer *mbuf)
size_t mbuf_fill (MBuffer *mbuf)
size_t mbuf_fill_excluding_msg (MBuffer *mbuf)
size_t mbuf_read_offset (MBuffer *mbuf)
size_t mbuf_write_offset (MBuffer *mbuf)
size_t mbuf_message_offset (MBuffer *mbuf)
size_t mbuf_message_length (MBuffer *mbuf)
size_t mbuf_message_index (MBuffer *mbuf)
int mbuf_resize (MBuffer *mbuf, size_t new_length)
int mbuf_check_resize (MBuffer *mbuf, size_t bytes)
int mbuf_begin_write (MBuffer *mbuf)
int mbuf_reset_write (MBuffer *mbuf)
int mbuf_write (MBuffer *mbuf, const uint8_t *buf, size_t len)
int mbuf_print (MBuffer *mbuf, const char *format,...)
int mbuf_begin_read (MBuffer *mbuf)
int mbuf_reset_read (MBuffer *mbuf)
int mbuf_read (MBuffer *mbuf, uint8_t *buf, size_t len)
int mbuf_read_skip (MBuffer *mbuf, size_t len)
int mbuf_read_byte (MBuffer *mbuf)
size_t mbuf_find (MBuffer *mbuf, uint8_t c)
size_t mbuf_find_not (MBuffer *mbuf, uint8_t c)
int mbuf_consume_message (MBuffer *mbuf)
void mbuf_message_start_advance (MBuffer *mbuf, size_t n)
int mbuf_repack (MBuffer *mbuf)
int mbuf_repack_message (MBuffer *mbuf)
int mbuf_repack_message2 (MBuffer *mbuf)
int mbuf_clear (MBuffer *mbuf)
int mbuf_clear2 (MBuffer *mbuf, int zeroBuffer)
Typedef Documentation
typedef struct MBuffer MBuffer
Function Documentation
int mbuf_begin_read (MBuffer * mbuf)
Prepare to read a message from an MBuffer.
Adjust the msgptr to the current rdptr.
Parameters
mbuf MBuffer to manipulate
Returns
0 on success, -1 on failure
See Also
mbuf_message, mbuf_message_length, mbuf_consume_message, mbuf_repack_message, mbuf_repack_message2
Definition at line 592 of file mbuf.c.
References MBuffer::msgptr, and MBuffer::rdptr.
Referenced by bin_read_msg_start(), START_TEST(), unmarshal_init(), and unmarshal_values().
{
  mbuf_check_invariant (mbuf);
  if (mbuf == NULL) return -1;
  mbuf->msgptr = mbuf->rdptr;
  mbuf_check_invariant (mbuf);
  return 0;
}
int mbuf_begin_write (MBuffer * mbuf)
Prepare to write a new message to an MBuffer.
Adjust the msgptr to the current wrptr.
Parameters
mbuf MBuffer to manipulate
Returns
0 on success, -1 on failure
See Also
mbuf_message, mbuf_consume_message, mbuf_repack_message, mbuf_repack_message2
Definition at line 614 of file mbuf.c.
References MBuffer::msgptr, and MBuffer::wrptr.
Referenced by marshal_init(), and START_TEST().
{
  mbuf_check_invariant (mbuf);
  if (mbuf == NULL) return -1;
  mbuf->msgptr = mbuf->wrptr;
  mbuf_check_invariant (mbuf);
  return 0;
}
uint8_t* mbuf_buffer (MBuffer * mbuf)
Get an MBuffer's storage.
Parameters
mbuf MBuffer to manipulate
Returns
a pointer to mbuf's memory buffer
Definition at line 109 of file mbuf.c.
References MBuffer::base.
Referenced by START_TEST().
{
  return mbuf->base;
}
int mbuf_check_resize (MBuffer * mbuf, size_t bytes)
Resize an MBuffer if it cannot contain the specified amount of data.
Parameters
mbuf MBuffer to manipulate
bytes amount of data which need to be stored into the MBuffer
Returns
0 on success, or -1 on error
See Also
mbuf_resize
Definition at line 354 of file mbuf.c.
References MBuffer::length, mbuf_resize(), MBuffer::min_resize, and MBuffer::wr_remaining.
Referenced by mbuf_print(), and mbuf_write().
{
  if (mbuf->wr_remaining < bytes) {
    size_t inc = bytes - mbuf->wr_remaining;
    size_t min_resize = mbuf->min_resize > 0 ? mbuf->min_resize : mbuf->length;
    inc = min_resize * (inc / min_resize + 1);
    return mbuf_resize (mbuf, mbuf->length + inc);
  } else {
    return 0;
  }
}
int mbuf_clear (MBuffer * mbuf)
Clear the content of an MBuffer and zero it out.
Parameters
mbuf MBuffer to manipulate
Returns
0 on success, -1 otherwise
See Also
mbuf_clear2
Definition at line 634 of file mbuf.c.
References mbuf_clear2().
Referenced by proxy_message_loop(), and START_TEST().
{
  return mbuf_clear2(mbuf, 1);
}
int mbuf_clear2 (MBuffer * mbuf, int zero_buffer)
Clear the content of an MBuffer and optionaly zero it out.
Resets the read, write and message pointers to the base.
Parameters
mbuf MBuffer to manipulate
zero_buffer non-zero if the memory must be actively cleared
Returns
0 on success, -1 otherwise
Definition at line 648 of file mbuf.c.
References MBuffer::base, MBuffer::fill, MBuffer::length, MBuffer::msgptr, MBuffer::rd_remaining, MBuffer::rdptr, MBuffer::wr_remaining, and MBuffer::wrptr.
Referenced by mbuf_clear().
{
  mbuf_check_invariant (mbuf);
  if (mbuf == NULL) return -1;
  if (zero_buffer) {
    memset (mbuf->base, 0, mbuf->length);
  }
  mbuf->rdptr = mbuf->wrptr = mbuf->msgptr = mbuf->base;
  mbuf->fill = 0;
  mbuf->wr_remaining = mbuf->length;
  mbuf->rd_remaining = 0;
  mbuf_check_invariant (mbuf);
  return 0;
}
int mbuf_consume_message (MBuffer * mbuf)
Advance to a new message.
This is syntactic sugar to be called when all of a message has been processed by the caller, to advance the message pointer to the current read pointer iff it is behind (i.e., not writing).
Parameters
mbuf MBuffer to manipulate
Returns
0 on success, -1 otherwise
See Also
mbuf_begin_read
Definition at line 731 of file mbuf.c.
References MBuffer::msgptr, and MBuffer::rdptr.
Referenced by bin_find_sync(), bin_read_msg_values(), proxy_message_loop(), START_TEST(), and text_read_msg_values().
{
  mbuf_check_invariant (mbuf);
  if (mbuf == NULL) return -1;
  // Can't consume message if we're in the middle of writing it
  if (mbuf->msgptr > mbuf->rdptr)
    return -1;
  mbuf->msgptr = mbuf->rdptr; /* Not using mbuf_begin_read to avoid redundant calls to mbuf_check_invariant */
  mbuf_check_invariant (mbuf);
  return 0;
}
MBuffer* mbuf_create (void)
Create an MBuf with the default parameters.
Returns
a pointer to the newly allocated MBuffer
See Also
mbuf_create2, DEF_BUF_SIZE, DEF_MIN_BUF_RESIZE
Definition at line 43 of file mbuf.c.
References DEF_BUF_SIZE, DEF_MIN_BUF_RESIZE, and mbuf_create2().
Referenced by bw_create(), check_server_prepare_client_handler(), client_handler_new(), client_new(), and START_TEST().
{
  return mbuf_create2(DEF_BUF_SIZE, DEF_MIN_BUF_RESIZE);
}
MBuffer* mbuf_create2 (size_t buffer_length, size_t min_resize)
Create an MBuf.
If buffer_length or min_resize are negative or NULL, the default values are used instead.
Parameters
buffer_length initial memory allocation length
min_resize minimun length by which the buffer should be grown when it is
Returns
a pointer to the newly allocated MBuffer
See Also
DEF_BUF_SIZE, DEF_MIN_BUF_RESIZE
Definition at line 58 of file mbuf.c.
References MBuffer::allow_resizing, MBuffer::base, DEF_BUF_SIZE, DEF_MIN_BUF_RESIZE, MBuffer::fill, MBuffer::length, MBuffer::min_resize, MBuffer::msgptr, oml_free(), oml_malloc(), MBuffer::rd_remaining, MBuffer::rdptr, MBuffer::wr_remaining, and MBuffer::wrptr.
Referenced by mbuf_create().
{
  MBuffer* mbuf = oml_malloc (sizeof (MBuffer));
  if (mbuf == NULL) return NULL;
  mbuf->length = buffer_length > 0 ? buffer_length : DEF_BUF_SIZE;
  mbuf->min_resize = min_resize > 0 ? min_resize : DEF_MIN_BUF_RESIZE;
  mbuf->base = oml_malloc (mbuf->length);
  if (mbuf->base == NULL) {
    oml_free (mbuf);
    return NULL;
  }
  mbuf->rdptr = mbuf->base;
  mbuf->wrptr = mbuf->base;
  mbuf->msgptr = mbuf->base;
  mbuf->fill = 0;
  mbuf->wr_remaining = mbuf->length;
  mbuf->rd_remaining = 0;
  mbuf->allow_resizing = 1;
  mbuf_check_invariant(mbuf);
  return mbuf;
}
void mbuf_destroy (MBuffer * mbuf)
Destroy an MBuffer and its storage.
Frees both the MBuffer object and its allocated buffer.
Parameters
mbuf MBuffer to free
Definition at line 92 of file mbuf.c.
References MBuffer::base, logdebug(), and oml_free().
Referenced by check_server_destroy_client_handler(), client_handler_free(), and START_TEST().
{
  if(!mbuf)
    return;
  logdebug("Destroying MBuffer %p\n", mbuf);
  oml_free (mbuf->base);
  oml_free (mbuf);
}
size_t mbuf_fill (MBuffer * mbuf)
Get the currently occupied size of the MBuffer.
Parameters
mbuf MBuffer to manipulate
Returns
the stored data size as an size_t
Definition at line 167 of file mbuf.c.
References MBuffer::fill.
Referenced by START_TEST().
{
  return mbuf->fill;
}
size_t mbuf_fill_excluding_msg (MBuffer * mbuf)
Get the currently occupied size of the MBuffer, not including the message currently being written.
Parameters
mbuf MBuffer to manipulate
Returns
the stored data size as an size_t, or 0 if a message is currently being read
Definition at line 179 of file mbuf.c.
References MBuffer::msgptr, and MBuffer::rdptr.
{
  if (mbuf->msgptr > mbuf->rdptr) /* message message being written */
    return mbuf->msgptr - mbuf->rdptr;
  return 0; /* message being read; don't know how long it will be */
}
size_t mbuf_find (MBuffer * mbuf, uint8_t c)
Find a byte in an MBuffer.
Parameters
mbuf MBuffer to search
c byte to search for
Returns
offset from the read pointer to the first matching byte, or -1 if not found
Definition at line 540 of file mbuf.c.
References MBuffer::rdptr.
Referenced by read_header(), and text_read_msg_start().
{
  if (mbuf == NULL) return -1;
  mbuf_check_invariant (mbuf);
  uint8_t* p = mbuf->rdptr;
  while (p < mbuf->wrptr && *p != c) p++;
  int result = -1;
  if (p < mbuf->wrptr && *p == c)
    result = p - mbuf->rdptr;
  mbuf_check_invariant (mbuf);
  return result;
}
size_t mbuf_find_not (MBuffer * mbuf, uint8_t c)
Find the first byte in an MBuffer different from argument.
Parameters
mbuf MBuffer to search
c byte to not find
Returns
offset from the read pointer to the first non-matching byte, or -1 if not found
Definition at line 565 of file mbuf.c.
References MBuffer::rdptr.
Referenced by read_header().
{
  if (mbuf == NULL) return -1;
  mbuf_check_invariant (mbuf);
  uint8_t* p = mbuf->rdptr;
  while (p < mbuf->wrptr && *p == c) p++;
  int result = -1;
  if (p < mbuf->wrptr && *p != c)
    result = p - mbuf->rdptr;
  mbuf_check_invariant (mbuf);
  return result;
}
size_t mbuf_length (MBuffer * mbuf)
Get the length of the MBuffer's allocated buffer.
Parameters
mbuf MBuffer to manipulate
Returns
the allocated size as an size_t
Definition at line 120 of file mbuf.c.
References MBuffer::length.
Referenced by START_TEST().
{
  return mbuf->length;
}
uint8_t* mbuf_message (MBuffer * mbuf)
Get the current message.
Parameters
mbuf MBuffer to manipulate
Returns
a pointer to the beginning of the current message (msgptr)
Definition at line 262 of file mbuf.c.
References MBuffer::msgptr.
Referenced by marshal_finalize(), marshal_get_msgtype(), marshal_values(), and START_TEST().
{
  return mbuf->msgptr;
}
size_t mbuf_message_index (MBuffer * mbuf)
Get the current message's index.
Parameters
mbuf MBuffer to manipulate
Returns
the difference between rdptr and msgptr
Definition at line 225 of file mbuf.c.
References MBuffer::msgptr, and MBuffer::rdptr.
Referenced by text_read_msg_values().
{
  return mbuf->rdptr - mbuf->msgptr;
}
size_t mbuf_message_length (MBuffer * mbuf)
Get the current message's length.
Parameters
mbuf MBuffer to manipulate
Returns
the difference between wrptr and msgptr
Definition at line 236 of file mbuf.c.
References MBuffer::msgptr, and MBuffer::wrptr.
Referenced by marshal_finalize(), and START_TEST().
{
  return mbuf->wrptr - mbuf->msgptr;
}
size_t mbuf_message_offset (MBuffer * mbuf)
Get the message offset from the base of the MBuffer.
Parameters
mbuf MBuffer to manipulate
Returns
the stored data size as an size_t
Definition at line 214 of file mbuf.c.
References MBuffer::base, and MBuffer::msgptr.
Referenced by mbuf_message_start_advance().
{
  return mbuf->msgptr - mbuf->base;
}
void mbuf_message_start_advance (MBuffer * mbuf, size_t n)
Advance the message pointer, if room.
XXX: Fails silently otherwise.
Parameters
mbuf MBuffer to manipulate
n the length by which the pointer is advanced
Definition at line 249 of file mbuf.c.
References mbuf_message_offset(), and MBuffer::msgptr.
{
  if (mbuf && n < mbuf->fill - mbuf_message_offset (mbuf)) {
    mbuf->msgptr += n;
  }
}
int mbuf_print (MBuffer * mbuf, const char * format, ...)
Append the printed string described by format to the MBuffer.
Write the string described by a format string and arguments to the MBuffer, resizing it if need be.
If the function succeeds, the string is written starting at the MBuffer's write pointer, and the write pointer is advanced by the size of the string (excluding the '\0').
NOTE: At the end, the write pointer points to the terminating NULL character of the string.
Parameters
mbuf MBuffer to write the string to
format format string
... arguments for the format string
Returns
0 on success, -1 on failure
See Also
vsnprintf(3)
Definition at line 421 of file mbuf.c.
References MBuffer::fill, mbuf_check_resize(), MBuffer::rd_remaining, MBuffer::wr_remaining, and MBuffer::wrptr.
{
  if (mbuf == NULL || format == NULL) return -1;
  mbuf_check_invariant (mbuf);
  int len;
  int success = 0;
  do {
    va_list arglist;
    va_start(arglist, format);
    len = vsnprintf((char*)mbuf->wrptr, mbuf->wr_remaining, format, arglist);
    va_end(arglist);
    if (! (success = (len <= (int)mbuf->wr_remaining))) {
      if (mbuf_check_resize(mbuf, len) == -1)
    return -1;
    }
  } while (! success);
  /* XXX: should we advance by one more to keep the '\0'? */
  mbuf->wrptr += len;
  mbuf->fill += len;
  mbuf->wr_remaining -= len;
  mbuf->rd_remaining += len;
  mbuf_check_invariant (mbuf);
  return 0;
}
size_t mbuf_rd_remaining (MBuffer * mbuf)
Get the remaining amount of data to read in MBuffer
XXX: Shall we use rd_remaining directly?
Parameters
mbuf MBuffer to manipulate
Returns
the number of unread bytes in the buffer
Definition at line 142 of file mbuf.c.
References MBuffer::rdptr, and MBuffer::wrptr.
Referenced by bin_find_sync(), bin_read_msg_start(), mbuf_remaining(), START_TEST(), unmarshal_init(), and unmarshal_value().
{
  return mbuf->wrptr - mbuf->rdptr;
}
uint8_t* mbuf_rdptr (MBuffer * mbuf)
Get the read pointer.
Parameters
mbuf MBuffer to manipulate
Returns
the read pointer rdptr
Definition at line 273 of file mbuf.c.
References MBuffer::rdptr.
Referenced by bin_find_sync(), proxy_message_loop(), and unmarshal_value().
{
  return mbuf->rdptr;
}
int mbuf_read (MBuffer * mbuf, uint8_t * buf, size_t len)
Read bytes from an MBuffer.
Read len bytes from the MBuffer into the raw buffer pointed to by buf. If the MBuffer doesn't have at least len bytes available to read, the function fails.
If the function succeeds, the bytes are written to buf, with reading starting at the MBuffer's read pointer, and the read pointer is then advanced by len bytes.
Parameters
mbuf MBuffer to read from
buf buffer into which the read data should be put
len size of data to read
Returns
0 on success, -1 on failure
Definition at line 466 of file mbuf.c.
References MBuffer::rd_remaining, and MBuffer::rdptr.
Referenced by bin_read_msg_start(), START_TEST(), unmarshal_init(), and unmarshal_value().
{
  if (mbuf == NULL || buf == NULL) return -1;
  mbuf_check_invariant (mbuf);
  if (mbuf->rd_remaining < len) return -1;
  memcpy (buf, mbuf->rdptr, len);
  mbuf->rdptr += len;
  mbuf->rd_remaining -= len;
  mbuf_check_invariant (mbuf);
  return 0;
}
int mbuf_read_byte (MBuffer * mbuf)
Read a single byte from an MBuffer.
Parameters
mbuf MBuffer to read from
Returns
the read byte, or -1 if no data was available
Definition at line 515 of file mbuf.c.
References MBuffer::rd_remaining, and MBuffer::rdptr.
Referenced by unmarshal_value().
{
  if (mbuf == NULL) return -1;
  mbuf_check_invariant (mbuf);
  if (mbuf->rd_remaining < 1) return -1;
  int byte = (int)*(mbuf->rdptr);
  mbuf->rdptr++;
  mbuf->rd_remaining--;
  mbuf_check_invariant (mbuf);
  return byte;
}
size_t mbuf_read_offset (MBuffer * mbuf)
Get the read offset from the base of the MBuffer.
Parameters
mbuf MBuffer to manipulate
Returns
the stored data size as an size_t
Definition at line 192 of file mbuf.c.
References MBuffer::base, and MBuffer::rdptr.
{
  return mbuf->rdptr - mbuf->base;
}
int mbuf_read_skip (MBuffer * mbuf, size_t len)
Skip some data to be read from an MBuffer.
This simply advances the read pointer.
Parameters
mbuf MBuffer to manipulate
len amount of data to skip
Returns
0 on success, or -1 otherwise
Definition at line 493 of file mbuf.c.
References MBuffer::rd_remaining, and MBuffer::rdptr.
Referenced by bin_find_sync(), bin_read_msg_start(), proxy_message_loop(), read_header(), START_TEST(), unmarshal_value(), and unmarshal_values().
{
  if (mbuf == NULL) return -1;
  mbuf_check_invariant (mbuf);
  if (mbuf->rd_remaining < len) return -1;
  mbuf->rdptr += len;
  mbuf->rd_remaining -= len;
  mbuf_check_invariant (mbuf);
  return 0;
}
size_t mbuf_remaining (MBuffer * mbuf) inline
Get the remaining amount of data to read in MBuffer XXX: Use mbuf_rd_remaining instead
Definition at line 129 of file mbuf.c.
References mbuf_rd_remaining().
{
  return mbuf_rd_remaining(mbuf);
}
int mbuf_repack (MBuffer * mbuf)
Repack an MBuffer so the next data to read is at the start of the allocated memory.
This adjust the read and write pointers accordingly, and resets the message pointer to the base of the allocated memory.
Parameters
mbuf MBuffer to manipulate
Returns
0 on success, -1 otherwise
See Also
mbuf_repack_message, mbuf_repack_message2
Definition at line 758 of file mbuf.c.
References MBuffer::base, MBuffer::fill, MBuffer::length, MBuffer::msgptr, MBuffer::rd_remaining, MBuffer::rdptr, MBuffer::wr_remaining, and MBuffer::wrptr.
Referenced by START_TEST().
{
  mbuf_check_invariant (mbuf);
  if (mbuf == NULL) return -1;
  memmove (mbuf->base, mbuf->rdptr, mbuf->rd_remaining);
  mbuf->fill = mbuf->rd_remaining;
  mbuf->wr_remaining = mbuf->length - mbuf->fill;
  mbuf->wrptr = mbuf->base + mbuf->fill;
  mbuf->msgptr = mbuf->rdptr = mbuf->base;
  mbuf_check_invariant (mbuf);
  return 0;
}
int mbuf_repack_message (MBuffer * mbuf)
Repack an MBuffer to start with the current message, keeping R/W pointers.
The read pointer is preserved so it points to the same location of the message after repacking, while the write pointer points right after the end of the data still to read in the buffer.
Parameters
mbuf MBuffer to manipulate
Returns
0 on success, -1 on failure
Definition at line 785 of file mbuf.c.
References MBuffer::base, MBuffer::fill, MBuffer::length, MBuffer::msgptr, MBuffer::rd_remaining, MBuffer::rdptr, MBuffer::wr_remaining, and MBuffer::wrptr.
Referenced by client_callback(), and START_TEST().
{
  mbuf_check_invariant (mbuf);
  if (mbuf == NULL) return -1;
  size_t msg_remaining = mbuf->wrptr - mbuf->msgptr;
  memmove (mbuf->base, mbuf->msgptr, msg_remaining);
  mbuf->fill = mbuf->wrptr - mbuf->msgptr;
  mbuf->wr_remaining = mbuf->length - mbuf->fill;
  mbuf->wrptr = mbuf->base + mbuf->fill;
  mbuf->msgptr = mbuf->base;
  mbuf->rdptr = mbuf->wrptr - mbuf->rd_remaining;
  mbuf_check_invariant (mbuf);
  return 0;
}
int mbuf_repack_message2 (MBuffer * mbuf)
Repack an MBuffer to start with the current message, resetting read pointer.
The read pointer is reset to point at the beginning of the message, while the write pointer points to the end of the data still to read in the buffer.
Parameters
mbuf MBuffer to manipulate
Returns
0 on success, -1 on failure
Definition at line 815 of file mbuf.c.
References MBuffer::base, MBuffer::fill, MBuffer::length, MBuffer::msgptr, MBuffer::rd_remaining, MBuffer::rdptr, MBuffer::wr_remaining, and MBuffer::wrptr.
{
  mbuf_check_invariant (mbuf);
  if (mbuf == NULL) return -1;
  size_t msg_size = mbuf->wrptr - mbuf->msgptr;
  if (msg_size > 0)
    memmove (mbuf->base, mbuf->msgptr, msg_size);
  mbuf->fill = msg_size;
  mbuf->wr_remaining = mbuf->length - msg_size;
  mbuf->rd_remaining = msg_size;
  mbuf->wrptr = mbuf->base + msg_size;
  mbuf->msgptr = mbuf->rdptr = mbuf->base;
  mbuf_check_invariant (mbuf);
  return 0;
}
int mbuf_reset_read (MBuffer * mbuf)
Reset the read pointer to the beginning of the message.
Adjust the rdptr to the current msgptr.
Parameters
mbuf MBuffer to manipulate
Returns
0 on success, -1 on failure
Definition at line 703 of file mbuf.c.
References MBuffer::msgptr, MBuffer::rd_remaining, MBuffer::rdptr, and MBuffer::wrptr.
Referenced by proxy_message_loop(), START_TEST(), and unmarshal_init().
{
  mbuf_check_invariant (mbuf);
  if (mbuf == NULL) return -1;
  // If in the middle of a write, can't do a read reset
  if (mbuf->msgptr > mbuf->rdptr)
    return -1;
  mbuf->rdptr = mbuf->msgptr;
  mbuf->rd_remaining = mbuf->wrptr - mbuf->rdptr;
  mbuf_check_invariant (mbuf);
  return 0;
}
int mbuf_reset_write (MBuffer * mbuf)
Reset the write pointer to the beginning of the message.
Adjust the wrptr to the current msgptr.
Parameters
mbuf MBuffer to manipulate
Returns
0 on success, -1 on failure
Definition at line 675 of file mbuf.c.
References MBuffer::fill, MBuffer::msgptr, MBuffer::rd_remaining, MBuffer::rdptr, MBuffer::wr_remaining, and MBuffer::wrptr.
Referenced by marshal_measurements(), marshal_value(), and START_TEST().
{
  mbuf_check_invariant (mbuf);
  if (mbuf == NULL) return -1;
  // If in the middle of a read, can't do a write reset
  if (mbuf->rdptr > mbuf->msgptr)
    return -1;
  size_t msglen = mbuf->wrptr - mbuf->msgptr;
  mbuf->fill -= msglen;
  mbuf->wr_remaining += msglen;
  mbuf->rd_remaining -= msglen;
  mbuf->wrptr = mbuf->msgptr;
  mbuf_check_invariant (mbuf);
  return 0;
}
int mbuf_resize (MBuffer * mbuf, size_t new_length)
Resize an MBuffer's allocated storage.
If new_length is smaller than that of the current storage, do nothing.
If new_length is larger than the current storage by less than the min_resize specified for the MBuffer, the allocated memory is grown by min_resize. (XXX: This behaviour is currently disabled).
Parameters
mbuf MBuffer to manipulate
new_length length to which the buffer should be grown
Returns
0 on success, or -1 on error
See Also
mbuf_create, mbuf_create2, DEF_MIN_BUF_RESIZE
Definition at line 303 of file mbuf.c.
References MBuffer::allow_resizing, MBuffer::base, MBuffer::fill, MBuffer::length, MBuffer::msgptr, oml_realloc(), MBuffer::rdptr, MBuffer::resized, MBuffer::wr_remaining, and MBuffer::wrptr.
Referenced by mbuf_check_resize(), and START_TEST().
{
  mbuf_check_invariant (mbuf);
  if (mbuf == NULL || mbuf->base == NULL)
    return -1;
  /* Don't resize if we don't have to */
  if (new_length <= mbuf->length)
    return 0;
  if (! mbuf->allow_resizing)
    return -1;
/*   // Make sure we grow at leat by a minimum delta */
/*   if ((new_length - mbuf->length) < mbuf->min_resize) { */
/*     new_length = mbuf->length + mbuf->min_resize; */
/*   } */
  int wr_offset = mbuf->wrptr - mbuf->base;
  int rd_offset = mbuf->rdptr - mbuf->base;
  int msg_offset = mbuf->msgptr - mbuf->base;
  assert (wr_offset == (int)mbuf->fill);
  uint8_t* new = oml_realloc (mbuf->base, new_length);
  if (new == NULL)
    return -1;
  mbuf->base = new;
  mbuf->wrptr = mbuf->base + wr_offset;
  mbuf->rdptr = mbuf->base + rd_offset;
  mbuf->msgptr = mbuf->base + msg_offset;
  mbuf->resized += (new_length - mbuf->length);
  mbuf->length = new_length;
  mbuf->wr_remaining = mbuf->length - mbuf->fill;
  mbuf_check_invariant (mbuf);
  return 0;
}
size_t mbuf_wr_remaining (MBuffer * mbuf)
Get the remaining amount of data to write in MBuffer
XXX: Shall we use wr_remaining directly?
Parameters
mbuf MBuffer to manipulate
Returns
the number of unread bytes in the buffer
Definition at line 155 of file mbuf.c.
References MBuffer::rdptr, and MBuffer::wrptr.
Referenced by _bw_push().
{
  return mbuf->wrptr - mbuf->rdptr;
}
int mbuf_write (MBuffer * mbuf, const uint8_t * buf, size_t len)
Write data into an MBuffer.
Write len bytes from the raw buffer pointed to by buf into the MBuffer. If the MBuffer doesn't have enough remaining space to fit len bytes, nothing is written and the function fails.
If the function succeeds, the data is written starting at the MBuffer's write pointer, and the write pointer is advanced by len bytes.
Parameters
mbuf MBuffer to write data into
buf data to write
len length of the buffer of data (not including \0 for strings)
Returns
0 on success, -1 on failure.
Definition at line 381 of file mbuf.c.
References MBuffer::fill, mbuf_check_resize(), MBuffer::rd_remaining, MBuffer::wr_remaining, and MBuffer::wrptr.
Referenced by _bw_push(), _bw_push_meta(), marshal_finalize(), marshal_measurements(), marshal_value(), proxy_message_loop(), and START_TEST().
{
  if (mbuf == NULL || buf == NULL) return -1;
  mbuf_check_invariant (mbuf);
  if (mbuf_check_resize (mbuf, len) == -1)
    return -1;
  memcpy (mbuf->wrptr, buf, len);
  mbuf->wrptr += len;
  mbuf->fill += len;
  mbuf->wr_remaining -= len;
  mbuf->rd_remaining += len;
  mbuf_check_invariant (mbuf);
  return 0;
}
size_t mbuf_write_offset (MBuffer * mbuf)
Get the write offset from the base of the MBuffer.
Parameters
mbuf MBuffer to manipulate
Returns
the stored data size as an size_t
Definition at line 203 of file mbuf.c.
References MBuffer::base, and MBuffer::wrptr.
Referenced by bw_get_write_buf().
{
  return mbuf->wrptr - mbuf->base;
}
uint8_t* mbuf_wrptr (MBuffer * mbuf)
Get the write pointer.
Parameters
mbuf MBuffer to manipulate
Returns
the write pointer wrptr
Definition at line 284 of file mbuf.c.
References MBuffer::wrptr.
{
  return mbuf->wrptr;
}