oml2: mem.c File Reference
mem.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <inttypes.h>
#include "ocomm/o_log.h"
#include "mem.h"
Macros
#define xreturn(ptr, size, str)
Functions
size_t xmembytes ()
size_t xmemnew ()
size_t xmemfreed ()
size_t xmaxbytes ()
char * oml_memsummary_r (char *summary, size_t summary_sz)
char * oml_memsummary ()
void oml_memreport (int loglevel)
void * oml_malloc (size_t size)
void * oml_calloc (size_t count, size_t size)
void * oml_realloc (void *ptr, size_t size)
size_t oml_malloc_usable_size (void *ptr)
void oml_free (void *ptr)
char * oml_stralloc (size_t len)
void * oml_memdupz (const void *data, size_t len)
char * oml_strndup (const char *str, size_t len)
Detailed Description
The "x*()" functions: accountable memory allocation functions.
To avoid confusion, these functions manipulate chunks of memory we call 'xchunks'. They are essentially normally malloc(3)'d memory, of length sizeof(size_t)+SIZE, and start with an offset of size_t from the malloc(3)'d block. The first size_t element is used to store the actual size of the xchunk (sizeof(size_t)+SIZE).
Definition in file mem.c.
Macro Definition Documentation
#define xreturn (ptr, size, str)
Value:
do {                                                                  \
    logerror(str);                                                      \
    logerror("%d bytes allocated, trying to add %d bytes\n",            \
             xbytes, size);                                             \
    return ptr;                                                         \
  } while (0);
Definition at line 139 of file mem.c.
Referenced by oml_calloc(), oml_malloc(), and oml_realloc().
Function Documentation
void* oml_calloc (size_t count, size_t size)
Allocate array, keeping track of allocated memory.
Parameters
number of elements in the array
size size of one element
Returns
an xchunk of memory at least as big as size, or NULL
See Also
calloc(3), oml_malloc
Definition at line 177 of file mem.c.
References xreturn.
Referenced by client_realloc_tables(), schema_copy(), and unmarshal_value().
{
  if (size >= sizeof (size_t))
    count++;
  else {
    int n = 0;
    size_t ssize = sizeof (size_t);
    while (ssize > size) {
      ssize >>= 1;
      n++;
    }
    count += (1 << n);
  }
  void *ret = calloc (count, size);
  if (!ret)
    xreturn (ret, count * size, "Out of memory, calloc failed\n");
  *(size_t*)ret = count * size;
  xcount_new (count * size);
  return (size_t*)ret + 1;
}
void oml_free (void * ptr)
Free an xchunk
Parameters
ptr pointer to an oml_malloc()'d bit of memory
See Also
oml_malloc, free(3)
Definition at line 240 of file mem.c.
Referenced by bw_close(), bw_create(), cbuf_add_page(), cbuf_create(), cbuf_destroy(), check_server_destroy_client_handler(), client_free(), client_handler_free(), client_send_header(), create_mstream(), create_writer(), database_create_table(), database_find(), database_find_or_create_table(), database_release(), database_table_free(), dba_table_create_from_schema(), destroy_filter(), destroy_ms(), destroy_sem_concepts(), handleValue(), header_free(), header_from_string(), main(), mbuf_create2(), mbuf_destroy(), msg_queue_destroy(), msg_queue_remove(), mstring_create(), mstring_delete(), omlc_add_mp(), omlc_close(), parse_uri(), psql_prepare(), schema_copy(), schema_field_from_meta(), schema_free(), schema_from_sql(), socket_free(), socket_group_remove(), socket_in_new(), table_descr_array_free(), table_descr_list_free(), table_descr_new(), and unregister_filters().
{
  if (ptr) {
    size_t *sptr = (size_t*)ptr - 1, size = *sptr;
    free (sptr);
    xcount_freed (size);
  }
}
void* oml_malloc (size_t size)
Allocate memory, keeping track of how much.
The allocated memory is one size_t larger, just before the returned pointer, to store the size of the xchunk.
Parameters
size desired size to allocate
Returns
an xchunk of memory at least as big as size, or NULL
See Also
oml_free, malloc(3)
Definition at line 157 of file mem.c.
References xreturn.
Referenced by bin_writer_new(), bw_create(), cbuf_add_page(), cbuf_create(), check_server_prepare_client_handler(), client_handler_new(), client_new(), client_send_header(), create_filter(), create_mstream(), database_create_table(), database_find(), eventloop_every(), file_stream_new(), fuseki_create_database(), header_from_string(), main(), mbuf_create2(), mksyn(), msg_queue_add(), msg_queue_create(), mstring_create(), net_stream_new(), oml_memdupz(), oml_realloc(), oml_sem_register_concepts(), oml_stralloc(), omlc_add_mp(), omlc_init(), omlf_average_new(), omlf_delta_new(), omlf_first_new(), omlf_histogram_new(), omlf_last_new(), omlf_register_filter(), omlf_stddev_new(), omlf_sum_new(), psql_create_database(), schema_copy(), schema_from_meta(), schema_from_sql(), schema_new(), socket_group_add(), socket_group_new(), sq3_create_database(), START_TEST(), store_received_message(), table_descr_new(), text_writer_new(), to_octets(), and virtuoso_create_database().
{
  size += sizeof (size_t);
  void *ret = malloc (size);
  if (!ret)
    xreturn (ret, size, "Out of memory, malloc failed\n");
  memset (ret, 0, size);
  *(size_t*)ret = size;
  xcount_new (size);
  return (size_t*)ret + 1;
}
size_t oml_malloc_usable_size (void * ptr)
Report the size of the given xchunk
Parameters
ptr pointer to an oml_malloc()'d bit of memory
Returns
the size of the allocated xchunk
See Also
oml_malloc, malloc_usable_size(3)
Definition at line 228 of file mem.c.
Referenced by START_TEST().
{
  if(!ptr) return 0;
  size_t *sptr = (size_t*)ptr - 1;
  return *sptr-sizeof(size_t);
}
void* oml_memdupz (const void * data, size_t len)
Allocates (len + 1) bytes of memory, copies "len" bytes from "data" into the new memory and zero terminates the copy
Parameters
data data to copy in the new xchunk
len length of the data
Returns
the newly allocated xchunk, or NULL
Definition at line 272 of file mem.c.
References oml_malloc().
Referenced by oml_strndup().
{
  char *ret = oml_malloc (len + 1);
  memcpy (ret, data, len);
  ret[len] = '\0';
  return ret;
}
void oml_memreport (int loglevel)
Log a summary of the dynamically allocated memory tracked by x*() functions
Parameters
loglevel log level at which the message should be issued
See Also
oml_memsummary
Definition at line 133 of file mem.c.
References o_log, and oml_memsummary_r().
Referenced by main(), and omlc_close().
{
  char summary[1024];
  o_log(loglevel, "%s\n", oml_memsummary_r(summary, sizeof(summary)));
}
char* oml_memsummary ()
Create a summary of the dynamically allocated memory tracked by x*() functions
Returns
a pointer to a statically allocated, nul-terminated, string containing the summary
See Also
oml_memreport
Definition at line 121 of file mem.c.
References oml_memsummary_r().
Referenced by eventloop_report().
{
  static char summary[1024];
  return oml_memsummary_r(summary, sizeof(summary));;
}
char* oml_memsummary_r (char * summary, size_t summary_sz)
Create a summary of the dynamically allocated memory tracked by x*() functions. This version of the function is re-entrant and requires the user to provide the buffer into which the report is written.
Parameters
summary A pointer to a buffer into which to write the report
summary_sz The size of the buffer
Returns
a pointer to the nul-terminated string containing the summary
See Also
oml_memsummary
Definition at line 89 of file mem.c.
Referenced by oml_memreport(), and oml_memsummary().
{
  size_t xbytes_h = xbytes;
  char *units = "bytes";
  if (xbytes_h > 10*(1<<10)) {
    units = "KiB";
    xbytes_h >>= 10;
  }
  if (xbytes_h > 10*(1<<10)) {
    units = "MiB";
    xbytes_h >>= 10;
  }
  snprintf(summary, summary_sz, "%"PRIuMAX" %s currently allocated [%"
             PRIuMAX" allocated overall, %"
             PRIuMAX" freed, %"
             PRIuMAX" current, %"
             PRIuMAX" maximum]",
             (uintmax_t)xbytes_h, units,
             (uintmax_t)xnew, (uintmax_t)oml_freed, (uintmax_t)xbytes,
             (uintmax_t)xmax);
  summary[summary_sz - 1] = '\0';
  return summary;
}
void* oml_realloc (void * ptr, size_t size)
Resize an allocated xchunk, keeping track of the changes.
Parameters
xchunk to resize
size minimum size to resize the xchunk to
Returns
a new xchunk of at least the requested size containing the old data, or NULL
See Also
realloc(3)
Definition at line 206 of file mem.c.
References oml_malloc(), and xreturn.
Referenced by client_realloc_tables(), client_realloc_values(), database_find_or_create_table(), mbuf_resize(), oml_ms_add_writer(), schema_add_field(), schema_from_meta(), schema_from_sql(), and socket_in_new().
{
  if (!ptr) return oml_malloc (size);
  size += sizeof (size_t);
  ptr = (size_t*)ptr - 1;
  size_t old = *(size_t*)ptr;
  void *ret = realloc (ptr, size);
  if (!ret)
    xreturn (ret, size - old, "Out of memory, realloc failed\n");
  *(size_t*)ret = size;
  xcount_new (size);
  xcount_freed (old);
  return (size_t*)ret + 1;
}
char* oml_stralloc (size_t len)
Allocates (len + 1) bytes of memory and initialise it to zero (hence, very suitable for a string of length up to len).
Parameters
len maximum size of the string to be stored in the allocated xchunk
Returns
the allocated xchunk, or NULL
See Also
oml_malloc, memset(3)
Definition at line 256 of file mem.c.
References oml_malloc().
{
  char *ret = oml_malloc (len + 1);
  memset (ret, 0, len + 1);
  return ret;
}
char* oml_strndup (const char * str, size_t len)
Duplicate string, up to len characters, and nul-terminate it.
Parameters
str string to copy in the new xchunk
len length of the string
Returns
the newly allocated xchunk, or NULL
See Also
strndup(3)
Definition at line 288 of file mem.c.
References oml_memdupz().
Referenced by client_new(), create_writer(), database_find_or_create_table(), file_stream_new(), header_from_string(), mksyn(), net_stream_new(), parse_uri(), schema_add_field(), schema_copy(), schema_field_from_meta(), schema_from_meta(), schema_from_sql(), schema_new(), schema_to_meta(), socket_tcp_out_new(), sq3_dbdir_setup(), and table_descr_new().
{
  char *p = memchr (str, '\0', len);
  return oml_memdupz (str, p ? (size_t)(p - str) : len);
}
size_t xmaxbytes ()
Report the high water mark of memory allocated by oml_mem* functions
Definition at line 77 of file mem.c.
Referenced by omlc_inject().
{ return xmax; }
size_t xmembytes ()
Report the current memory allocation tracked by oml_mem*() functions
Definition at line 71 of file mem.c.
Referenced by omlc_inject(), and START_TEST().
{ return xbytes; }
size_t xmemfreed ()
Report the cumulated freed memory tracked by oml_mem*() functions
Definition at line 75 of file mem.c.
Referenced by omlc_inject().
{ return oml_freed; }
size_t xmemnew ()
Report the cumulated allocated memory tracked by oml_mem*() functions
Definition at line 73 of file mem.c.
Referenced by omlc_inject().
{ return xnew; }