oml2: message_queue.c File Reference
message_queue.c File Reference
Implement a FIFO message queue containing CBuffer objects.
#include <assert.h>
#include "mem.h"
#include "cbuf.h"
#include "message.h"
#include "message_queue.h"
Functions
struct msg_queue * msg_queue_create (void)
void msg_queue_destroy (struct msg_queue *queue)
struct msg_queue_node * msg_queue_add (struct msg_queue *queue)
struct msg_queue_node * msg_queue_head (struct msg_queue *queue)
void msg_queue_remove (struct msg_queue *queue)
Detailed Description
Implement a FIFO message queue containing CBuffer objects.
Definition in file message_queue.c.
Function Documentation
struct msg_queue_node* msg_queue_add (struct msg_queue * queue) read
Create a new node at the end of the queue and return a pointer to it. This operation is O(1).
Definition at line 44 of file message_queue.c.
References msg_queue::length, msg_queue_node::next, oml_malloc(), and msg_queue::tail.
Referenced by store_received_message().
{
  if (queue == NULL)
    return NULL;
  struct msg_queue_node *node = oml_malloc (sizeof (struct msg_queue_node));
  if (node == NULL)
    return NULL;
  node->next = NULL;
  if (queue->tail == NULL) {
    queue->tail = node;
    queue->tail->next = node;
  } else {
    node->next = queue->tail->next;
    queue->tail->next = node;
    queue->tail = node;
  }
  queue->length++;
  return node;
}
struct msg_queue* msg_queue_create (void) read
Definition at line 21 of file message_queue.c.
References oml_malloc(), and msg_queue::tail.
Referenced by client_new().
{
  struct msg_queue *q = oml_malloc (sizeof (struct msg_queue));
  if (q == NULL)
    return NULL;
  q->tail = NULL;
  return q;
}
void msg_queue_destroy (struct msg_queue * queue)
Definition at line 33 of file message_queue.c.
References msg_queue::length, msg_queue_remove(), and oml_free().
Referenced by client_free().
{
  while (queue->length > 0)
    msg_queue_remove (queue);
  oml_free (queue);
}
struct msg_queue_node* msg_queue_head (struct msg_queue * queue) read
Return a pointer to the head of the queue (next node to be processed).
This operation is O(1).
Definition at line 72 of file message_queue.c.
References msg_queue_node::next, and msg_queue::tail.
Referenced by client_send_thread(), and main().
{
  if (queue == NULL || queue->tail == NULL)
    return NULL;
  return queue->tail->next;
}
void msg_queue_remove (struct msg_queue * queue)
Remove the node at the head of the queue. This operation is O(1).
Definition at line 82 of file message_queue.c.
References msg_queue::length, msg_queue_node::next, oml_free(), and msg_queue::tail.
Referenced by client_send_thread(), main(), and msg_queue_destroy().
{
  if (queue == NULL || queue->tail == NULL)
    return;
  struct msg_queue_node *head = queue->tail->next;
  assert (head != NULL);
  /* Unlink the head */
  queue->length--;
  if (queue->length == 0)
    queue->tail = NULL;
  else
    queue->tail->next = head->next;
  oml_free (head);
}