oml2: misc.c File Reference
misc.c File Reference
Implements various common utility functions (XXX: Only mutex lock/unlock).
#include <stdlib.h>
#include <unistd.h>
#include <pthread.h>
#include <errno.h>
#include <string.h>
#include "oml2/omlc.h"
#include "ocomm/o_log.h"
#include "client.h"
Functions
int mp_lock (OmlMP *mp)
void mp_unlock (OmlMP *mp)
int oml_lock (pthread_mutex_t *mutexP, const char *mutexName)
void oml_unlock (pthread_mutex_t *mutexP, const char *mutexName)
void oml_lock_persistent (pthread_mutex_t *mutexP, const char *mutexName)
Detailed Description
Implements various common utility functions (XXX: Only mutex lock/unlock).
Definition in file misc.c.
Function Documentation
int mp_lock (OmlMP * mp)
Lock a measurement point mutex
Parameters
mp OmlMP to lock
Returns
0 if successful, -1 otherwise
See Also
mp_unlock, oml_lock
Definition at line 30 of file misc.c.
References OmlMP::mutexP, OmlMP::name, and oml_lock().
Referenced by destroy_mp(), and omlc_inject().
{
  return oml_lock(mp->mutexP, mp->name);
}
void mp_unlock (OmlMP * mp)
Unlock a measurement point mutex
Parameters
mp OmlMP to unlock
See Also
mp_lock, oml_unlock
Definition at line 40 of file misc.c.
References OmlMP::mutexP, OmlMP::name, and oml_unlock().
Referenced by destroy_mp(), and omlc_inject().
{
  oml_unlock(mp->mutexP, mp->name);
}
int oml_lock (pthread_mutex_t * mutexP, const char * mutexName)
Lock a mutex
Parameters
mutexP pointer to mutex lock
mutexName name of mutex; used for error reporting only
Returns
0 if successful, -1 otherwise
See Also
oml_unlock
Definition at line 52 of file misc.c.
References logwarn().
Referenced by bw_close(), bw_get_write_buf(), bw_push(), bw_push_meta(), mp_lock(), and oml_lock_persistent().
{
  if (mutexP) {
    if (pthread_mutex_lock(mutexP)) {
      logwarn("%s: Couldn't get mutex lock (%s)\n",
          mutexName, strerror(errno));
      return -1;
    }
  }
  return 0;
}
void oml_lock_persistent (pthread_mutex_t * mutexP, const char * mutexName)
Try to obtain a lock on the BufferedWriter until it succeeds
Parameters
mutexP pointer to mutex to unlock
mutexName name of mutex; used for error reporting only
See Also
oml_lock, oml_unlock
Definition at line 86 of file misc.c.
References logwarn(), and oml_lock().
{
  while (oml_lock(mutexP, mutexName)) {
    logwarn("Cannot get lock in %s; will try again soon.\n", mutexName);
    sleep(1);
  }
}
void oml_unlock (pthread_mutex_t * mutexP, const char * mutexName)
Unock a mutex
Parameters
mutexP pointer to mutex to unlock
mutexName name of mutex; used for error reporting only
See Also
oml_lock
Definition at line 70 of file misc.c.
References logwarn().
Referenced by bw_close(), bw_get_write_buf(), bw_push(), bw_push_meta(), bw_unlock_buf(), and mp_unlock().
{
  if (mutexP) {
    if (pthread_mutex_unlock(mutexP)) {
      logwarn("%s: Couldn't unlock mutex (%s)\n",
          mutexName, strerror(errno));
    }
  }
}