oml2: monitoring_server.c File Reference
monitoring_server.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include "oml2/omlc.h"
#include "oml2-server_oml.h"
Macros
#define OML_FROM_MAIN
Functions
void oml_setup (int *argc, const char **argv)
void oml_cleanup (void)
void client_event_inject (const char *address, uint32_t port, const char *oml_id, const char *domain, const char *appname, const char *event, const char *message)
Macro Definition Documentation
#define OML_FROM_MAIN
Definition at line 25 of file monitoring_server.c.
Function Documentation
void client_event_inject (const char * address, uint32_t port, const char * oml_id, const char * domain, const char * appname, const char * event, const char * message)
Inject a client report into the monitoring OML server.
Parameters
address pointer to the client IP address string
port client port number
oml_id pointer to a string containing the client OML ID.
domain pointer to a string containing the client domain.
appname pointer to a string containing the client appname.
event (possibly NULL) pointer to an event string
message (possibly NULL) pointer to a message string
Definition at line 78 of file monitoring_server.c.
References oml_mps_t::clients, and g_oml_mps_oml2_server.
{
  if(oml_enabled) {
    oml_inject_clients(g_oml_mps_oml2_server->clients, address, port, oml_id, domain, appname, event, message);
  }
}
void oml_cleanup (void)
Clean up connection to the monitoring OML server.
Definition at line 59 of file monitoring_server.c.
References omlc_close().
Referenced by main().
{
  if(oml_enabled) {
    omlc_close();
    oml_enabled = 0;
  }
}
void oml_setup (int * argc, const char ** argv)
Set up connection to a monitoring OML server.
Parameters
argc non-NULL pointer to the argument count
argv argument vector
Definition at line 36 of file monitoring_server.c.
References logdebug(), logwarn(), omlc_init(), and omlc_start().
Referenced by main().
{
  int result;
  /* connect to the monitoring server */
  result = omlc_init("server", argc, argv, NULL);
  if(0 == result) {
    logdebug("Initialised OML client library\n");
    oml_register_mps();
    if(omlc_start() == 0) {
      logdebug("Started OML reporting of server's internal metrics\n");
      oml_enabled = 1;
    } else {
      logwarn("Could not start OML client library; this does not impact the server's collection capabilities\n");
    }
  } else if (result == 1) {
    logdebug ("OML was disabled by the user\n");
  } else {
    logwarn("Could not initialise OML client library; this does not impact the server's collection capabilities\n");
  }
}