oml2: msgloop.c File Reference
msgloop.c File Reference
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include "ocomm/o_log.h"
#include "proxy_client.h"
Macros
#define HEADER_LENGTH (sizeof (header_prototype) - 1)
Enumerations
enum TestType { TT_SERVER, TT_PROXY }
Functions
void proxy_message_loop (const char *client_id, Client *client, void *buf, size_t size)
int hex_to_int (char a)
int read_ascii_hex_int (char *buf, int nybbles)
int read_message (char **line, size_t *size, size_t *length_out, int *seqno_out)
int main (int argc, char **argv)
Variables
const char header_prototype [] = "OML0123ABCD0123ABCD"
Macro Definition Documentation
#define HEADER_LENGTH (sizeof (header_prototype) - 1)
Definition at line 44 of file msgloop.c.
Referenced by read_message().
Enumeration Type Documentation
enum TestType
Enumerator:
TT_SERVER
TT_PROXY
Definition at line 37 of file msgloop.c.
              {
  TT_SERVER,
  TT_PROXY
};
Function Documentation
int hex_to_int (char a)
Definition at line 47 of file msgloop.c.
Referenced by read_ascii_hex_int().
{
  int digit = a - '0';
  int letter = toupper (a) - 'A' + 0xA;
  if (letter >= 0xA)
    return letter;
  else if (digit >= 0)
    return digit;
  else
    fprintf (stderr, "'%c' (%d) is not a hex digit\n", a, a);
  return 0;
}
int main (int argc, char ** argv)
Definition at line 144 of file msgloop.c.
References cbuf_consume_cursor(), cbuf_cursor_page_remaining(), cbuf_cursor_pointer(), client_new(), msg_queue_node::cursor, _client::headers, oml_message::length, msg_queue::length, _client::messages, msg_queue_node::msg, msg_queue_head(), msg_queue_remove(), header::next, O_LOG_DEBUG, o_set_log_file(), o_set_log_level(), proxy_message_loop(), read_message(), seqno, header::tag, tag_to_string(), TT_PROXY, TT_SERVER, and header::value.
{
  int test = TT_PROXY;
  size_t length = 1024;
  char *line = NULL;
  int result = 0;
  int n = 0;
  Client *client = NULL;
  setlinebuf (stdout);
  o_set_log_file ("log.txt");
  o_set_log_level (O_LOG_DEBUG);
  if (argc > 1) {
    if (strcmp (argv[0], "--proxy") == 0) {
      test = TT_PROXY;
    } else if (strcmp (argv[0], "--server") == 0) {
      test = TT_SERVER;
    }
  }
  line = malloc (length);
  if (line == NULL) {
    fprintf (stderr, "malloc():  %s\n", strerror (errno));
    exit (1);
  }
  client = client_new (NULL, 4096, "dummy.bin", 0, "dummy.com");
  fprintf (stderr, "# msgloop: receiving test data...");
  do {
    int seqno = 0;
    size_t msg_length = 0;
    result = read_message (&line, &length, &msg_length, &seqno);
    n++;
    if (result == -1) {
      fprintf (stderr, "read_message() failed\n");
      exit (1);
    } else if (result == 0) {
      break;
    }
    switch (test) {
    case TT_PROXY:
      proxy_message_loop ("client", client, line, msg_length);
      break;
    case TT_SERVER:
    default:
      break;
    }
    fprintf (stderr, " %d", n);
  } while (result == 1);
  fprintf (stderr, "# msgloop: sending interpreted headers...\n");
  struct header *header = client->headers;
  while (header) {
    printf ("H>%s>%s\n", tag_to_string (header->tag),
            header->value);
    header = header->next;
  }
  fprintf (stderr, "# msgloop: sending %d interpreted messages...\n", (int)client->messages->length);
  while (client->messages->length > 0) {
    struct msg_queue_node *head = msg_queue_head (client->messages);
    struct cbuffer_cursor *cursor = &head->cursor;
    size_t length = head->msg->length;
    printf ("T>");
    while (length > 0) {
      char *buf = cbuf_cursor_pointer (cursor);
      size_t page_remaining = cbuf_cursor_page_remaining (cursor);
      size_t to_write = length < page_remaining ? length : page_remaining;
      fwrite (buf, 1, to_write, stdout);
      cbuf_consume_cursor (cursor, to_write);
      length -= to_write;
    }
    msg_queue_remove (client->messages);
  }
  fflush (stdout);
  fclose (stdout);
  return 0;
}
void proxy_message_loop (const char * client_id, Client * client, void * buf, size_t size)
Definition at line 145 of file receiver.c.
References bin_read_msg_start(), C_CONFIGURE, C_DATA, C_HEADER, C_PROTOCOL_ERROR, _client::content, CONTENT_BINARY, content_from_string(), CONTENT_NONE, CONTENT_TEXT, _client::domain, H_CONTENT, H_DOMAIN, H_NONE, header, _client::header_table, _client::headers, oml_message::length, logdebug(), logerror(), loop, _client::mbuf, mbuf_clear(), mbuf_consume_message(), mbuf_rdptr(), mbuf_read_skip(), mbuf_reset_read(), mbuf_write(), _client::msg_start, header::next, read_header(), oml_message::seqno, _client::state, store_received_message(), oml_message::stream, header::tag, tag_to_string(), text_read_msg_start(), oml_message::timestamp, and header::value.
{
  MBuffer *mbuf = client->mbuf;
  struct header *header;
  struct oml_message msg;
  int result;
  size_t message_length;
  result = mbuf_write (mbuf, buf, size);
  if (result == -1) {
    logerror ("'%s': Failed to write message from client into message buffer. Data is being lost!\n",
              client_id);
    return;
  }
 loop:
  switch (client->state) {
  case C_HEADER:
    /* Read headers until out of header data to read*/
    while (read_header (client, mbuf) == 1);
    if (client->state != C_HEADER)
      goto loop;
    break;
  case C_CONFIGURE:
    if (client->header_table[H_DOMAIN] == NULL ||
        client->header_table[H_CONTENT] == NULL ||
        client->header_table[H_DOMAIN]->tag == H_NONE ||
        client->header_table[H_CONTENT]->tag == H_NONE) {
      if (client->headers == NULL) {
        logdebug ("Headers NULL!");
      }
      client->state = C_PROTOCOL_ERROR;
    } else {
      client->domain = client->header_table[H_DOMAIN]->value;
      client->content = content_from_string (client->header_table[H_CONTENT]->value);
      if (client->content == CONTENT_NONE)
        client->state = C_PROTOCOL_ERROR;
    }
    if (client->state != C_PROTOCOL_ERROR) {
      logdebug ("%s\n", client->domain);
      logdebug ("%d\n", client->content);
    } else {
      logdebug ("Can't write out domain and content because of protocol error in input\n");
      logdebug ("Input is: '%s'\n", buf);
    }
    for (header = client->headers; header != NULL; header = header->next) {
      logdebug ("HEADER:  '%s' : '%s'\n",
                tag_to_string(header->tag),
                header->value);
    }
    switch (client->content){
    case CONTENT_TEXT:
      client->msg_start = text_read_msg_start;
      break;
    case CONTENT_BINARY:
      client->msg_start = bin_read_msg_start;
      break;
    default:
      /* Default is set when client is created (client_new()) */
      logerror ("Client content is not TEXT or BINARY\n");
      break;
    }
    mbuf_consume_message (mbuf); // Next message starts after the headers.
    client->state = C_DATA;
    break;
  case C_DATA:
    result = client->msg_start (&msg, mbuf);
    if (result == -1) {
      logerror ("'%s': protocol error in received message\n", client_id);
      client->state = C_PROTOCOL_ERROR;
      goto loop;
    } else if (result == 0) {
      // Try again when we get more data.
      logdebug ("'%s': need more data\n", client_id);
      mbuf_reset_read (mbuf);
      return;
    } else {
      logdebug ("'%s': received message of length %d\n", client_id, result);
      message_length = result;
    }
    logdebug ("Received [strm=%d seqno=%d ts=%f %d bytes]\n",
              msg.stream, msg.seqno, msg.timestamp, msg.length);
    mbuf_reset_read (mbuf);
    store_received_message (client, &msg, (char*)mbuf_rdptr (mbuf), message_length);
    mbuf_read_skip (mbuf, message_length);
    mbuf_consume_message (mbuf);
    break;
  case C_PROTOCOL_ERROR:
    logdebug ("'%s': protocol error!\n");
    break;
  default:
    logerror ("'%s': unknown client state '%d'\n", client_id, client->state);
    mbuf_clear (mbuf);
    return;
  }
}
int read_ascii_hex_int (char * buf, int nybbles)
Definition at line 63 of file msgloop.c.
References hex_to_int().
Referenced by read_message().
{
  int i = 0;
  uint32_t value = 0;
  for (i = 0; i < nybbles; i++) {
    value <<= 4;
    value |= hex_to_int (buf[i]);
  }
  return value;
}
int read_message (char ** line, size_t * size, size_t * length_out, int * seqno_out)
Definition at line 76 of file msgloop.c.
References count, HEADER_LENGTH, read_ascii_hex_int(), and seqno.
Referenced by main().
{
  int length = 0;
  int seqno = 0; // Message sequence number
  int count = 0;
  int result = 0;
  char header[HEADER_LENGTH+1] = {0};
  bzero (*line, *size);
  do {
    result = read (0, header + count, HEADER_LENGTH - count);
    if (result == -1) {
      fprintf (stderr, "reading header:  %s\n", strerror (errno));
      return -1;
    } else if (result == 0) {
      fprintf (stderr, "\n# msgloop: no more data, assuming closed pipe\n");
      return 0;
    }
    count += result;
  } while (count < HEADER_LENGTH);
  count = 0;
  if (result < HEADER_LENGTH) {
    fprintf (stderr, "Couldn't read the whole header length at once!\n");
    fprintf (stderr, "%d: %s\n", result, header);
    return -1;
  }
  if (strncmp ("OML", header, 3) != 0) {
    fprintf (stderr, "Packet format error (not OML)\n");
    return -1;
  }
  seqno = read_ascii_hex_int  (&header[3], 8);
  length = read_ascii_hex_int (&header[11], 8);
  if (*size < length) {
    char *new = realloc (*line, length);
    if (new == NULL) {
      fprintf (stderr, "realloc() error! %s\n", strerror (errno));
      return -1;
    }
    *line = new;
    *size = length;
  }
  char *p = *line;
  do {
    result = read (0, p + count, length - count);
    if (result == -1) {
      fprintf (stderr, "Error reading message payload: %s\n", strerror (errno));
      return -1;
    } else if (result == 0) {
      fprintf (stderr, "Read no bytes! Pipe closed?\n");
      return 0;
    }
    count += result;
  } while (count < length);
  *length_out = length;
  *seqno_out = seqno;
  return 1;
}
Variable Documentation
const char header_prototype[] = "OML0123ABCD0123ABCD"
Definition at line 43 of file msgloop.c.