oml2: mstring.c File Reference
mstring.c File Reference
A simple managed string abstraction which is dynamically allocated and can be transparently resized on demand which provides access to the underlying C string as required.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <assert.h>
#include "mem.h"
#include "mstring.h"
Macros
#define DEFAULT_MSTRING_SIZE 64
Functions
MString * mstring_create (void)
int mstring_set (MString *mstr, const char *str)
int mstring_cat (MString *mstr, const char *str)
int mstring_sprintf (MString *mstr, const char *fmt,...)
size_t mstring_len (MString *mstr)
char * mstring_buf (MString *mstr)
void mstring_delete (MString *mstr)
Detailed Description
A simple managed string abstraction which is dynamically allocated and can be transparently resized on demand which provides access to the underlying C string as required.
MStrings encapsulate a variable amount of allocated space, and manage it transparently, increasing it when needed. They are allocated with mstring_create and freed with mstring_delete. Classical manipulation such as, setting, concatenating or appending a formatted string. There also are low-level access function to get the nil-terminated C-string and its length.
See Also
mstring_set, mstring_cat, mstring_sprintf, mstring_buf, mstring_len
Definition in file mstring.c.
Macro Definition Documentation
#define DEFAULT_MSTRING_SIZE 64
Increments by which an MString's storage is increased.
Definition at line 31 of file mstring.c.
Function Documentation
char* mstring_buf (MString * mstr)
Get the C string contained in an MString
Parameters
mstr MString to manipulate
Returns
the C string contained in the MString, or NULL on error
Definition at line 222 of file mstring.c.
References MString::buf.
Referenced by create_mstream(), dba_table_create_from_schema(), fuseki_create_database(), net_stream_new(), omlc_add_mp(), omlc_inject_metadata(), on_connect(), psql_backend_setup(), psql_create_database(), psql_prepare(), schema_to_meta(), sq3_create_database(), START_TEST(), and virtuoso_create_database().
{
  if (mstr) {
    return mstr->buf;
  } else {
    return NULL;
  }
}
int mstring_cat (MString * mstr, const char * str)
Concatenate a C string to the end of an mstring
Parameters
mstr MString to manipulate
str C string to concatenate into the MString
Returns
0 on success, -1 otherwise
See Also
mstring_ensure_space
strncat(3)
Definition at line 130 of file mstring.c.
References MString::buf, MString::length, and MString::size.
Referenced by create_mstream(), mp_fields_summary(), psql_prepare(), schema_to_sql(), and START_TEST().
{
  size_t len;
  if (mstr == NULL || str == NULL) {
    return -1;
  }
  len = strlen (str);
  if(mstring_ensure_space(mstr, mstr->length + len) < 0) {
    return -1;
  }
  strncat (mstr->buf, str, len);
  mstr->length += len;
  assert (mstr->length < mstr->size);
  return 0;
}
MString* mstring_create (void)
Create a new MString
Returns
a pointer to the newly allocated MString, or NULL on error
See Also
mstring_delete, mstring_ensure_space, oml_malloc, oml_free
Definition at line 73 of file mstring.c.
References oml_free(), and oml_malloc().
Referenced by create_mstream(), dba_table_create_from_schema(), fuseki_create_database(), mp_fields_summary(), net_stream_new(), omlc_add_mp(), omlc_inject_metadata(), on_connect(), psql_backend_setup(), psql_create_database(), psql_prepare(), schema_to_meta(), schema_to_sql(), sq3_create_database(), START_TEST(), and virtuoso_create_database().
{
  MString* mstr = oml_malloc (sizeof (MString));
  memset(mstr, 0, sizeof(MString));
  if (mstr) {
    if (mstring_ensure_space(mstr, 0) < 0) {
      oml_free (mstr);
      mstr = NULL;
    }
  }
  return mstr;
}
void mstring_delete (MString * mstr)
Delete an MString and free its storage
Parameters
mstr MString to deallocate
See Also
oml_free
Definition at line 237 of file mstring.c.
References MString::buf, and oml_free().
Referenced by create_mstream(), dba_table_create_from_schema(), net_stream_new(), omlc_add_mp(), omlc_inject_metadata(), on_connect(), psql_backend_setup(), psql_create_database(), psql_prepare(), schema_to_meta(), schema_to_sql(), sq3_create_database(), START_TEST(), and virtuoso_create_database().
{
  if (mstr) {
    oml_free (mstr->buf);
    oml_free (mstr);
  }
}
size_t mstring_len (MString * mstr)
Get the current length of an MString.
Parameters
mstr MString to manipulate
Returns
the length of the contained C string, or 0 on error
Definition at line 207 of file mstring.c.
References MString::buf, and MString::length.
Referenced by net_stream_new(), schema_to_meta(), and START_TEST().
{
  if (mstr) {
    assert (mstr->buf && mstr->length == strlen (mstr->buf));
    return mstr->length;
  }
  return 0;
}
int mstring_set (MString * mstr, const char * str)
Set the content of the MString to a given C string.
The C-string is duplicated into the MString's internal storage.
Parameters
mstr MString to set
str C string to copy into the MString
Returns
0 on success, -1 otherwise
See Also
mstring_ensure_space
strncpy(3)
Definition at line 100 of file mstring.c.
References MString::buf, MString::length, and MString::size.
Referenced by create_mstream(), mp_fields_summary(), omlc_inject_metadata(), psql_create_database(), schema_to_sql(), and START_TEST().
{
  size_t len;
  if (mstr == NULL || str == NULL) {
    return -1;
  }
  len = strlen (str);
  if(mstring_ensure_space(mstr, len) < 0) {
    return -1;
  }
  strncpy (mstr->buf, str, len + 1);
  mstr->length = len;
  assert (mstr->length < mstr->size);
  return 0;
}
int mstring_sprintf (MString * mstr, const char * fmt, ...)
Add formatted string to the end of an MString.
The contents of the MString is not overwritten, rather, the newly-formatted string is added to the end.
Parameters
mstr MString to manipulate
fmt,... sprintf(3)-style format string and arguments
Returns
0 on success, -1 otherwise
Definition at line 160 of file mstring.c.
References MString::buf, MString::length, and MString::size.
Referenced by dba_table_create_from_schema(), fuseki_create_database(), handleValue(), net_stream_new(), omlc_add_mp(), omlc_inject_metadata(), on_connect(), psql_backend_setup(), psql_create_database(), psql_prepare(), schema_to_meta(), schema_to_sql(), sq3_create_database(), START_TEST(), and virtuoso_create_database().
{
  char *buf;
  size_t space;
  size_t n;
  va_list va;
  if(NULL == mstr || NULL == fmt) {
    return -1;
  }
  buf = mstr->buf + mstr->length;
  space = mstr->size - mstr->length;
  va_start (va, fmt);
  n = vsnprintf (buf, space, fmt, va);
  if (n >= space) {
    va_end (va);
    if(mstring_ensure_space(mstr, mstr->length + n) < 0) {
      return -1;
    }
    /* mstring_ensure_space's call to oml_realloc might have moved things ... */
    buf = mstr->buf + mstr->length;
    /* ... and we have more space */
    space = mstr->size - mstr->length;
    va_start (va, fmt);
    n = vsnprintf (buf, space, fmt, va);
    if (n >= space) {
      return -1;
    }
  }
  va_end (va);
  mstr->length += n;
  assert (mstr->length < mstr->size);
  return 0;
}