oml2: net_stream.c File Reference
net_stream.c File Reference
An OmlOutStream implementation that writer that sends measurement tuples over the network.
#include <assert.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/socket.h>
#include <signal.h>
#include "oml2/omlc.h"
#include "oml2/oml_out_stream.h"
#include "ocomm/o_log.h"
#include "ocomm/o_socket.h"
#include "mem.h"
#include "oml_util.h"
#include "client.h"
Data Structures
struct OmlNetOutStream
Typedefs
typedef struct OmlNetOutStream OmlNetOutStream
Functions
OmlOutStream * net_stream_new (const char *transport, const char *hostname, const char *service)
Detailed Description
An OmlOutStream implementation that writer that sends measurement tuples over the network.
Definition in file net_stream.c.
Typedef Documentation
typedef struct OmlNetOutStream OmlNetOutStream
OmlOutStream writing out to an OComm Socket
Function Documentation
OmlOutStream* net_stream_new (const char * transport, const char * hostname, const char * service)
Create a new out stream for sending over the network
Parameters
transport string representing the protocol used to establish the connection (oml_strndup()'d locally)
hostname string representing the host to connect to (oml_strndup()'d locally)
service symbolic name or port number of the service to connect to (oml_strndup()'d locally)
Returns
a new OmlOutStream instance
See Also
oml_strndup
Definition at line 80 of file net_stream.c.
References logdebug(), mstring_buf(), mstring_create(), mstring_delete(), mstring_len(), mstring_sprintf(), oml_malloc(), oml_strndup(), and socket_set_non_blocking_mode().
Referenced by create_writer().
{
  MString *dest;
  assert(transport != NULL && hostname != NULL && service != NULL);
  OmlNetOutStream* self = (OmlNetOutStream *)oml_malloc(sizeof(OmlNetOutStream));
  memset(self, 0, sizeof(OmlNetOutStream));
  dest = mstring_create();
  mstring_sprintf(dest, "%s:%s:%s", transport, hostname, service);
  self->dest = (char*)oml_strndup (mstring_buf(dest), mstring_len(dest));
  mstring_delete(dest);
  self->protocol = (char*)oml_strndup (transport, strlen (transport));
  self->host = (char*)oml_strndup (hostname, strlen (hostname));
  self->service = (char*)oml_strndup (service, strlen (service));
  logdebug("%s: Created OmlNetOutStream\n", self->dest);
  socket_set_non_blocking_mode(0);
  /* // Now see if we can connect to server */
  /* if (! open_socket(self)) { */
  /*   free(self); */
  /*   return NULL; */
  /* } */
  self->write = net_stream_write;
  self->close = net_stream_close;
  return (OmlOutStream*)self;
}