oml2: o_eventloop.h File Reference
o_eventloop.h File Reference
#include <time.h>
#include "ocomm/o_socket.h"
Data Structures
struct _TimerEvtSource
struct _sockEvtSource
Typedefs
typedef struct _TimerEvtSource TimerEvtSource
typedef struct _sockEvtSource SockEvtSource
typedef enum _SockStatus SocketStatus
typedef void(* o_el_timer_callback)(TimerEvtSource *source, void *handle)
typedef void(* o_el_read_socket_callback)(SockEvtSource *source, void *handle, void *buffer, int buf_size)
typedef void(* o_el_monitor_socket_callback)(SockEvtSource *source, void *handle)
typedef void(* o_el_state_socket_callback)(SockEvtSource *source, SocketStatus status, int error, void *handle)
Enumerations
enum _SockStatus {
SOCKET_UNKNOWN = -1, SOCKET_WRITEABLE, SOCKET_CONN_CLOSED, SOCKET_CONN_REFUSED,
SOCKET_DROPPED, SOCKET_IDLE
}
Functions
const char * socket_status_string (SocketStatus status)
void eventloop_init (void)
void eventloop_set_socket_timeout (unsigned int to)
int eventloop_run (void)
void eventloop_stop (int reason)
void eventloop_terminate (int reason)
void eventloop_report (int loglevel)
TimerEvtSource * eventloop_every (char *name, int period, o_el_timer_callback callback, void *handle)
void eventloop_timer_stop (TimerEvtSource *timer)
SockEvtSource * eventloop_on_stdin (o_el_read_socket_callback callback, void *handle)
SockEvtSource * eventloop_on_monitor_in_channel (Socket *socket, o_el_monitor_socket_callback monitor_cbk, o_el_state_socket_callback status_cbk, void *handle)
SockEvtSource * eventloop_on_read_in_channel (Socket *socket, o_el_read_socket_callback data_cbk, o_el_state_socket_callback status_cbk, void *handle)
SockEvtSource * eventloop_on_out_channel (Socket *socket, o_el_state_socket_callback status_cbk, void *handle)
void eventloop_socket_activate (SockEvtSource *source, int flag)
void eventloop_socket_release (SockEvtSource *source)
void eventloop_socket_remove (SockEvtSource *source)
Typedef Documentation
typedef void(* o_el_monitor_socket_callback)(SockEvtSource *source, void *handle)
Monitoring callback prototype for sockets.
This callback is a fallback when no data-read callback. Listening sockets, for example, do not need to read any data, but need to be warned of incoming connections. This is the role of this callback.
XXX: Couldn't this be wrapped to a default read callback?
Parameters
source SockEvtSource from which the event originated
handle pointer to application-supplied data
Definition at line 129 of file o_eventloop.h.
typedef void(* o_el_read_socket_callback)(SockEvtSource *source, void *handle, void *buffer, int buf_size)
Data-read callback prototype for sockets.
The EventLoop takes care of recv(2)ing data from a socket ready to be read, then passes this data to this callback.
Called on POLLIN, and POLLHUP before o_el_state_socket_callback if some data remains to be read.
Parameters
source SockEvtSource from which the event originated
handle pointer to application-supplied data
buffer pointer to a buffer containing the read data
buf_size size of data in buffer
See Also
o_el_state_socket_callback
poll(3)
Definition at line 116 of file o_eventloop.h.
typedef void(* o_el_state_socket_callback)(SockEvtSource *source, SocketStatus status, int error, void *handle)
State-changes callback prototype for sockets.
If defined, this callback should release and free both application data, pointed by handle, and the socket, in source->socket, on termination conditions.
By default (no callback), source->socket is closed on SOCKET_CONN_CLOSED, SOCKET_CONN_REFUSED, SOCKET_DROPPED and SOCKET_IDLE.
Parameters
source SockEvtSource from which the event originated
status SocketStatus new status for the socket
error errno related to that status
handle pointer to application-supplied data
XXX: This prototype is not very regular, with status and error appearing before handle, unlike, e.g., o_el_read_socket_callback.
See Also
SocketStatus, o_el_read_socket_callback
errno(3)
Definition at line 151 of file o_eventloop.h.
typedef void(* o_el_timer_callback)(TimerEvtSource *source, void *handle)
Timout callback prototype for timers.
Parameters
source TimerEvtSource which expired
handle pointer to application-supplied data
Definition at line 97 of file o_eventloop.h.
typedef enum _SockStatus SocketStatus
Possible socket statuses after state change.
Depends on poll(3) revents and additional condition during further processing (e.g., read from FD).
XXX: Make sure to update socket_status_string when adding values here.
See Also
o_el_state_socket_callback, socket_status_string
poll(3)
typedef struct _sockEvtSource SockEvtSource
Socket-based event source base class for the EventLoop.
typedef struct _TimerEvtSource TimerEvtSource
Prototypes and interfaces for the OComm EventLoop
Author
Max Ott (max@w.nosp@m.inla.nosp@m.b.rut.nosp@m.gers.nosp@m..edu)
XXX: Names 'SockEvtSource' and 'Channel' would make more sense it they were swapped, or something like 'ChannelEvtSource' and 'ChannelInt', to match the Timer*'s regularity. Also, note SockEvtSources and Channels are used for STDIN.
See Also
eventloop_init, eventloop_run, eventloop_stop , eventloop_on_monitor_in_channel, eventloop_on_read_in_channel, eventloop_on_out_channel
o_el_timer_callback, o_el_read_socket_callback, o_el_monitor_socket_callback, o_el_state_socket_callback, o_el_timer_callback
poll(3)Timer-based event source base class for the EventLoop.
Enumeration Type Documentation
enum _SockStatus
Possible socket statuses after state change.
Depends on poll(3) revents and additional condition during further processing (e.g., read from FD).
XXX: Make sure to update socket_status_string when adding values here.
See Also
o_el_state_socket_callback, socket_status_string
poll(3)
Enumerator:
SOCKET_UNKNOWN
Unknown POLLERR
SOCKET_WRITEABLE
POLLOUT
SOCKET_CONN_CLOSED
POLLHUP or POLLIN and no data read (for sockets only)
SOCKET_CONN_REFUSED
If relevant on POLLERR
SOCKET_DROPPED
POLLNVAL
SOCKET_IDLE
No data was receveid for more than DEF_SOCKET_TIMEOUT s
Definition at line 75 of file o_eventloop.h.
{
  SOCKET_UNKNOWN = -1,
  SOCKET_WRITEABLE,
  SOCKET_CONN_CLOSED,
  SOCKET_CONN_REFUSED,
  SOCKET_DROPPED,
  SOCKET_IDLE,
} SocketStatus;
Function Documentation
TimerEvtSource* eventloop_every (char * name, int period, o_el_timer_callback callback, void * handle)
Register a new periodic timer to the event loop
Parameters
name name of this object, used for debugging
period period [s] of the timer
timer_cbk function called when the state of the timer expires
handle pointer to opaque data passed to callback functions
Returns
a pointer to the newly-created TimerInt, cast as a TimerEvtSource
See Also
o_el_timer_callback, eventloop_timer_stop
Definition at line 490 of file eventloop.c.
References _timerInt::callback, _timerInt::due_time, _timerInt::handle, _timerInt::is_active, _timerInt::is_periodic, _timerInt::name, _timerInt::nameBuf, _timerInt::next, oml_malloc(), and _timerInt::period.
  {
  TimerInt* t = (TimerInt*)oml_malloc(sizeof(TimerInt));
  memset(t, 0, sizeof(TimerInt));
  t->name = t->nameBuf;
  strcpy(t->name, name);
  t->is_active = 1;
  t->is_periodic = 1;
  t->period = period;
  t->due_time = time(NULL) + period;
  t->callback = callback;
  t->handle = handle;
  t->next = self.timers;
  self.timers = t;
  return (TimerEvtSource*)t;
}
void eventloop_init (void)
Initialise the global EventLoop
See Also
eventloop_run, eventloop_stop, eventloop_terminate
Definition at line 210 of file eventloop.c.
References DEF_SOCKET_TIMEOUT, and eventloop_set_socket_timeout().
Referenced by main().
{
  memset(&self, 0, sizeof(EventLoop));
  self.fds = NULL;
  self.channels = NULL;
  self.timers = NULL;
  self.size = 0;
  self.length = 0;
  eventloop_set_socket_timeout(DEF_SOCKET_TIMEOUT);
  /* Just to be sure we initialise everything */
  self.start = self.now = self.last_reaped = -1;
}
SockEvtSource* eventloop_on_monitor_in_channel (Socket * socket, o_el_monitor_socket_callback monitor_cbk, o_el_state_socket_callback status_cbk, void * handle)
Register a Socket as a new channel to monitor (e.g., listening socket).
Parameters
socket OComm Socket
monitor_cbk monitoring callback called when a new event arrives, can be NULL
status_cbk status-change callback, can be NULL
handle pointer to opaque data passed to callback functions
Returns
a pointer to a new Channel cast as a SockEvtSource
See Also
Socket, o_el_monitor_socket_callback, o_el_state_socket_callback
Definition at line 620 of file eventloop.c.
References Socket::get_sockfd, Socket::name, o_log, O_LOG_ERROR, and _channel::socket.
Referenced by socket_server_new().
  {
  if (socket == NULL) {
    o_log(O_LOG_ERROR, "EventLoop: Missing socket\n");
    return NULL;
  }
  Channel* ch;
  ch = eventloop_on_in_fd(socket->name, socket->get_sockfd(socket),
              NULL, monitor_cbk, status_cbk, handle);
  ch->socket = socket;
  return (SockEvtSource*)ch;
}
SockEvtSource* eventloop_on_out_channel (Socket * socket, o_el_state_socket_callback status_cbk, void * handle)
Register a Socket as a new output channel.
In essence, this only registers status-change callback to allow reception of a SOCKET_WRITEABLE SocketStatus.
Parameters
socket OComm Socket
status_cbk status-change callback, can be NULL
handle pointer to opaque data passed to callback functions
Returns
a pointer to a new Channel cast as a SockEvtSource
See Also
Socket, o_el_state_socket_callback, SocketStatus
Definition at line 649 of file eventloop.c.
References Socket::get_sockfd, Socket::name, o_log, O_LOG_ERROR, and _channel::socket.
  {
  if (socket == NULL) {
    o_log(O_LOG_ERROR, "EventLoop: Missing socket\n");
    return NULL;
  }
  Channel* ch;
  ch = eventloop_on_out_fd(socket->name, socket->get_sockfd(socket),
              status_cbk, handle);
  ch->socket = socket;
  return (SockEvtSource*)ch;
}
SockEvtSource* eventloop_on_read_in_channel (Socket * socket, o_el_read_socket_callback data_cbk, o_el_state_socket_callback status_cbk, void * handle)
Register a Socket as a new input channel to read data from.
Parameters
socket OComm Socket
data_cbk read callback called with freshly-read data, can be NULL
status_cbk status-change callback, can be NULL
handle pointer to opaque data passed to callback functions
Returns
a pointer to a new Channel cast as a SockEvtSource
See Also
Socket, o_el_read_socket_callback, o_el_state_socket_callback
Definition at line 592 of file eventloop.c.
References Socket::get_sockfd, _channel::last_activity, Socket::name, o_log, O_LOG_ERROR, and _channel::socket.
Referenced by client_handler_new(), on_connect(), and on_control_connect().
  {
  if (socket == NULL) {
    o_log(O_LOG_ERROR, "EventLoop: Missing socket\n");
    return NULL;
  }
  Channel* ch;
  ch = eventloop_on_in_fd(socket->name, socket->get_sockfd(socket),
              data_cbk, NULL, status_cbk, handle);
  ch->socket = socket;
  ch->last_activity = self.now;
  return (SockEvtSource*)ch;
}
SockEvtSource* eventloop_on_stdin (o_el_read_socket_callback read_cbk, void * handle)
Register STDIN as a new input channel to read data from.
Parameters
data_cbk read callback called with freshly-read data, can be NULL
status_cbk status-change callback, can be NULL
handle pointer to opaque data passed to callback functions
Returns
a pointer to a new Channel cast as a SockEvtSource
See Also
o_el_read_socket_callback, o_el_state_socket_callback
Definition at line 570 of file eventloop.c.
Referenced by main().
  {
  char* s = "stdin";
  Channel* ch;
  ch = eventloop_on_in_fd(s, 0, read_cbk, NULL, NULL, handle);
  return (SockEvtSource*)ch;
}
void eventloop_report (int loglevel)
Log a summary of resource usage.
Parameters
loglevel log level at which the message should be issued
See Also
oml_memsummary
Definition at line 473 of file eventloop.c.
References o_log, and oml_memsummary().
{
  o_log(loglevel, "EventLoop: Open file descriptors: %d/%d\n", self.size, self.length);
  o_log(loglevel, "EventLoop: Memory usage: %s\n", oml_memsummary());
}
int eventloop_run (void)
Run the global EventLoop until eventloop_stop() or eventloop_terminate() is called.
The loop is based around the poll(3) system call. It monitor event sources such as Channel or Timers, registered in the respective fields of the global EventLoop object self. It first consider all timers to find whether some have expired and to set the timeout for the poll(3) call. It then calls poll(3) on the file descriptors (STDIN or sockets) related to active Channels, and runs the relevant callbacks for those with pending events. It finally executes the callback functions of the expired timers. The loop will not return until eventloop_stop() or eventloop_terminate() is called. In the former case, it will try to wait until all active sockets are close, while not in the latter.
Returns
the (non-zero) value passed to eventloop_stop() or eventloop_terminate()
See Also
eventloop_init, eventloop_stop, eventloop_terminate , eventloop_on_monitor_in_channel, eventloop_on_read_in_channel, eventloop_on_out_channel
o_el_timer_callback, o_el_read_socket_callback, o_el_monitor_socket_callback, o_el_state_socket_callback, o_el_timer_callback
poll(3)
Definition at line 257 of file eventloop.c.
References _timerInt::callback, count, _timerInt::due_time, eventloop_socket_activate(), eventloop_socket_release(), eventloop_socket_remove(), _timerInt::handle, _timerInt::is_active, _timerInt::is_periodic, _channel::is_removable, _channel::is_shutting_down, _channel::last_activity, MAX_READ_BUFFER_SIZE, _timerInt::name, _channel::name, _timerInt::next, o_log, O_LOG_DEBUG2, O_LOG_DEBUG3, O_LOG_DEBUG4, O_LOG_ERROR, O_LOG_WARN, _timerInt::period, _channel::read_cbk, _channel::socket, SOCKET_CONN_CLOSED, SOCKET_CONN_REFUSED, SOCKET_DROPPED, SOCKET_IDLE, SOCKET_UNKNOWN, SOCKET_WRITEABLE, and _channel::status_cbk.
Referenced by main().
{
  int i;
  self.stopping = 0;
  self.force_stop = 0;
  self.start = self.now = self.last_reaped = time(NULL);
  while (!self.stopping || (self.size>0 && !self.force_stop)) {
    // Check for active timers
    int timeout = -1;
    TimerInt* t = self.timers;
    while (t != NULL) {
      if (t->is_active) {
        int delta = 1000 * (t->due_time - self.now);
        if (delta < 0) delta = 0; // overdue
        if (delta < timeout || timeout < 0) timeout = delta;
      }
      t = t->next;
    }
    if (timeout != -1)
      o_log(O_LOG_DEBUG3, "EventLoop: Timeout = %d\n", timeout);
    if (self.fds_dirty)
      if (update_fds()<1 && timeout < 0) /* No FD nor timeout */
        continue;
    o_log(O_LOG_DEBUG4, "EventLoop: About to poll() on %d FDs with a timeout of %ds\n", self.size, timeout);
    /* for(i=0; i < self.size; i++) {
      o_log(O_LOG_DEBUG4, "EventLoop: FD %d->%s\n", self.fds[i].fd, self.fds_channels[i]->name);
    } */
    int count = poll(self.fds, self.size, timeout);
    self.now = time(NULL);
    if (count < 1) {
      o_log(O_LOG_DEBUG4, "EventLoop: Timeout\n");
    } else {
    // Check sockets
      i = 0;
      o_log(O_LOG_DEBUG4, "EventLoop: Got events\n");
      for (; i < self.size; i++) {
        Channel* ch = self.fds_channels[i];
        if (self.fds[i].revents & POLLERR) {
          char buf[32];
          SocketStatus status;
          int len;
          if ((len = recv(self.fds[i].fd, buf, 32, 0)) <= 0) {
            switch (errno) {
            case ECONNREFUSED:
              status = SOCKET_CONN_REFUSED;
              break;
            default:
              status = SOCKET_UNKNOWN;
              if (!ch->status_cbk) {
                o_log(O_LOG_ERROR, "EventLoop: While reading from socket '%s': (%d) %s\n",
                      ch->name, errno, strerror(errno));
              }
            }
            eventloop_socket_activate((SockEvtSource*)ch, 0);
            do_status_callback (ch, status, errno);
          } else {
            o_log(O_LOG_ERROR, "EventLoop: Expected error on socket '%s' but read '%s'\n", ch->name, buf);
          }
        } else if (self.fds[i].revents & POLLHUP) {
          eventloop_socket_activate((SockEvtSource*)ch, 0);
          /* Client closed the connection, but there might still be bytes
             for us to read from our end of the connection. */
          int len;
          int fd = self.fds[i].fd;
          char buf[MAX_READ_BUFFER_SIZE];
          do {
            if (fd == 0) {
              len = read(fd, buf, MAX_READ_BUFFER_SIZE);
            } else {
              len = recv(fd, buf, 512, 0);
            }
            if (len > 0) {
              o_log(O_LOG_DEBUG3, "EventLoop: Received last %i bytes\n", len);
              do_read_callback (ch, buf, len);
            }
          } while (len > 0);
          do_status_callback (ch, SOCKET_CONN_CLOSED, 0);
        } else if (self.fds[i].revents & POLLIN) {
          char buf[MAX_READ_BUFFER_SIZE];
          if (ch->read_cbk) {
            int len;
            int fd = self.fds[i].fd;
            if (fd == 0) {
              // stdin
              len = read(fd, buf, MAX_READ_BUFFER_SIZE);
            } else {
              // socket
              len = recv(fd, buf, 512, 0);
            }
            ch->last_activity = self.now;
            if (len > 0) {
              o_log(O_LOG_DEBUG3, "EventLoop: Received %i bytes\n", len);
              do_read_callback (ch, buf, len);
            } else if (len == 0 && ch->socket != NULL) {  // skip stdin
              // closed down
              eventloop_socket_activate((SockEvtSource*)ch, 0);
              do_status_callback (ch, SOCKET_CONN_CLOSED, 0);
            } else if (len < 0) {
              if (errno == ENOTSOCK) {
                o_log(O_LOG_ERROR,
                      "EventLoop: Monitored socket '%s' is now invalid; "
                      "removing from monitored set\n",
                      ch->name);
                eventloop_socket_remove ((SockEvtSource*)ch);
              } else {
                o_log(O_LOG_ERROR, "EventLoop: Unrecognized read error not handled (errno=%d)\n",
                      errno);
              }
            }
          } else {
            do_monitor_callback (ch);
          }
        } else if (ch->is_shutting_down) {
          /* The socket was shutting down, and nothing new has appeared;
           * We flushed the buffers, mark it as removable */
          eventloop_socket_release((SockEvtSource*)ch);
        }
        if (self.fds[i].revents & POLLOUT) {
          do_status_callback(ch, SOCKET_WRITEABLE, 0);
          if (0 != ch->last_activity) {
            /* If we track the activity of this socket */
            ch->last_activity = self.now;
          }
        }
        if (self.fds[i].revents & POLLNVAL) {
          o_log(O_LOG_WARN, "EventLoop: socket '%s' invalid, deactivating...\n", ch->name);
          eventloop_socket_activate((SockEvtSource*)ch, 0);
          do_status_callback(ch, SOCKET_DROPPED, 0);
        }
        /* We reap idle channels as we go through the list.  XXX: There might
         * be a corner case where all FDs are already used, and some of them
         * idle, however a new a new connection (on one listening socket early
         * in the list) would be dropped before cleanup triggered by its
         * arrival freed the resources it needs (from the idle sockets further
         * towards the end of the list. See #959.*/
        if (ch->last_activity != 0 &&
            self.socket_timeout > 0 &&
            self.now - ch->last_activity > self.socket_timeout) {
            o_log(O_LOG_DEBUG2, "EventLoop: Socket '%s' idle for %ds, reaping...\n", ch->name, self.now - ch->last_activity);
          do_status_callback(ch, SOCKET_IDLE, 0);
        }
      }
      for (i = 0; i < self.size; i++) {
        Channel* ch = self.fds_channels[i];
        if (ch->is_removable)
          eventloop_socket_remove ((SockEvtSource*)ch);
      }
    }
    if (timeout >= 0) {
      // check timers
      TimerInt* t = self.timers;
      while (t != NULL) {
        if (t->is_active) {
          if (t->due_time <= self.now) {
            // fires
            o_log(O_LOG_DEBUG2, "EventLoop: Timer '%s' fired\n", t->name);
            if (t->callback) t->callback((TimerEvtSource*)t, t->handle);
            if (t->is_periodic) {
              while ((t->due_time += t->period) < self.now) {
                // should really only happen during debugging
                o_log(O_LOG_WARN, "EventLoop: Skipped timer period for '%s'\n",
                      t->name);
              }
            } else {
              t->is_active = 0;
            }
          }
        }
        t = t->next;
      }
    }
  }
  return self.stopping;
}
void eventloop_set_socket_timeout (unsigned int to)
Set the timeout, in seconds, after which idle sockets are reaped.
Parameters
to timeout [s], 0 to disable
Definition at line 231 of file eventloop.c.
References o_log, and O_LOG_DEBUG2.
Referenced by eventloop_init(), and main().
{
  o_log(O_LOG_DEBUG2, "EventLoop: Setting socket idleness timeout to %ds\n", to);
  self.socket_timeout = to;
}
void eventloop_socket_activate (SockEvtSource * source, int flag)
Mark socket event source (channel) as active or not.
This triggers FD update if need be.
Parameters
source SockEvtSource to (de)activate
flag 0 to deactivate, anything else to activate (use 1)
See Also
update_fds
Definition at line 675 of file eventloop.c.
References _channel::is_active.
Referenced by eventloop_run(), eventloop_socket_release(), and eventloop_socket_remove().
{
  Channel* ch = (Channel*)source;
  if (ch->is_active != flag) {
    ch->is_active = flag;
    self.fds_dirty = 1;
  }
}
void eventloop_socket_release (SockEvtSource * source)
Tell the EventLoop to release a channel.
This marks the socket as "removable", but does not remove it immediately. The next time the event loop finishes processing events, it will scan the list of channels/sockets for ones that are removable, and will call eventloop_socket_remove() on them.
At that point, the socket data structure will be destroyed.
After this function is called on a socket, the eventloop will no longer generate callbacks for that socket, therefore the client code must ensure that it has already disposed of the socket's handle data structure, otherwise a memory leak might occur.
Definition at line 698 of file eventloop.c.
References eventloop_socket_activate(), _channel::handle, and _channel::is_removable.
Referenced by client_handler_free(), and eventloop_run().
{
  Channel *ch = (Channel*)source;
  eventloop_socket_activate(source, 0);
  ch->is_removable = 1;
  ch->handle = NULL;
}
void eventloop_socket_remove (SockEvtSource * source)
Remove channels from monitoring of the EventLoop.
The EventLoop calls this function on its own when sockets have been released using eventloop_socket_release(). You probably want to use that one instead.
Parameters
source SockEvtSource to remove and free
See Also
eventloop_socket_release, channel_free
Definition at line 714 of file eventloop.c.
References eventloop_socket_activate(), and _channel::next.
Referenced by client_callback(), eventloop_run(), and status_callback().
{
  Channel* ch = (Channel*)source;
  eventloop_socket_activate(source, 0);
  /* Update the linked list */
  if (self.channels == ch) {
    self.channels = ch->next;
  } else {
    Channel* prev = self.channels;
    Channel* p = prev->next;
    while (p != NULL) {
      if (p == ch) {
        prev->next = ch->next;
        p = NULL; /* We're done */
      } else {
        prev = p;
        p = p->next;
      }
    }
  }
  channel_free(ch);
}
void eventloop_stop (int reason)
Stop the eventloop,
The eventloop will try to gracefully finish by waiting for all active FDs to be closed.
Parameters
reason a non-zero reason for stopping the loop; default to 1, with a warning
Definition at line 447 of file eventloop.c.
References o_log, and O_LOG_WARN.
Referenced by eventloop_terminate().
{
  if(reason) {
    self.stopping = reason;
  } else {
    o_log(O_LOG_WARN, "EventLoop: Tried to stop with no reason, defaulting to 1");
    self.stopping = 1;
  }
  terminate_fds();
}
void eventloop_terminate (int reason)
Terminate the eventloop,
Parameters
reason a non-zero reason for stopping the loop; default to 1, with a warning
Definition at line 462 of file eventloop.c.
References eventloop_stop().
{
    self.force_stop = 1;
    eventloop_stop(reason);
}
void eventloop_timer_stop (TimerEvtSource * timer)
Stop timer and free its allocated memory
Parameters
timer TimerEvtSource to terminate and free
See Also
eventloop_every
oml_free
Definition at line 534 of file eventloop.c.
References _timerInt::next.
{
  TimerInt *t = (TimerInt *)timer;
  /* Update the linked list */
  if (self.timers == t) {
    self.timers = t->next;
  } else {
    TimerInt* prev = self.timers;
    TimerInt* p = prev->next;
    while (p != NULL) {
      if (p == t) {
        prev->next = t->next;
        p = NULL; /* We're done */
      } else {
        prev = p;
        p = p->next;
      }
    }
  }
  eventloop_timer_free(t);
}
const char* socket_status_string (SocketStatus status)
Definition at line 45 of file eventloop.c.
References case_string, SOCKET_CONN_CLOSED, SOCKET_CONN_REFUSED, SOCKET_DROPPED, SOCKET_IDLE, SOCKET_UNKNOWN, and SOCKET_WRITEABLE.
{
  switch(status) {
    case_string(SOCKET_UNKNOWN);
    case_string(SOCKET_WRITEABLE);
    case_string(SOCKET_CONN_CLOSED);
    case_string(SOCKET_CONN_REFUSED);
    case_string(SOCKET_DROPPED);
    case_string(SOCKET_IDLE);
  default:
    return "Unknown SocketStatus";
  }
}