oml2: o_log.h File Reference
o_log.h File Reference
#include <stdarg.h>
Macros
#define O_LOG_ERROR -2
#define O_LOG_WARN -1
#define O_LOG_INFO 0
#define O_LOG_DEBUG 1
#define O_LOG_DEBUG2 2
#define O_LOG_DEBUG3 3
#define O_LOG_DEBUG4 4
#define LOGDEBUG(...) /* o_log(O_LOG_DEBUG3, __VA_ARGS__) */
Typedefs
typedef void(* o_log_fn)(int log_level, const char *format,...)
Functions
void o_set_log_file (char *name)
void o_set_log_level (int level)
int o_log_level_active (int log_level)
o_log_fn o_set_log (o_log_fn log_fn)
void o_set_simplified_logging (void)
void logerror (const char *fmt,...)
void logwarn (const char *fmt,...)
void loginfo (const char *fmt,...)
void logdebug (const char *fmt,...)
void logdebug2 (const char *fmt,...)
void logdebug3 (const char *fmt,...)
void logdebug4 (const char *fmt,...)
Variables
o_log_fn o_log
Macro Definition Documentation
#define LOGDEBUG (...) /* o_log(O_LOG_DEBUG3, __VA_ARGS__) */
Definition at line 82 of file o_log.h.
Referenced by omlc_inject().
#define O_LOG_DEBUG 1
Definition at line 26 of file o_log.h.
Referenced by logdebug(), main(), omlc_close(), sockaddr_get_name(), socket_in_new(), socket_sendto(), and socket_shutdown().
#define O_LOG_DEBUG2 2
Definition at line 27 of file o_log.h.
Referenced by eventloop_run(), eventloop_set_socket_timeout(), logdebug2(), and START_TEST().
#define O_LOG_DEBUG3 3
Definition at line 28 of file o_log.h.
Referenced by eventloop_run(), and logdebug3().
#define O_LOG_DEBUG4 4
Definition at line 29 of file o_log.h.
Referenced by eventloop_run(), and logdebug4().
#define O_LOG_ERROR -2
Definition at line 23 of file o_log.h.
Referenced by eventloop_on_monitor_in_channel(), eventloop_on_out_channel(), eventloop_on_read_in_channel(), eventloop_run(), socket_in_new(), socket_sendto(), socket_tcp_out_new(), START_TEST(), vector_bool_to_json(), vector_double_to_json(), vector_int32_to_json(), vector_int64_to_json(), vector_uint32_to_json(), and vector_uint64_to_json().
#define O_LOG_INFO 0
Definition at line 25 of file o_log.h.
Referenced by loginfo(), main(), and omlc_init().
#define O_LOG_WARN -1
Definition at line 24 of file o_log.h.
Referenced by eventloop_run(), eventloop_stop(), logwarn(), socket_get_peer_addr(), socket_in_new(), socket_sendto(), and socket_shutdown().
Typedef Documentation
typedef void(* o_log_fn)(int log_level, const char *format,...)
The o_log_fn function pointer is for format string-based log functions.
A typical function will check that the log_level is larger than the o_log_level, then report the message by creating a string from the format. The default is to create the va_list and call o_vlog().
if (level > o_log_level) return;
va_list va;
va_start(va, format);
vfprintf(stderr, format, va);
va_end(va);
This function will then be used on calls to o_log()
Parameters
log_level log level for the message
format format string
... arguments for the format string
See Also
o_set_log
Definition at line 53 of file o_log.h.
Function Documentation
void logdebug (const char * fmt, ...)
Convenience function logging at level O_LOG_DEBUG.
Convenience function logging at level O_LOG_DEBUG.
Parameters
fmt format string
... format string arguments
Definition at line 333 of file log.c.
References O_LOG_DEBUG.
Referenced by bw_close(), bw_create(), client_realloc_tables(), client_send_header(), client_send_thread(), create_default_filters(), create_mstream(), database_cleanup(), database_find(), database_find_or_create_table(), database_init(), database_setup_backend(), database_table_free(), dba_table_create_meta(), destroy_filter(), destroy_mp(), destroy_ms(), filter_engine_start(), find_mp_field(), hook_cleanup(), hook_read(), hook_setup(), hook_write(), marshal_measurements(), marshal_value(), mbuf_destroy(), net_stream_new(), oml_mp_get_default_ms(), oml_setup(), omlc_add_mp(), omlc_inject_metadata(), on_connect(), on_control_connect(), parse_config(), proxy_message_loop(), psql_backend_setup(), START_TEST(), status_callback(), stdin_handler(), unmarshal_init(), unmarshal_value(), and unregister_filters().
{
  va_list va;
  va_start (va, fmt);
  o_vlog (O_LOG_DEBUG, fmt, va);
  va_end (va);
}
void logdebug2 (const char * fmt, ...)
Convenience function logging at level O_LOG_DEBUG2.
Convenience function logging at level O_LOG_DEBUG2.
Parameters
fmt format string
... format string arguments
Definition at line 345 of file log.c.
References O_LOG_DEBUG2.
Referenced by psql_prepare().
{
  va_list va;
  va_start (va, fmt);
  o_vlog (O_LOG_DEBUG2, fmt, va);
  va_end (va);
}
void logdebug3 (const char * fmt, ...)
Convenience function logging at level O_LOG_DEBUG3.
Convenience function logging at level O_LOG_DEBUG3.
Parameters
fmt format string
... format string arguments
Definition at line 357 of file log.c.
References O_LOG_DEBUG3.
Referenced by marshal_value(), and unmarshal_value().
{
  va_list va;
  va_start (va, fmt);
  o_vlog (O_LOG_DEBUG3, fmt, va);
  va_end (va);
}
void logdebug4 (const char * fmt, ...)
Convenience function logging at level O_LOG_DEBUG4.
Convenience function logging at level O_LOG_DEBUG4.
Parameters
fmt format string
... format string arguments
Definition at line 369 of file log.c.
References O_LOG_DEBUG4.
{
  va_list va;
  va_start (va, fmt);
  o_vlog (O_LOG_DEBUG4, fmt, va);
  va_end (va);
}
void logerror (const char * fmt, ...)
Convenience function logging at level O_LOG_ERROR.
Convenience function logging at level O_LOG_ERROR.
Parameters
fmt format string
... format string arguments
Definition at line 297 of file log.c.
Referenced by bw_close(), client_callback(), client_handler_update_name(), client_sender_connect(), create_default_filters(), create_filter(), create_mstream(), create_writer(), database_find_or_create_table(), database_init(), database_release(), database_setup_backend(), dba_table_create_from_schema(), die(), file_stream_new(), filter_process(), main(), marshal_init(), marshal_measurements(), marshal_value(), oml_mp_get_default_ms(), oml_ms_add_writer(), oml_value_set(), oml_value_to_double(), oml_value_to_int(), omlc_add_mp(), omlc_guid_generate(), omlc_init(), omlc_inject(), omlc_inject_metadata(), omlc_start(), omlf_average_new(), omlf_delta_new(), omlf_first_new(), omlf_histogram_new(), omlf_last_new(), omlf_register_filter(), omlf_stddev_new(), omlf_sum_new(), parse_config(), parse_uri(), prepare_stdin(), process_schema(), proxy_message_loop(), psql_backend_setup(), psql_create_database(), psql_prepare(), read_header(), schema_to_sql(), sq3_backend_setup(), sq3_create_database(), unmarshal_init(), unmarshal_typed_value(), and unmarshal_value().
{
  va_list va;
  va_start (va, fmt);
  o_vlog (O_LOG_ERROR, fmt, va);
  va_end (va);
}
void loginfo (const char * fmt, ...)
Convenience function logging at level O_LOG_INFO.
Convenience function logging at level O_LOG_INFO.
Parameters
fmt format string
... format string arguments
Definition at line 321 of file log.c.
References O_LOG_INFO.
Referenced by bw_close(), client_send_thread(), create_mstream(), database_find(), database_release(), destroy_ms(), file_stream_new(), fuseki_create_database(), hook_setup(), main(), omlc_init(), process_schema(), psql_backend_setup(), psql_create_database(), sq3_backend_setup(), and sq3_create_database().
{
  va_list va;
  va_start (va, fmt);
  o_vlog (O_LOG_INFO, fmt, va);
  va_end (va);
}
void logwarn (const char * fmt, ...)
Convenience function logging at level O_LOG_WARN.
Convenience function logging at level O_LOG_WARN.
Parameters
fmt format string
... format string arguments
Definition at line 309 of file log.c.
References O_LOG_WARN.
Referenced by bw_close(), client_handler_update_name(), client_realloc_values(), database_find_or_create_table(), database_init(), database_table_free(), dba_table_create_meta(), filter_process(), hook_cleanup(), hook_setup(), logwrite(), marshal_finalize(), oml_lock(), oml_lock_persistent(), oml_setup(), oml_type_from_s(), oml_unlock(), oml_value_copy(), oml_value_reset(), oml_value_set(), oml_value_string_to_bool(), oml_value_to_double(), oml_value_to_int(), omlc_add_mp(), omlc_init(), omlc_inject(), omlc_inject_metadata(), omlc_process(), parse_uri(), process_schema(), resolve_service(), run(), socket_get_name(), socket_sendto(), unmarshal_init(), and unmarshal_values().
{
  va_list va;
  va_start (va, fmt);
  o_vlog (O_LOG_WARN, fmt, va);
  va_end (va);
}
int o_log_level_active (int log_level)
Test if a given log level is currently active
Parameters
level log level
Returns
0 if inactive, 1 otherwise
See Also
o_set_log_level
Definition at line 94 of file log.c.
References o_log_level.
{
  if (log_level <= o_log_level) { return 1; }
  return 0;
}
o_log_fn o_set_log (o_log_fn new_log_fn)
Set the format string-based log function if non NULL, or o_log_simplified
Parameters
log_fn function to use for logging
Returns
the current logging function
Set the format string-based log function if non NULL, or o_log_simplified
Parameters
log_fn function to use for logging
Returns
the current logging function
See Also
o_log_simplified
Definition at line 106 of file log.c.
References o_log, and o_log_function.
Referenced by o_set_simplified_logging(), and omlc_init().
{
  if ((o_log_function = new_log_fn) == NULL) {
    o_log_function = o_log_simplified;
  }
  return o_log;
}
void o_set_log_file (char * name)
Direct the log stream to the named file.
Parameters
name name of the file to write log into (if '-' or NULL, defaults to stderr)
Direct the log stream to the named file.
Parameters
name name of the file to write log into (if '-' or NULL, defaults to stderr)
See Also
o_log_simplified
Definition at line 57 of file log.c.
Referenced by main(), omlc_init(), setup_logging(), and START_TEST().
{
  if (name == NULL) {
    fprintf (stderr, "The log file name is NULL!  Logging to stderr instead\n");
    logfile = stderr;
  } else {
    if (*name == '-') {
      logfile = stderr;
    } else {
      logfile = fopen(name, "a");
      if (logfile == NULL) {
        fprintf(stderr, "Can't open logfile '%s'\n", name);
        return;
      }
      setvbuf (logfile, NULL, _IOLBF, 1024);
    }
  }
}
void o_set_log_level (int level)
Set the log level below which messages should be displayed.
Parameters
level log level
See Also
o_log, o_log_level
Definition at line 83 of file log.c.
References o_log_level.
Referenced by main(), omlc_init(), setup_logging(), and START_TEST().
{
  o_log_level = level;
}
void o_set_simplified_logging (void)
Reset the logging function to the internal default
Reset the logging function to the internal o_log_simplified.
See Also
o_log_simplified, o_set_log
Definition at line 118 of file log.c.
References o_set_log().
Referenced by setup_logging().
{
  o_set_log(NULL);
}
Variable Documentation
o_log_fn o_log
Log a message following the current logging parameters.
Output will be rate-limited, and timestamped (except on stderr). One should however use the convenience functions logerror(), logwarn(), loginfo() and logdebug() for user-facing code.
Parameters
level log level for the message
fmt format string
... format string arguments
See Also
logerror, logwarn, loginfo, logdebug
o_set_log_file, o_set_log_level, o_set_log, o_set_simplified_logging
Definition at line 48 of file log.c.
Referenced by eventloop_on_monitor_in_channel(), eventloop_on_out_channel(), eventloop_on_read_in_channel(), eventloop_report(), eventloop_run(), eventloop_set_socket_timeout(), eventloop_stop(), o_set_log(), oml_memreport(), sockaddr_get_name(), socket_get_peer_addr(), socket_in_new(), socket_sendto(), socket_shutdown(), socket_tcp_out_new(), START_TEST(), vector_bool_to_json(), vector_double_to_json(), vector_int32_to_json(), vector_int64_to_json(), vector_uint32_to_json(), and vector_uint64_to_json().