oml2: o_socket_group.h File Reference
o_socket_group.h File Reference
Header file for socket groups.
Functions
Socket * socket_group_new (char *name)
Return a new 'instance' structure.
void socket_group_add (Socket *this, Socket *socket)
void socket_group_remove (Socket *this, Socket *socket)
Detailed Description
Header file for socket groups.
Author
Max Ott (max@w.nosp@m.inla.nosp@m.b.rut.nosp@m.gers.nosp@m..edu)
Definition in file o_socket_group.h.
Function Documentation
void socket_group_add (Socket * this, Socket * socket)
Add a socket to the group.
Parameters
socket This object Socket to add
Definition at line 56 of file socket_group.c.
References _sockHolder::next, oml_malloc(), and _sockHolder::socket.
  {
  SocketGroupInt* self = (SocketGroupInt*)this;
  SocketHolder* holder = (SocketHolder *)oml_malloc(sizeof(SocketHolder));
  memset(holder, 0, sizeof(SocketHolder));
  holder->socket = socket;
  holder->next = self->first;
  self->first = holder;
}
Socket* socket_group_new (char * name)
Return a new 'instance' structure.
Create an new socket group.
Parameters
name Name used for debugging
Definition at line 130 of file socket_group.c.
References oml_malloc().
  {
  SocketGroupInt* self = (SocketGroupInt *)oml_malloc(sizeof(SocketGroupInt));
  memset(self, 0, sizeof(SocketGroupInt));
  self->name = self->nameBuf;
  strcpy(self->name, name != NULL ? name : "UNKNOWN");
  self->sendto = sg_sendto;
  self->get_sockfd = sg_get_sockfd;
  return (Socket*)self;
}
void socket_group_remove (Socket * this, Socket * socket)
Remove a socket to the group.
Parameters
socket This object Socket to remove
Definition at line 71 of file socket_group.c.
References _sockHolder::next, oml_free(), and _sockHolder::socket.
  {
  SocketGroupInt* self = (SocketGroupInt*)this;
  SocketHolder* prev = NULL;
  SocketHolder* holder = self->first;
  while (holder != NULL) {
    if (socket ==  holder->socket) {
      // remove holder
      if (prev == NULL) {
    self->first = holder->next;
      } else {
    prev->next = holder->next;
      }
      oml_free(holder);
      return;
    }
    prev = holder;
    holder = holder->next;
  }
}