oml2: oml2-proxy-server.c File Reference
oml2-proxy-server.c File Reference
Implement the proxy server's top-level main() and its supporting functions.
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <signal.h>
#include <popt.h>
#include "ocomm/o_log.h"
#include "ocomm/o_socket.h"
#include "ocomm/o_eventloop.h"
#include "mstring.h"
#include "session.h"
#include "proxy_client.h"
Macros
#define V_STRING "OML2 Proxy Server V%s\n"
#define COPYRIGHT "Copyright 2007-2014 NICTA\n"
#define DEF_PORT 3003
#define DEF_PORT_STR "3003"
#define DEF_CTRL_PORT 3004
#define DEF_CTRL_PORT_STR "3004"
#define DEFAULT_LOG_FILE "oml_proxy_server.log"
#define DEFAULT_RESULT_FILE "oml_result_proxy.res"
#define DEF_PAGE_SIZE 1024
#define DEFAULT_SERVER_ADDRESS "localhost"
Functions
void * client_send_thread (void *handle)
void proxy_message_loop (const char *client_id, Client *client, void *buf, size_t size)
void client_callback (SockEvtSource *source, void *handle, void *buf, int buf_size)
void status_callback (SockEvtSource *source, SocketStatus status, int error, void *handle)
void on_connect (Socket *client_sock, void *handle)
void * prepare_stdin (void *handle)
void stdin_handler (SockEvtSource *source, void *handle, void *buf, int buf_size)
void on_control_connect (Socket *sock, void *handle)
void sigpipe_handler (int signum)
void setup_logging (char *logfile, int level)
int main (int argc, const char *argv[])
Variables
int sigpipe_flag = 0
Session * session = NULL
struct poptOption options []
Detailed Description
Implement the proxy server's top-level main() and its supporting functions.
Definition in file oml2-proxy-server.c.
Macro Definition Documentation
#define COPYRIGHT "Copyright 2007-2014 NICTA\n"
Definition at line 31 of file oml2-proxy-server.c.
Referenced by main().
#define DEF_CTRL_PORT 3004
Definition at line 35 of file oml2-proxy-server.c.
#define DEF_CTRL_PORT_STR "3004"
Definition at line 36 of file oml2-proxy-server.c.
#define DEF_PAGE_SIZE 1024
Definition at line 39 of file oml2-proxy-server.c.
#define DEF_PORT 3003
Definition at line 33 of file oml2-proxy-server.c.
#define DEF_PORT_STR "3003"
Definition at line 34 of file oml2-proxy-server.c.
#define DEFAULT_LOG_FILE "oml_proxy_server.log"
Definition at line 37 of file oml2-proxy-server.c.
Referenced by setup_logging().
#define DEFAULT_RESULT_FILE "oml_result_proxy.res"
Definition at line 38 of file oml2-proxy-server.c.
#define DEFAULT_SERVER_ADDRESS "localhost"
Definition at line 40 of file oml2-proxy-server.c.
#define V_STRING "OML2 Proxy Server V%s\n"
Definition at line 30 of file oml2-proxy-server.c.
Referenced by main().
Function Documentation
void client_callback (SockEvtSource * source, void * handle, void * buf, int buf_size)
Callback function called when the socket receive some data
Parameters
source the socket event
handle the client handler
buf data received from the socket
bufsize the size of the data set from the socket
Callback function called when the socket receive some data
Parameters
source the socket event
handle the client handler
buf data received from the socket
bufsize the size of the data set from the socket
Definition at line 81 of file oml2-proxy-server.c.
Referenced by client_handler_new(), on_connect(), and START_TEST().
{
  (void)source;
  Client* self = (Client*)handle;
  //  logdebug ("'%s': received %d octets of data\n", source->name, buf_size);
  //  logdebug ("'%s': %s\n", source->name, to_octets (buf, buf_size));
  proxy_message_loop (source->name, self, buf, buf_size);
  mbuf_repack_message (self->mbuf);
  if (self->state == C_PROTOCOL_ERROR) {
    socket_close (self->recv_socket);
    logerror("'%s': protocol error, proxy server will disconnect upstream client\n", source->name);
    eventloop_socket_remove (self->recv_event);  // Note:  this free()'s source!
    self->recv_event = NULL;
  }
  fwrite (buf, sizeof (char), buf_size, self->file);
  pthread_mutex_lock (&self->mutex);
  pthread_cond_signal (&self->condvar);
  pthread_mutex_unlock (&self->mutex);
}
void* client_send_thread (void * handle)
Try to send data to the real OML server
Parameters
handle the client data structure i.e. a pointer to a Client*.
Definition at line 147 of file sender.c.
References C_CONFIGURE, C_DISCONNECTED, C_HEADER, cbuf_advance_cursor(), cbuf_consume_cursor(), cbuf_cursor_page_remaining(), cbuf_cursor_pointer(), client_free(), client_send_headers(), client_sender_connect(), _client::condvar, count, msg_queue_node::cursor, cbuffer_page::fill, oml_message::length, msg_queue::length, logdebug(), loginfo(), _client::messages, msg_queue_node::msg, msg_queue_head(), msg_queue_remove(), _client::mutex, Socket::name, cbuffer_cursor::page, ProxyState_PAUSED, ProxyState_SENDING, _client::recv_socket, _client::send_socket, _client::sender_connected, oml_message::seqno, session, _client::session, session_remove_client(), sigpipe_flag, _session::state, and _client::state.
Referenced by on_connect().
{
  Client *client = (Client*)handle;
  Session *session = client->session;
  loginfo ("'%s': client sender thread started\n", client->recv_socket->name);
  pthread_mutex_lock (&client->mutex);
  logdebug ("Mutex locked...\n");
  while(1) {
    logdebug ("Sender waiting...\n");
    pthread_cond_wait (&client->condvar, &client->mutex);
    if (session->state == ProxyState_SENDING) {
      if (!client->sender_connected) {
        // try to connect
        if (client->state == C_HEADER || client->state == C_CONFIGURE)
          continue; // Haven't finished receiving the headers
        pthread_mutex_unlock (&client->mutex);
        while (!client->sender_connected && session->state == ProxyState_SENDING) {
          if (client_sender_connect (client) == 0) {
            logdebug ("Connected to downstream OK\n");
            client->sender_connected = 1;
          } else {
            logdebug ("Failed to connect to downstream:  %s\n", strerror (errno));
            sleep (1); // Retry every second.
            continue;
          }
        }
        pthread_mutex_lock (&client->mutex);
        if (client->sender_connected && client_send_headers (client) == -1) {
          logdebug ("Something failed while sending headers:  %s\n", strerror (errno));
          client->sender_connected = 0;
          continue;
        }
      }
      while (client->messages->length > 0 && client->sender_connected) {
        struct msg_queue_node *head = msg_queue_head (client->messages);
        struct cbuffer_cursor cursor = head->cursor;
        size_t length = head->msg->length;
        size_t count = 0;
        int result = 0;
        while (length > 0) {
          char *buf = cbuf_cursor_pointer (&cursor);
          size_t page_remaining = cbuf_cursor_page_remaining (&cursor);
          size_t to_write = length < page_remaining ? length : page_remaining;
          logdebug ("Seqno: %d Sending %d bytes (fill=%d, remain=%d)\n", head->msg->seqno, to_write, cursor.page->fill, page_remaining);
          pthread_mutex_unlock (&client->mutex);
          result = send (client->send_socket, buf, to_write, 0);
          pthread_mutex_lock (&client->mutex);
          if (result == -1) {
            logdebug ("send(2) returned -1 (%s)\n", strerror (errno));
            if (sigpipe_flag == 1) {
              logdebug ("sigpipe_flag is 1\n");
              sigpipe_flag = 0;
            }
            client->sender_connected = 0;
            break;
          } else if (result < (int)to_write) {
            logdebug ("Wrote less than expected \n");
          }
          cbuf_advance_cursor (&cursor, result);
          length -= result;
          count += result;
        }
        if (result != -1) {
          cbuf_consume_cursor (&head->cursor, head->msg->length);
          msg_queue_remove (client->messages);
        }
      }
      if (client->state == C_DISCONNECTED && client->messages->length == 0) {
        loginfo ("Client disconnected and all pending measurements have been sent; shutting down this client\n");
        shutdown (client->send_socket, SHUT_RDWR);
        sleep (1);
        close (client->send_socket);
        session_remove_client (session, client);
        client_free (client);
        pthread_exit (NULL);
      }
    } else if (session->state == ProxyState_PAUSED && client->sender_connected) {
      shutdown (client->send_socket, SHUT_RDWR);
      sleep (1);
      close (client->send_socket);
      client->sender_connected = 0;
    }
  }
}
int main (int argc, const char * argv[])
Definition at line 307 of file oml2-proxy-server.c.
References COPYRIGHT, eventloop_init(), eventloop_on_stdin(), eventloop_run(), logerror(), loginfo(), oml_free(), oml_malloc(), on_connect(), on_control_connect(), options, prepare_stdin(), ProxyState_PAUSED, setup_logging(), sigpipe_handler(), socket_free(), socket_server_new(), _session::state, stdin_handler(), V_STRING, and VERSION.
{
  Socket* serverSock, *controlSock;
  int c, ret = -1;
  poptContext optCon = poptGetContext(NULL, argc, argv, options, 0);
  poptSetOtherOptionHelp(optCon, "configFile");
  while ((c = poptGetNextOpt(optCon)) >= 0) {
    switch (c) {
    case 'v':
      printf(V_STRING, VERSION);
      printf(COPYRIGHT);
      return 0;
    }
  }
  setup_logging (logfile_name, log_level);
  if (c < -1) {
    /* an error occurred during option processing */
    fprintf(stderr, "%s: %s\n",
      poptBadOption(optCon, POPT_BADOPTION_NOALIAS),
      poptStrerror(c));
    return -1;
  }
  loginfo (V_STRING, VERSION);
  loginfo (COPYRIGHT);
  struct sigaction new_action, old_action;
  new_action.sa_handler = sigpipe_handler;
  sigemptyset (&new_action.sa_mask);
  new_action.sa_flags = 0;
  sigaction (SIGPIPE, NULL, &old_action);
  if (old_action.sa_handler != SIG_IGN)
    sigaction (SIGPIPE, &new_action, NULL);
  prepare_stdin(NULL);
  eventloop_init();
  session = (Session*)oml_malloc(sizeof(Session));
  memset(session, 0, sizeof(Session));
  session->state = ProxyState_PAUSED;
  serverSock = socket_server_new("proxy_server", NULL, listen_service, on_connect, NULL);
  controlSock = socket_server_new("proxy_server_control", NULL, control_service, on_control_connect, NULL);
  if(!serverSock || !controlSock) {
    logerror("Unable to listen for either client and/or control connections");
    ret = -1;
  } else {
    eventloop_on_stdin(stdin_handler, session);
    eventloop_run();
    ret = 0;
  }
  socket_free(serverSock);
  socket_free(controlSock);
  oml_free(session);
  return ret;
}
void on_connect (Socket * client_sock, void * handle)
Callback function called when a node connects via TCP
Parameters
client_sock Socket of the client
handle the client handler
Definition at line 143 of file oml2-proxy-server.c.
References client_callback(), _session::client_count, client_new(), client_send_thread(), eventloop_on_read_in_channel(), logdebug(), mstring_buf(), mstring_create(), mstring_delete(), mstring_sprintf(), _client::recv_event, session, _client::session, session_add_client(), status_callback(), and _client::thread.
Referenced by main().
{
  (void)handle;  // This parameter is unused
  MString *mstr = mstring_create ();
  mstring_sprintf (mstr,"%s.%d", resultfile_name, session->client_count);
  logdebug("New client (index %d) connected\n", session->client_count);
  session->client_count++;
  Client* client = client_new(client_sock, page_size, mstring_buf (mstr),
                              downstream_port, downstream_address);
  mstring_delete (mstr);
  session_add_client (session, client);
  client->session = session;
  client->recv_event = eventloop_on_read_in_channel(client_sock, client_callback,
                                                    status_callback, (void*)client);
  pthread_create (&client->thread, NULL, client_send_thread, (void*)client);
}
void on_control_connect (Socket * sock, void * handle)
Definition at line 261 of file oml2-proxy-server.c.
References eventloop_on_read_in_channel(), logdebug(), and stdin_handler().
Referenced by main().
{
  (void)handle; // This parameter is unused
  logdebug ("New control connection\n");
  eventloop_on_read_in_channel (sock, stdin_handler, NULL, (void*)session);
}
void* prepare_stdin (void * handle)
Definition at line 177 of file oml2-proxy-server.c.
References count, and logerror().
Referenced by main().
{
  (void)handle;
#ifdef __APPLE__
  static int thread_started = 0;
  static int stdin_dup;
  static int stdin_pipe[2];
  static pthread_t self;
  if (!thread_started) {
    int result;
    result = pipe (stdin_pipe);
    if (result) {
      logerror ("Could not create pipe for stdin duplication: %s\n", strerror(errno));
      exit(EXIT_FAILURE);
    }
    stdin_dup = dup(fileno(stdin));
    dup2(stdin_pipe[0], fileno(stdin));
    thread_started = 1;
    result = pthread_create (&self, NULL, prepare_stdin, NULL);
    if (result == -1) {
      logerror ("Error creating thread for reading stdin: %s\n", strerror (errno));
      exit (EXIT_FAILURE);
    }
  } else {
    char buf [512];
    while (1) {
      ssize_t count = read (stdin_dup, buf, 512);
      if (count < 0)
        logerror ("Error reading from stdin: %s\n", strerror(errno));
      if (count <= 0)
        return NULL;
      write (stdin_pipe[1], buf, count);
    }
  }
#endif
  return NULL;
}
void proxy_message_loop (const char * client_id, Client * client, void * buf, size_t size)
Definition at line 145 of file receiver.c.
Referenced by client_callback(), and main().
{
  MBuffer *mbuf = client->mbuf;
  struct header *header;
  struct oml_message msg;
  int result;
  size_t message_length;
  result = mbuf_write (mbuf, buf, size);
  if (result == -1) {
    logerror ("'%s': Failed to write message from client into message buffer. Data is being lost!\n",
              client_id);
    return;
  }
 loop:
  switch (client->state) {
  case C_HEADER:
    /* Read headers until out of header data to read*/
    while (read_header (client, mbuf) == 1);
    if (client->state != C_HEADER)
      goto loop;
    break;
  case C_CONFIGURE:
    if (client->header_table[H_DOMAIN] == NULL ||
        client->header_table[H_CONTENT] == NULL ||
        client->header_table[H_DOMAIN]->tag == H_NONE ||
        client->header_table[H_CONTENT]->tag == H_NONE) {
      if (client->headers == NULL) {
        logdebug ("Headers NULL!");
      }
      client->state = C_PROTOCOL_ERROR;
    } else {
      client->domain = client->header_table[H_DOMAIN]->value;
      client->content = content_from_string (client->header_table[H_CONTENT]->value);
      if (client->content == CONTENT_NONE)
        client->state = C_PROTOCOL_ERROR;
    }
    if (client->state != C_PROTOCOL_ERROR) {
      logdebug ("%s\n", client->domain);
      logdebug ("%d\n", client->content);
    } else {
      logdebug ("Can't write out domain and content because of protocol error in input\n");
      logdebug ("Input is: '%s'\n", buf);
    }
    for (header = client->headers; header != NULL; header = header->next) {
      logdebug ("HEADER:  '%s' : '%s'\n",
                tag_to_string(header->tag),
                header->value);
    }
    switch (client->content){
    case CONTENT_TEXT:
      client->msg_start = text_read_msg_start;
      break;
    case CONTENT_BINARY:
      client->msg_start = bin_read_msg_start;
      break;
    default:
      /* Default is set when client is created (client_new()) */
      logerror ("Client content is not TEXT or BINARY\n");
      break;
    }
    mbuf_consume_message (mbuf); // Next message starts after the headers.
    client->state = C_DATA;
    break;
  case C_DATA:
    result = client->msg_start (&msg, mbuf);
    if (result == -1) {
      logerror ("'%s': protocol error in received message\n", client_id);
      client->state = C_PROTOCOL_ERROR;
      goto loop;
    } else if (result == 0) {
      // Try again when we get more data.
      logdebug ("'%s': need more data\n", client_id);
      mbuf_reset_read (mbuf);
      return;
    } else {
      logdebug ("'%s': received message of length %d\n", client_id, result);
      message_length = result;
    }
    logdebug ("Received [strm=%d seqno=%d ts=%f %d bytes]\n",
              msg.stream, msg.seqno, msg.timestamp, msg.length);
    mbuf_reset_read (mbuf);
    store_received_message (client, &msg, (char*)mbuf_rdptr (mbuf), message_length);
    mbuf_read_skip (mbuf, message_length);
    mbuf_consume_message (mbuf);
    break;
  case C_PROTOCOL_ERROR:
    logdebug ("'%s': protocol error!\n");
    break;
  default:
    logerror ("'%s': unknown client state '%d'\n", client_id, client->state);
    mbuf_clear (mbuf);
    return;
  }
}
void setup_logging (char * logfile, int level)
Set up the logging system.
This function sets up the server logging system to log to file logfile, with the given log verbosity level. All messages with severity less than or equal to level will be logged; all others will be discarded (lower levels are more important).
If logfile is not NULL then the named file is opened for logging. If logfile is NULL and the application's stderr stream is not attached to a tty, then the file DEF_LOG_FILE is opened for logging; otherwise, if logfile is NULL and stderr is attached to a tty then log messages will sent to stderr.
Parameters
logfile the file to open
level the severity level at which to log
Definition at line 292 of file oml2-proxy-server.c.
References DEFAULT_LOG_FILE, o_set_log_file(), o_set_log_level(), and o_set_simplified_logging().
Referenced by main().
{
  if (!logfile) {
    if (isatty (fileno (stderr)))
      logfile = "-";
    else
      logfile = DEFAULT_LOG_FILE;
  }
  o_set_log_file(logfile);
  o_set_log_level(level);
  o_set_simplified_logging ();
}
void sigpipe_handler (int signum)
Definition at line 269 of file oml2-proxy-server.c.
References sigpipe_flag.
Referenced by main().
{
  if (signum == SIGPIPE)
    sigpipe_flag = 1;
}
void status_callback (SockEvtSource * source, SocketStatus status, int errcode, void * handle)
Callback function when the status of the socket change
Parameters
source the socket event
status the status of the socket
error the value of the error if there is
handle the Client handler structure
Callback function called when the status of the socket change
Parameters
source the socket event
status the status of the socket
errno the value of the error if there is
handle the Client handler structure
Definition at line 114 of file oml2-proxy-server.c.
References C_DISCONNECTED, eventloop_socket_remove(), logdebug(), _sockEvtSource::name, _sockEvtSource::socket, socket_close(), and SOCKET_CONN_CLOSED.
Referenced by client_handler_new(), and on_connect().
{
  (void)error;
  switch (status) {
    case SOCKET_CONN_CLOSED: {
      Client* self = (Client*)handle;
      if (self->recv_event != NULL) {
        socket_close (source->socket);
        logdebug("socket '%s' closed\n", source->name);
        eventloop_socket_remove (source); // Note:  this free()'s source!
      }
      /* Signal the sender thread for this client that the client disconnected */
      pthread_mutex_lock (&self->mutex);
      self->state = C_DISCONNECTED;
      pthread_cond_signal (&self->condvar);
      pthread_mutex_unlock (&self->mutex);
      break;
    default:
      break;
    }
  }
}
void stdin_handler (SockEvtSource * source, void * handle, void * buf, int buf_size)
Definition at line 218 of file oml2-proxy-server.c.
References _session::clients, _client::condvar, logdebug(), _client::mutex, _client::next, ProxyState_PAUSED, ProxyState_SENDING, ProxyState_STOPPED, and _session::state.
Referenced by main(), and on_control_connect().
{
  Session *proxy = (Session*)handle;
  char command[80];
  (void)source;
  strncpy (command, buf, 80);
  if (buf_size < 80 && command[buf_size-1] == '\n')
    command[buf_size-1] = '\0';
  printf ("Received command: %s\n", command);
  logdebug ("Received command: %s\n", command);
  if ((strcmp (command, "OMLPROXY-RESUME") == 0) ||
      (strcmp (command, "RESUME") == 0)) {
    proxy->state = ProxyState_SENDING;
  } else if (strcmp (command, "OMLPROXY-STOP") == 0 ||
             strcmp (command, "STOP") == 0) {
    proxy->state = ProxyState_STOPPED;
  } else if (strcmp (command, "OMLPROXY-PAUSE") == 0 ||
             strcmp (command, "PAUSE") == 0) {
    proxy->state = ProxyState_PAUSED;
  }
  /*
   * If we're in sending state, wake up the client sender threads
   * so that they will start sending to the downstream server.  We do
   * this even if the state was already ProxyState_SENDING because
   * some of the clients might have dropped back to idle due to
   * disconnection from the upstream server.
   */
  if (session->state == ProxyState_SENDING) {
    Client *current = session->clients;
    while (current) {
      pthread_mutex_lock (&current->mutex);
      pthread_cond_signal (&current->condvar);
      pthread_mutex_unlock (&current->mutex);
      current = current->next;
    }
  }
}
Variable Documentation
struct poptOption options[]
Initial value:
 {
  POPT_AUTOHELP
  { "listen",      'l',  POPT_ARG_STRING, &listen_service,  0,   "Service to listen for TCP based clients", DEF_PORT_STR},
  { "control",     'c',  POPT_ARG_STRING, &control_service, 0,   "Service to listen for commands",       DEF_CTRL_PORT_STR},
  { "debug-level", 'd',  POPT_ARG_INT,    &log_level,       0,   "Debug level - error:1 .. debug:4",     NULL},
  { "logfile",     '\0', POPT_ARG_STRING, &logfile_name,    0,   "File to log to",                       DEFAULT_LOG_FILE },
  { "version",     'v',  POPT_ARG_NONE,   NULL,             'v', "Print version information and exit",   NULL},
  { "resultfile",  'r',  POPT_ARG_STRING, &resultfile_name, 0,   "File name for storing received data",  DEFAULT_RESULT_FILE},
  { "size",        's',  POPT_ARG_INT,    &page_size,       0,   "Page size for buffering measurements", NULL},
  { "dstport",     'p',  POPT_ARG_INT,    &downstream_port, 0,   "Downstream OML server port",       NULL},
  { "dstaddress",  'a',  POPT_ARG_STRING, &downstream_address,  0,   "Downstream OML server address",    DEFAULT_SERVER_ADDRESS },
  { NULL,          0,    0,               NULL,             0,   NULL,                                   NULL }
}
Definition at line 57 of file oml2-proxy-server.c.
Referenced by main().
Session* session = NULL
Definition at line 53 of file oml2-proxy-server.c.
Referenced by client_send_thread(), and on_connect().
int sigpipe_flag = 0
Definition at line 51 of file oml2-proxy-server.c.
Referenced by client_send_thread(), and sigpipe_handler().