oml2: oml2-server.c File Reference
oml2-server.c File Reference
Main oml2-server functions.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <pwd.h>
#include <grp.h>
#include <popt.h>
#include <signal.h>
#include <errno.h>
#include "oml2/omlc.h"
#include "oml2/oml_writer.h"
#include "ocomm/o_log.h"
#include "ocomm/o_socket.h"
#include "ocomm/o_eventloop.h"
#include "mem.h"
#include "oml_util.h"
#include "hook.h"
#include "client_handler.h"
#include "database.h"
#include "sqlite_adapter.h"
#include "monitoring_server.h"
#include "fuseki_adapter.h"
#include "virtuoso_adapter.h"
Macros
#define V_STRING "OML Server %s\n"
#define V_STRING_UAM "Semantic-OML Server %s\n"
#define COPYRIGHT "Copyright 2007-2014 NICTA\n"
#define COPYRIGHT_UAM "Copyright 2007-2014 NICTA & 2012-2014 UAM\n"
#define DEFAULT_PORT 3003
#define DEFAULT_PORT_STR "3003"
#define DEFAULT_LOG_FILE "oml_server.log"
Typedefs
typedef void(* sh_t)(int)
Functions
void die (const char *fmt,...)
int main (int argc, const char **argv)
Variables
char * dbbackend
char * sqlite_database_dir
char * fus_host
char * fus_port
char * fus_namespace
char * vir_host
char * vir_port
char * vir_user
char * vir_pass
struct poptOption options []
Detailed Description
Main oml2-server functions.
Definition in file oml2-server.c.
Macro Definition Documentation
#define COPYRIGHT "Copyright 2007-2014 NICTA\n"
Definition at line 56 of file oml2-server.c.
Referenced by main().
#define COPYRIGHT_UAM "Copyright 2007-2014 NICTA & 2012-2014 UAM\n"
Definition at line 57 of file oml2-server.c.
Referenced by main().
#define DEFAULT_LOG_FILE "oml_server.log"
Definition at line 86 of file oml2-server.c.
#define DEFAULT_PORT 3003
Definition at line 84 of file oml2-server.c.
#define DEFAULT_PORT_STR "3003"
Definition at line 85 of file oml2-server.c.
#define V_STRING "OML Server %s\n"
Definition at line 53 of file oml2-server.c.
Referenced by main().
#define V_STRING_UAM "Semantic-OML Server %s\n"
Definition at line 54 of file oml2-server.c.
Referenced by main().
Typedef Documentation
typedef void(* sh_t)(int)
XXX: Type of a signal handler, as I'm not sure __sighandler_t from <signal.h> is portable
Definition at line 195 of file oml2-server.c.
Function Documentation
void die (const char * fmt, ...)
Die showing an error message A newline is appended to the message.
Parameters
fmt format string
... arguments for fmt
Definition at line 71 of file oml2-server.c.
References logerror().
Referenced by main().
{
  char buf[1024]; /* This should be plenty... */
  va_list va;
  va_start (va, fmt);
  vsnprintf(buf, sizeof(buf), fmt, va);
  va_end (va);
  logerror("%s\n", buf);
  exit (EXIT_FAILURE);
}
int main (int argc, const char ** argv)
Definition at line 292 of file oml2-server.c.
References COPYRIGHT, COPYRIGHT_UAM, database_setup_backend(), dbbackend, die(), eventloop_init(), eventloop_run(), eventloop_set_socket_timeout(), fus_host, fus_namespace, fus_port, hook_cleanup(), hook_setup(), loginfo(), MAX_PROTOCOL_VERSION, MIN_PROTOCOL_VERSION, O_LOG_INFO, oml_cleanup(), oml_memreport(), oml_setup(), on_connect(), options, pg_conninfo, pg_pass, socket_server_new(), V_STRING, V_STRING_UAM, VERSION, vir_host, vir_pass, vir_port, and vir_user.
{
  int c;
#ifdef HAVE_LIBPQ
  char *pass_replace = "--pg-pass=WITHHELD", *conninfo_replace = "--pg-connect=WITHHELD";
#endif
  char *vir_pass_replace = "--vir-pass=WITHHELD";
  char semantic = 0;
  oml_setup(&argc, argv);
  poptContext optCon = poptGetContext(NULL, argc, (const char**) argv, options, 0);
  while ((c = poptGetNextOpt(optCon)) >= 0) {
    switch (c) {
    case 'v':
      printf(V_STRING, VERSION);
      printf("OML Protocol V%d--%d\n", MIN_PROTOCOL_VERSION, MAX_PROTOCOL_VERSION);
      printf(COPYRIGHT);
      return 0;
    }
  }
#ifdef HAVE_LIBPQ
  /* Cleanup command line to avoid showing credentials in ps(1) output, amongst
   * others.
   *
   * XXX: This is a poor man's security measure, as this creates a race
   * condition where, prior to doing the following, the credentials are still
   * visible to everybody.
   */
  if (pg_pass || pg_conninfo) {
    for(c=1; c<argc; c++) {
      if(pg_pass && !strncmp(argv[c],"--pg-pass", 9)) {
        argv[c] = pass_replace;
      }
      if(pg_conninfo && !strncmp(argv[c],"--pg-connect", 12)) {
        argv[c] = conninfo_replace;
      }
    }
  }
  for(c=1; c<argc; c++) {
      if (vir_user && !strncmp(argv[c],"--vir-user", 10))
        semantic = 1;
      else if (vir_pass && !strncmp(argv[c],"--vir-pass", 10))
      {
        argv[c] = conninfo_replace;
        semantic = 1;
      }
      else if (vir_host && !strncmp(argv[c],"--vir-host", 10))
        semantic = 1;
      else if (vir_port && !strncmp(argv[c],"--vir-port", 10))
        semantic = 1;
      else if (fus_host && !strncmp(argv[c],"--fus-host", 10))
        semantic = 1;
      else if (fus_port && !strncmp(argv[c],"--fus-port", 10))
        semantic = 1;
      else if (fus_namespace && !strncmp(argv[c],"--fus-namespace", 15))
        semantic = 1;
  }
#endif /* HAVE_LIBPQ */
  logging_setup (logfile_name, log_level);
  if (c < -1) {
    die ("%s: %s\n", poptBadOption (optCon, POPT_BADOPTION_NOALIAS), poptStrerror (c));
  }
  if (semantic)
  {
    loginfo(V_STRING_UAM, VERSION);
    loginfo("Semantic-OML Protocol V%d--%d\n", MIN_PROTOCOL_VERSION, MAX_PROTOCOL_VERSION);
    loginfo(COPYRIGHT_UAM);
  }
  else
  {
    loginfo(V_STRING, VERSION);
    loginfo("OML Protocol V%d--%d\n", MIN_PROTOCOL_VERSION, MAX_PROTOCOL_VERSION);
    loginfo(COPYRIGHT);
  }
  eventloop_init();
  eventloop_set_socket_timeout(socket_timeout);
  Socket* server_sock;
  server_sock = socket_server_new("server", NULL, listen_service, on_connect, NULL);
  if (!server_sock) {
    die ("Failed to create listening socket for service %s\n", listen_service);
  }
  drop_privileges (uidstr, gidstr);
  /* Important that this comes after drop_privileges(). */
  if(database_setup_backend(dbbackend)) {
      die("Failed to setup database backend '%s'\n", dbbackend);
  }
  signal_setup();
  hook_setup();
  eventloop_run();
  signal_cleanup();
  hook_cleanup();
  oml_cleanup();
  oml_memreport(O_LOG_INFO);
  return 0;
}
Variable Documentation
char* dbbackend
Definition at line 93 of file database.c.
char* fus_host
Definition at line 110 of file fuseki_adapter-new-yahya.c.
Referenced by fuseki_create_database(), and main().
char* fus_namespace
Definition at line 112 of file fuseki_adapter-new-yahya.c.
Referenced by fuseki_create_database(), and main().
char* fus_port
Definition at line 111 of file fuseki_adapter-new-yahya.c.
Referenced by fuseki_create_database(), and main().
struct poptOption options[]
Initial value:
 {
  POPT_AUTOHELP
  { "listen", 'l', POPT_ARG_STRING, &listen_service, 0, "Service to listen for TCP based clients", DEFAULT_PORT_STR},
  { "backend", 'b', POPT_ARG_STRING, &dbbackend, 0, "Database server backend", DEFAULT_DB_BACKEND},
  { "data-dir", 'D', POPT_ARG_STRING, &sqlite_database_dir, 0, "Directory to store database files (sqlite)", "DIR" },
  { "fus-host", '\0', POPT_ARG_STRING, &fus_host, 0, "Fuseki server host to connect to", DEFAULT_FUS_HOST },
  { "fus-port", '\0', POPT_ARG_STRING, &fus_port, 0, "Fuseki server port to connect to", DEFAULT_FUS_PORT },
  { "fus-namespace", '\0', POPT_ARG_STRING, &fus_namespace, 0, "Fuseki server namespace", DEFAULT_FUS_NAMESPACE },
  { "vir-user", '\0', POPT_ARG_STRING, &vir_user, 0, "Virtuoso server user to connect to", DEFAULT_VIR_USER },
  { "vir-pass", '\0', POPT_ARG_STRING, &vir_pass, 0, "Virtuoso server pass to connect to", DEFAULT_VIR_PASS },
  { "vir-host", '\0', POPT_ARG_STRING, &vir_host, 0, "Database server host to connect to", DEFAULT_VIR_HOST },
  { "vir-port", '\0', POPT_ARG_STRING, &vir_port, 0, "Database server port to connect to", DEFAULT_VIR_PORT },
  { "user", '\0', POPT_ARG_STRING, &uidstr, 0, "Change server's user id", "UID" },
  { "group", '\0', POPT_ARG_STRING, &gidstr, 0, "Change server's group id", "GID" },
  { "event-hook", 'H', POPT_ARG_STRING, &hook, 0, "Path to an event hook taking input on stdin", "HOOK" },
  { "timeout", 't', POPT_ARG_INT, &socket_timeout, 0, "Timeout after which idle receiving sockets are cleaned up to avoid resource exhaustion", "60"  },
  { "debug-level", 'd', POPT_ARG_INT, &log_level, 0, "Increase debug level", "{1 .. 4}"  },
  { "logfile", '\0', POPT_ARG_STRING, &logfile_name, 0, "File to log to", DEFAULT_LOG_FILE },
  { "version", 'v', POPT_ARG_NONE, NULL, 'v', "Print version information and exit", NULL },
  { NULL, 0, 0, NULL, 0, NULL, NULL }
}
Definition at line 112 of file oml2-server.c.
char* sqlite_database_dir
Definition at line 40 of file sqlite_adapter.c.
Referenced by binary_protocol_suite(), sq3_backend_setup(), sq3_create_database(), sq3_dbdir_setup(), and text_protocol_suite().
char* vir_host
Definition at line 104 of file virtuoso_adapter.c.
Referenced by main(), and virtuoso_create_database().
char* vir_pass
Definition at line 107 of file virtuoso_adapter.c.
Referenced by main(), and virtuoso_create_database().
char* vir_port
Definition at line 105 of file virtuoso_adapter.c.
Referenced by main(), and virtuoso_create_database().
char* vir_user
Definition at line 106 of file virtuoso_adapter.c.
Referenced by main(), and virtuoso_create_database().