oml2: oml_writer.h File Reference
oml_writer.h File Reference
Abstract interface for writers.
#include <oml2/omlc.h>
Data Structures
struct OmlWriter
Macros
#define OML_PROTOCOL_VERSION 5
Typedefs
typedef struct BufferedWriter BufferedWriter
typedef int(* oml_writer_meta)(struct OmlWriter *writer, char *string)
typedef int(* oml_writer_header_done)(struct OmlWriter *writer)
typedef int(* oml_writer_row_start)(struct OmlWriter *writer, OmlMStream *ms, double now)
typedef int(* oml_writer_row_end)(struct OmlWriter *writer, OmlMStream *ms)
typedef int(* oml_writer_out)(struct OmlWriter *writer, OmlValue *values, int values_count)
typedef struct OmlWriter *(* oml_writer_close)(struct OmlWriter *writer)
typedef struct OmlWriter OmlWriter
Enumerations
enum StreamEncoding { SE_None, SE_Text, SE_Binary }
Functions
OmlWriter * create_writer (const char *uri, enum StreamEncoding encoding)
Detailed Description
Abstract interface for writers.
A writer is in charge of serialising the OML samples (using either the text or binary protocol OMSP Binary Marshalling), and outputting them somewhere (network or file).
See Also
OmlTextWriter, OmlBinWriter
Definition in file oml_writer.h.
Macro Definition Documentation
#define OML_PROTOCOL_VERSION 5
The OMSP version that this library speaks.
This also defines the highest protocol revision that the oml2-server built along can understand.
Definition at line 30 of file oml_writer.h.
Referenced by omlc_init().
Typedef Documentation
typedef struct BufferedWriter BufferedWriter
Definition at line 33 of file oml_writer.h.
typedef struct OmlWriter*(* oml_writer_close)(struct OmlWriter *writer)
Function called to close the writer and free its allocated objects.
This function is designed so it can be used in a while loop to clean up the entire linked list:
while((w=w->close(w)));
Parameters
writer pointer to the writer to close and destroy
Returns
a pointer to the next writer in the list (writer->next, which can be NULL)
Definition at line 95 of file oml_writer.h.
typedef int(* oml_writer_header_done)(struct OmlWriter *writer)
Function called to finalise meta header
This function should essentially add the 'content: [binary|text]' line to the already written headers
Parameters
writer pointer to OmlWriter instance
Returns
1 on success, 0 on error
See Also
oml_writer_meta
Definition at line 52 of file oml_writer.h.
typedef int(* oml_writer_meta)(struct OmlWriter *writer, char *string)
Function called whenever some header metadata needs to be added.
Parameters
writer pointer to OmlWriter instance
string character string to add to headers
Returns
1 on success, 0 on error
Definition at line 40 of file oml_writer.h.
typedef int(* oml_writer_out)(struct OmlWriter *writer, OmlValue *values, int values_count)
Function called for every result value in a measurement tuple (sample)
Parameters
writer pointer to OmlWriter instance
values array of OmlValue to write out
values_count size of the values array
Returns
the number of values written on success, or 0 otherwise
Definition at line 83 of file oml_writer.h.
typedef int(* oml_writer_row_end)(struct OmlWriter *writer, OmlMStream *ms)
Function called after all items in a tuple have been sent
Parameters
writer pointer to OmlWriter instance
ms OmlMStream for which the sample is
Returns
1 on success, 0 on error
See Also
oml_writer_row_start, oml_writer_out
Definition at line 74 of file oml_writer.h.
typedef int(* oml_writer_row_start)(struct OmlWriter *writer, OmlMStream *ms, double now)
Function called to prepare a new sample.
Parameters
writer pointer to OmlWriter instance
ms OmlMStream for which the sample is
now current timestamp
Returns
1 on success, 0 on error
See Also
oml_writer_out, oml_writer_row_end
Definition at line 64 of file oml_writer.h.
typedef struct OmlWriter OmlWriter
An instance of an OML Writer
Enumeration Type Documentation
enum StreamEncoding
Stream encoding type, for use with create_writer
Enumerator:
SE_None
SE_Text
SE_Binary
Definition at line 125 of file oml_writer.h.
                    {
  SE_None, // Not explicitly specified by the user
  SE_Text,
  SE_Binary
};
Function Documentation
OmlWriter* create_writer (const char * uri, enum StreamEncoding encoding)
Create either a file writer or a network writer
Parameters
uri collection URI
encoding StreamEncoding to use for the output, either SE_Text or SE_Binary
Returns
a pointer to the new OmlWriter, or NULL on error
Definition at line 741 of file init.c.
References bin_writer_new(), DEF_PORT_STRING, OmlClient::domain, file_stream_new(), file_stream_set_buffered(), OmlClient::first_writer, logerror(), net_stream_new(), OmlWriter::next, OmlClient::node_name, oml_free(), oml_strndup(), OML_URI_FILE_FLUSH, oml_uri_is_file, oml_uri_type(), parse_uri(), SE_Binary, SE_None, SE_Text, and text_writer_new().
{
  OmlURIType uri_type = oml_uri_type(uri);
  if (omlc_instance == NULL){
    logerror("No omlc_instance:  OML client was not initialized properly.\n");
    return NULL;
  }
  if (uri == NULL || strlen(uri) < 1) {
    logerror ("Missing or invalid collection URI definition (e.g., --oml-collect)\n");
    return NULL;
  }
  if (omlc_instance->node_name == NULL) {
    logerror ("Missing '--oml-id' flag \n");
    return NULL;
  }
  if (omlc_instance->domain == NULL) {
    logerror ("Missing '--oml-domain' flag \n");
    return NULL;
  }
  const char *transport = NULL;
  const char *path = NULL;
  const char *port = NULL;
  if (parse_uri (uri, &transport, &path, &port) == -1) {
    logerror ("Error parsing server destination URI '%s'; failed to create stream for this destination\n",
              uri);
    if (transport) oml_free ((void*)transport);
    if (path) oml_free ((void*)path);
    if (port) oml_free ((void*)port);
    return NULL;
  }
  const char *filepath = NULL;
  const char *hostname = NULL;
  if (oml_uri_is_file(uri_type)) {
    /* 'file://path/to/file' is equivalent to unix path '/path/to/file' */
    if (strncmp (path, "//", 2) == 0)
      filepath = &path[1];
    else
      filepath = path;
  } else if (transport) {
    if (strncmp (path, "//", 2) == 0)
      hostname = &path[2];
    else
      hostname = path;
  } else {
    hostname = path; /* If no transport specified, it must be tcp */
  }
  /* Default transport is tcp if not specified */
  if (!transport) {
    transport = oml_strndup ("tcp", strlen ("tcp"));
  }
  /* If not file transport, use the OML default port if unspecified */
  if (!port && !oml_uri_is_file(uri_type)) {
    port = oml_strndup (DEF_PORT_STRING, strlen (DEF_PORT_STRING));
  }
  OmlOutStream* out_stream;
  if (oml_uri_is_file(uri_type)) {
    out_stream = file_stream_new(filepath);
    if (encoding == SE_None) encoding = SE_Text; /* default encoding */
    if(OML_URI_FILE_FLUSH == uri_type) {
      file_stream_set_buffered(out_stream, 0);
    }
  } else {
    out_stream = net_stream_new(transport, hostname, port);
    if (encoding == SE_None) encoding = SE_Binary; /* default encoding */
  }
  if (out_stream == NULL) {
    logerror ("Failed to create stream for URI %s\n", uri);
    return NULL;
  }
  oml_free ((void*)transport);
  oml_free ((void*)path);
  oml_free ((void*)port);
  // Now create a write on top of the stream
  OmlWriter* writer = NULL;
  switch (encoding) {
  case SE_Text:   writer = text_writer_new (out_stream); break;
  case SE_Binary: writer = bin_writer_new (out_stream); break;
  case SE_None:
    logerror ("No encoding specified (this should never happen -- please report this as an OML bug)\n");
    // should cleanup streams
    return NULL;
  }
  if (writer == NULL) {
    logerror ("Failed to create writer for encoding '%s'.\n", encoding == SE_Binary ? "binary" : "text");
    return NULL;
  }
  writer->next = omlc_instance->first_writer;
  omlc_instance->first_writer = writer;
  return writer;
}