oml2: oml_filter.h File Reference
oml_filter.h File Reference
Abstract interface for filters.
#include <oml2/omlc.h>
#include <oml2/oml_writer.h>
Data Structures
struct OmlFilterDef
struct OmlFilter
Typedefs
typedef void *(* oml_filter_create)(OmlValueT type, OmlValue *result)
typedef int(* oml_filter_set)(struct OmlFilter *filter, const char *name, OmlValue *value)
typedef int(* oml_filter_input)(struct OmlFilter *filter, OmlValue *value)
typedef int(* oml_filter_output)(struct OmlFilter *filter, struct OmlWriter *writer)
typedef int(* oml_filter_newwindow)(struct OmlFilter *filter)
typedef int(* oml_filter_meta)(struct OmlFilter *filter, int index_offset, char **namePtr, OmlValueT *type, OMLSemDef *concepts)
typedef struct OmlFilterDef OmlFilterDef
typedef struct OmlFilter OmlFilter
Functions
int omlf_register_filter (const char *filter_name, oml_filter_create create, oml_filter_set set, oml_filter_input input, oml_filter_output output, oml_filter_newwindow newwindow, oml_filter_meta meta, OmlFilterDef *filter_def)
Detailed Description
Abstract interface for filters.
Definition in file oml_filter.h.
Typedef Documentation
typedef void*(* oml_filter_create)(OmlValueT type, OmlValue *result)
Filter instance creation function.
If this filter needs to dynamically allocate instance date, this instance MUST be allocated using oml_malloc().
Parameters
type OmlValueT of the sample stream that this instance will process
result pointer to a vector of OmlValue (of size output_count) where the oml_filter_output() will write
Returns
oml_malloc()ed instance data
See Also
OmlFilter, oml_filter_output, oml_malloc
Definition at line 35 of file oml_filter.h.
typedef int(* oml_filter_input)(struct OmlFilter *filter, OmlValue *value)
Function called whenever a new sample is to be delivered to the filter.
Parameters
filter pointer to OmlFilter instance
value new sample, as a pointer to an OmlValue
Returns
0 on success, -1 otherwise
Definition at line 52 of file oml_filter.h.
typedef int(* oml_filter_meta)(struct OmlFilter *filter, int index_offset, char **namePtr, OmlValueT *type, OMLSemDef *concepts)
Optional function returning metainformation for complex outputs.
XXX: This function will probably go at some point soon. Don't use it.
If a filter returns more than one output value, of possibly different types, they each need to be named and properly typed. This function allows to query information about a specific output, identified by its index. It is however preferable to do so through the filter_def argument of the omlf_register_filter() function.
Parameters
filter pointer to OmlFilter instance
index_offset index in result array to query for meta information
[out] namePtr name of the output value at index index_offset (XXX: must be statically allocated)
[out] type OmlTypeT of the output value at index index_offset
[out] semantic definition of the filter
Returns
0 on success, -1 otherwise
See Also
omlf_register_filter, OmlFilterDef
Definition at line 90 of file oml_filter.h.
typedef int(* oml_filter_newwindow)(struct OmlFilter *filter)
Function called whenever aggregated output has been written to all writers, and can then be cleared.
Parameters
filter pointer to OmlFilter instance
Returns
0 on success, -1 otherwise
Definition at line 70 of file oml_filter.h.
typedef int(* oml_filter_output)(struct OmlFilter *filter, struct OmlWriter *writer)
Function called whenever aggregated output is requested from the filter. some function over the samples received since the last call.
Parameters
filter pointer to OmlFilter instance
writer pointor to an OmlWriter in charge of outputting the aggregated sample
Returns
0 on success, -1 otherwise
Definition at line 62 of file oml_filter.h.
typedef int(* oml_filter_set)(struct OmlFilter *filter, const char *name, OmlValue *value)
Optional unction to set filter parameters at runtime.
Parameters
filter pointer to OmlFilter instance
name name of the parameter
value new value of the parameter, as a pointer to an OmlValue
Returns
0 on success, -1 otherwise
Definition at line 44 of file oml_filter.h.
typedef struct OmlFilter OmlFilter
Definition of a filter instance.
A filter is defined by its output schema and its methods.
See Also
OmlFilterDef, oml_filter_create, oml_filter_set, oml_filter_input, oml_filter_output
typedef struct OmlFilterDef OmlFilterDef
Definition of a filter's output element.
Function Documentation
int omlf_register_filter (const char * filter_name, oml_filter_create create, oml_filter_set set, oml_filter_input input, oml_filter_output output, oml_filter_newwindow newwindow, oml_filter_meta meta, OmlFilterDef * filter_def)
Register a new filter type.
The filter type is created with the supplied oml_filter_create(), oml_filter_set(), oml_filter_input(), oml_filter_output() functions. Its output conforms to the filter_def, if supplied, or oml_filter_meta() otherwise.
If meta is NULL, the default meta function is used for instances of this filter, which inspects the filter_def to provide the filter meta information.
If filter_def is NULL, then meta must not be NULL; the meta function must be supplied to provide the filter meta information (for schema output).
If the set parameter is NULL, then a default no-op set function is supplied for instances of this filter type.
Parameters
filter_name string describing this type of filter, for use in create_filter()
create oml_filter_create() function which should initialize instance data
set oml_filter_set() function which allows parameter setting (can be NULL)
input oml_filter_input() function which adds new input samples to be filtered
output oml_filter_output() function which puts a filtered result in the result vector
newwindow oml_filter_newwindow() output function which is used to start a new sampling window
meta oml_filter_meta() output function which is used to define the output schema (can be NULL is filter_def is not)
filter_def output spec (name and type of each element of the output n-tuple; can be NULL if meta is not)
See Also
oml_filter_create, oml_filter_set, oml_filter_input, oml_filter_output, oml_filter_meta, OmlFilterDef
Register an instance of a filter of type filter_name.
Definition at line 210 of file factory.c.
References FilterType::create, FilterType::definition, FilterType::input, input, logerror(), FilterType::meta, FilterType::name, OmlFilterDef::name, FilterType::newwindow, FilterType::next, oml_malloc(), FilterType::output, FilterType::output_count, FilterType::set, and OmlFilterDef::type.
Referenced by omlf_register_filter_average(), omlf_register_filter_delta(), omlf_register_filter_first(), omlf_register_filter_histogram(), omlf_register_filter_last(), omlf_register_filter_stddev(), and omlf_register_filter_sum().
{
  if (create == NULL || input == NULL || output == NULL) {
    logerror ("Filter %s needs a create function, an input function, and an output function (one of them was null).\n", filter_name);
    return -1;
  }
  if (filter_def == NULL) {
    logerror ("Filter %s needs a filter definition (got a null definition).\n", filter_name);
    return -1;
  }
  FilterType* ft = (FilterType*)oml_malloc(sizeof(FilterType));
  ft->name = filter_name;
  ft->create = create;
  ft->set = set;
  ft->input = input;
  ft->output = output;
  ft->newwindow = newwindow;
  ft->output_count = 0;
  OmlFilterDef* dp = filter_def;
  for (; !(dp->name == NULL && dp->type == 0); dp++)
    ft->output_count++;
  ft->definition = copy_filter_definition (filter_def, ft->output_count);
  if (set == NULL)
      ft->set = default_filter_set;
  if (meta == NULL)
    ft->meta = default_filter_meta;
  else
    ft->meta = meta;
  ft->next = filter_types;
  filter_types = ft;
  return 0;
}