oml2: oml_util.c File Reference
oml_util.c File Reference
Various utility functions, mainly strings and memory-buffer related.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <netdb.h>
#include "ocomm/o_log.h"
#include "mem.h"
#include "oml_util.h"
Macros
#define find_matching(p, cond, len)
#define trydup(i) (parts[(i)] && lengths[(i)]>0 ? oml_strndup (parts[(i)], lengths[(i)]) : NULL)
Functions
void chomp (char *str)
const char * skip_white (const char *p)
const char * find_white (const char *p)
const char * find_charn (const char *str, char c, int len)
char * to_octets (unsigned char *buf, int len)
int resolve_service (const char *service, int defport)
OmlURIType oml_uri_type (const char *uri)
int parse_uri (const char *uri, const char **protocol, const char **path, const char **port)
Detailed Description
Various utility functions, mainly strings and memory-buffer related.
Definition in file oml_util.c.
Macro Definition Documentation
#define find_matching (p, cond, len)
Value:
do {                                 \
  while (len-- && *p && !(cond)) {  \
    p++;                             \
  }                                  \
} while(0)
Template code to search for a matching condition in a string or array up to a given length or nil-terminator.
p should be of a dereferenceable type that can be compared to 0.
If len is negative, this allows for a very long string to be parsed. Very long here being entirely machine dependent, one should not really rely on this...
Parameters
[in,out] p pointer to the beginning of the string or array; updated to the matching element, or the end of the search area if not found
cond success condition involving p
[in,out] len maximum length to search for; updated to the remaining number of characters when finishing (-1 if not found)
Definition at line 48 of file oml_util.c.
Referenced by find_charn(), find_white(), and skip_white().
#define trydup (i) (parts[(i)] && lengths[(i)]>0 ? oml_strndup (parts[(i)], lengths[(i)]) : NULL)
Referenced by parse_uri().
Function Documentation
void chomp (char * str)
Remove trailing space from a string
Parameters
[in,out] str nil-terminated string to chomp, with the first trailing space replaced by '\0'
Definition at line 26 of file oml_util.c.
{
  char *p = str + strlen (str);
  while (p != str && isspace (*--p));
  *++p = '\0';
}
const char* find_charn (const char * str, char c, int len)
Find the first occurence of a character in a string up to a nul character or a given number of characters, whichever comes first,
Parameters
str a possibly nul-terminated string
c the character to look for
len the maximum length to search the string for
Returns
a pointer to character c in str, or NULL
Definition at line 89 of file oml_util.c.
References find_matching, and str.
Referenced by schema_field_from_meta(), and START_TEST().
{
  find_matching(str, (*str == c), len);
  if (len<0 || !*str) {
    return NULL;
  }
  return str;
}
const char* find_white (const char * p)
Find first whitespace in a string
Parameters
p string to search for whitespace in
Returns
a pointer to the first whitespace character of the string, which might be the end of the string
See Also
isspace(3)
Definition at line 74 of file oml_util.c.
References find_matching.
Referenced by header_from_string(), schema_from_meta(), schema_from_sql(), and START_TEST().
{
  int l = -1;
  find_matching(p, (isspace (*p)), l);
  return p;
}
OmlURIType oml_uri_type (const char * uri)
Parse the scheme of na URI and return its type as an +OmlURIType+
Parameters
[in] uri the URI to parse
Returns
an +OmlURIType+ indicating the type of the URI
Definition at line 202 of file oml_util.c.
References OML_URI_FILE, OML_URI_FILE_FLUSH, OML_URI_TCP, OML_URI_UDP, and OML_URI_UNKNOWN.
Referenced by create_writer(), parse_uri(), and START_TEST().
{
  int len = strlen(uri);
  if(len>5 && !strncmp(uri, "flush", 5))
    return OML_URI_FILE_FLUSH;
  else if(len>4 && !strncmp(uri, "file", 4))
    return OML_URI_FILE;
  else if(len>3 && !strncmp(uri, "tcp", 3))
      return OML_URI_TCP;
  else if(len>3 && !strncmp(uri, "udp", 3))
      return OML_URI_UDP;
  return OML_URI_UNKNOWN;
}
int parse_uri (const char * uri, const char ** protocol, const char ** path, const char ** port)
Parse a collection URI of the form [proto:]path[:service].
path can be a hostname, an IPv4 address or an IPv6 address within brackets if proto is a network protocol. service is invalid if proto indicates a local file.
Parameters
uri string containing the URI to parse
protocol pointer to be updated to a string containing the selected protocol, to be oml_free()'d by the caller
path pointer to be updated to a string containing the node name or address, to be oml_free()'d by the caller
service pointer to be updated to a string containing the service name or port number, to be oml_free()'d by the caller
Returns
0 on success, -1 otherwise
See Also
oml_strndup, oml_free, oml_uri_type
Definition at line 231 of file oml_util.c.
References logerror(), logwarn(), oml_free(), oml_strndup(), oml_uri_is_file, oml_uri_is_network, oml_uri_type(), OML_URI_UNKNOWN, and trydup.
Referenced by create_writer(), and START_TEST().
{
  const int MAX_PARTS = 3;
  char *parts[3] = { NULL, NULL, NULL }, *tmp, *orig;
  size_t lengths[3] = { 0, 0, 0 };
  int is_valid = 1;
  int i;
  OmlURIType uri_type;
  if (uri) {
    uri_type = oml_uri_type(uri);
    orig = parts[2] = oml_strndup (uri, strlen (uri));
    parts[0] = strsep(&parts[2], "[");
    if (parts[2]) {
      i = 0;
      if (*parts[i] != '\0') {
        /* there was something before the brackets, clean it some more */
        tmp = parts[i];
        parts[i] = strsep(&tmp, ":");
        lengths[i] = parts[i] ? strlen (parts[i]) : 0;
        i++;
      }
      parts[i] = strsep(&parts[2], "]");
      lengths[i] = parts[i] ? strlen (parts[i]) : 0;
      i++;
      parts[i] = parts[2];
      tmp = strsep(&parts[i], ":");
      lengths[i] = parts[i] ? strlen (parts[i]) : 0;
    } else {
      /* restart the parsing */
      parts[2] = parts[0];
      i = 0;
      parts[i] = strsep(&parts[2], ":");
      lengths[i] = parts[i] ? strlen (parts[i]) : 0;
      i++;
      parts[i] = strsep(&parts[2], ":");
      lengths[i] = parts[i] ? strlen (parts[i]) : 0;
      i++;
      lengths[i] = parts[i] ? strlen (parts[i]) : 0;
    }
    /* make sure unused items are clearly so */
    for(++i; i<MAX_PARTS; i++) {
      parts[i] = NULL;
      lengths[i] = 0;
    }
#define trydup(i) (parts[(i)] && lengths[(i)]>0 ? oml_strndup (parts[(i)], lengths[(i)]) : NULL)
    *protocol = *path = *port = NULL;
    if (lengths[0] > 0 && lengths[1] > 0) {
      /* Case 1:  "abc:xyz" or "abc:xyz:123" -- if abc is a transport, use it; otherwise, it's a hostname/path */
      if (oml_uri_is_network(uri_type)) {
        *protocol = trydup (0);
        *path = trydup (1);
        *port = trydup (2);
      } else if (oml_uri_is_file(uri_type)) {
        *protocol = trydup (0);
        *path = trydup (1);
        *port = NULL;
      } else {
        *protocol = NULL;
        *path = trydup (0);
        *port = trydup (1);
      }
    } else if (lengths[0] > 0 && lengths[2] > 0) {
      /* Case 2:  "abc::123" -- not valid, as we can't infer a hostname/path */
      logwarn ("Server URI '%s' is invalid as it does not contain a hostname/path\n", uri);
      is_valid = 0;
    } else if (lengths[0] > 0) {
      *protocol = NULL;
      *path = trydup (0);
      *port = NULL;
      /* Look for potential user errors and issue a warning but proceed as normal */
      if (uri_type != OML_URI_UNKNOWN) {
        logwarn ("Server URI with unknown scheme, assuming 'tcp:%s'\n",
                 *path);
      }
    } else {
      logerror ("Server URI '%s' seems to be empty\n", uri);
      is_valid = 0;
    }
#undef trydup
    oml_free (orig);
  }
  if (is_valid)
    return 0;
  else
    return -1;
}
int resolve_service (const char * service, int defport)
Resolve a string containing a service or port into an integer port.
Setting default to an impossible value (say, -1) is sufficient to catch resolving errors;
Parameters
port string containing the textual service name or port
defport default port value to return if resolving fails
Returns
the port number as a host-order integer, or the default value if something failed
See Also
getservbyname(3)
Definition at line 177 of file oml_util.c.
References logwarn().
{
  struct servent *sse;
  char *endptr;
  int portnum = defport, tmpport;
  sse = getservbyname(service, NULL);
  if (sse) {
    portnum = ntohs(sse->s_port);
  } else {
    tmpport = strtol(service, &endptr, 10);
    if (endptr > service)
      portnum = tmpport;
    else
      logwarn("Could not resolve service '%s', defaulting to %d\n", service, portnum);
  }
  return portnum;
}
const char* skip_white (const char * p)
Skip whitespaces in a string
Parameters
p string to skip whitespace out of
Returns
a pointer to the first non-white character of the string, which might be the end of the string
See Also
isspace(3)
Definition at line 61 of file oml_util.c.
References find_matching.
Referenced by header_from_string(), read_mp(), read_mp_def(), schema_from_meta(), schema_from_sql(), and START_TEST().
{
  int l = -1;
  find_matching(p, !(isspace (*p)), l);
  return p;
}
char* to_octets (unsigned char * buf, int len)
Dump the contents of a buffer as a string of hex characters
Parameters
buf array of data to dump
len length of buf
Returns
a character string which needs to be oml_free()'d
See Also
oml_malloc, oml_free
Definition at line 106 of file oml_util.c.
References oml_malloc().
{
  const int octet_width = 2;
  const int columns = 16;
  len = (len>0xff)?0xff:len; /* Limit the output to something manageable */
  const int rows = len / columns + 2; /* Integer division plus first line */
  /* Each row has 7 non-data characters (numbers and spaces), one more space, and columns*ASCII characters, plus a '\n' */
  const int rowlength = (octet_width * columns + 7 + 1 + columns + 1);
  const int outlength = rows * rowlength + 1;
  char *out = oml_malloc (outlength);
  char strrep[columns + 1];
  int n = 0, i, col, rw=0;
  strrep[columns] = 0;
  if(out) {
    /* Don't forget nil-terminator in snprintf's size */
    n += snprintf(out, outlength - n, "   0 1 2 3  4 5 6 7   8 9 a b  c d e f  0123456789abcdef\n%2x ", rw++);
    for (i = 0; i < len; i++) {
      col = i % columns;
      if (i == 0) {
        while(0); /* Do nothing */
      } else if (col == 0) {
        n += snprintf(&out[n], outlength - n,  " %s\n%2x ", strrep, rw++);
        /* Add some spacing for readability */
      } else if(0 == (col % 8)) {
        n += snprintf(&out[n], outlength - n, "  ");
      } else if (0 == (col % 4)) {
        n += snprintf(&out[n], outlength - n, " ");
      }
      n += snprintf(&out[n], outlength - n, "%02x", (unsigned int)buf[i]);
      if (isprint(buf[i])) {
        strrep[col] = buf[i];
      } else {
        strrep[col] = '.';
      }
    }
    if(col != 0) {
      while(++col<columns) {
        /* Add padding to align ASCII output */
        if (0 == (col % 8)) {
          n += snprintf(&out[n], outlength - n, "    ");
        } else if (0 == (col % 4)) {
          n += snprintf(&out[n], outlength - n, "   ");
        } else {
          n += snprintf(&out[n], outlength - n, "  ");
        }
      }
      strrep[col] = 0;
      n += snprintf(&out[n], outlength - n, " %s", strrep);
    }
  }
  out[outlength - 1] = 0;
  return out;
}