oml2: oml_value.h File Reference
oml_value.h File Reference
#include <stdint.h>
#include <limits.h>
#include "oml2/omlc.h"
#include "ocomm/o_log.h"
Macros
#define oml_value_get_value(v) ((OmlValueU*)&(v)->value)
#define oml_value_get_type(v) ((OmlValueT)(v)->type)
Functions
int oml_value_set (OmlValue *to, const OmlValueU *value, OmlValueT type)
int oml_value_copy (OmlValueU *value, OmlValueT type, OmlValue *to) __attribute__((deprecated))
void oml_value_init (OmlValue *v)
void oml_value_array_init (OmlValue *v, unsigned int n)
void oml_value_set_type (OmlValue *v, OmlValueT type)
int oml_value_reset (OmlValue *v)
void oml_value_array_reset (OmlValue *v, unsigned int n)
int oml_value_duplicate (OmlValue *dst, OmlValue *src)
const char * oml_type_to_s (OmlValueT type)
OmlValueT oml_type_from_s (const char *s)
char * oml_value_to_s (OmlValue *value, char *buf, size_t size)
int oml_value_from_s (OmlValue *value, const char *value_s)
int oml_value_from_typed_s (OmlValue *value, const char *type_s, const char *value_s)
double oml_value_to_double (OmlValue *value)
int oml_value_to_int (OmlValue *value)
uint8_t oml_value_string_to_bool (const char *value_s)
Macro Definition Documentation
#define oml_value_get_type (v) ((OmlValueT)(v)->type)
Get the type of an OmlValue.
Parameters
v pointer to the OmlValue to manipulate
Returns
the type of the data stored in theOmlValue
Definition at line 60 of file oml_value.h.
Referenced by bin_value_size(), marshal_values(), oml_value_duplicate(), oml_value_from_s(), oml_value_to_double(), oml_value_to_int(), oml_value_to_s(), START_TEST(), unmarshal_typed_value(), and vector_type_check().
#define oml_value_get_value (v) ((OmlValueU*)&(v)->value)
Get the OmlValueU of an OmlValue.
Parameters
v pointer to the OmlValue to manipulate
Returns
a pointer to the OmlValueU contained in v
Definition at line 51 of file oml_value.h.
Referenced by bin_read_msg_start(), bin_value_size(), marshal_values(), oml_value_duplicate(), oml_value_from_s(), oml_value_from_typed_s(), oml_value_set(), oml_value_to_double(), oml_value_to_int(), oml_value_to_s(), START_TEST(), text_read_msg_start(), unmarshal_init(), unmarshal_value(), and vector_values_check().
Function Documentation
OmlValueT oml_type_from_s (const char * s)
Convert string to an OmlValueT type.
Parameters
s string representing the type to get
Returns
the OmlValueT corresponding to the string, or OML_UNKNOWN_VALUE
See Also
oml_value_ut_to_s
type_names
Definition at line 325 of file oml_value.c.
References LENGTH, logwarn(), name, OML_LONG_VALUE, OML_UNKNOWN_VALUE, and type.
Referenced by oml_value_from_typed_s(), read_mp_def(), and schema_field_from_meta().
{
  int i = 0;
  int n = LENGTH(type_names);
  OmlValueT type = OML_UNKNOWN_VALUE;
  if (NULL == s) {
    logwarn("%s(): trying to resolve a NULL type string\n", __FUNCTION__);
  } else {
    for (i = 0; i < n; i++) {
      if (strcmp (s, type_names[i].name) == 0) {
        type = type_names[i].type;
        break;
      }
    }
    if (type == OML_LONG_VALUE) {
      logwarn("%s(): OML_LONG_VALUE is deprecated, please use OML_INT32_VALUE instead\n", __FUNCTION__);
    }
  }
  return type;
}
const char* oml_type_to_s (OmlValueT type)
Get a string representing the given OmlValueT type.
Parameters
type OmlValueT type to get the representation for
Returns
a string that represent the type, or "UNKNOWN"
See Also
oml_value_ut_from_s
type_names
Definition at line 298 of file oml_value.c.
References LENGTH, and name.
Referenced by main(), marshal_value(), schema_to_meta(), START_TEST(), unmarshal_typed_value(), and unmarshal_value().
{
  int i = 0;
  int n = LENGTH(type_names);
  static const char unknown[] = "unknown OML type";
  const char *name = unknown;
  for (i = 0; i < n; i++) {
    if (type_names[i].type == type) {
      name = (const char *)type_names[i].name;
      break;
    }
  }
  return name;
}
void oml_value_array_init (OmlValue * v, unsigned int n)
Initialise arrays of OmlValues.
It is MANDATORY to use this function before any OmlValue setting, otherwise, uninitialised memory might lead to various issues with dynamic allocation.
Parameters
v pointer to the first OmlValue of the array to manipulate
n length of the array
See Also
oml_value_init
Definition at line 97 of file oml_value.c.
Referenced by client_realloc_tables(), client_realloc_values(), oml_value_init(), and START_TEST().
{
  memset(v, 0, n*sizeof(OmlValue));
}
void oml_value_array_reset (OmlValue * v, unsigned int n)
Reset array of OmlValue, cleaning any allocated memory.
Parameters
v pointer to the first OmlValue of the array to manipulate
n length of the array
See Also
oml_value_init
Definition at line 267 of file oml_value.c.
References oml_value_reset().
Referenced by destroy_filter(), and START_TEST().
{
 int i;
 for (i=0; i<n; i++) {
   oml_value_reset(&v[i]);
 }
}
int oml_value_copy (OmlValueU * value, OmlValueT type, OmlValue * to)
DEPRECATED
See Also
oml_value_set
Definition at line 202 of file oml_value.c.
References logwarn(), and oml_value_set().
{
 logwarn("%s() is deprecated, please use oml_value_set(to, value, type) instead\n", __FUNCTION__);
 return oml_value_set(to, value, type);
}
int oml_value_duplicate (OmlValue * dst, OmlValue * src)
Deep copy an OmlValue.
Parameters
dst OmlValue to copy to
src OmlValue to copy
Returns
0 on success, -1 otherwise
See Also
oml_value_init, oml_value_set, oml_value_get_value, oml_value_get_type
Definition at line 283 of file oml_value.c.
References oml_value_get_type, oml_value_get_value, and oml_value_set().
Referenced by START_TEST().
{
  return oml_value_set(dst, oml_value_get_value(src), oml_value_get_type(src));
}
int oml_value_from_s (OmlValue * value, const char * value_s)
Try to convert a string to the current type of OmlValue, and store it there.
Parameters
value pointer to output OmlValue
value_s input string
Returns
0 on success, -1 otherwise
See Also
oml_value_init, oml_value_ut_from_s
Definition at line 470 of file oml_value.c.
References oml_value_get_type, and oml_value_get_value.
{
  return oml_value_ut_from_s(oml_value_get_value(value), oml_value_get_type(value), value_s);
}
int oml_value_from_typed_s (OmlValue * value, const char * type_s, const char * value_s)
Try to convert a string to the type represented by the given string, and store it an OmlValue.
Parameters
value pointer to output OmlValue
type_s string representing an OmlValueT
value_s input string
Returns
0 on success, -1 otherwise
See Also
oml_value_init, oml_value_ut_from_s, oml_type_from_s
Definition at line 484 of file oml_value.c.
References oml_type_from_s(), oml_value_get_value, and oml_value_set_type().
{
  OmlValueT type = oml_type_from_s (type_s);
  oml_value_set_type(value, type);
  return oml_value_ut_from_s(oml_value_get_value(value), type, value_s);
}
void oml_value_init (OmlValue * v)
Initialise one OmlValues.
It is MANDATORY to use this function before any OmlValue setting, otherwise, uninitialised memory might lead to various issues with dynamic allocation.
Parameters
v pointer to the OmlValue to manipulate
See Also
oml_value_array_init
Definition at line 81 of file oml_value.c.
References oml_value_array_init().
Referenced by bin_read_msg_start(), omlc_inject(), run_filter_test(), START_TEST(), text_read_msg_start(), unmarshal_init(), and vector_values_ut_stringify().
{
  oml_value_array_init(v, 1);
}
int oml_value_reset (OmlValue * v)
Reset one OmlValue, cleaning any allocated memory.
The type of the value is also reset (to 0, i.e., OML_DOUBLE_VALUE).
Parameters
v pointer to OmlValue to reset
Returns
0 if successful, -1 otherwise
See Also
oml_value_init, oml_value_array_reset, memset(3)
Definition at line 217 of file oml_value.c.
References logwarn(), OML_BLOB_VALUE, OML_BOOL_VALUE, OML_DATETIME_VALUE, OML_DOUBLE_VALUE, OML_GUID_VALUE, OML_INT32_VALUE, OML_INT64_VALUE, OML_LONG_VALUE, OML_STRING_VALUE, OML_UINT32_VALUE, OML_UINT64_VALUE, OML_VECTOR_BOOL_VALUE, OML_VECTOR_DOUBLE_VALUE, OML_VECTOR_INT32_VALUE, OML_VECTOR_INT64_VALUE, OML_VECTOR_UINT32_VALUE, OML_VECTOR_UINT64_VALUE, omlc_reset_blob, omlc_reset_string, omlc_reset_vector, OmlValue::type, and OmlValue::value.
Referenced by bin_read_msg_start(), client_handler_free(), oml_value_array_reset(), oml_value_set_type(), omlc_inject(), run_filter_test(), START_TEST(), text_read_msg_start(), unmarshal_init(), and vector_values_ut_stringify().
{
  switch(v->type) {
  case OML_LONG_VALUE:
    logwarn("%s(): OML_LONG_VALUE is deprecated, please use OML_INT32_VALUE instead\n", __FUNCTION__);
  case OML_INT32_VALUE:
  case OML_UINT32_VALUE:
  case OML_INT64_VALUE:
  case OML_UINT64_VALUE:
  case OML_DOUBLE_VALUE:
  case OML_GUID_VALUE:
  case OML_BOOL_VALUE:
    /* No deep cleanup needed, memset(3) below is sufficient */
    break;
  case OML_STRING_VALUE:
    omlc_reset_string(v->value);
    break;
  case OML_DATETIME_VALUE:
    omlc_reset_string(v->value);
    break;
  case OML_BLOB_VALUE:
    omlc_reset_blob(v->value);
    break;
  case OML_VECTOR_DOUBLE_VALUE:
  case OML_VECTOR_INT32_VALUE:
  case OML_VECTOR_UINT32_VALUE:
  case OML_VECTOR_INT64_VALUE:
  case OML_VECTOR_UINT64_VALUE:
  case OML_VECTOR_BOOL_VALUE:
    omlc_reset_vector(v->value);
    break;
  default:
    logwarn("%s() for type '%d' not implemented, zeroing storage\n", __FUNCTION__, v->type);
  }
  memset(v, 0, sizeof(OmlValue));
  return 0;
}
int oml_value_set (OmlValue * to, const OmlValueU * value, OmlValueT type)
Assign the content of an OmlValueU of the given OmlValueT to an OmlValue.
This function copies value, which is assumed to be of the given type (no check can be made), into the OmlValue pointed to by to. The to object is set to have the given type. If type is a simple numeric type, the copy simply copies the value.
If type is OML_STRING_VALUE, then the string contents are copied into new storage in to. If to was previously set to be a const string, then the is_const flag is cleared and a new block of memory is allocated to store the copy and its terminating null character. If to did not previously have the is_const flag set, and its string pointer was NULL, then a new block of memory is also allocated as well. If the string pointer was not NULL, then the string is copied into the previously allocated memory block if it is large enough to fit; otherwise the block is freed and a new one allocated large enough to hold the string (and its terminator).
Blobs are handled in a similar fashion.
If the source pointer is NULL then an error is returned and a warning message is sent to the log.
Parameters
to pointer to OmlValue into which the value should be copied
value pointer to original OmlValueU to copy into to
type OmlValueT of value
Returns
0 if successful, -1 otherwise
See Also
oml_value_init, omlc_copy_string, omlc_copy_blob
Definition at line 146 of file oml_value.c.
References logerror(), logwarn(), OML_BLOB_VALUE, OML_DATETIME_VALUE, OML_STRING_VALUE, oml_value_get_value, oml_value_set_type(), OML_VECTOR_BOOL_VALUE, OML_VECTOR_DOUBLE_VALUE, OML_VECTOR_INT32_VALUE, OML_VECTOR_INT64_VALUE, OML_VECTOR_UINT32_VALUE, OML_VECTOR_UINT64_VALUE, omlc_copy_blob, omlc_copy_string, omlc_copy_vector, omlc_get_blob_ptr, omlc_get_string_ptr, omlc_get_vector_ptr, omlc_is_bool_type, omlc_is_guid_type, omlc_is_numeric_type, and OmlValue::value.
Referenced by oml_value_copy(), oml_value_duplicate(), omlc_inject(), START_TEST(), and vector_values_ut_stringify().
{
  oml_value_set_type(to, type);
  if (omlc_is_numeric_type (type) ||
      omlc_is_guid_type (type) ||
      omlc_is_bool_type (type)) {
    to->value = *value;
  } else {
    switch (type) {
    case OML_STRING_VALUE:
      if (!omlc_get_string_ptr(*value)) {
        logwarn("Trying to copy OML_STRING_VALUE from a NULL source\n");
        return -1;
      }
      omlc_copy_string(*oml_value_get_value(to), *value);
      break;
    case OML_DATETIME_VALUE:
      if (!omlc_get_string_ptr(*value)) {
        logwarn("Trying to copy OML_DATETIME_VALUE from a NULL source\n");
        return -1;
      }
      omlc_copy_string(*oml_value_get_value(to), *value);
      break;
    case OML_BLOB_VALUE:
      if (!omlc_get_blob_ptr(*value)) {
        logwarn("Trying to copy OML_BLOB_VALUE from a NULL source\n");
        return -1;
      }
      omlc_copy_blob(*oml_value_get_value(to), *value);
      break;
    case OML_VECTOR_DOUBLE_VALUE:
    case OML_VECTOR_INT32_VALUE:
    case OML_VECTOR_UINT32_VALUE:
    case OML_VECTOR_INT64_VALUE:
    case OML_VECTOR_UINT64_VALUE:
    case OML_VECTOR_BOOL_VALUE:
      if (!omlc_get_vector_ptr(*value)) {
        logwarn("Trying to copy OML_VECTOR_*_VALUE from a NULL source\n");
        return -1;
      }
      omlc_copy_vector(*oml_value_get_value(to), *value);
      break;
  default:
      logerror("%s() for type '%d' not implemented'\n", __FUNCTION__, type);
      return -1;
    }
  }
  return 0;
}
void oml_value_set_type (OmlValue * v, OmlValueT type)
Set the type of an OmlValue, cleaning up if need be.
Parameters
v pointer to the OmlValue to manipulate
type new type to set
See Also
oml_value_init, oml_value_reset
Definition at line 109 of file oml_value.c.
References oml_value_reset(), type, and OmlValue::type.
Referenced by bin_read_msg_start(), oml_value_from_typed_s(), oml_value_set(), run_filter_test(), START_TEST(), text_read_msg_start(), text_read_msg_values(), and unmarshal_value().
{
  if (v->type != type) {
    oml_value_reset(v);
    v->type = type;
  }
}
uint8_t oml_value_string_to_bool (const char * value_s)
Try to read a string as a boolean
Anything is True except if clearly False (which includes a NULL string).
Partial matches work too: 'f', 'Fa', 'fAl' or 'FAlS' are equivalents to 'false'; longer strings starting with a variation of 'false' are true.
Parameters
value_s string to read as a boolean
Returns
a bool representation suitable for omlc_set_bool
See Also
omlc_set_bool
Definition at line 850 of file oml_value.c.
References logwarn().
Referenced by START_TEST().
{
  if (NULL != value_s) {
    return (uint8_t)(strncasecmp(value_s, "false", strlen(value_s)) != 0);
  }
  logwarn("%s: trying to convert NULL string to bool, assuming false\n", __FUNCTION__);
  return (uint8_t)0;
}
double oml_value_to_double (OmlValue * value)
Cast the data contained in an OmlValue to a double.
Parameters
value pointer to OmlValue containing the data to cast
Returns
a double, which defaults to 0. on error
Definition at line 794 of file oml_value.c.
References logerror(), logwarn(), OML_DOUBLE_VALUE, OML_INT32_VALUE, OML_INT64_VALUE, OML_LONG_VALUE, OML_UINT32_VALUE, OML_UINT64_VALUE, oml_value_get_type, oml_value_get_value, omlc_get_double, omlc_get_int32, omlc_get_int64, omlc_get_long, omlc_get_uint32, and omlc_get_uint64.
{
  OmlValueU *v = oml_value_get_value(value);
  OmlValueT type = oml_value_get_type(value);
  switch (type) {
  case OML_LONG_VALUE:
    logwarn("%s(): OML_LONG_VALUE is deprecated, please use OML_INT32_VALUE instead\n", __FUNCTION__);
    return (double) omlc_get_long(*v);
  case OML_INT32_VALUE:  return (double) omlc_get_int32(*v);
  case OML_UINT32_VALUE: return (double) omlc_get_uint32(*v);
  case OML_INT64_VALUE:  return (double) omlc_get_int64(*v);
  case OML_UINT64_VALUE: return (double) omlc_get_uint64(*v);
  case OML_DOUBLE_VALUE: return (double) omlc_get_double(*v);
  default:
    logerror("%s() for type '%d' not implemented'\n", __FUNCTION__, type);
    return 0.0;
  }
}
int oml_value_to_int (OmlValue * value)
Cast the data contained in an OmlValue to an int.
Parameters
value pointer to OmlValue containing the data to cast
Returns
an integer, which defaults to 0 on error
Definition at line 819 of file oml_value.c.
References logerror(), logwarn(), OML_DOUBLE_VALUE, OML_INT32_VALUE, OML_INT64_VALUE, OML_LONG_VALUE, OML_UINT32_VALUE, OML_UINT64_VALUE, oml_value_get_type, oml_value_get_value, omlc_get_double, omlc_get_int32, omlc_get_int64, omlc_get_long, omlc_get_uint32, and omlc_get_uint64.
{
  OmlValueU *v = oml_value_get_value(value);
  OmlValueT type = oml_value_get_type(value);
  switch (type) {
  case OML_LONG_VALUE:
    logwarn("%s(): OML_LONG_VALUE is deprecated, please use OML_INT32_VALUE instead\n", __FUNCTION__);
    return (int) omlc_get_long(*v);
  case OML_INT32_VALUE:  return (int) omlc_get_int32(*v);
  case OML_UINT32_VALUE: return (int) omlc_get_uint32(*v);
  case OML_INT64_VALUE:  return (int) omlc_get_int64(*v);
  case OML_UINT64_VALUE: return (int) omlc_get_uint64(*v);
  case OML_DOUBLE_VALUE: return (int) omlc_get_double(*v);
  default:
    logerror("%s() for type '%d' not implemented'\n", __FUNCTION__, type);
  return 0;
  }
}
char* oml_value_to_s (OmlValue * value, char * buf, size_t size)
Convert data stored in an OmlValue to a string representation.
The given buffer will contain a nul-terminated C string.
Parameters
value pointer to OmlValue containing data
buf buffer to put the textual representation of the value in
size size of the buffer
Returns
a pointer to buf, or NULL on error
See Also
oml_value_ut_to_s
Definition at line 360 of file oml_value.c.
References oml_value_get_type, oml_value_get_value, and type.
Referenced by START_TEST(), vector_values_stringify(), and vector_values_ut_stringify().
{
  OmlValueU* v = oml_value_get_value(value);
  OmlValueT type = oml_value_get_type(value);
  return oml_value_ut_to_s(v, type, buf, size);
}