oml2: omlc.h File Reference
omlc.h File Reference
Public API of the OML client library.
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <errno.h>
#include <pthread.h>
#include <ocomm/o_log.h>
Data Structures
struct OmlVector
struct OmlString
struct OmlBlob
union OmlValueU
struct OmlValue
struct OMLSemDef
struct OmlMPDef
struct OmlMP
struct OmlMStream
Macros
#define omlc_is_integer_type(t)
#define omlc_is_numeric_type(t)
#define omlc_is_string_type(t) ((t) == OML_STRING_VALUE)
#define omlc_is_blob_type(t) ((t) == OML_BLOB_VALUE)
#define omlc_is_guid_type(t) ((t) == OML_GUID_VALUE)
#define omlc_is_bool_type(t) ((t) == OML_BOOL_VALUE)
#define omlc_is_vector_type(t)
#define omlc_is_scalar_type(t) (!omlc_isvector_type(t))
#define omlc_is_datetime_type(t) ((t) == OML_DATETIME_VALUE)
#define omlc_is_integer(v) omlc_is_integer_type((v).type)
#define omlc_is_numeric(v) omlc_is_numeric_type((v).type)
#define omlc_is_string(v) omlc_is_string_type((v).type)
#define omlc_is_blob(v) omlc_is_blob_type((v).type)
#define omlc_is_guid(v) omlc_is_guid_type((v).type)
#define omlc_is_bool(v) omlc_is_bool_type((v).type)
#define omlc_is_vector(v) omlc_is_vector_type((v).type)
#define omlc_is_datetime(v) omlc_is_datetime_type((v).type)
#define OMLC_GUID_NULL ((oml_guid_t) 0)
#define OMLC_BOOL_FALSE 0
#define OMLC_BOOL_TRUE (!0)
#define omlc_zero(var) memset(&(var), 0, sizeof(OmlValueU))
#define omlc_zero_array(var, n) memset((var), 0, n*sizeof(OmlValueU))
#define _omlc_get_intrinsic_value(var, type) ((var).type ## Value)
#define _omlc_set_intrinsic_value(var, type, val) ((var).type ## Value = (val))
#define omlc_get_int32(var) ((int32_t)(_omlc_get_intrinsic_value(var, int32)))
#define omlc_get_uint32(var) ((uint32_t)(_omlc_get_intrinsic_value(var, uint32)))
#define omlc_get_int64(var) ((int64_t)(_omlc_get_intrinsic_value(var, int64)))
#define omlc_get_uint64(var) ((uint64_t)(_omlc_get_intrinsic_value(var, uint64)))
#define omlc_get_double(var) ((double)(_omlc_get_intrinsic_value(var, double)))
#define omlc_get_long(var) ((long)(_omlc_get_intrinsic_value(var, long)))
#define omlc_get_guid(var) ((oml_guid_t)(_omlc_get_intrinsic_value(var, guid)))
#define omlc_get_bool(var) ((_omlc_get_intrinsic_value(var, bool)) != OMLC_BOOL_FALSE)
#define omlc_get_datetime(var) ((_omlc_get_intrinsic_value(var, datetime)))
#define omlc_set_int32(var, val) _omlc_set_intrinsic_value(var, int32, (int32_t)(val))
#define omlc_set_uint32(var, val) _omlc_set_intrinsic_value(var, uint32, (uint32_t)(val))
#define omlc_set_int64(var, val) _omlc_set_intrinsic_value(var, int64, (int64_t)(val))
#define omlc_set_uint64(var, val) _omlc_set_intrinsic_value(var, int64, (uint64_t)(val))
#define omlc_set_double(var, val) _omlc_set_intrinsic_value(var, double, (double)(val))
#define omlc_set_long(var, val) _omlc_set_intrinsic_value(var, long, (long)(val))
#define omlc_set_guid(var, val) _omlc_set_intrinsic_value(var, guid, (oml_guid_t)(val))
#define omlc_set_bool(var, val) _omlc_set_intrinsic_value(var, bool, (val != OMLC_BOOL_FALSE))
#define _oml_get_storage_field(var, type, field) ((var).type ## Value.field)
#define _oml_set_storage_field(var, type, field, val) ((var).type ## Value.field = (val))
#define omlc_get_string_ptr(var) (_oml_get_storage_field(var, string, ptr))
#define omlc_get_string_length(var) (_oml_get_storage_field(var, string, length))
#define omlc_get_string_size(var) (_oml_get_storage_field(var, string, size))
#define omlc_get_string_is_const(var) (_oml_get_storage_field(var, string, is_const))
#define omlc_set_string_ptr(var, val) _oml_set_storage_field(var, string, ptr, (char*)(val))
#define omlc_set_string_length(var, val) _oml_set_storage_field(var, string, length, (size_t)(val))
#define omlc_set_string_size(var, val) _oml_set_storage_field(var, string, size, (size_t)(val))
#define omlc_set_string_is_const(var, val) _oml_set_storage_field(var, string, is_const, (int)(val))
#define omlc_get_blob_ptr(var) ((void *)_oml_get_storage_field(var, blob, ptr))
#define omlc_get_blob_length(var) (_oml_get_storage_field(var, blob, length))
#define omlc_get_blob_size(var) (_oml_get_storage_field(var, blob, size))
#define omlc_set_blob_ptr(var, val) _oml_set_storage_field(var, blob, ptr, (char*)(val))
#define omlc_set_blob_length(var, val) _oml_set_storage_field(var, blob, length, (size_t)(val))
#define omlc_set_blob_size(var, val) _oml_set_storage_field(var, blob, size, (size_t)(val))
#define _omlc_free_storage(var, type)
#define _omlc_reset_storage(var, type)
#define _omlc_set_storage_copy(var, type, data, len)
#define omlc_free_string(var) _omlc_free_storage((var), string)
#define omlc_reset_string(var)
#define omlc_set_string_copy(var, str, len)
#define omlc_copy_string(dst, src) omlc_set_string_copy((dst), omlc_get_string_ptr(src), omlc_get_string_length(src))
#define omlc_set_string(var, str)
#define omlc_set_datetime(var, str)
#define omlc_set_const_string(var, str)
#define omlc_free_blob(var) _omlc_free_storage((var), blob)
#define omlc_reset_blob(var) _omlc_reset_storage((var), blob)
#define omlc_set_blob(var, val, len) omlc_set_blob_copy(var, val, len)
#define omlc_set_blob_copy(var, val, len) _omlc_set_storage_copy((var), blob, (val), (len))
#define omlc_copy_blob(dst, src) _omlc_set_storage_copy((dst), blob, omlc_get_blob_ptr(src), omlc_get_blob_length(src))
#define omlc_get_vector_ptr(var) (_oml_get_storage_field((var), vector, ptr))
#define omlc_get_vector_length(var) (_oml_get_storage_field((var), vector, length))
#define omlc_get_vector_size(var) (_oml_get_storage_field((var), vector, size))
#define omlc_get_vector_elt_size(var) (_oml_get_storage_field((var), vector, elt_sz))
#define omlc_get_vector_nof_elts(var) (_oml_get_storage_field((var), vector, nof_elts))
#define omlc_set_vector_ptr(var, val) _oml_set_storage_field((var), vector, ptr, (void*)(val))
#define omlc_set_vector_length(var, val) _oml_set_storage_field((var), vector, length, (size_t)(val))
#define omlc_set_vector_size(var, val) _oml_set_storage_field((var), vector, size, (size_t)(val))
#define omlc_set_vector_elt_size(var, val) _oml_set_storage_field((var), vector, elt_sz, (size_t)(val))
#define omlc_set_vector_nof_elts(var, val) (_oml_set_storage_field((var), vector, nof_elts, (uint16_t)(val)))
#define omlc_free_vector(var) _omlc_free_storage((var), vector)
#define omlc_reset_vector(var)
#define _omlc_set_vector_copy(var, data, nof_elts, size)
#define omlc_set_vector_double(var, val, nof_elts) _omlc_set_vector_copy((var), (val), (nof_elts), sizeof(double))
#define omlc_set_vector_long(var, val, nof_elts) _omlc_set_vector_copy((var), (val), (nof_elts), sizeof(long))
#define omlc_set_vector_int32(var, val, nof_elts) _omlc_set_vector_copy((var), (val), (nof_elts), sizeof(int32_t))
#define omlc_set_vector_uint32(var, val, nof_elts) _omlc_set_vector_copy((var), (val), (nof_elts), sizeof(uint32_t))
#define omlc_set_vector_int64(var, val, nof_elts) _omlc_set_vector_copy((var), (val), (nof_elts), sizeof(int64_t))
#define omlc_set_vector_uint64(var, val, nof_elts) _omlc_set_vector_copy((var), (val), (nof_elts), sizeof(uint64_t))
#define omlc_set_vector_bool(var, val, nof_elts) _omlc_set_vector_copy((var), (val), (nof_elts), sizeof(bool))
#define omlc_copy_vector(dst, src) _omlc_set_vector_copy((dst), omlc_get_vector_ptr(src), omlc_get_vector_nof_elts(src), omlc_get_vector_elt_size(src))
#define firstStream streams
#define firstFilter filters
Typedefs
typedef enum OmlValueT OmlValueT
typedef struct OmlVector OmlVector
typedef struct OmlString OmlString
typedef struct OmlBlob OmlBlob
typedef uint64_t oml_guid_t
typedef union OmlValueU OmlValueU
typedef struct OmlValue OmlValue
typedef struct OMLSemDef OMLSemDef
typedef struct OmlMPDef OmlMPDef
typedef struct OmlMP OmlMP
typedef struct OmlMStream OmlMStream
Enumerations
enum OmlValueT {
OML_DB_PRIMARY_KEY = -3, OML_INPUT_VALUE = -2, OML_UNKNOWN_VALUE = -1, OML_DOUBLE_VALUE = 0,
OML_LONG_VALUE, OML_PADDING1_VALUE, OML_STRING_VALUE, OML_INT32_VALUE,
OML_UINT32_VALUE, OML_INT64_VALUE, OML_UINT64_VALUE, OML_BLOB_VALUE,
OML_GUID_VALUE, OML_BOOL_VALUE, OML_DATETIME_VALUE, OML_VECTOR_DOUBLE_VALUE,
OML_VECTOR_INT32_VALUE, OML_VECTOR_UINT32_VALUE, OML_VECTOR_INT64_VALUE, OML_VECTOR_UINT64_VALUE,
OML_VECTOR_BOOL_VALUE, OML_LAST_VALUE
}
Functions
void * oml_malloc (size_t size)
void oml_free (void *ptr)
size_t oml_malloc_usable_size (void *ptr)
int omlc_init (const char *appName, int *argcPtr, const char **argv, o_log_fn oml_log)
OmlMP * omlc_add_mp (const char *mp_name, OmlMPDef *mp_def)
int omlc_start (void)
OMLSemDef * oml_sem_register_concepts (char ***concepts, int n)
int omlc_inject (OmlMP *mp, OmlValueU *values)
int omlc_inject_metadata (OmlMP *mp, const char *key, const OmlValueU *value, OmlValueT type, const char *fname)
oml_guid_t omlc_guid_generate ()
void omlc_process (OmlMP *mp, OmlValueU *values)
int omlc_close (void)
Detailed Description
Public API of the OML client library.
Definition in file omlc.h.
Macro Definition Documentation
#define _oml_get_storage_field (var, type, field) ((var).type ## Value.field)
Get fields of an OmlValueU containing pointer to possibly dynamically allocated storage.
DO NOT USE THIS MACRO DIRECTLY!
It is a helper for specific manipulation macros, which share its behaviour, but have less parameters.
Parameters
var OmlValueU to manipulate
type type of data contained in the OmlValueU
field field to access
Returns
the value of the field
See Also
OmlString, omlc_get_string_ptr, omlc_get_string_length, omlc_get_string_size, omlc_get_string_is_const
OmlBlob, omlc_get_blob_ptr, omlc_get_blob_length, omlc_get_blob_size
Definition at line 318 of file omlc.h.
#define _oml_set_storage_field (var, type, field, val) ((var).type ## Value.field = (val))
Set fields of an OmlValueU containing pointer to possibly dynamically allocated storage.
DO NOT USE THIS MACRO DIRECTLY!
It is a helper for specific manipulation macros, which share its behaviour, but have less parameters.
Parameters
var OmlValueU to manipulate
type type of data contained in the OmlValueU
field field to access
val value to set the field to
Returns
the newly-set value of the field (val)
See Also
OmlString, omlc_set_string_ptr, omlc_set_string_length, omlc_set_string_size, omlc_set_string_is_const
OmlBlob, omlc_set_blob_ptr, omlc_set_blob_length, omlc_set_blob_size
Definition at line 336 of file omlc.h.
#define _omlc_free_storage (var, type)
Value:
do {                                                    \
    if (_oml_get_storage_field((var), type, size) > 0) {  \
      oml_free(_oml_get_storage_field((var), type, ptr));    \
      _oml_set_storage_field((var), type, size, 0);       \
    }                                                     \
  } while(0)
Free the storage contained in an OmlValueU if needed.
Other metadata such as length is not changed, unlike _omlc_reset_storage.
DO NOT USE THIS MACRO DIRECTLY!
It is a helper for specific manipulation macros, which share its behaviour, but have less parameters.
Parameters
var OmlValueU to operate on
type type of data contained in the OmlValueU
See Also
omlc_free_string, omlc_free_blob, oml_free, _omlc_reset_storage
Definition at line 400 of file omlc.h.
#define _omlc_get_intrinsic_value (var, type) ((var).type ## Value)
Get an intrinsic C value from an OmlValueU.
DO NOT USE THIS MACRO DIRECTLY!
It is a helper for specific manipulation macros, which share its behaviour, but have less parameters.
Parameters
var OmlValueU to manipulate
type type of data contained in the OmlValueU
Returns
the value
See Also
omlc_get_int32, omlc_get_uint32, omlc_get_int64, omlc_get_uint64, omlc_get_double, omlc_get_guid, omlc_get_bool
Definition at line 232 of file omlc.h.
#define _omlc_reset_storage (var, type)
Value:
do {                                                    \
    _omlc_free_storage((var), type);                      \
    _oml_set_storage_field((var), type, ptr, NULL);       \
    _oml_set_storage_field((var), type, length, 0);       \
  } while(0)
Reset the contents of an OmlValueU, freeing allocated memory if needed.
DO NOT USE THIS MACRO DIRECTLY!
It is a helper for specific manipulation macros, which share its behaviour, but have less parameters.
Parameters
var OmlValueU to operate on
type type of data contained in the OmlValueU
See Also
omlc_reset_string, omlc_reset_blob, omlc_reset_vector, _omlc_free_storage
Definition at line 419 of file omlc.h.
#define _omlc_set_intrinsic_value (var, type, val) ((var).type ## Value = (val))
Set an intrinsic C value in an OmlValueU.
DO NOT USE THIS MACRO DIRECTLY!
It is a helper for specific manipulation macros, which share its behaviour, but have less parameters.
Parameters
var OmlValueU to manipulate
type type of data contained in the OmlValueU
val value to store in the OmlValueU
Returns
the new value (val)
See Also
omlc_set_int32, omlc_set_uint32, omlc_set_int64, omlc_set_uint64, omlc_set_double, omlc_set_guid, omlc_get_bool
Definition at line 248 of file omlc.h.
#define _omlc_set_storage_copy (var, type, data, len)
Value:
do {                                                                        \
    if (len >= _oml_get_storage_field((var), type, size)) {                   \
      _omlc_reset_storage((var), type);                                       \
      _oml_set_storage_field((var), type, ptr, oml_malloc(len));                 \
      _oml_set_storage_field((var), type, size,                               \
          oml_malloc_usable_size(_oml_get_storage_field((var), type, ptr)));     \
    }                                                                         \
    memcpy(_oml_get_storage_field((var), type, ptr), (void*)(data), (len));   \
    _oml_set_storage_field((var), type, length, (len));                       \
  } while(0)
Copy data into the dedicated storage of an OmlValueU, allocating memory if needed.
DO NOT USE THIS MACRO DIRECTLY!
It is a helper for specific manipulation macros, which share its behaviour, but have less parameters.
Parameters
var OmlValueU to manipulate
type type of data contained in the OmlValueU
str data to copy
len length of the data
See Also
omlc_set_string_copy, omlc_set_blob, oml_malloc
oml_malloc, memcpy(3)
Definition at line 441 of file omlc.h.
#define _omlc_set_vector_copy (var, data, nof_elts, size)
Value:
do {                                                           \
    size_t bytes = (nof_elts) * (size);                          \
    _omlc_set_storage_copy((var), vector, data, bytes);          \
    omlc_set_vector_nof_elts((var), (nof_elts));                 \
    omlc_set_vector_elt_size((var), (size));                     \
  } while(0)
Set an vector into the dedicated storage area of an OmlValueU.
DO NOT USE THIS MACRO DIRECTLY!
It is a helper for specific manipulation macros, which share its behaviour, but have fewer parameters.
Parameters
var The OMLValueU to set.
data Non-null pointer to the base of the vector.
nof_elts The number of elements in the vector.
size The size (in bytes) of each vector element.
Definition at line 610 of file omlc.h.
#define firstFilter filters
Definition at line 750 of file omlc.h.
#define firstStream streams
Definition at line 703 of file omlc.h.
#define OMLC_BOOL_FALSE 0
Definition at line 167 of file omlc.h.
Referenced by START_TEST(), and unmarshal_value().
#define OMLC_BOOL_TRUE (!0)
Definition at line 168 of file omlc.h.
Referenced by START_TEST(), and unmarshal_value().
#define omlc_copy_blob (dst, src) _omlc_set_storage_copy((dst), blob, omlc_get_blob_ptr(src), omlc_get_blob_length(src))
Duplicate an OmlValueU containing a blob, allocating storage for an actual copy of the data.
Allocate (or reuse) a buffer of size len and copy the data
Parameters
dst destination OmlValueU
src source OmlValueU
See Also
_omlc_set_storage_copy
Definition at line 552 of file omlc.h.
Referenced by oml_value_set(), and START_TEST().
#define omlc_copy_string (dst, src) omlc_set_string_copy((dst), omlc_get_string_ptr(src), omlc_get_string_length(src))
Duplicate an OmlValueU containing a string, allocating storage for an actual copy of the C string.
Allocate (or reuse) a buffer of size len+1, copy the string, and nul-terminate it. As the string is actually copied. the destination string is never const, regardless of the source.
Parameters
dst destination OmlValueU
src source OmlValueU
See Also
omlc_set_string_copy
Definition at line 494 of file omlc.h.
Referenced by oml_value_set(), omlc_inject_metadata(), and START_TEST().
#define omlc_copy_vector (dst, src) _omlc_set_vector_copy((dst), omlc_get_vector_ptr(src), omlc_get_vector_nof_elts(src), omlc_get_vector_elt_size(src))
Definition at line 633 of file omlc.h.
Referenced by oml_value_set().
#define omlc_free_blob (var) _omlc_free_storage((var), blob)
See Also
_omlc_free_storage
Definition at line 532 of file omlc.h.
#define omlc_free_string (var) _omlc_free_storage((var), string)
See Also
_omlc_free_storage
Definition at line 454 of file omlc.h.
#define omlc_free_vector (var) _omlc_free_storage((var), vector)
See Also
_omlc_free_storage
Definition at line 588 of file omlc.h.
#define omlc_get_blob_length (var) (_oml_get_storage_field(var, blob, length))
See Also
_oml_get_storage_field
Definition at line 371 of file omlc.h.
Referenced by marshal_value(), and START_TEST().
#define omlc_get_blob_ptr (var) ((void *)_oml_get_storage_field(var, blob, ptr))
See Also
_oml_get_storage_field
Definition at line 368 of file omlc.h.
Referenced by marshal_value(), oml_value_set(), and START_TEST().
#define omlc_get_blob_size (var) (_oml_get_storage_field(var, blob, size))
See Also
_oml_get_storage_field
Definition at line 374 of file omlc.h.
Referenced by START_TEST().
#define omlc_get_bool (var) ((_omlc_get_intrinsic_value(var, bool)) != OMLC_BOOL_FALSE)
See Also
_omlc_get_intrinsic_value
Definition at line 273 of file omlc.h.
Referenced by marshal_value(), START_TEST(), and unmarshal_value().
#define omlc_get_datetime (var) ((_omlc_get_intrinsic_value(var, datetime)))
Definition at line 276 of file omlc.h.
#define omlc_get_double (var) ((double)(_omlc_get_intrinsic_value(var, double)))
See Also
_omlc_get_intrinsic_value
Definition at line 264 of file omlc.h.
Referenced by bin_read_msg_start(), marshal_value(), oml_value_to_double(), oml_value_to_int(), START_TEST(), text_read_msg_start(), unmarshal_init(), unmarshal_value(), and vector_values_check().
#define omlc_get_guid (var) ((oml_guid_t)(_omlc_get_intrinsic_value(var, guid)))
See Also
_omlc_get_intrinsic_value
Definition at line 270 of file omlc.h.
Referenced by marshal_value(), START_TEST(), and unmarshal_value().
#define omlc_get_int32 (var) ((int32_t)(_omlc_get_intrinsic_value(var, int32)))
See Also
_omlc_get_intrinsic_value
Definition at line 252 of file omlc.h.
Referenced by bin_read_msg_start(), oml_value_to_double(), oml_value_to_int(), START_TEST(), unmarshal_init(), unmarshal_value(), and vector_values_check().
#define omlc_get_int64 (var) ((int64_t)(_omlc_get_intrinsic_value(var, int64)))
See Also
_omlc_get_intrinsic_value
Definition at line 258 of file omlc.h.
Referenced by oml_value_to_double(), oml_value_to_int(), START_TEST(), unmarshal_value(), and vector_values_check().
#define omlc_get_long (var) ((long)(_omlc_get_intrinsic_value(var, long)))
DEPRECATED
See Also
omlc_get_uint32, omlc_get_uint64
Definition at line 267 of file omlc.h.
Referenced by marshal_value(), oml_value_to_double(), oml_value_to_int(), and vector_values_check().
#define omlc_get_string_is_const (var) (_oml_get_storage_field(var, string, is_const))
See Also
_oml_get_storage_field
Definition at line 350 of file omlc.h.
Referenced by START_TEST().
#define omlc_get_string_length (var) (_oml_get_storage_field(var, string, length))
Get string length (not including nil-terminator)
See Also
_oml_get_storage_field, strlen(3)
Definition at line 344 of file omlc.h.
Referenced by bin_value_size(), START_TEST(), and vector_values_check().
#define omlc_get_string_ptr (var) (_oml_get_storage_field(var, string, ptr))
See Also
_oml_get_storage_field
Definition at line 340 of file omlc.h.
Referenced by marshal_value(), oml_value_set(), START_TEST(), unmarshal_value(), and vector_values_check().
#define omlc_get_string_size (var) (_oml_get_storage_field(var, string, size))
See Also
_oml_get_storage_field
Definition at line 347 of file omlc.h.
Referenced by START_TEST().
#define omlc_get_uint32 (var) ((uint32_t)(_omlc_get_intrinsic_value(var, uint32)))
See Also
_omlc_get_intrinsic_value
Definition at line 255 of file omlc.h.
Referenced by marshal_value(), oml_value_to_double(), oml_value_to_int(), START_TEST(), text_read_msg_start(), unmarshal_value(), and vector_values_check().
#define omlc_get_uint64 (var) ((uint64_t)(_omlc_get_intrinsic_value(var, uint64)))
See Also
_omlc_get_intrinsic_value
Definition at line 261 of file omlc.h.
Referenced by marshal_value(), oml_value_to_double(), oml_value_to_int(), START_TEST(), unmarshal_value(), and vector_values_check().
#define omlc_get_vector_elt_size (var) (_oml_get_storage_field((var), vector, elt_sz))
See Also
_oml_get_storage_field
Definition at line 565 of file omlc.h.
#define omlc_get_vector_length (var) (_oml_get_storage_field((var), vector, length))
See Also
_oml_get_storage_field
Definition at line 559 of file omlc.h.
#define omlc_get_vector_nof_elts (var) (_oml_get_storage_field((var), vector, nof_elts))
See Also
_oml_get_storage_field
Definition at line 568 of file omlc.h.
Referenced by marshal_value(), and START_TEST().
#define omlc_get_vector_ptr (var) (_oml_get_storage_field((var), vector, ptr))
See Also
_oml_get_storage_field
Definition at line 556 of file omlc.h.
Referenced by marshal_value(), oml_value_set(), and START_TEST().
#define omlc_get_vector_size (var) (_oml_get_storage_field((var), vector, size))
See Also
_oml_get_storage_field
Definition at line 562 of file omlc.h.
#define OMLC_GUID_NULL ((oml_guid_t) 0)
Definition at line 165 of file omlc.h.
Referenced by omlc_guid_generate(), and run().
#define omlc_is_blob (v) omlc_is_blob_type((v).type)
Definition at line 101 of file omlc.h.
#define omlc_is_blob_type (t) ((t) == OML_BLOB_VALUE)
Definition at line 75 of file omlc.h.
#define omlc_is_bool (v) omlc_is_bool_type((v).type)
Definition at line 105 of file omlc.h.
#define omlc_is_bool_type (t) ((t) == OML_BOOL_VALUE)
Definition at line 79 of file omlc.h.
Referenced by oml_value_set().
#define omlc_is_datetime (v) omlc_is_datetime_type((v).type)
Definition at line 110 of file omlc.h.
#define omlc_is_datetime_type (t) ((t) == OML_DATETIME_VALUE)
Definition at line 91 of file omlc.h.
#define omlc_is_guid (v) omlc_is_guid_type((v).type)
Definition at line 103 of file omlc.h.
#define omlc_is_guid_type (t) ((t) == OML_GUID_VALUE)
Definition at line 77 of file omlc.h.
Referenced by oml_value_set().
#define omlc_is_integer (v) omlc_is_integer_type((v).type)
Definition at line 95 of file omlc.h.
#define omlc_is_integer_type (t)
Value:
(((t) == OML_LONG_VALUE) ||                               \
   ((t) == OML_INT32_VALUE) ||                              \
   ((t) == OML_UINT32_VALUE) ||                             \
   ((t) == OML_INT64_VALUE) ||                              \
   ((t) == OML_UINT64_VALUE))
Definition at line 62 of file omlc.h.
#define omlc_is_numeric (v) omlc_is_numeric_type((v).type)
Definition at line 97 of file omlc.h.
#define omlc_is_numeric_type (t)
Value:
((omlc_is_integer_type(t)) ||                             \
   ((t) == OML_DOUBLE_VALUE))
Definition at line 69 of file omlc.h.
Referenced by create_default_filter(), oml_value_set(), omlf_average_new(), omlf_delta_new(), omlf_histogram_new(), omlf_stddev_new(), and omlf_sum_new().
#define omlc_is_scalar_type (t) (!omlc_isvector_type(t))
Definition at line 88 of file omlc.h.
#define omlc_is_string (v) omlc_is_string_type((v).type)
Definition at line 99 of file omlc.h.
#define omlc_is_string_type (t) ((t) == OML_STRING_VALUE)
Definition at line 73 of file omlc.h.
#define omlc_is_vector (v) omlc_is_vector_type((v).type)
Definition at line 107 of file omlc.h.
#define omlc_is_vector_type (t)
Value:
(((t) == OML_VECTOR_DOUBLE_VALUE) ||                       \
   ((t) == OML_VECTOR_INT32_VALUE)  ||                       \
   ((t) == OML_VECTOR_UINT32_VALUE) ||                       \
   ((t) == OML_VECTOR_INT64_VALUE)  ||                       \
   ((t) == OML_VECTOR_UINT64_VALUE) ||                       \
   ((t) == OML_VECTOR_BOOL_VALUE))
Definition at line 81 of file omlc.h.
#define omlc_reset_blob (var) _omlc_reset_storage((var), blob)
See Also
_omlc_reset_storage
Definition at line 535 of file omlc.h.
Referenced by main(), oml_value_reset(), run(), and START_TEST().
#define omlc_reset_string (var)
Value:
do {                                  \
    _omlc_reset_storage((var), string); \
    omlc_set_string_is_const(var, 0);   \
  } while(0)
See Also
_omlc_reset_storage
Definition at line 457 of file omlc.h.
Referenced by main(), oml_value_reset(), omlc_add_mp(), omlc_inject_metadata(), run(), and START_TEST().
#define omlc_reset_vector (var)
Value:
do {                                                           \
    _omlc_reset_storage((var), vector);                          \
    omlc_set_vector_elt_size((var), 0);                          \
    omlc_set_vector_nof_elts((var), 0);                          \
  } while(0);
See Also
_omlc_reset_storage
Definition at line 591 of file omlc.h.
Referenced by oml_value_reset().
#define omlc_set_blob (var, val, len) omlc_set_blob_copy(var, val, len)
Convenience alias to omlc_set_blob_copy
Definition at line 538 of file omlc.h.
Referenced by run(), set_value(), START_TEST(), and unmarshal_value().
#define omlc_set_blob_copy (var, val, len) _omlc_set_storage_copy((var), blob, (val), (len))
See Also
_omlc_set_storage
Definition at line 541 of file omlc.h.
#define omlc_set_blob_length (var, val) _oml_set_storage_field(var, blob, length, (size_t)(val))
See Also
_oml_set_storage_field
Definition at line 381 of file omlc.h.
#define omlc_set_blob_ptr (var, val) _oml_set_storage_field(var, blob, ptr, (char*)(val))
See Also
_oml_set_storage_field
Definition at line 378 of file omlc.h.
#define omlc_set_blob_size (var, val) _oml_set_storage_field(var, blob, size, (size_t)(val))
See Also
_oml_set_storage_field
Definition at line 384 of file omlc.h.
#define omlc_set_bool (var, val) _omlc_set_intrinsic_value(var, bool, (val != OMLC_BOOL_FALSE))
See Also
_omlc_set_intrinsic_value
Definition at line 302 of file omlc.h.
Referenced by START_TEST(), and unmarshal_value().
#define omlc_set_const_string (var, str)
Value:
do {                                                          \
    omlc_free_string(var);                                      \
    omlc_set_string_ptr((var), (char *)(str));                  \
    omlc_set_string_is_const((var), 1);                         \
    omlc_set_string_length((var), ((str)==NULL)?0:strlen(str)); \
  } while (0)
Store a pointer to a constant C string in an OmlValueU's string storage.
Parameters
var OmlValueU to operate on
str constant C-string pointer to use
Definition at line 523 of file omlc.h.
Referenced by START_TEST().
#define omlc_set_datetime (var, str)
Value:
do {                                                          \
  omlc_reset_string(var);                                     \
  omlc_set_string_ptr((var), (str));                          \
  omlc_set_string_length((var), ((str)==NULL)?0:strlen(str)); \
} while (0)
Definition at line 512 of file omlc.h.
#define omlc_set_double (var, val) _omlc_set_intrinsic_value(var, double, (double)(val))
See Also
_omlc_set_intrinsic_value
Definition at line 293 of file omlc.h.
Referenced by main(), make_vector(), marshal_measurements(), set_value(), START_TEST(), and unmarshal_value().
#define omlc_set_guid (var, val) _omlc_set_intrinsic_value(var, guid, (oml_guid_t)(val))
See Also
_omlc_set_intrinsic_value
Definition at line 299 of file omlc.h.
Referenced by START_TEST(), and unmarshal_value().
#define omlc_set_int32 (var, val) _omlc_set_intrinsic_value(var, int32, (int32_t)(val))
See Also
_omlc_set_intrinsic_value
Definition at line 281 of file omlc.h.
Referenced by make_vector(), marshal_measurements(), run(), set_value(), START_TEST(), and unmarshal_value().
#define omlc_set_int64 (var, val) _omlc_set_intrinsic_value(var, int64, (int64_t)(val))
See Also
_omlc_set_intrinsic_value
Definition at line 287 of file omlc.h.
Referenced by make_vector(), set_value(), START_TEST(), and unmarshal_value().
#define omlc_set_long (var, val) _omlc_set_intrinsic_value(var, long, (long)(val))
DEPRECATED
See Also
omlc_set_uint32, omlc_set_uint64
Definition at line 296 of file omlc.h.
Referenced by make_vector(), set_value(), and START_TEST().
#define omlc_set_string (var, str)
Value:
do {                                                          \
    omlc_reset_string(var);                                     \
    omlc_set_string_ptr((var), (str));                          \
    omlc_set_string_length((var), ((str)==NULL)?0:strlen(str)); \
  } while (0)
Store a pointer to a C string in an OmlValueU's string storage. The string is marked as statically allocated, so subsequent calls so omlc_reset_string will NOT free the memory is needed.
Parameters
var OmlValueU to operate on
str C-string pointer to use
See Also
omlc_set_string_size,omlc_reset_string
Definition at line 505 of file omlc.h.
Referenced by main(), omlc_add_mp(), omlc_inject_metadata(), run(), and START_TEST().
#define omlc_set_string_copy (var, str, len)
Value:
do {                                                         \
    _omlc_set_storage_copy((var), string, (str), (len) + 1);   \
    ((char*)(var).stringValue.ptr)[len] = '\0';                \
    omlc_set_string_length(var, len);                          \
    omlc_set_string_is_const(var, 0);                          \
  } while(0)
Copy a string into the dedicated storage of an OmlValueU.
Allocate (or reuse) a buffer of size len+1, copy the string, and nul-terminate it.
The length attribute is the length of the string; not how much of the storage is used (len + 1), as is the case for generic storage (blobs).
Parameters
var OmlValueU to manipulate
str terminated string to copy
len length of the string (not including nul terminator, i.e., output of strlen(3))
See Also
_omlc_set_storage_copy, strlen(3)
Definition at line 476 of file omlc.h.
Referenced by set_value(), START_TEST(), and unmarshal_value().
#define omlc_set_string_is_const (var, val) _oml_set_storage_field(var, string, is_const, (int)(val))
See Also
_oml_set_storage_field
Definition at line 364 of file omlc.h.
#define omlc_set_string_length (var, val) _oml_set_storage_field(var, string, length, (size_t)(val))
Set string length (not including nil-terminator)
See Also
_oml_set_storage_field, strlen(3)
Definition at line 358 of file omlc.h.
#define omlc_set_string_ptr (var, val) _oml_set_storage_field(var, string, ptr, (char*)(val))
See Also
_oml_set_storage_field
Definition at line 354 of file omlc.h.
#define omlc_set_string_size (var, val) _oml_set_storage_field(var, string, size, (size_t)(val))
See Also
_oml_set_storage_field
Definition at line 361 of file omlc.h.
#define omlc_set_uint32 (var, val) _omlc_set_intrinsic_value(var, uint32, (uint32_t)(val))
See Also
_omlc_set_intrinsic_value
Definition at line 284 of file omlc.h.
Referenced by main(), make_vector(), set_value(), START_TEST(), and unmarshal_value().
#define omlc_set_uint64 (var, val) _omlc_set_intrinsic_value(var, int64, (uint64_t)(val))
See Also
_omlc_set_intrinsic_value
Definition at line 290 of file omlc.h.
Referenced by make_vector(), set_value(), START_TEST(), and unmarshal_value().
#define omlc_set_vector_bool (var, val, nof_elts) _omlc_set_vector_copy((var), (val), (nof_elts), sizeof(bool))
Definition at line 630 of file omlc.h.
Referenced by START_TEST().
#define omlc_set_vector_double (var, val, nof_elts) _omlc_set_vector_copy((var), (val), (nof_elts), sizeof(double))
Definition at line 618 of file omlc.h.
Referenced by START_TEST().
#define omlc_set_vector_elt_size (var, val) _oml_set_storage_field((var), vector, elt_sz, (size_t)(val))
See Also
_oml_set_storage_field
Definition at line 581 of file omlc.h.
Referenced by unmarshal_value().
#define omlc_set_vector_int32 (var, val, nof_elts) _omlc_set_vector_copy((var), (val), (nof_elts), sizeof(int32_t))
Definition at line 622 of file omlc.h.
Referenced by START_TEST().
#define omlc_set_vector_int64 (var, val, nof_elts) _omlc_set_vector_copy((var), (val), (nof_elts), sizeof(int64_t))
Definition at line 626 of file omlc.h.
Referenced by START_TEST().
#define omlc_set_vector_length (var, val) _oml_set_storage_field((var), vector, length, (size_t)(val))
See Also
_oml_set_storage_field
Definition at line 575 of file omlc.h.
Referenced by unmarshal_value().
#define omlc_set_vector_long (var, val, nof_elts) _omlc_set_vector_copy((var), (val), (nof_elts), sizeof(long))
Definition at line 620 of file omlc.h.
#define omlc_set_vector_nof_elts (var, val) (_oml_set_storage_field((var), vector, nof_elts, (uint16_t)(val)))
See Also
_oml_get_storage_field
Definition at line 584 of file omlc.h.
Referenced by unmarshal_value().
#define omlc_set_vector_ptr (var, val) _oml_set_storage_field((var), vector, ptr, (void*)(val))
See Also
_oml_set_storage_field
Definition at line 572 of file omlc.h.
Referenced by unmarshal_value().
#define omlc_set_vector_size (var, val) _oml_set_storage_field((var), vector, size, (size_t)(val))
See Also
_oml_set_storage_field
Definition at line 578 of file omlc.h.
Referenced by unmarshal_value().
#define omlc_set_vector_uint32 (var, val, nof_elts) _omlc_set_vector_copy((var), (val), (nof_elts), sizeof(uint32_t))
Definition at line 624 of file omlc.h.
#define omlc_set_vector_uint64 (var, val, nof_elts) _omlc_set_vector_copy((var), (val), (nof_elts), sizeof(uint64_t))
Definition at line 628 of file omlc.h.
#define omlc_zero (var) memset(&(var), 0, sizeof(OmlValueU))
Zero out a freshly declared OmlValueU.
Parameters
var OmlValueU to manipulate
Definition at line 209 of file omlc.h.
Referenced by main(), marshal_measurements(), omlc_add_mp(), and START_TEST().
#define omlc_zero_array (var, n) memset((var), 0, n*sizeof(OmlValueU))
Zero out a freshly declared array of OmlValueU.
Parameters
var OmlValueU to manipulate
n number of OmlValueU in the array
Definition at line 217 of file omlc.h.
Referenced by main(), make_vector(), omlc_inject_metadata(), and run().
Typedef Documentation
typedef uint64_t oml_guid_t
An opaque type to represent globally unique IDs.
Definition at line 163 of file omlc.h.
typedef struct OmlBlob OmlBlob
Representation of a blob measurement value.
typedef struct OmlMP OmlMP
Definition of a Measurement Point.
This structure contains an array of OmlMPDef defining the fields of the MP, and an array of OmlMStream defining which streams need to receive output from this MP.
See Also
omlc_inject, OmlMStream, omlc_add_mp, OmlMP
typedef struct OmlMPDef OmlMPDef
Definition of one field of an MP.
An array of these create a full measurement point.
See Also
omlc_add_mp, OmlMP
typedef struct OmlMStream OmlMStream
Definition of a Measurement Stream.
A measurement stream links an MP to an output, defined by a writing function (OmlWriter), passing some or all of the fields into a filter (OmlFilter).
All the samples injected into an MP are received, but through filtering and aggregation, the output rate of the MS might be different (e.g., 1/n samples, or with a time-based periodicity).
See Also
OmlMP, OmlWriter, OmlFilter, omlc_inject
typedef struct OMLSemDef OMLSemDef
typedef struct OmlString OmlString
Representation of a string measurement value.
typedef struct OmlValue OmlValue
Typed container for an OmlValueU
WARNING: OmlValue MUST be oml_value_init()ialised before use and oml_value_reset() after. Not doing so might result in memory problems (double free or memory leak).
This takes care of manipulating the contained OmlValueU properly.
See Also
oml_value_init, oml_value_array_init, oml_value_reset,oml_value_array_reset
typedef enum OmlValueT OmlValueT
typedef union OmlValueU OmlValueU
Multi-typed variable container without type information.
WARNING: OmlValueU MUST be omlc_zero()d out before use. Additionally, if the last type of data they contained was an OML_STRING_VALUE, OML_BLOB_VALUE or OML_VECTOR_*_VALUE, they should be omlc_reset_(string|blob|vector)(). Not doing so might result in memory problems (double free or memory leak).
When wrapped in OmlValue, the right thing is done, by the initialisation/reset functions.
See Also
omlc_zero, omlc_zero_array, omlc_reset_string, omlc_reset_blob
oml_value_init, oml_value_array_init, oml_value_reset, oml_value_array_reset
typedef struct OmlVector OmlVector
Representation of a vector value.
Enumeration Type Documentation
enum OmlValueT
Enumerator:
OML_DB_PRIMARY_KEY
OML_INPUT_VALUE
OML_UNKNOWN_VALUE
OML_DOUBLE_VALUE
OML_LONG_VALUE
OML_PADDING1_VALUE
OML_STRING_VALUE
OML_INT32_VALUE
OML_UINT32_VALUE
OML_INT64_VALUE
OML_UINT64_VALUE
OML_BLOB_VALUE
OML_GUID_VALUE
OML_BOOL_VALUE
OML_DATETIME_VALUE
OML_VECTOR_DOUBLE_VALUE
OML_VECTOR_INT32_VALUE
OML_VECTOR_UINT32_VALUE
OML_VECTOR_INT64_VALUE
OML_VECTOR_UINT64_VALUE
OML_VECTOR_BOOL_VALUE
OML_LAST_VALUE
Definition at line 29 of file omlc.h.
                       {
  /* Meta value types */
  OML_DB_PRIMARY_KEY = -3,
  OML_INPUT_VALUE = -2,
  OML_UNKNOWN_VALUE = -1,
  /* Concrete value types */
  OML_DOUBLE_VALUE = 0,
  OML_LONG_VALUE,
  OML_PADDING1_VALUE,
  OML_STRING_VALUE,
  OML_INT32_VALUE,
  OML_UINT32_VALUE,
  OML_INT64_VALUE,
  OML_UINT64_VALUE,
  OML_BLOB_VALUE,
  OML_GUID_VALUE,
  OML_BOOL_VALUE,
  OML_DATETIME_VALUE,
  /* Vector types */
  OML_VECTOR_DOUBLE_VALUE,
  OML_VECTOR_INT32_VALUE,
  OML_VECTOR_UINT32_VALUE,
  OML_VECTOR_INT64_VALUE,
  OML_VECTOR_UINT64_VALUE,
  OML_VECTOR_BOOL_VALUE,
  OML_LAST_VALUE /* For easy range checks */
} OmlValueT;
Function Documentation
void oml_free (void * ptr)
Free an xchunk
Parameters
ptr pointer to an oml_malloc()'d bit of memory
See Also
oml_malloc, free(3)
Definition at line 240 of file mem.c.
Referenced by bw_close(), bw_create(), cbuf_add_page(), cbuf_create(), cbuf_destroy(), check_server_destroy_client_handler(), client_free(), client_handler_free(), client_send_header(), create_mstream(), create_writer(), database_create_table(), database_find(), database_find_or_create_table(), database_release(), database_table_free(), dba_table_create_from_schema(), destroy_filter(), destroy_ms(), destroy_sem_concepts(), handleValue(), header_free(), header_from_string(), main(), mbuf_create2(), mbuf_destroy(), msg_queue_destroy(), msg_queue_remove(), mstring_create(), mstring_delete(), omlc_add_mp(), omlc_close(), parse_uri(), psql_prepare(), schema_copy(), schema_field_from_meta(), schema_free(), schema_from_sql(), socket_free(), socket_group_remove(), socket_in_new(), table_descr_array_free(), table_descr_list_free(), table_descr_new(), and unregister_filters().
{
  if (ptr) {
    size_t *sptr = (size_t*)ptr - 1, size = *sptr;
    free (sptr);
    xcount_freed (size);
  }
}
void* oml_malloc (size_t size)
Allocate memory, keeping track of how much.
The allocated memory is one size_t larger, just before the returned pointer, to store the size of the xchunk.
Parameters
size desired size to allocate
Returns
an xchunk of memory at least as big as size, or NULL
See Also
oml_free, malloc(3)
Definition at line 157 of file mem.c.
Referenced by bin_writer_new(), bw_create(), cbuf_add_page(), cbuf_create(), check_server_prepare_client_handler(), client_handler_new(), client_new(), client_send_header(), create_filter(), create_mstream(), database_create_table(), database_find(), eventloop_every(), file_stream_new(), fuseki_create_database(), header_from_string(), main(), mbuf_create2(), mksyn(), msg_queue_add(), msg_queue_create(), mstring_create(), net_stream_new(), oml_memdupz(), oml_realloc(), oml_sem_register_concepts(), oml_stralloc(), omlc_add_mp(), omlc_init(), omlf_average_new(), omlf_delta_new(), omlf_first_new(), omlf_histogram_new(), omlf_last_new(), omlf_register_filter(), omlf_stddev_new(), omlf_sum_new(), psql_create_database(), schema_copy(), schema_from_meta(), schema_from_sql(), schema_new(), socket_group_add(), socket_group_new(), sq3_create_database(), START_TEST(), store_received_message(), table_descr_new(), text_writer_new(), to_octets(), and virtuoso_create_database().
{
  size += sizeof (size_t);
  void *ret = malloc (size);
  if (!ret)
    xreturn (ret, size, "Out of memory, malloc failed\n");
  memset (ret, 0, size);
  *(size_t*)ret = size;
  xcount_new (size);
  return (size_t*)ret + 1;
}
size_t oml_malloc_usable_size (void * ptr)
Report the size of the given xchunk
Parameters
ptr pointer to an oml_malloc()'d bit of memory
Returns
the size of the allocated xchunk
See Also
oml_malloc, malloc_usable_size(3)
Definition at line 228 of file mem.c.
Referenced by START_TEST().
{
  if(!ptr) return 0;
  size_t *sptr = (size_t*)ptr - 1;
  return *sptr-sizeof(size_t);
}
OMLSemDef* oml_sem_register_concepts (char *** concepts, int n)
Asign all concepts to the measurement Point
Parameters
concepts matrix of concepts
n number of triples
Returns
OMLSemDef* (can be NULL)
Author
Mario Poyato Pino mario.nosp@m..poy.nosp@m.ato@u.nosp@m.am.e.nosp@m.s
Definition at line 461 of file init.c.
References oml_malloc(), and xstrdup.
{
  int i=0;
  OMLSemDef *sd=NULL,*sd_last,*sd_aux;
  if (n>0) {
    sd = sd_last = sd_aux = (OMLSemDef*)oml_malloc(sizeof(OMLSemDef));
    while (i<n) {
      sd_aux->subject   = xstrdup(concepts[i][0]);
      sd_aux->predicate      = xstrdup(concepts[i][1]);
      sd_aux->object = xstrdup(concepts[i][2]);
      sd_aux->next      = NULL;
      if (++i<n) {
        sd_aux = (OMLSemDef*)oml_malloc(sizeof(OMLSemDef));
        sd_last->next = sd_aux;
        sd_last=sd_aux;
      }
    }
  }
  return sd;
}
OmlMP* omlc_add_mp (const char * mp_name, OmlMPDef * mp_def)
Register a measurement point.
This function should be called after omlc_init() and before omlc_start(). It can be called multiple times, once for each measurement point that the application needs to define.
The returned OmlMP must be the first argument in every omlc_inject() call for this specific measurement point.
XXX: The supplied name is not checked for existence.
The MP's input structure is defined by the mp_def parameter, it should be initialised as this example shows.
OmlMPDef mp_def[] =
{
  { "source", OML_UINT32_VALUE, NULL},
  { "destination", OML_UINT32_VALUE, NULL},
  { "length", OML_UINT32_VALUE, NULL},
  { "weight", OML_DOUBLE_VALUE, NULL},
  { "protocol", OML_STRING_VALUE, NULL},
  { NULL, (OmlValueT)0, NULL }
};
Parameters
mp_name The name of this MP. The name must not contain whitespace
mp_def Definition of this MP's input tuple, as an array of OmlMPDef objects
Returns
a new measurement point
See Also
omlc_init, omlc_start
Definition at line 365 of file init.c.
References OmlMP::active, OmlClient::app_name, destroy_sem_concepts(), OmlMStream::index, OmlClient::last_mpoint, logdebug(), logerror(), logwarn(), mp, mp_def, OmlClient::mpoints, mstring_buf(), mstring_create(), mstring_delete(), mstring_sprintf(), OmlMPDef::name, OmlMP::name, OmlMP::next, OmlClient::next_ms_idx, oml_free(), OML_LONG_VALUE, oml_malloc(), oml_mp_get_default_ms(), OML_STRING_VALUE, omlc_inject_metadata(), omlc_reset_string, omlc_set_string, omlc_zero, OmlMP::param_count, OmlMP::param_defs, OmlMPDef::param_types, OmlMPDef::relations, OmlClient::start_time, OmlMP::streams, and validate_name().
Referenced by main(), omlc_init(), and START_TEST().
{
  int pc = 0;
  char *schemastr;
  MString *meta;
  OmlValueU v;
  omlc_zero(v);
  if (omlc_instance == NULL) { return NULL; }
  if (!validate_name (mp_name)) {
    logerror("Illegal MP name '%s': missing or containing whitespaces or dashes; MP will not be created\n", mp_name);
    return NULL;
  }
  logdebug("Adding MP %s\n", mp_name);
  OmlMP* mp = (OmlMP*)oml_malloc(sizeof(OmlMP));
  memset(mp, 0, sizeof(OmlMP));
  mp->name = mp_name;
  mp->param_defs = mp_def;
  OmlMPDef* dp = mp_def;
  while (dp != NULL && dp->name != NULL) {
    if (dp->param_types == OML_LONG_VALUE) {
      logwarn("MP '%s', field '%s': OML_LONG_VALUE is deprecated, please use OML_INT32_VALUE instead; "
          "values outside of [INT_MIN, INT_MAX] will be clamped\n",
          mp->name, dp->name);
    }
    if (!validate_name (dp->name)) {
      logerror("Illegal field name '%s' in MP %s: missing or containing whitespaces or dashes; MP will not be created\n",
          dp->name, mp_name);
      while (destroy_sem_concepts(mp->param_defs->relations));
      oml_free (mp);
      return NULL;
    }
    pc++;
    dp++;
  }
  mp->param_count = pc;
  mp->active = 1;  // True if there is an attached MS.
  if(omlc_instance->start_time > 0) {
    /* omlc_start has already been called, declare MP through schema0 */
    meta = mstring_create();
    schemastr = schemastr_from_mpdef(mp_def);
    /* Unlike how we manage schema0, we do prepend the application name to the
     * MP name, even when declared after the start. This is mostly because that
     * concatenation happens anyway on the client side, when creating the
     * default filter configuration, and we don't want too many discrepancies
     * between the client and servers views at this stage. See #1055. */
    mstring_sprintf(meta, "%d %s_%s%s",
        omlc_instance->next_ms_idx, omlc_instance->app_name, mp_name, schemastr);
    oml_free(schemastr);
    logdebug("omlc_start already called, adding MP through schema 0: %s\n",
        mstring_buf(meta));
    omlc_set_string(v, mstring_buf(meta));
    omlc_inject_metadata(NULL, "schema", &v, OML_STRING_VALUE, NULL);
    omlc_reset_string(v);
    mstring_delete(meta);
    if (!oml_mp_get_default_ms(mp)) {
      logerror("Failed to create default MS for MP %s\n", mp_name);
      oml_free(mp);
      return NULL;
    }
    /* At this stage, we only have one stream set up, and we now its index */
    mp->streams->index = omlc_instance->next_ms_idx++;
  }
  if (NULL == omlc_instance->mpoints) {
    omlc_instance->mpoints = mp;
  } else {
    omlc_instance->last_mpoint->next = mp;
  }
  omlc_instance->last_mpoint = mp;
  return mp;
}
int omlc_close (void)
Terminate all open connections.
Terminate all open connections.
Once this function has been called, any futher calls to omlc_inject() will be ignored.
This call doesn't free all memory used by OML immediately. There may be a few threads which will take some time to finish while the remaining buffered data is sent.
Returns
0 on sucess, -1 otherwise
Definition at line 637 of file init.c.
References OmlWriter::close, destroy_mp(), OmlClient::first_writer, OmlClient::mpoints, O_LOG_DEBUG, oml_free(), oml_memreport(), and unregister_filters().
Referenced by main(), oml_cleanup(), omlc_init(), omlc_start(), and START_TEST().
{
  if (NULL == omlc_instance) {
    return 0; /* Already clear */
  } else {
    OmlWriter* w = omlc_instance->first_writer;
    OmlMP* mp = omlc_instance->mpoints;
    install_close_handler(SIG_DFL);
    while( (mp = destroy_mp(mp)) );
    if (w) {
      while( (w =  w->close(w)) );
    }
    unregister_filters ();
    oml_free(omlc_instance);
  }
  omlc_instance = NULL;
  oml_memreport(O_LOG_DEBUG);
  return 0;
}
oml_guid_t omlc_guid_generate ()
Generate a new GUID
Initialize a guid to a unique new value.
Returns
in A non-NULL pointer to the oml_guid_t to initialize.
Definition at line 76 of file guid.c.
Referenced by START_TEST().
{
  FILE *fp = random_open();
  oml_guid_t out = OMLC_GUID_NULL;
  while(OMLC_GUID_NULL == out) {
    if(fread(&out, sizeof(out), 1, fp) != 1) {
      char msg[4096];
      strerror_r(errno, msg, sizeof(msg));
      logerror("Failed to read from %s: %s\n", random_path, msg);
      exit(EXIT_FAILURE);
    }
  }
  return out;
}
int omlc_init (const char * application, int * pargc, const char ** argv, o_log_fn custom_oml_log)
Initialise the measurement library.
This functions parses the command line for –oml-* options and acts accordingly when they are found. A side effect of this function is that these options and their arguments are removed from argv, so the instrumented application doesn't see spurious OML option it can't make sense of.
Parameters
name name of the application
pargc argc of the command line of the application
argv argv of the command line of the application
custom_oml_log custom format-based logging function
Returns
0 on success, -1 on failure, 1 when OML is disabled.
See Also
omlc_add_mp, omlc_start, omlc_close
o_log_fn, o_set_log
Definition at line 96 of file init.c.
References OmlClient::app_name, OmlClient::client_instr, OmlClient::collection_uri, COLLECTION_URI_MAX_LENGTH, OmlClient::config_file, OmlClient::default_encoding, OmlClient::domain, OmlClient::instr_interval, OmlClient::instr_time, logerror(), loginfo(), logwarn(), OmlClient::max_queue, name, OmlClient::node_name, O_LOG_INFO, o_set_log(), o_set_log_file(), o_set_log_level(), oml_malloc(), OML_PROTOCOL_VERSION, omlc_add_mp(), omlc_close(), OMLC_COPYRIGHT, register_builtin_filters(), OmlClient::sample_count, OmlClient::sample_interval, SE_Binary, SE_None, SE_Text, validate_app_name(), and VERSION.
Referenced by main(), oml_setup(), and START_TEST().
{
  const char *app_name = validate_app_name (application);
  const char* name = NULL;
  const char* domain = NULL;
  const char* config_file = NULL;
  const char* local_data_file = NULL;
  const char* collection_uri = NULL;
  char *start = NULL, *end = NULL; /* For strtoX(3) */
  enum StreamEncoding default_encoding = SE_None;
  int sample_count = 0;
  double sample_interval = 0.0;
  int max_queue = 0;
  uint32_t instr_interval = 1;
  const char** arg = argv;
  if (!app_name) {
    logerror("Illegal application name '%s': missing or containing whitespaces or dashes\n", application);
    return -1;
  }
  omlc_instance = NULL;
  o_set_log_level(O_LOG_INFO);
  if (custom_oml_log)
    o_set_log (custom_oml_log);
  if (pargc && arg) {
    int i;
    for (i = *pargc; i > 0; i--, arg++) {
      if (strcmp(*arg, "--oml-id") == 0) {
        if (--i <= 0) {
          logerror("Missing argument for '--oml-id'\n");
          return -1;
        }
        name = *++arg;
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-domain") == 0) {
        if (--i <= 0) {
          logerror("Missing argument for '--oml-domain'\n");
          return -1;
        }
        domain = *++arg;
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-exp-id") == 0) {
        if (--i <= 0) {
          logerror("Missing argument for '--oml-exp-id'\n");
          return -1;
        }
        domain = *++arg;
        logwarn("Option --oml-exp-id is getting deprecated; please use '--oml-domain %s' instead\n", domain);
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-file") == 0) {
        if (--i <= 0) {
          logerror("Missing argument for '--oml-file'\n");
          return -1;
        }
        local_data_file = *++arg;
        logwarn("Option --oml-file is getting deprecated; please use '--oml-collect file:%s' instead\n", local_data_file);
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-collect") == 0) {
        if (--i <= 0) {
          logerror("Missing argument for '--oml-collect'\n");
          return -1;
        }
        collection_uri = (char*)*++arg;
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-config") == 0) {
        if (--i <= 0) {
          logerror("Missing argument for '--oml-config'\n");
          return -1;
        }
        config_file = *++arg;
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-samples") == 0) {
        if (--i <= 0) {
          logerror("Missing argument to '--oml-samples'\n");
          return -1;
        }
        sample_count = atoi(*++arg);
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-interval") == 0) {
        if (--i <= 0) {
          logerror("Missing argument to '--oml-interval'\n");
          return -1;
        }
        sample_interval = atof(*++arg);
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-log-file") == 0) {
        if (--i <= 0) {
          logerror("Missing argument to '--oml-log-file'\n");
          return -1;
        }
        o_set_log_file((char*)*++arg);
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-log-level") == 0) {
        if (--i <= 0) {
          logerror("Missing argument to '--oml-log-level'\n");
          return -1;
        }
        o_set_log_level(atoi(*++arg));
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-server") == 0) {
        if (--i <= 0) {
          logerror("Missing argument for '--oml-server'\n");
          return -1;
        }
        collection_uri = (char*)*++arg;
        logwarn("Option --oml-server is getting deprecated; please use '--oml-collect %s' instead\n", collection_uri);
        *pargc -= 2;
      } else if (strcmp (*arg, "--oml-text") == 0) {
        *pargc -= 1;
        default_encoding = SE_Text;
      } else if (strcmp (*arg, "--oml-binary") == 0) {
        *pargc -= 1;
        default_encoding = SE_Binary;
      } else if (strcmp(*arg, "--oml-bufsize") == 0) {
        if (--i <= 0) {
          logerror("Missing argument to '--oml-bufsize'\n");
          return -1;
        }
        max_queue = atoi(*++arg);
        *pargc -= 2;
      } else if (strcmp(*arg, "--oml-instr-interval") == 0) {
        start = (char *)*++arg; /* XXX: Drop arg's const */
        end = NULL;
        if (--i <= 0) {
          logerror("Missing argument to '--oml-instr-interval'\n");
          return -1;
        }
        instr_interval = strtoul(start, &end, 10);
        if(end == *arg || *end != '\0') {
          logwarn("Invalid argument to '--oml-instr-interval'\n");
          instr_interval = 0;
        }
        *pargc -= 2;
        if(0 == instr_interval) {
          loginfo("Client instrumentation disabled\n");
        }
      } else if (strcmp(*arg, "--oml-noop") == 0) {
        *pargc -= 1;
        omlc_close();
        return 1;
      } else if (strcmp(*arg, "--oml-help") == 0) {
        usage();
        *pargc -= 1;
        exit(0);
      } else if (strcmp(*arg, "--oml-list-filters") == 0) {
        print_filters();
        *pargc -= 1;
        exit(0);
      } else {
        *argv++ = *arg;
      }
    }
  }
  if (name == NULL) {
    name = getenv("OML_NAME");
  }
  if (domain == NULL) {
    if(!(domain = getenv("OML_DOMAIN"))) {
      if ((domain= getenv("OML_EXP_ID"))) {
        logwarn("Enviromnent variable OML_EXP_ID is getting deprecated; please use 'OML_DOMAIN=\"%s\"' instead\n",
            domain);
      }
    }
  }
  if (config_file == NULL) {
    config_file = getenv("OML_CONFIG");
  }
  if (local_data_file == NULL && collection_uri == NULL) {
    if(!(collection_uri = getenv("OML_COLLECT"))) {
      if ((collection_uri = getenv("OML_SERVER"))) {
        logwarn("Enviromnent variable OML_SERVER is getting deprecated; please use 'OML_COLLECT=\"%s\"' instead\n",
            collection_uri);
      }
    }
  }
  if(collection_uri == NULL) {
    collection_uri = default_uri(app_name, name, domain);
  }
  setup_features (getenv ("OML_FEATURES"));
  omlc_instance = oml_malloc(sizeof(OmlClient));
  memset(omlc_instance, 0, sizeof(OmlClient));
  omlc_instance->app_name = app_name;
  omlc_instance->node_name = name;
  omlc_instance->domain = domain;
  omlc_instance->sample_count = sample_count;
  omlc_instance->sample_interval = sample_interval;
  omlc_instance->default_encoding = default_encoding;
  omlc_instance->max_queue = max_queue;
  omlc_instance->instr_time = 0;
  omlc_instance->instr_interval = instr_interval;
  if (local_data_file != NULL) {
    // dump every sample into local_data_file
    if (local_data_file[0] == '-')
      local_data_file = "stdout";
    snprintf(omlc_instance->collection_uri, COLLECTION_URI_MAX_LENGTH, "file:%s", local_data_file);
  } else if (collection_uri != NULL) {
    strncpy(omlc_instance->collection_uri, collection_uri, COLLECTION_URI_MAX_LENGTH);
  }
  omlc_instance->config_file = config_file;
  register_builtin_filters ();
  schema0 = omlc_add_mp("_experiment_metadata", _experiment_metadata);
  omlc_instance->client_instr = omlc_add_mp("_client_instrumentation", _client_instrumentation);
  loginfo ("OML Client %s [OMSPv%d] %s\n",
           VERSION,
           OML_PROTOCOL_VERSION,
           OMLC_COPYRIGHT);
  return 0;
}
int omlc_inject (OmlMP * mp, OmlValueU * values)
Inject a measurement sample into a Measurement Point.
Parameters
mp pointer to OmlMP into which the new sample is being injected
values an array of OmlValueU to be processed
Returns
0 on success, <0 otherwise
The values' types is assumed to be the same as what was passed to omlc_add_mp Type information is stored in (stored in mp->param_defs[].param_types)
Traverse the list of MSs attached to this MP and, for each MS, the list of filters to apply to the sample. Input the relevant field of the MP to each filter, the call omlc_ms_process() to determine whether a new sample has to be output on that MS.
The content of values is deep-copied into the MSs' storage, so values can be directly freed/reused when inject returns.
This function might call omlc_inject_client_instr which in turns calls omlc_inject. We make sure not to loop.
See Also
omlc_add_mp, omlc_ms_process, oml_value_set, omlc_inject_client_instr
Definition at line 149 of file api.c.
References OmlWriter::bufferedWriter, bw_nlost_reset(), OmlClient::client_instr, OmlMStream::dropped, OmlMStream::filters, OmlFilter::index, OmlFilter::input, OmlClient::instr_interval, OmlClient::instr_time, LOGDEBUG, logerror(), logwarn(), mp_lock(), mp_unlock(), OmlMP::name, OmlFilter::next, OmlMStream::next, OmlMStream::nwriters, oml_value_init(), oml_value_reset(), oml_value_set(), omlc_instance, OmlMP::param_defs, OmlMPDef::param_types, OmlClient::start_time, OmlMP::streams, OmlMStream::table_name, OmlMStream::writers, OmlMStream::written, xmaxbytes(), xmembytes(), xmemfreed(), and xmemnew().
Referenced by main(), omlc_inject_metadata(), omlc_process(), run(), and START_TEST().
{
  OmlMStream* ms;
  OmlValue v;
  int i;
  if (NULL == omlc_instance || omlc_instance->start_time <= 0) {
    logerror("Cannot inject samples prior to calling omlc_init and omlc_start\n");
    return -1;
  }
  if (mp == NULL || values == NULL) {
    return -1;
  }
  LOGDEBUG("Injecting data into MP '%s'\n", mp->name);
  oml_value_init(&v);
  if (mp_lock(mp) == -1) {
    logwarn("Cannot lock MP '%s' for injection\n", mp->name);
    return -1;
  }
  uint64_t written = 0;
  uint64_t dropped = 0;
  for (ms = mp->streams; ms; ms = ms->next) {
    LOGDEBUG("Filtering MP '%s' data into MS '%s'\n", mp->name, ms->table_name);
    OmlFilter* f = ms->filters;
    for (; f != NULL; f = f->next) {
      /* FIXME:  Should validate this indexing */
      oml_value_set(&v, &values[f->index], mp->param_defs[f->index].param_types);
      f->input(f, &v);
    }
    omlc_ms_process(ms);
    written += ms->written;
    dropped += ms->dropped;
    for (i=0; i<ms->nwriters; i++) {
      dropped += bw_nlost_reset(ms->writers[i]->bufferedWriter);
    }
  }
  mp_unlock(mp);
  oml_value_reset(&v);
  /* do we need to send client instrumentation? */
  if(mp != omlc_instance->client_instr && omlc_instance->instr_interval) {
    time_t now;
    time(&now);
    if(omlc_instance->instr_time + omlc_instance->instr_interval <= now) {
      omlc_instance->instr_time = now; /* Make sure we don't loop */
      omlc_inject_client_instr(written, dropped, xmemnew(), xmemfreed(), xmembytes(), xmaxbytes());
    }
  }
  return 0;
}
int omlc_inject_metadata (OmlMP * mp, const char * key, const OmlValueU * value, OmlValueT type, const char * fname)
Inject metadata (key/value) for a specific MP.
Inject metadata (key/value) for a specific MP.
Parameters
mp pointer to the OmlMP to which the metadata relates
key base name for the key (keys are unique)
value OmlValueU containing the value for the given key
type OmlValueT of value, currently only OML_STRING_VALUE is valid
fname optional field name to which this metadata relates
Returns
0 on success, -1 otherwise
See Also
omlc_add_mp
Definition at line 218 of file api.c.
References OmlClient::app_name, find_mp_field(), logdebug(), logerror(), logwarn(), mstring_buf(), mstring_create(), mstring_delete(), mstring_set(), mstring_sprintf(), OmlMP::name, OML_STRING_VALUE, omlc_copy_string, omlc_inject(), omlc_instance, omlc_reset_string, omlc_set_string, omlc_zero_array, OmlClient::start_time, and validate_name().
Referenced by main(), omlc_add_mp(), run(), and START_TEST().
{
  int ret = -1;
  OmlValueU v[3];
  omlc_zero_array(v, 3);
  MString *subject = mstring_create();
  if (NULL == omlc_instance || omlc_instance->start_time <= 0) {
    logerror("Cannot inject metadata prior to calling omlc_init and omlc_start\n");
  } else if (!key || !value) {
    logwarn("Trying to inject metadata with missing key and/or value\n");
  } else if (! validate_name(key)) {
    logerror("%s is an invalid metadata key name\n", key);
  } else if (type != OML_STRING_VALUE) {
    logwarn("Currently, only OML_STRING_VALUE are valid as metadata value\n");
  } else {
    mstring_set (subject, ".");
    if(NULL == mp) {
      logdebug("%s: supplied MP is NULL, assuming experiment metadata\n",
          __FUNCTION__);
    } else {
      /* XXX: At the moment, MS are named as APPNAME_MPNAME.
       * Be consistent with it here, until #1055 is addressed */
      mstring_sprintf(subject, "%s_%s", omlc_instance->app_name, mp->name);
      if (fname) {
        if (find_mp_field(fname, mp) < 0) {
          logwarn("Field %s not found in MP %s, not reporting\n", fname, mp->name);
        } else {
          mstring_sprintf(subject, ".%s", fname);
        }
      }
    }
    omlc_set_string(v[0], mstring_buf(subject));
    omlc_set_string(v[1], key);
    omlc_copy_string(v[2], *value);
    omlc_inject(schema0, v);
    omlc_reset_string(v[0]);
    omlc_reset_string(v[1]);
    omlc_reset_string(v[2]);
    mstring_delete(subject);
    ret = 0;
  }
  return ret;
}
void omlc_process (OmlMP * mp, OmlValueU * values)
DEPRECATED
See Also
omlc_inject
Definition at line 120 of file api.c.
References logwarn(), and omlc_inject().
{
  logwarn("'omlc_process' is deprecated, use 'omlc_inject' instead\n");
  omlc_inject(mp, values);
}
int omlc_start (void)
Get ready to start the measurement collection.
This function must be called after omlc_init and after any calls to omlc_add_mp(). It finalises the initialisation process and initialises filters on all measurement points, according to the current configuration (based on either command line options or the XML config file named by the –oml-config command line option).
It also registers a termination handler.
Once this function has been called, and if it succeeds, the application is free to start creating measurement samples by calling omlc_inject().
If this function fails, subsequent calls to omlc_inject() will result in undefined behaviour.
Returns
0 on success, -1 on failure
See Also
omlc_init, omlc_add_mp, omlc_close
install_close_handler, termination_handler
Definition at line 539 of file init.c.
References OmlClient::collection_uri, OmlClient::config_file, logerror(), omlc_close(), parse_config(), and OmlClient::start_time.
Referenced by main(), oml_setup(), and START_TEST().
{
  if (omlc_instance == NULL) { return -1; }
  struct timeval tv;
  gettimeofday(&tv, NULL);
  omlc_instance->start_time = tv.tv_sec;
  const char* config_file = omlc_instance->config_file;
  if (config_file) {
    if (parse_config((char*)config_file)) {
      logerror("Error while parsing configuration '%s'\n", config_file);
      omlc_close();
      return -1;
    }
  } else {
    if (omlc_instance->collection_uri == NULL) {
      logerror("Missing --oml-collect declaration.\n");
      omlc_close();
      return -2;
    }
    if (default_configuration()) {
      omlc_close();
      return -3;
    }
  }
  install_close_handler(termination_handler);
  if (write_meta() == -1) {
    return -1;
  }
  return 0;
}