oml2: parse_config.c File Reference
parse_config.c File Reference
The XML configuration file parser functions.
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <libxml/tree.h>
#include "ocomm/o_log.h"
#include "mstring.h"
#include "mem.h"
#include "filter/factory.h"
#include "client.h"
#include "oml_value.h"
Data Structures
struct synonym
Enumerations
enum ConfToken {
CT_ROOT, CT_NODE, CT_EXP, CT_COLLECT,
CT_COLLECT_URL, CT_COLLECT_ENCODING, CT_STREAM, CT_STREAM_NAME,
CT_STREAM_SOURCE, CT_STREAM_SAMPLES, CT_STREAM_INTERVAL, CT_FILTER,
CT_FILTER_FIELD, CT_FILTER_OPER, CT_FILTER_RENAME, CT_FILTER_PROP,
CT_FILTER_PROP_NAME, CT_FILTER_PROP_TYPE, CT_Max
}
Functions
void setcurtok (enum ConfToken tok)
void mksyn (const char *const str)
int parse_config (char *configFile)
Detailed Description
The XML configuration file parser functions.
Definition in file parse_config.c.
Enumeration Type Documentation
enum ConfToken
Enumerator:
CT_ROOT
CT_NODE
CT_EXP
CT_COLLECT
CT_COLLECT_URL
CT_COLLECT_ENCODING
CT_STREAM
CT_STREAM_NAME
CT_STREAM_SOURCE
CT_STREAM_SAMPLES
CT_STREAM_INTERVAL
CT_FILTER
CT_FILTER_FIELD
CT_FILTER_OPER
CT_FILTER_RENAME
CT_FILTER_PROP
CT_FILTER_PROP_NAME
CT_FILTER_PROP_TYPE
CT_Max
Definition at line 26 of file parse_config.c.
               {
  CT_ROOT,
  CT_NODE,
  CT_EXP,
  CT_COLLECT,
  CT_COLLECT_URL,
  CT_COLLECT_ENCODING,
  CT_STREAM,
  CT_STREAM_NAME,
  CT_STREAM_SOURCE,
  CT_STREAM_SAMPLES,
  CT_STREAM_INTERVAL,
  CT_FILTER,
  CT_FILTER_FIELD,
  CT_FILTER_OPER,
  CT_FILTER_RENAME,
  CT_FILTER_PROP,
  CT_FILTER_PROP_NAME,
  CT_FILTER_PROP_TYPE,
  CT_Max
};
Function Documentation
void mksyn (const char *const str)
Definition at line 74 of file parse_config.c.
References oml_malloc(), and oml_strndup().
{
  struct synonym *new = oml_malloc (sizeof (struct synonym));
  new->name = oml_strndup (str, strlen (str));
  new->next = tokmap_[curtok];
  tokmap_[curtok] = new;
}
int parse_config (char * configFile)
Parse the config file to configure liboml2.
Parameters
configFile the name of the config file
Returns
0 if successful <0 otherwise
Definition at line 223 of file parse_config.c.
References CT_COLLECT, CT_EXP, CT_NODE, CT_ROOT, OmlClient::domain, logdebug(), logerror(), OmlClient::node_name, and omlc_instance.
Referenced by omlc_start().
{
  xmlDocPtr doc;
  xmlNodePtr cur;
  logdebug("Using configuration file '%s'\n", configFile);
  if ((doc = xmlParseFile(configFile)) == NULL) {
    logerror("Config file '%s' not parsed successfully.\n",
      configFile);
    return -1;
  }
  if ((cur = xmlDocGetRootElement(doc)) == NULL) {
    logerror("Config file '%s' is empty.\n", configFile);
    xmlFreeDoc(doc);
    return -2;
  }
  if (!match_xml_elt (cur, CT_ROOT)) {
    logerror("Config file has incorrect root '%s', should be '%s'.\n",
             cur->name, canonical_name (CT_ROOT));
    xmlFreeDoc(doc);
    return -3;
  }
  if (omlc_instance->node_name == NULL) {
    omlc_instance->node_name = get_xml_attr(cur, CT_NODE);
  }
  if (omlc_instance->domain == NULL) {
    omlc_instance->domain = get_xml_attr(cur, CT_EXP);
  }
  cur = cur->xmlChildrenNode;
  while (cur != NULL) {
    if (match_xml_elt(cur, CT_COLLECT)) {
      if (parse_collector(cur)) {
        xmlFreeDoc(doc);
        return -4;
      }
    }
    cur = cur->next;
  }
  xmlFreeDoc(doc);
  return 0;
}
void setcurtok (enum ConfToken tok)
Definition at line 68 of file parse_config.c.
{
  curtok = tok;
}