oml2: proxy_client.c File Reference
proxy_client.c File Reference
Functions to manage the Client structure.
#include <stdlib.h>
#include <string.h>
#include "ocomm/o_log.h"
#include "mem.h"
#include "mbuf.h"
#include "cbuf.h"
#include "proxy_client.h"
#include "message_queue.h"
Functions
Client * client_new (Socket *client_sock, int page_size, char *file_name, int server_port, char *server_address)
void client_free (Client *client)
Detailed Description
Functions to manage the Client structure.
Definition in file proxy_client.c.
Function Documentation
void client_free (Client * client)
Definition at line 74 of file proxy_client.c.
References _client::cbuf, cbuf_destroy(), _client::condvar, _client::downstream_addr, _client::file, _client::file_name, header_free(), _client::headers, _client::messages, msg_queue_destroy(), _client::mutex, header::next, oml_free(), _client::recv_socket, and socket_free().
Referenced by client_send_thread().
{
  if (client == NULL) return;
  if (client->file) {
    fflush (client->file);
    fclose (client->file);
    client->file = NULL;
  }
  oml_free (client->file_name);
  oml_free (client->downstream_addr);
  struct header *header = client->headers;
  while (header) {
    struct header *next = header->next;
    header_free (header);
    header = next;
  }
  msg_queue_destroy (client->messages);
  cbuf_destroy (client->cbuf);
  pthread_cond_destroy (&client->condvar);
  pthread_mutex_destroy (&client->mutex);
  socket_free (client->recv_socket);
  oml_free (client);
}
Client* client_new (Socket * client_sock, int page_size, char * file_name, int server_port, char * server_address)
Create and initialise a +Client+ structure to represent a single client.
Parameters
client_sock the socket associated to the client transmission (from libocomm). The client_sock should be attached to an active client that has been accepted by the server socket.
page_size the page size for the underlying memory store for buffering received measurements.
file_name save measurements to a file with this name.
server_port the port of the downstream OML server
server_address the address of the downstream OML Server
Returns
a new Client structure
Definition at line 45 of file proxy_client.c.
References C_HEADER, cbuf_create(), mbuf_create(), msg_queue_create(), oml_malloc(), and oml_strndup().
Referenced by main(), and on_connect().
{
  Client* self = (Client *)oml_malloc(sizeof(Client));
  memset(self, 0, sizeof(Client));
  self->state = C_HEADER;
  self->downstream_port = server_port;
  self->downstream_addr = oml_strndup (server_address, strlen (server_address));
  self->mbuf = mbuf_create ();
  self->headers = NULL;
  self->msg_start = dummy_read_msg_start;
  self->messages = msg_queue_create ();
  self->cbuf = cbuf_create (page_size);
  self->file = fopen(file_name, "wa");
  self->file_name =  oml_strndup (file_name, strlen (file_name));
  self->recv_socket = client_sock;
  /* FIXME:  Return value checking */
  pthread_mutex_init (&self->mutex, NULL);
  pthread_cond_init (&self->condvar, NULL);
  return self;
}