oml2: psql_adapter.c File Reference
psql_adapter.c File Reference
Adapter code for the PostgreSQL database backend.
#include <math.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <inttypes.h>
#include <libpq-fe.h>
#include <time.h>
#include <sys/time.h>
#include <arpa/inet.h>
#include "ocomm/o_log.h"
#include "mem.h"
#include "mstring.h"
#include "guid.h"
#include "json.h"
#include "oml_value.h"
#include "oml_util.h"
#include "database.h"
#include "database_adapter.h"
#include "psql_adapter.h"
Macros
#define _GNU_SOURCE /* For NAN */
#define MAX_DIGITS 32
Functions
MString * psql_prepare (Database *db, DbTable *table)
int psql_backend_setup (void)
int psql_create_database (Database *db)
Variables
char * pg_host = DEFAULT_PG_HOST
char * pg_port = DEFAULT_PG_PORT
char * pg_user = DEFAULT_PG_USER
char * pg_pass = DEFAULT_PG_PASS
char * pg_conninfo = DEFAULT_PG_CONNINFO
Detailed Description
Adapter code for the PostgreSQL database backend.
Definition in file psql_adapter.c.
Macro Definition Documentation
#define _GNU_SOURCE /* For NAN */
Definition at line 15 of file psql_adapter.c.
#define MAX_DIGITS 32
Used as allocation size of strings to hold integers. XXX: We play it safe as INT64_MAX is 9223372036854775807, that is 19 characters
Definition at line 505 of file psql_adapter.c.
Function Documentation
int psql_backend_setup (void)
Setup the PostgreSQL backend.
Returns
0 on success, -1 otherwise
See Also
database_setup_backend
Definition at line 127 of file psql_adapter.c.
References logdebug(), logerror(), loginfo(), mstring_buf(), mstring_create(), mstring_delete(), mstring_sprintf(), pg_conninfo, pg_host, pg_pass, pg_port, pg_user, and str.
Referenced by database_setup_backend().
{
  MString *str, *conninfo;
  loginfo ("psql: Sending experiment data to PostgreSQL server %s:%s as user '%s'\n",
           pg_host, pg_port, pg_user);
  conninfo = psql_prepare_conninfo("postgres", pg_host, pg_port, pg_user, pg_pass, pg_conninfo);
  PGconn *conn = PQconnectdb (mstring_buf (conninfo));
  if (PQstatus (conn) != CONNECTION_OK) {
    logerror ("psql: Could not connect to PostgreSQL database (conninfo \"%s\"): %s", /* PQerrorMessage strings already have '\n'  */
         mstring_buf(conninfo), PQerrorMessage (conn));
    mstring_delete(conninfo);
    return -1;
  }
  /* oml2-server must be able to create new databases, so check that
     our user has the required role attributes */
  str = mstring_create();
  mstring_sprintf (str, "SELECT rolcreatedb FROM pg_roles WHERE rolname='%s'", pg_user);
  PGresult *res = PQexec (conn, mstring_buf (str));
  mstring_delete(str);
  if (PQresultStatus (res) != PGRES_TUPLES_OK) {
    logerror ("psql: Failed to determine role privileges for role '%s': %s", /* PQerrorMessage strings already have '\n'  */
         pg_user, PQerrorMessage (conn));
    return -1;
  }
  char *has_create = PQgetvalue (res, 0, 0);
  if (strcmp (has_create, "t") == 0)
    logdebug ("psql: User '%s' has CREATE DATABASE privileges\n", pg_user);
  else {
    logerror ("psql: User '%s' does not have required role CREATE DATABASE\n", pg_user);
    return -1;
  }
  mstring_delete(conninfo);
  PQclear (res);
  PQfinish (conn);
  return 0;
}
int psql_create_database (Database * db)
Create or open an PostgreSQL database
See Also
db_adapter_create
Definition at line 242 of file psql_adapter.c.
References Database::add_sender_id, Database::backend_name, Database::create, dba_begin_transaction(), dba_table_create_meta(), Database::get_metadata, Database::get_table_list, Database::get_uri, Database::handle, Database::insert, logerror(), loginfo(), mstring_buf(), mstring_create(), mstring_delete(), mstring_set(), mstring_sprintf(), Database::name, Database::o2t, oml_malloc(), pg_conninfo, pg_host, pg_pass, pg_port, pg_user, Database::prepare, Database::prepared_var, psql_create_database(), psql_prepare(), Database::release, Database::set_metadata, Database::stmt, str, Database::t2o, Database::table_create, Database::table_create_meta, and Database::table_free.
Referenced by psql_create_database().
{
  MString *conninfo = NULL;
  MString *str = NULL;
  PGconn  *conn = NULL;
  PGresult *res = NULL;
  int ret = -1;
  loginfo ("psql:%s: Accessing database\n", db->name);
  /*
   * Make a connection to the database server -- check if the
   * requested database exists or not by connecting to the 'postgres'
   * database and querying that.
   */
  conninfo = psql_prepare_conninfo("postgres", pg_host, pg_port, pg_user, pg_pass, pg_conninfo);
  conn = PQconnectdb(mstring_buf (conninfo));
  /* Check to see that the backend connection was successfully made */
  if (PQstatus(conn) != CONNECTION_OK) {
    logerror ("psql: Could not connect to PostgreSQL database (conninfo \"%s\"): %s", /* PQerrorMessage strings already have '\n'  */
         mstring_buf(conninfo), PQerrorMessage (conn));
    goto cleanup_exit;
  }
  PQsetNoticeReceiver(conn, psql_receive_notice, "postgres");
  str = mstring_create();
  mstring_sprintf (str, "SELECT datname from pg_database where datname='%s';", db->name);
  res = PQexec (conn, mstring_buf (str));
  if (PQresultStatus (res) != PGRES_TUPLES_OK) {
    logerror ("psql: Could not get list of existing databases\n");
    goto cleanup_exit;
  }
  /* No result rows means database doesn't exist, so create it instead */
  if (PQntuples (res) == 0) {
    loginfo ("psql:%s: Database does not exist, creating it\n", db->name);
    mstring_set (str, "");
    mstring_sprintf (str, "CREATE DATABASE \"%s\";", db->name);
    res = PQexec (conn, mstring_buf (str));
    if (PQresultStatus (res) != PGRES_COMMAND_OK) {
      logerror ("psql:%s: Could not create database: %s", /* PQerrorMessage strings already have '\n'  */
          db->name, PQerrorMessage (conn));
      goto cleanup_exit;
    }
  }
  mstring_delete(str);
  str = NULL;
  PQfinish (conn);
  mstring_delete(conninfo);
  /* Now that the database should exist, make a connection to the it for real */
  conninfo = psql_prepare_conninfo(db->name, pg_host, pg_port, pg_user, pg_pass, pg_conninfo);
  conn = PQconnectdb(mstring_buf (conninfo));
  /* Check to see that the backend connection was successfully made */
  if (PQstatus(conn) != CONNECTION_OK) {
    logerror ("psql:%s: Could not connect to PostgreSQL database (conninfo \"%s\"): %s",
  /* PQerrorMessage strings already have '\n'  */
        db->name, mstring_buf(conninfo), PQerrorMessage (conn));
    goto cleanup_exit;
  }
  PQsetNoticeReceiver(conn, psql_receive_notice, db->name);
  mstring_delete(conninfo);
  conninfo = NULL;
  PsqlDB* self = (PsqlDB*)oml_malloc(sizeof(PsqlDB));
  self->conn = conn;
  self->last_commit = time (NULL);
  db->backend_name = backend_name;
  db->o2t = psql_oml_to_type;
  db->t2o = psql_type_to_oml;
  db->stmt = psql_stmt;
  db->create = psql_create_database;
  db->release = psql_release;
  db->prepared_var = psql_prepared_var;
  db->table_create = psql_table_create;
  db->table_create_meta = dba_table_create_meta;
  db->table_free = psql_table_free;
  db->prepare = psql_prepare;
  db->insert = psql_insert;
  db->add_sender_id = psql_add_sender_id;
  db->get_metadata = psql_get_metadata;
  db->set_metadata = psql_set_metadata;
  db->get_uri = psql_get_uri;
  db->get_table_list = psql_get_table_list;
  db->handle = self;
  dba_begin_transaction (db);
  /* Everything was successufl, prepare for cleanup */
  ret = 0;
cleanup_exit:
  if (res) { PQclear (res) ; }
  if (ret) { PQfinish (conn); } /* If return !=0, cleanup connection */
  if (str) { mstring_delete (str); }
  if (conninfo) { mstring_delete (conninfo); }
  /* All paths leading to here have conn uninitialised */
  return ret;
}
MString * psql_prepare (Database * db, DbTable * table)
Prepare an INSERT statement for a given table
The returned value is to be destroyed by the caller.
Parameters
db Database
table DbTable adapter for the target SQLite3 table
Returns
an MString containing the prepared statement, or NULL on error
See Also
mstring_create, mstring_delete
Definition at line 518 of file psql_adapter.c.
References Database::backend_name, schema::fields, logdebug2(), logerror(), mstring_buf(), mstring_cat(), mstring_create(), mstring_delete(), mstring_sprintf(), schema_field::name, schema::name, Database::name, schema::nfields, oml_free(), Database::prepared_var, and DbTable::schema.
Referenced by psql_create_database().
{
  MString* mstr = mstring_create ();
  int n = 0, i = 0;
  int max = table->schema->nfields;
  char *pvar;
  if (max <= 0) {
    logerror ("%d: Trying to insert 0 values into table %s\n",
        db->backend_name, table->schema->name);
    goto fail_exit;
  }
  if (mstr == NULL) {
    logerror("%d: Failed to create managed string for preparing SQL INSERT statement\n",
        db->backend_name);
    goto fail_exit;
  }
  /* Build SQL "INSERT INTO" statement */
    n += mstring_sprintf (mstr,
        "INSERT INTO \"%s\" (\"oml_sender_id\", \"oml_seq\", \"oml_ts_client\", \"oml_ts_server\"",
        table->schema->name);
    /* Add specific column names */
    for (i=0; i<max; i++) {
      n += mstring_sprintf (mstr, ", \"%s\"", table->schema->fields[i].name);
    }
    /* Close column names, and add variables for the prepared statement */
    pvar = db->prepared_var(db, 1);
    n += mstring_sprintf (mstr, ") VALUES (%s", pvar);
    oml_free(pvar); /* XXX: Not really efficient, but we only do this rarely */
    max += 4; /* Number of metadata columns we want to be able to insert */
    for (i=2; i<=max; i++) {
      pvar = db->prepared_var(db, i);
      n += mstring_sprintf (mstr, ", %s", pvar);
      oml_free(pvar);
    }
    /* We're done */
    n += mstring_cat (mstr, ");");
    logdebug2("%s:%s: Prepared insert statement for table %s: %s\n",
      db->backend_name, db->name, table->schema->name, mstring_buf(mstr));
  if (n != 0) {
    /* mstring_* return -1 on error, with no error, the sum in n should be 0 */
    goto fail_exit;
  }
  return mstr;
 fail_exit:
  if (mstr) mstring_delete (mstr);
  return NULL;
}
Variable Documentation
char* pg_conninfo = DEFAULT_PG_CONNINFO
Definition at line 43 of file psql_adapter.c.
Referenced by main(), psql_backend_setup(), and psql_create_database().
char* pg_host = DEFAULT_PG_HOST
Definition at line 39 of file psql_adapter.c.
Referenced by psql_backend_setup(), and psql_create_database().
char* pg_pass = DEFAULT_PG_PASS
Definition at line 42 of file psql_adapter.c.
Referenced by main(), psql_backend_setup(), and psql_create_database().
char* pg_port = DEFAULT_PG_PORT
Definition at line 40 of file psql_adapter.c.
Referenced by psql_backend_setup(), and psql_create_database().
char* pg_user = DEFAULT_PG_USER
Definition at line 41 of file psql_adapter.c.
Referenced by psql_backend_setup(), and psql_create_database().