oml2: psql_adapter.h File Reference
psql_adapter.h File Reference
#include <libpq-fe.h>
#include "database.h"
Data Structures
struct PsqlDB
struct PsqlTable
Macros
#define DEFAULT_PG_HOST "localhost"
#define DEFAULT_PG_PORT "postgresql"
#define DEFAULT_PG_USER "oml"
#define DEFAULT_PG_PASS ""
#define DEFAULT_PG_CONNINFO ""
Typedefs
typedef struct PsqlDB PsqlDB
typedef struct PsqlTable PsqlTable
Functions
int psql_backend_setup ()
int psql_create_database (Database *db)
Macro Definition Documentation
#define DEFAULT_PG_CONNINFO ""
Definition at line 21 of file psql_adapter.h.
#define DEFAULT_PG_HOST "localhost"
Definition at line 17 of file psql_adapter.h.
#define DEFAULT_PG_PASS ""
Definition at line 20 of file psql_adapter.h.
#define DEFAULT_PG_PORT "postgresql"
Definition at line 18 of file psql_adapter.h.
#define DEFAULT_PG_USER "oml"
Definition at line 19 of file psql_adapter.h.
Typedef Documentation
typedef struct PsqlDB PsqlDB
typedef struct PsqlTable PsqlTable
Function Documentation
int psql_backend_setup (void)
Setup the PostgreSQL backend.
Returns
0 on success, -1 otherwise
See Also
database_setup_backend
Definition at line 127 of file psql_adapter.c.
References logdebug(), logerror(), loginfo(), mstring_buf(), mstring_create(), mstring_delete(), mstring_sprintf(), pg_conninfo, pg_host, pg_pass, pg_port, pg_user, and str.
Referenced by database_setup_backend().
{
  MString *str, *conninfo;
  loginfo ("psql: Sending experiment data to PostgreSQL server %s:%s as user '%s'\n",
           pg_host, pg_port, pg_user);
  conninfo = psql_prepare_conninfo("postgres", pg_host, pg_port, pg_user, pg_pass, pg_conninfo);
  PGconn *conn = PQconnectdb (mstring_buf (conninfo));
  if (PQstatus (conn) != CONNECTION_OK) {
    logerror ("psql: Could not connect to PostgreSQL database (conninfo \"%s\"): %s", /* PQerrorMessage strings already have '\n'  */
         mstring_buf(conninfo), PQerrorMessage (conn));
    mstring_delete(conninfo);
    return -1;
  }
  /* oml2-server must be able to create new databases, so check that
     our user has the required role attributes */
  str = mstring_create();
  mstring_sprintf (str, "SELECT rolcreatedb FROM pg_roles WHERE rolname='%s'", pg_user);
  PGresult *res = PQexec (conn, mstring_buf (str));
  mstring_delete(str);
  if (PQresultStatus (res) != PGRES_TUPLES_OK) {
    logerror ("psql: Failed to determine role privileges for role '%s': %s", /* PQerrorMessage strings already have '\n'  */
         pg_user, PQerrorMessage (conn));
    return -1;
  }
  char *has_create = PQgetvalue (res, 0, 0);
  if (strcmp (has_create, "t") == 0)
    logdebug ("psql: User '%s' has CREATE DATABASE privileges\n", pg_user);
  else {
    logerror ("psql: User '%s' does not have required role CREATE DATABASE\n", pg_user);
    return -1;
  }
  mstring_delete(conninfo);
  PQclear (res);
  PQfinish (conn);
  return 0;
}
int psql_create_database (Database * db)
Create or open an PostgreSQL database
See Also
db_adapter_create
Definition at line 242 of file psql_adapter.c.
References Database::add_sender_id, Database::backend_name, Database::create, dba_begin_transaction(), dba_table_create_meta(), Database::get_metadata, Database::get_table_list, Database::get_uri, Database::handle, Database::insert, logerror(), loginfo(), mstring_buf(), mstring_create(), mstring_delete(), mstring_set(), mstring_sprintf(), Database::name, Database::o2t, oml_malloc(), pg_conninfo, pg_host, pg_pass, pg_port, pg_user, Database::prepare, Database::prepared_var, psql_create_database(), psql_prepare(), Database::release, Database::set_metadata, Database::stmt, str, Database::t2o, Database::table_create, Database::table_create_meta, and Database::table_free.
Referenced by psql_create_database().
{
  MString *conninfo = NULL;
  MString *str = NULL;
  PGconn  *conn = NULL;
  PGresult *res = NULL;
  int ret = -1;
  loginfo ("psql:%s: Accessing database\n", db->name);
  /*
   * Make a connection to the database server -- check if the
   * requested database exists or not by connecting to the 'postgres'
   * database and querying that.
   */
  conninfo = psql_prepare_conninfo("postgres", pg_host, pg_port, pg_user, pg_pass, pg_conninfo);
  conn = PQconnectdb(mstring_buf (conninfo));
  /* Check to see that the backend connection was successfully made */
  if (PQstatus(conn) != CONNECTION_OK) {
    logerror ("psql: Could not connect to PostgreSQL database (conninfo \"%s\"): %s", /* PQerrorMessage strings already have '\n'  */
         mstring_buf(conninfo), PQerrorMessage (conn));
    goto cleanup_exit;
  }
  PQsetNoticeReceiver(conn, psql_receive_notice, "postgres");
  str = mstring_create();
  mstring_sprintf (str, "SELECT datname from pg_database where datname='%s';", db->name);
  res = PQexec (conn, mstring_buf (str));
  if (PQresultStatus (res) != PGRES_TUPLES_OK) {
    logerror ("psql: Could not get list of existing databases\n");
    goto cleanup_exit;
  }
  /* No result rows means database doesn't exist, so create it instead */
  if (PQntuples (res) == 0) {
    loginfo ("psql:%s: Database does not exist, creating it\n", db->name);
    mstring_set (str, "");
    mstring_sprintf (str, "CREATE DATABASE \"%s\";", db->name);
    res = PQexec (conn, mstring_buf (str));
    if (PQresultStatus (res) != PGRES_COMMAND_OK) {
      logerror ("psql:%s: Could not create database: %s", /* PQerrorMessage strings already have '\n'  */
          db->name, PQerrorMessage (conn));
      goto cleanup_exit;
    }
  }
  mstring_delete(str);
  str = NULL;
  PQfinish (conn);
  mstring_delete(conninfo);
  /* Now that the database should exist, make a connection to the it for real */
  conninfo = psql_prepare_conninfo(db->name, pg_host, pg_port, pg_user, pg_pass, pg_conninfo);
  conn = PQconnectdb(mstring_buf (conninfo));
  /* Check to see that the backend connection was successfully made */
  if (PQstatus(conn) != CONNECTION_OK) {
    logerror ("psql:%s: Could not connect to PostgreSQL database (conninfo \"%s\"): %s",
  /* PQerrorMessage strings already have '\n'  */
        db->name, mstring_buf(conninfo), PQerrorMessage (conn));
    goto cleanup_exit;
  }
  PQsetNoticeReceiver(conn, psql_receive_notice, db->name);
  mstring_delete(conninfo);
  conninfo = NULL;
  PsqlDB* self = (PsqlDB*)oml_malloc(sizeof(PsqlDB));
  self->conn = conn;
  self->last_commit = time (NULL);
  db->backend_name = backend_name;
  db->o2t = psql_oml_to_type;
  db->t2o = psql_type_to_oml;
  db->stmt = psql_stmt;
  db->create = psql_create_database;
  db->release = psql_release;
  db->prepared_var = psql_prepared_var;
  db->table_create = psql_table_create;
  db->table_create_meta = dba_table_create_meta;
  db->table_free = psql_table_free;
  db->prepare = psql_prepare;
  db->insert = psql_insert;
  db->add_sender_id = psql_add_sender_id;
  db->get_metadata = psql_get_metadata;
  db->set_metadata = psql_set_metadata;
  db->get_uri = psql_get_uri;
  db->get_table_list = psql_get_table_list;
  db->handle = self;
  dba_begin_transaction (db);
  /* Everything was successufl, prepare for cleanup */
  ret = 0;
cleanup_exit:
  if (res) { PQclear (res) ; }
  if (ret) { PQfinish (conn); } /* If return !=0, cleanup connection */
  if (str) { mstring_delete (str); }
  if (conninfo) { mstring_delete (conninfo); }
  /* All paths leading to here have conn uninitialised */
  return ret;
}