oml2: receiver.c File Reference
receiver.c File Reference
Functions responsible for implementing the receive loop that reads stores meessages in the message queue.
#include <string.h>
#include "ocomm/o_log.h"
#include "mem.h"
#include "mbuf.h"
#include "headers.h"
#include "message.h"
#include "text.h"
#include "binary.h"
#include "message_queue.h"
#include "proxy_client.h"
Functions
int read_header (Client *self, MBuffer *mbuf)
enum ContentType content_from_string (const char *str)
void store_received_message (Client *client, struct oml_message *msg, char *buf, size_t length)
void proxy_message_loop (const char *client_id, Client *client, void *buf, size_t size)
Detailed Description
Functions responsible for implementing the receive loop that reads stores meessages in the message queue.
Definition in file receiver.c.
Function Documentation
enum ContentType content_from_string (const char * str)
Convert a content header into the correct symbol type.
Parameters
str the string represention of the content type, either "text" or "binary".
Returns
The symbolic representation of the content type, either CONTENT_BINARY, CONTENT_TEXT, or CONTENT_NONE to indicate an unrecognized content type string.
Definition at line 109 of file receiver.c.
References CONTENT_BINARY, CONTENT_NONE, and CONTENT_TEXT.
Referenced by proxy_message_loop().
{
  if (str == NULL)
    return CONTENT_NONE;
  if (strcmp (str, "binary") == 0)
    return CONTENT_BINARY;
  else if (strcmp (str, "text") == 0)
    return CONTENT_TEXT;
  return CONTENT_NONE;
}
void proxy_message_loop (const char * client_id, Client * client, void * buf, size_t size)
Definition at line 145 of file receiver.c.
References bin_read_msg_start(), C_CONFIGURE, C_DATA, C_HEADER, C_PROTOCOL_ERROR, _client::content, CONTENT_BINARY, content_from_string(), CONTENT_NONE, CONTENT_TEXT, _client::domain, H_CONTENT, H_DOMAIN, H_NONE, header, _client::header_table, _client::headers, oml_message::length, logdebug(), logerror(), loop, _client::mbuf, mbuf_clear(), mbuf_consume_message(), mbuf_rdptr(), mbuf_read_skip(), mbuf_reset_read(), mbuf_write(), _client::msg_start, header::next, read_header(), oml_message::seqno, _client::state, store_received_message(), oml_message::stream, header::tag, tag_to_string(), text_read_msg_start(), oml_message::timestamp, and header::value.
Referenced by client_callback(), and main().
{
  MBuffer *mbuf = client->mbuf;
  struct header *header;
  struct oml_message msg;
  int result;
  size_t message_length;
  result = mbuf_write (mbuf, buf, size);
  if (result == -1) {
    logerror ("'%s': Failed to write message from client into message buffer. Data is being lost!\n",
              client_id);
    return;
  }
 loop:
  switch (client->state) {
  case C_HEADER:
    /* Read headers until out of header data to read*/
    while (read_header (client, mbuf) == 1);
    if (client->state != C_HEADER)
      goto loop;
    break;
  case C_CONFIGURE:
    if (client->header_table[H_DOMAIN] == NULL ||
        client->header_table[H_CONTENT] == NULL ||
        client->header_table[H_DOMAIN]->tag == H_NONE ||
        client->header_table[H_CONTENT]->tag == H_NONE) {
      if (client->headers == NULL) {
        logdebug ("Headers NULL!");
      }
      client->state = C_PROTOCOL_ERROR;
    } else {
      client->domain = client->header_table[H_DOMAIN]->value;
      client->content = content_from_string (client->header_table[H_CONTENT]->value);
      if (client->content == CONTENT_NONE)
        client->state = C_PROTOCOL_ERROR;
    }
    if (client->state != C_PROTOCOL_ERROR) {
      logdebug ("%s\n", client->domain);
      logdebug ("%d\n", client->content);
    } else {
      logdebug ("Can't write out domain and content because of protocol error in input\n");
      logdebug ("Input is: '%s'\n", buf);
    }
    for (header = client->headers; header != NULL; header = header->next) {
      logdebug ("HEADER:  '%s' : '%s'\n",
                tag_to_string(header->tag),
                header->value);
    }
    switch (client->content){
    case CONTENT_TEXT:
      client->msg_start = text_read_msg_start;
      break;
    case CONTENT_BINARY:
      client->msg_start = bin_read_msg_start;
      break;
    default:
      /* Default is set when client is created (client_new()) */
      logerror ("Client content is not TEXT or BINARY\n");
      break;
    }
    mbuf_consume_message (mbuf); // Next message starts after the headers.
    client->state = C_DATA;
    break;
  case C_DATA:
    result = client->msg_start (&msg, mbuf);
    if (result == -1) {
      logerror ("'%s': protocol error in received message\n", client_id);
      client->state = C_PROTOCOL_ERROR;
      goto loop;
    } else if (result == 0) {
      // Try again when we get more data.
      logdebug ("'%s': need more data\n", client_id);
      mbuf_reset_read (mbuf);
      return;
    } else {
      logdebug ("'%s': received message of length %d\n", client_id, result);
      message_length = result;
    }
    logdebug ("Received [strm=%d seqno=%d ts=%f %d bytes]\n",
              msg.stream, msg.seqno, msg.timestamp, msg.length);
    mbuf_reset_read (mbuf);
    store_received_message (client, &msg, (char*)mbuf_rdptr (mbuf), message_length);
    mbuf_read_skip (mbuf, message_length);
    mbuf_consume_message (mbuf);
    break;
  case C_PROTOCOL_ERROR:
    logdebug ("'%s': protocol error!\n");
    break;
  default:
    logerror ("'%s': unknown client state '%d'\n", client_id, client->state);
    mbuf_clear (mbuf);
    return;
  }
}
int read_header (Client * self, MBuffer * mbuf)
Definition at line 58 of file receiver.c.
References C_CONFIGURE, C_PROTOCOL_ERROR, H_NONE, header, header_from_string(), logerror(), mbuf_find(), mbuf_find_not(), mbuf_read_skip(), header::next, and header::tag.
Referenced by proxy_message_loop().
{
  char *line;
  int len;
  struct header *header;
  if (self == NULL || mbuf == NULL) {
    logerror ("read_header():  NULL client or input buffer.\n");
    return 0;
  }
  if (read_line (&line, &len, mbuf) == -1)
    return 0;
  if (len == 0) {
    // Empty line denotes separator between header and body
    int skip_count = mbuf_find_not (mbuf, '\n');
    if (skip_count == -1) {
      while (mbuf_find (mbuf, '\n') != (size_t)-1)
        mbuf_read_skip (mbuf, 1);
    } else {
      mbuf_read_skip (mbuf, skip_count);
    }
    self->state = C_CONFIGURE;
    return 0;
  }
  header = header_from_string (line, len);
  mbuf_read_skip (mbuf, len + 1);
  if (header == NULL) {
    /* Could be protocol error (not ':'), memory alloc error, or unknown tag */
    self->state = C_PROTOCOL_ERROR;
    return -1;
  }
  /* Store the header for later processing */
  header->next = self->headers;
  self->headers = header;
  if (header->tag != H_NONE) {
    self->header_table[header->tag] = header;
  }
  return 1; // still in header
}
void store_received_message (Client * client, struct oml_message * msg, char * buf, size_t length)
Store a received OML message into the client's message queue.
Definition at line 127 of file receiver.c.
References _client::cbuf, cbuf_write(), cbuf_write_cursor(), msg_queue_node::cursor, _client::messages, msg_queue_node::msg, msg_queue_add(), _client::mutex, and oml_malloc().
Referenced by proxy_message_loop().
{
  struct msg_queue *queue = client->messages;
  struct msg_queue_node *node;
  pthread_mutex_lock (&client->mutex);
  node = msg_queue_add (queue);
  cbuf_write_cursor (client->cbuf, &node->cursor);
  cbuf_write (client->cbuf, buf, length);
  node->msg = oml_malloc (sizeof (struct oml_message));
  *node->msg = *msg;
  pthread_mutex_unlock (&client->mutex);
}