oml2: schema.c File Reference
schema.c File Reference
Manipulate schema structures, and convert to/from string or SQL representation.
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "ocomm/o_log.h"
#include "mem.h"
#include "mstring.h"
#include "oml_value.h"
#include "schema.h"
#include "oml_util.h"
Functions
void add_oml_sem_def (OMLSemDef **list, OMLSemDef *element)
int schema_field_from_meta (const char *meta, size_t len, struct schema_field *field)
struct schema * schema_from_meta (const char *meta)
char * schema_to_meta (const struct schema *schema)
MString * schema_to_sql (const struct schema *schema, reverse_typemap o2t)
struct schema * schema_from_sql (const char *sql, OmlValueT(*t2o)(const char *s))
struct schema * schema_new (const char *name)
OMLSemDef * destroy_sem_concepts (OMLSemDef *sd)
void schema_free (struct schema *schema)
int schema_add_field (struct schema *schema, const char *name, OmlValueT type)
struct schema * schema_copy (const struct schema *schema)
int schema_diff (struct schema *s1, struct schema *s2)
Detailed Description
Manipulate schema structures, and convert to/from string or SQL representation.
Definition in file schema.c.
Function Documentation
void add_oml_sem_def (OMLSemDef ** list, OMLSemDef * element)
Add an Semantic-OML concept.
Parameters
meta nil-terminated string to parse
list list of concepts to add
element to add
Returns
0 on success, -1 on failure.
Author
Mario Poyato Pino mario.nosp@m..poy.nosp@m.ato@e.nosp@m.stud.nosp@m.iante.nosp@m..uam.nosp@m..es
Definition at line 133 of file schema.c.
References OMLSemDef::next.
Referenced by schema_copy().
{
    if (!*list) // if empty list
        *list = element;
    else
    {
        element->next = (*list)->next;
        (*list)->next = element;
    }
    return ;
}
OMLSemDef* destroy_sem_concepts (OMLSemDef * sd)
Definition at line 589 of file schema.c.
References OMLSemDef::next, OMLSemDef::object, oml_free(), OMLSemDef::predicate, and OMLSemDef::subject.
{
    OMLSemDef *sd_aux = NULL;
    if (sd)
    {
        oml_free(sd->subject);
        oml_free(sd->predicate);
        oml_free(sd->object);
        sd_aux = sd->next;
        oml_free(sd);
    }
    return sd_aux;
}
int schema_add_field (struct schema * schema, const char * name, OmlValueT type)
Add a field to an existing schema.
Parameters
schema schema to add a field to
name name of that field
type OmlValueT representing the type of that field
Returns
0 un success, -1 otherwise
Definition at line 634 of file schema.c.
References schema_field::concepts, schema::fields, schema_field::name, schema::nfields, oml_realloc(), oml_strndup(), schema_field::type, and type.
{
  if (!schema || !name) return -1;
  size_t fields_size = (schema->nfields + 1) * sizeof (struct schema_field);
  struct schema_field *new = oml_realloc (schema->fields, fields_size);
  if (!new) return -1;
  schema->fields = new;
  schema->fields[schema->nfields].name = oml_strndup (name, strlen (name));
  schema->fields[schema->nfields].type = type;
  schema->fields[schema->nfields].concepts = NULL;
  if (!schema->fields[schema->nfields].name) return -1;
  schema->nfields += 1;
  return 0;
}
struct schema* schema_copy (const struct schema * schema) read
Deep copy of an existing schema structure
Parameters
schema schema structur to copy
Returns
a new oml_malloc'd copy (to be cleaned by the caller), or NULL
Definition at line 655 of file schema.c.
References add_oml_sem_def(), schema_field::concepts, schema::fields, schema::index, schema_field::name, schema::name, OMLSemDef::next, schema::nfields, OMLSemDef::object, oml_calloc(), oml_free(), oml_malloc(), oml_strndup(), OMLSemDef::predicate, OMLSemDef::subject, and schema_field::type.
Referenced by database_create_table(), database_find_or_create_table(), database_init(), and dba_table_create_from_schema().
{
  OMLSemDef*osd,*new_osd;
  struct schema *new;
  int i;
  if (!schema) { return NULL; }
  new = oml_malloc (sizeof (struct schema));
  if (!new) { return NULL; }
  new->name = oml_strndup (schema->name, strlen (schema->name));
  new->index = schema->index;
  new->nfields = schema->nfields;
  new->fields = oml_calloc (new->nfields, sizeof (struct schema_field));
  if (!new->name || !new->fields) {
    goto exit;
  }
  for (i = 0; i < new->nfields; i++) {
    new->fields[i].name = oml_strndup (schema->fields[i].name, strlen (schema->fields[i].name));
    if (!new->fields[i].name) {
      goto exit;
    }
    new->fields[i].concepts = NULL;
    new->fields[i].nconcepts = 0;
    osd = schema->fields[i].concepts;
    while(osd!=NULL)
    {
        new_osd = (OMLSemDef*)oml_malloc(sizeof(OMLSemDef));
        new_osd->subject = oml_strndup (osd->subject, strlen (osd->subject));
        new_osd->predicate = oml_strndup (osd->predicate, strlen (osd->predicate));
        new_osd->object = oml_strndup (osd->object, strlen (osd->object));
        new_osd->next = NULL;
        add_oml_sem_def(&new->fields[i].concepts,new_osd);
        (new->fields[i].nconcepts)++;
        osd = osd->next;
    }
    new->fields[i].type = schema->fields[i].type;
  }
  return new;
 exit:
  /* new has been successfully allocated if we reach here */
  if (new->name) { oml_free (new->name); }
  if (new->fields) {
    for (i = 0; i < new->nfields; i++) {
      if (new->fields[i].name) {
        oml_free (new->fields[i].name);
      }
    }
    oml_free (new->fields);
  }
  oml_free (new);
  return NULL;
}
int schema_diff (struct schema * s1, struct schema * s2)
Compare two schemas.
Schema are equal if they have the same names and identical field names/numbers/types. They may have a different index and still be considered equal.
If the schema are the same object, or if the schema are identical in a deep compare sense as outlined above, return 0.
If either s1 or s2 is NULL, or if their names differ, or if they differ in number of fields, or if either's fields vector is NULL, return -1.
If s1 and s2 have differing field names and/or types, return the column number of the field that differs (fields are numbered from 1 in this case to distinguish from return value 0, corresponding to "schema are equal".).
Parameters
s1 first schema structure
s2 second schema structure
Returns
0 on equality, -1 on error, or a positive index+1 of the first mismatching field
Definition at line 733 of file schema.c.
References schema::fields, schema_field::name, schema::name, schema::nfields, and schema_field::type.
Referenced by database_find_or_create_table().
{
  int i=0, nfields = 0, diffn=0;
  if (s1 == s2) return 0;
  if (!s1 || !s2) return -1;
  if (strcmp (s1->name, s2->name)) return -1;
  if (s1->fields && s2->fields) {
    if (s1->nfields != s2->nfields) { diffn=1; }
    nfields = (s1->nfields<s2->nfields)?s1->nfields:s2->nfields;
    for (i = 0; i < nfields; i++) {
      if (strcmp (s1->fields[i].name, s2->fields[i].name) ||
          s1->fields[i].type != s2->fields[i].type) {
        return i+1;
      }
    }
    if (diffn) {
      /* The first differing field is the first one
       * beyond the shortest schema's */
      return nfields + 1;
    }
  } else {
    return -1;
  }
  return 0;
}
int schema_field_from_meta (const char * meta, size_t len, struct schema_field * field)
Parse a schema field like '<name>:<type>:<concepts>' into a struct schema_field.
Parameters
meta nil-terminated string to parse
len length to parse in the string
schema_field client-provided memory to store the parsed field
Returns
0 on success, -1 on failure.
Definition at line 191 of file schema.c.
References schema_field::concepts, find_charn(), if, schema_field::name, schema_field::nconcepts, oml_free(), OML_INT32_VALUE, OML_LONG_VALUE, oml_strndup(), oml_type_from_s(), OML_UNKNOWN_VALUE, schema_field::type, and type.
Referenced by schema_from_meta(), and START_TEST().
{
  char *type = NULL,*concepts=NULL;
  memset(field, 0, sizeof(struct schema_field));
  const char *p = meta, *q = (char*)find_charn (p, ':', len),*t;
  if (!q) {
    return -1;
  }
  field->name = oml_strndup (p, q++ - p);
  field->concepts = NULL;
  field->nconcepts = 0;
  // Check if meta has concepts
  if ((t=(char*)find_charn(q,':',len - (q - p))) != NULL)
  {
    type = oml_strndup (q, t-q);
    concepts = (len-(t-p) > 0) ? oml_strndup(t,len-(t-p)) : NULL;
    field->concepts = (concepts&&*concepts) ? sem_to_mpdef(concepts,&field->nconcepts) : NULL;
    if (field->concepts == NULL)
      field->nconcepts = 0;
  }
  else
    type = oml_strndup (q, len - (q - p));
  if (!field->name || !type) {
    goto exit;
  }
  field->type = oml_type_from_s (type);
  // OML_LONG_VALUE is deprecated, and converted to INT32 internally in server.
  field->type = (field->type == OML_LONG_VALUE) ? OML_INT32_VALUE : field->type;
  if (field->type == OML_UNKNOWN_VALUE) {
    goto exit;
  }
  oml_free (type);
  return 0;
 exit:
  if (field->name) {
    oml_free (field->name);
    field->name = NULL;
  }
  if (type) { oml_free (type); }
  return -1;
}
void schema_free (struct schema * schema)
Free an allocated schema structures
Parameters
schema schema structure to free
Definition at line 607 of file schema.c.
References schema::fields, schema_field::name, schema::name, schema::nfields, and oml_free().
Referenced by database_find_or_create_table(), database_table_free(), dba_table_create_from_meta(), dba_table_create_from_schema(), process_schema(), schema_from_meta(), schema_new(), table_descr_array_free(), and table_descr_list_free().
{
  if (schema) {
    if (schema->name) {
      oml_free (schema->name);
    }
    if (schema->fields) {
      int i;
      for (i = 0; i < schema->nfields; i++) {
        if (schema->fields[i].name) {
          oml_free (schema->fields[i].name);
        }
      }
      oml_free (schema->fields);
    }
    oml_free (schema);
  }
}
struct schema* schema_from_meta (const char * meta) read
Parse a schema metadata line from client headers.
Schema meta lines look like: schema: <n> <name> <field_name1>:<field_type1> <field_name2>:<field_type2> ... We get everything from the first colon ':' onwards in "meta" parameter.
Parameters
meta nil-terminated string to parse
Returns
a pointer to an oml_malloc'd struct schema, to be freed by the caller, or NULL on error (e.g., meta is NULL)
See Also
schema_field_from_meta
Definition at line 245 of file schema.c.
References schema::fields, find_white(), schema::index, schema::name, schema::nfields, oml_malloc(), oml_realloc(), oml_strndup(), schema, schema_field_from_meta(), schema_free(), and skip_white().
Referenced by dba_table_create_from_meta(), process_schema(), and START_TEST().
{
  if (!meta) return NULL;
  struct schema *schema = NULL;
  struct schema_field *f = NULL;
  size_t fields_size = 0;
  const char *p = meta;
  char *q;
  schema = oml_malloc (sizeof (struct schema));
  if (!schema) { goto exit; }
  schema->nfields = 0;
  schema->fields = NULL;
  /* Parse the schema index */
  schema->index = strtol (p, &q, 0);
  if (p == q) {
    return NULL; /* no digits found */
  }
  p = q;
  /* Get the name of the schema */
  p = (char*)skip_white (p);
  q = (char*)find_white (p);
  schema->name = oml_strndup (p, (q - p));
  if (!schema->name) { goto exit; }
  p = q;
  /* Parse the field definitions */
  while (q && *q) {
    p = (char*)skip_white (p);
    q = (char*)find_white (p);
    if (p != q) {
      schema->nfields++;
      fields_size += sizeof (struct schema_field);
      /* We need this intermediary to be able to free the previous block on failure */
      if (!(f = oml_realloc (schema->fields, fields_size))) {
        goto exit;
      }
      schema->fields = f;
      if (schema_field_from_meta (p, (q - p), &(schema->fields[schema->nfields-1])) == -1) {
        goto exit;
      }
      p = q;
    }
  }
  return schema;
 exit:
  if (schema) {
    schema_free(schema);
  }
  return NULL;
}
struct schema* schema_from_sql (const char * sql, OmlValueT(*)(const char *s) t2o) read
Parse an SQL input into a schema object.
Parameters
sql pointer to the start of the column specifier can be part of a longer string and does not have to be null terminated. There must be no leading whitespace.
t2o function pointer to the database adapter's SQL to OML type converter function
Returns
0 on success, -1 on failure.
Definition at line 490 of file schema.c.
References schema_field::concepts, schema::fields, find_white(), schema::index, schema_field::name, schema::name, name, schema::nfields, oml_free(), oml_malloc(), oml_realloc(), oml_strndup(), schema, and skip_white().
{
  const char * const command = "CREATE TABLE ";
  int command_len = strlen (command);
  /* Check that it's a CREATE TABLE statement */
  if (strncmp (sql, command, command_len)) return NULL;
  struct schema *schema = NULL;
  struct schema_field *fields = NULL;
  int nfields = 0;
  size_t fields_size = 0;
  char *name;
  char *p = (char *)sql + command_len, *up;
  char *q, *uq;
  p = (char*)skip_white (p);
  q = (char*)find_white (p);
  up = *p == '"' ? p+1 : p;
  uq = *(q-1) == '"' ? q-1 : q;
  name = oml_strndup (up, uq - up);
  p = q;
  p = (char*)skip_white (p);
  if (*p++ != '(') /* Opening paren of colspec */
    goto exit;
  q = p;
  while (q && *q && *q != ';') {
    p = (char*)skip_white (p);
    q = memchr (p, ',', strlen (p));
    if (q == NULL) {
      q = memchr (p, ')', strlen (p));
    }
    if (q != NULL) {
      fields_size = (nfields + 1) * sizeof (struct schema_field);
      struct schema_field *f = oml_realloc (fields, fields_size);
      if (!f)
        goto exit;
      fields = f;
      if (schema_field_from_sql (p, (q - p), &fields[nfields], t2o) == -1)
        goto exit;
      int n = schema_check_metadata (&fields[nfields]);
      if (n == -1)
        goto exit;
      /* n == 0 means metadata column (must be skipped here) */
      if (n == 0) {
        oml_free (fields[nfields].name);
        fields[nfields].name = NULL;
      }
      fields[nfields].concepts = NULL;
      nfields += n;
      p = ++q;
    }
  }
  schema = oml_malloc (sizeof (struct schema));
  if (!schema) goto exit;
  schema->name = name;
  schema->index = -1;
  schema->fields = fields;
  schema->nfields = nfields;
  return schema;
 exit:
  if (name) oml_free (name);
  if (fields) {
    int i = 0;
    for (; i < nfields; i++)
      if (fields[i].name)
        oml_free (fields[i].name);
    oml_free (fields);
  }
  oml_free (schema);
  return NULL;
}
struct schema* schema_new (const char * name) read
Create a new schema structure
Parameters
name name for that schema
Definition at line 572 of file schema.c.
References schema::index, schema::name, oml_malloc(), oml_strndup(), schema, and schema_free().
{
  struct schema *schema = oml_malloc (sizeof (struct schema));
  if (!schema) { goto exit; }
  memset(schema, 0, sizeof(struct schema));
  schema->name = oml_strndup (name, strlen (name));
  if (!schema->name) { goto exit; }
  schema->index = -1;
  return schema;
 exit:
  schema_free(schema);
  return NULL;
}
char* schema_to_meta (const struct schema * schema)
Create a string representation of a schema
Parameters
schema a schema structure to trancribe
Returns
a pointer to an oml_malloc'd string containing the schema; the caller should free the memory
Definition at line 306 of file schema.c.
References schema::fields, schema::index, mstring_buf(), mstring_create(), mstring_delete(), mstring_len(), mstring_sprintf(), schema_field::name, schema::name, schema::nfields, oml_strndup(), oml_type_to_s(), str, and schema_field::type.
Referenced by dba_table_create_from_schema().
{
  int i;
  char *s = NULL;
  if (!schema) return NULL;
  MString *str = mstring_create ();
  mstring_sprintf (str, "%d %s", schema->index, schema->name);
  if (schema->fields)
    for (i = 0; i < schema->nfields; i++) {
      mstring_sprintf (str, " %s:%s",
                       schema->fields[i].name,
                       oml_type_to_s (schema->fields[i].type));
    }
  else
    goto fail_exit;
  s = oml_strndup (mstring_buf (str), mstring_len (str));
  mstring_delete (str);
  return s;
 fail_exit:
  if (str)
    mstring_delete (str);
  return NULL;
}
MString* schema_to_sql (const struct schema * schema, reverse_typemap o2t)
Definition at line 398 of file schema.c.
References schema::fields, logerror(), mstring_cat(), mstring_create(), mstring_delete(), mstring_set(), mstring_sprintf(), schema_field::name, schema::name, name, schema::nfields, OML_DB_PRIMARY_KEY, OML_DOUBLE_VALUE, OML_INT32_VALUE, and schema_field::type.
Referenced by dba_table_create_from_schema().
{
  int n = 0;
  int max = schema->nfields;
  if (max <= 0) {
    logerror ("Tried to create SQL CREATE TABLE statement for schema with 0 columns\n");
    return NULL;
  }
  MString* mstr = mstring_create ();
  if (mstr == NULL) {
    logerror("Failed to create managed string for preparing SQL CREATE TABLE statement\n");
    return NULL;
  }
  /* Build SQL "CREATE TABLE" statement */
  n += mstring_set (mstr, "CREATE TABLE \"");
  n += mstring_cat (mstr, schema->name);
  n += mstring_sprintf (mstr, "\" (oml_tuple_id %s, ", o2t (OML_DB_PRIMARY_KEY));
  n += mstring_sprintf (mstr, "oml_sender_id %s, ", o2t (OML_INT32_VALUE));
  n += mstring_sprintf (mstr, "oml_seq %s, ", o2t (OML_INT32_VALUE));
  n += mstring_sprintf (mstr, "oml_ts_client %s, ", o2t (OML_DOUBLE_VALUE));
  n += mstring_sprintf (mstr, "oml_ts_server %s", o2t (OML_DOUBLE_VALUE));
  int i = 0;
  while (max > 0) {
    OmlValueT type = schema->fields[i].type;
    char *name = schema->fields[i].name;
    const char* t = o2t (type);
    if (!t) {
      logerror("Unknown type in column '%s'\n", name);
      goto fail_exit;
    }
    n += mstring_sprintf (mstr, ", \"%s\" %s", name, t);
    i++; max--;
  }
  n += mstring_cat (mstr, ");");
  if (n != 0) {
    /* mstring_* return -1 on error, with no error, the sum in n should be 0 */
    goto fail_exit;
  }
  return mstr;
 fail_exit:
  if (mstr) mstring_delete (mstr);
  return NULL;
}