oml2: socket.c File Reference
socket.c File Reference
OComm Socket (OSocket) are a thin abstraction layer that manages sockets and provides some additional state management functions.
#include <assert.h>
#include <sys/timeb.h>
#include <sys/stat.h>
#include <netdb.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <errno.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/ioctl.h>
#include <net/if.h>
#include <fcntl.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "mem.h"
#include "ocomm/o_log.h"
#include "ocomm/o_socket.h"
#include "ocomm/o_eventloop.h"
Data Structures
struct SocketInt
Macros
#define TRUE 1
#define FALSE !TRUE
#define MAX_SOCKET_INSTANCES 100
#define HOSTLEN 256 /* RFC 1035, section 2.3.4 + 1 */
#define ADDRLEN INET6_ADDRSTRLEN
#define SERVLEN 7 /* ndigits(65536) + 1 */
#define SOCKNAMELEN (HOSTLEN+SERVLEN+2)
Typedefs
typedef struct SocketInt SocketInt
Functions
int socket_set_non_blocking_mode (int flag)
int socket_get_non_blocking_mode ()
int socket_is_disconnected (Socket *socket)
int socket_is_listening (Socket *socket)
void socket_free (Socket *socket)
Socket * socket_new (const char *name, int is_tcp)
Socket * socket_in_new (const char *name, const char *node, const char *service, int is_tcp)
Socket * socket_tcp_out_new (const char *name, const char *dest, const char *service)
Socket * socket_server_new (const char *name, const char *node, const char *service, o_so_connect_callback callback, void *handle)
int socket_shutdown (Socket *socket)
int socket_close (Socket *socket)
int socket_sendto (Socket *socket, char *buf, int buf_size)
int socket_get_sockfd (Socket *socket)
uint16_t socket_get_port (Socket *s)
size_t socket_get_addr_sz (Socket *s)
void socket_get_peer_addr (Socket *s, char *addr, size_t addr_sz)
void socket_get_name (Socket *s, char *name, size_t namelen, int remote)
void sockaddr_get_name (const sockaddr_t *sa, socklen_t sa_len, char *name, size_t namelen)
Detailed Description
OComm Socket (OSocket) are a thin abstraction layer that manages sockets and provides some additional state management functions.
Functions for managing a group of sockets as a unit. Internally maintains a linked list of sockets which can be modified at.
Author
Max Ott (max@w.nosp@m.inla.nosp@m.b.rut.nosp@m.gers.nosp@m..edu), Olivier Mehani olivi.nosp@m.er.m.nosp@m.ehani.nosp@m.@nic.nosp@m.ta.co.nosp@m.m.au
Definition in file socket.c.
Macro Definition Documentation
#define ADDRLEN INET6_ADDRSTRLEN
Definition at line 46 of file socket.c.
Referenced by sockaddr_get_name().
#define FALSE !TRUE
Definition at line 41 of file socket.c.
#define HOSTLEN 256 /* RFC 1035, section 2.3.4 + 1 */
Definition at line 45 of file socket.c.
#define MAX_SOCKET_INSTANCES 100
Definition at line 44 of file socket.c.
#define SERVLEN 7 /* ndigits(65536) + 1 */
Definition at line 47 of file socket.c.
Referenced by sockaddr_get_name().
#define SOCKNAMELEN (HOSTLEN+SERVLEN+2)
Definition at line 48 of file socket.c.
Referenced by socket_get_addr_sz(), and socket_in_new().
#define TRUE 1
Definition at line 38 of file socket.c.
Referenced by socket_server_new(), and socket_tcp_out_new().
Typedef Documentation
typedef struct SocketInt SocketInt
Implementation of the Socket interface store communication related parameters and information.
Function Documentation
void sockaddr_get_name (const sockaddr_t * sa, socklen_t sa_len, char * name, size_t namelen)
Get the name (address+service) of a socket.
Parameters
sa sockaddr_t containig the data
sa_len length of sa
name memory buffer to return the string in (nil-terminated)
namelen length of nam, SOCKNAMELEN is a good idea
See Also
socket_get_name, getnameinfo(3)
Definition at line 707 of file socket.c.
References ADDRLEN, o_log, O_LOG_DEBUG, sockaddr_t::sa, and SERVLEN.
Referenced by socket_get_name(), and socket_in_new().
{
  char host[ADDRLEN], serv[SERVLEN];
  int ret;
  assert(sa);
  assert(name);
  *host = 0;
  *serv = 0;
  if (!(ret=getnameinfo(&sa->sa, sa_len,
        host, ADDRLEN, serv, SERVLEN,
        NI_NUMERICHOST|NI_NUMERICSERV))) {
    snprintf(name, namelen, "[%s]:%s", host, serv);
  } else {
    o_log(O_LOG_DEBUG, "Error converting sockaddr %p to name: %s\n", sa, gai_strerror(ret));
    snprintf(name, namelen, "AF%d", sa->sa.sa_family);
  }
}
int socket_close (Socket * socket)
Close the communication channel associated to an OSocket.
Parameters
socket Socket to close
Returns
0 on success, -1 otherwise
Definition at line 507 of file socket.c.
Referenced by client_callback(), socket_free(), and status_callback().
{
  SocketInt *self = (SocketInt*)socket;
  if (self->sockfd >= 0) {
    close(self->sockfd);
    // TODO: should check if close suceeds
    self->sockfd = -1;
  }
  return 0;
}
void socket_free (Socket * socket)
Terminate the Socket and free its allocated memory.
If the socket is still open, it will be closed.
Parameters
socket Socket to free
See Also
socket_new, socket_close
Definition at line 157 of file socket.c.
References oml_free(), and socket_close().
Referenced by client_free(), client_handler_free(), main(), and socket_in_new().
{
  SocketInt* self = (SocketInt *)socket;
  socket_close(socket);
  if (self->name) { oml_free(self->name); }
  if (self->dest) { oml_free(self->dest); }
  if (self->service) { oml_free(self->service); }
  if (self->results) { freeaddrinfo(self->results); }
  oml_free (self);
}
size_t socket_get_addr_sz (Socket * s)
Get the size needed to store a string representation of an OSocket's address
This is just a dummy function exposing SOCKNAMELEN
Parameters
s Socket under consideration
Definition at line 613 of file socket.c.
References SOCKNAMELEN.
Referenced by socket_get_peer_addr().
{
  assert(s);
  return SOCKNAMELEN;
}
void socket_get_name (Socket * s, char * name, size_t namelen, int remote)
Get the name (address+service) of an OSocket.
Parameters
s OSocket
name memory buffer to return the string in (nil-terminated)
namelen length of name, using socket_get_addr_sz() is a good idea
remote 0 if the local name is needed, non-zero for the remote peer
See Also
sockaddr_get_name, getsockname(3), socket_get_addr_sz
Definition at line 664 of file socket.c.
References logwarn(), Socket::name, sockaddr_t::sa, and sockaddr_get_name().
{
  sockaddr_t sa;
  socklen_t sa_len = sizeof(sa);
  SocketInt *self = (SocketInt*) s;
  assert(self);
  assert(name);
  assert(self->sockfd);
  memset(&sa, 0, sa_len);
  if(remote) {
    if(!getpeername(self->sockfd, &sa.sa, &sa_len)) {
      sockaddr_get_name(&sa, sa_len, name, namelen);
    } else {
      logwarn("%s: Cannot get details of socket peer: %s", s->name, strerror(errno));
      *name = 0;
    }
  } else {
    if(!getsockname(self->sockfd, &sa.sa, &sa_len)) {
      sockaddr_get_name(&sa, sa_len, name, namelen);
    } else {
      logwarn("%s: Cannot get details of socket: %s", s->name, strerror(errno));
      *name = 0;
    }
  }
}
int socket_get_non_blocking_mode (void)
If the return value is non-zero all newly created sockets will be put in non-blocking mode, otherwise the sockets remain in the system default mode.
Definition at line 100 of file socket.c.
{
  return nonblocking_mode;
}
void socket_get_peer_addr (Socket * s, char * addr, size_t addr_sz)
Get the peer address of an OSocket.
Parameters
s OSocket
addr memory buffer to return the string in (nil-terminated)
namelen length of name, using socket_get_addr_sz() is a good idea
See Also
sockaddr_get_name, getsockname(3), socket_get_addr_sz
Definition at line 628 of file socket.c.
References o_log, O_LOG_WARN, sockaddr_t::sa, and socket_get_addr_sz().
{
  int ret;
  sockaddr_t sa;
  socklen_t sa_len = sizeof(sa);
  SocketInt *self = (SocketInt*)s;
  assert(self);
  assert(self->sockfd>=0);
  assert(addr);
  assert(socket_get_addr_sz(s) <= addr_sz);
  memset(&sa, 0, sa_len);
  if(getpeername(self->sockfd, &sa.sa, &sa_len)) {
    o_log(O_LOG_WARN, "%s: Error getting peer address: %s\n",
        self->name, strerror(errno));
    snprintf(addr, addr_sz, "Unknown peer");
  } else if ((ret=getnameinfo(&sa.sa, sa_len, addr, addr_sz, NULL, 0, NI_NUMERICHOST))) {
    o_log(O_LOG_WARN, "%s: Error converting peer address to name: %s\n",
        self->name, gai_strerror(ret));
    snprintf(addr, addr_sz, "Unknown address (AF%d)", sa.sa.sa_family);
  }
}
uint16_t socket_get_port (Socket * s)
Get the port of socket contained in an OComm Socket object
Parameters
socket OSocket
Returns
the underlying socket descriptor
Definition at line 599 of file socket.c.
{
  assert(s);
  SocketInt *self = (SocketInt*)s;
  return ntohs(self->servAddr.sa_in.sin_port);
}
int socket_get_sockfd (Socket * socket)
Get the socket FD of an OComm Socket object
Parameters
socket OSocket
Returns
the underlying socket descriptor
Definition at line 587 of file socket.c.
{
  SocketInt *self = (SocketInt*)socket;
  return self->sockfd;
}
Socket* socket_in_new (const char * name, const char * node, const char * service, int is_tcp)
Create OSocket objects bound to name and service.
This function binds the newly-created socket, but doesn't listen on it just yet. If name resolves to more than one AF, several sockets are created, linked through their `next' field.
Parameters
name name of the object, used for debugging
node address or name to listen on; defaults to all if NULL
service symbolic name or port number of the service to bind to
is_tcp true if TCP, false for UDP XXX: This should be more generic
Returns
a pointer to a linked list of SocketInt objects, cast as Socket
See Also
getaddrinfo(3)
Definition at line 199 of file socket.c.
References o_log, O_LOG_DEBUG, O_LOG_ERROR, O_LOG_WARN, oml_free(), oml_realloc(), sockaddr_get_name(), socket_free(), socket_new(), and SOCKNAMELEN.
Referenced by socket_server_new().
{
  SocketInt *self = NULL, *list = NULL;
  char nameserv[SOCKNAMELEN], *namestr = NULL;
  size_t namestr_size;
  struct addrinfo hints, *results, *rp;
  int ret;
  *nameserv = 0;
  memset(&hints, 0, sizeof(struct addrinfo));
  hints.ai_socktype = SOCK_STREAM;
  hints.ai_protocol = IPPROTO_TCP; /* FIXME: We should check self->is_tcp */
  hints.ai_flags= AI_PASSIVE;
  int val = 1;
  if((ret=getaddrinfo(node, service, &hints, &results))) {
      o_log(O_LOG_ERROR, "socket(%s): Error resolving %s:%s: %s\n",
          name, node, service, gai_strerror(ret));
      return NULL;
  }
  for (rp = results; rp != NULL; rp = rp->ai_next) {
    sockaddr_get_name((sockaddr_t*)rp->ai_addr, rp->ai_addrlen, nameserv, SOCKNAMELEN);
    namestr_size = strlen(name) + strlen(nameserv + 2);
    namestr = oml_realloc(namestr, namestr_size);
    snprintf(namestr, namestr_size, "%s-%s", name, nameserv);
    o_log(O_LOG_DEBUG, "socket(%s): Binding to %s (AF %d, proto %d)\n",
        name, nameserv, rp->ai_family, rp->ai_protocol);
    if (NULL == (self = (SocketInt*)socket_new(namestr, is_tcp))) {
      o_log(O_LOG_WARN, "socket(%s): Could allocate Socket to listen on %s: %s\n",
          self->name, nameserv, strerror(errno));
    } else if(0 > (self->sockfd =
          socket(rp->ai_family, rp->ai_socktype, rp->ai_protocol))) {
      /* It's OK if some AFs fail, we check that in the end */
      o_log(O_LOG_DEBUG, "socket(%s): Could not create socket to listen on %s: %s\n",
          self->name, nameserv, strerror(errno));
      socket_free((Socket*)self);
    } else if(0 != setsockopt(self->sockfd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(int))){
      o_log(O_LOG_WARN, "socket(%s): Could not set option SO_REUSEADDR on socket to listen on %s: %s\n",
          self->name, nameserv, strerror(errno));
      close(self->sockfd);
      /* XXX: Not optimal: we could reuse the Socket */
      socket_free((Socket*)self);
    } else if (0 != bind(self->sockfd, rp->ai_addr, rp->ai_addrlen)) {
      o_log(O_LOG_WARN, "socket(%s): Error binding socket to listen on %s: %s\n",
          self->name, nameserv, strerror(errno));
      close(self->sockfd);
      /* XXX: Not optimal: we could reuse the Socket */
      socket_free((Socket*)self);
    } else {
      /* The last connected AFs (hence less important according to GAI) are
       * now at the front, but it's not a big deal as we treat them all
       * equally (i.e, we're going to listen on them all */
      self->next = (Socket*)list;
      list = self;
      self = NULL;
    }
  }
  if (namestr) { oml_free(namestr); }
  freeaddrinfo(results);
  if (NULL == list) {
    o_log(O_LOG_ERROR, "socket(%s): Could not create any socket to listen on port %s\n",
        name, service);
  }
  return (Socket*)list;
}
int socket_is_disconnected (Socket * socket)
Get information about the connected state of a Socket
Parameters
socket Socket to examine
Returns
0 if the socket is connected, non-zero otherwise
Definition at line 110 of file socket.c.
{
  return ((SocketInt*)socket)->is_disconnected;
}
int socket_is_listening (Socket * socket)
Get information about the listening state of a Socket
Parameters
socket Socket to examine
Returns
0 if the socket is listening, non-zero otherwise
Definition at line 120 of file socket.c.
{
  return (NULL != ((SocketInt*)socket)->connect_callback);
}
Socket* socket_new (const char * name, int is_tcp)
Create an unbound Socket object.
Parameters
name name of the object, used for debugging
is_tcp true if TCP, false for UDP XXX: This should be more generic
Returns
a pointer to the SocketInt object, cast as a Socket, with a newly opened system socket
See Also
socket_free, socket_close
Definition at line 176 of file socket.c.
Referenced by socket_in_new(), and socket_tcp_out_new().
{
  SocketInt* self = socket_initialize(name);
  self->is_tcp = is_tcp; /* XXX: replace is_tcp with a more meaningful variable to contain that */
  self->is_disconnected = 1;
  return (Socket*)self;
}
int socket_sendto (Socket * socket, char * buf, int buf_size)
Send a message through the socket
Parameters
socket Socket to send message through
buf data to send
buf_size amount of data to read from buf
Returns
the amount of data sent
See Also
sendto(3)
Definition at line 528 of file socket.c.
References logwarn(), o_log, O_LOG_DEBUG, O_LOG_ERROR, and O_LOG_WARN.
{
  SocketInt *self = (SocketInt*)socket;
  int sent;
  if (self->is_disconnected) {
    if(!s_connect(self)) {
      return 0;
    }
  } else if((sent = recv(self->sockfd, NULL, 0, MSG_DONTWAIT)) == 0) {
    /* Test that the server kept the other side of the connection alive */
    if (!(sent < 0 && EAGAIN == errno)) {
      /* EAGAIN is the expected case: connection alive but no data,
       * everything else is a problem */
      logwarn("socket(%s): Server appears to have closed the connection\n", self->name);
      self->is_disconnected = 1;
      /* We want higher levels to be aware of this disconnection */
      return 0;
    }
  }
  if ((sent = sendto(self->sockfd, buf, buf_size, MSG_NOSIGNAL,
                    &(self->servAddr.sa),
                    sizeof(self->servAddr.sa_stor))) < 0) {
    if (errno == EPIPE || errno == ECONNRESET) {
      // The other end closed the connection.
      self->is_disconnected = 1;
      o_log(O_LOG_ERROR, "socket(%s): The remote peer closed the connection: %s\n",
            self->name, strerror(errno));
      return 0;
    } else if (errno == ECONNREFUSED) {
      self->is_disconnected = 1;
      o_log(O_LOG_DEBUG, "socket(%s): Connection refused, trying next AI\n",
            self->name);
      self->rp = self->rp->ai_next;
      return 0;
    } else if (errno == EINTR) {
      o_log(O_LOG_WARN, "socket(%s): Sending data interrupted: %s\n",
            self->name, strerror(errno));
      return 0;
    } else {
      o_log(O_LOG_ERROR, "socket(%s): Sending data failed: %s\n",
            self->name, strerror(errno));
    }
    return -1;
  }
  return sent;
}
Socket* socket_server_new (const char * name, const char * node, const char * service, o_so_connect_callback callback, void * handle)
Create listening OSocket objects, and register them with the EventLoop.
If callback is non-NULL, it is registered to the OCOMM eventloop to handle monitor_in events.
Parameters
name name of the object, used for debugging
node address or name to listen on; defaults to all if NULL
service symbolic name or port number of the service to bind to
callback function to call when a client connects
handle pointer to opaque data passed to callback function
Returns
a pointer to a linked list of Socket objects
See Also
socket_in_new
Definition at line 464 of file socket.c.
References SocketInt::connect_callback, SocketInt::connect_handle, eventloop_on_monitor_in_channel(), SocketInt::next, socket_in_new(), SocketInt::sockfd, and TRUE.
Referenced by main().
{
  Socket *socketlist;
  SocketInt *it;
  socketlist = socket_in_new(name, node, service, TRUE);
  for (it=(SocketInt*)socketlist; it; it=(SocketInt*)it->next) {
    listen(it->sockfd, 5);
    it->connect_callback = callback;
    it->connect_handle = handle;
    if (callback) {
      // Wait for a client to connect. Handle that in callback
      eventloop_on_monitor_in_channel((Socket*)it, on_client_connect, NULL, it);
    }
  }
  return socketlist;
}
int socket_set_non_blocking_mode (int flag)
Set a global flag which, when set true will cause all newly created sockets to be put in non-blocking mode, otherwise the sockets remain in the system default mode.
Parameters
flag non-zero to enable nonblocking_mode
Returns
flag
Definition at line 92 of file socket.c.
Referenced by net_stream_new().
{
  return nonblocking_mode = flag;
}
int socket_shutdown (Socket * socket)
Prevent the remote sender from trasmitting more data.
Parameters
socket Socket object for which to shut communication down
See Also
shutdown(3)
Definition at line 491 of file socket.c.
References Socket::name, o_log, O_LOG_DEBUG, and O_LOG_WARN.
{
  int ret = -1;
  o_log(O_LOG_DEBUG, "socket(%s): Shutting down for R/W\n", socket->name);
  ret = shutdown(((SocketInt *)socket)->sockfd, SHUT_RDWR);
  if(ret) o_log(O_LOG_WARN, "socket(%s): Failed to shut down: %s\n", socket->name, strerror(errno));
  return ret;
}
Socket* socket_tcp_out_new (const char * name, const char * dest, const char * service)
Create a new outgoing TCP Socket.
Parameters
name name of this Socket, for debugging purposes
dest DNS name or address of the destination
service symbolic name or port number of the service to connect to
Returns
a newly-allocated Socket, or NULL on error
Definition at line 371 of file socket.c.
References o_log, O_LOG_ERROR, oml_strndup(), socket_new(), and TRUE.
{
  SocketInt* self;
  if (dest == NULL) {
    o_log(O_LOG_ERROR, "socket(%s): Missing destination\n", name);
    return NULL;
  }
  if ((self = (SocketInt*)socket_new(name, TRUE)) == NULL) {
    return NULL;
  }
  self->dest = oml_strndup(dest, strlen(dest));
  self->service = oml_strndup(service, strlen(service));
  //  eventloop_on_out_channel((Socket*)self, on_self_connected, NULL);
  return (Socket*)self;
}