oml2: socket_group.c File Reference
socket_group.c File Reference
#include <string.h>
#include <stdlib.h>
#include "mem.h"
#include "ocomm/o_socket.h"
#include "ocomm/o_socket_group.h"
#include "ocomm/o_log.h"
Data Structures
struct _sockHolder
struct _socketGroup
Data-structure, to store object state.
Typedefs
typedef struct _sockHolder SocketHolder
typedef struct _socketGroup SocketGroupInt
Data-structure, to store object state.
Functions
void socket_group_add (Socket *this, Socket *socket)
void socket_group_remove (Socket *this, Socket *socket)
Socket * socket_group_new (char *name)
Return a new 'instance' structure.
Typedef Documentation
typedef struct _socketGroup SocketGroupInt
Data-structure, to store object state.
typedef struct _sockHolder SocketHolder
Function Documentation
void socket_group_add (Socket * this, Socket * socket)
Add a socket to the group.
Parameters
socket This object Socket to add
Definition at line 56 of file socket_group.c.
References _sockHolder::next, oml_malloc(), and _sockHolder::socket.
  {
  SocketGroupInt* self = (SocketGroupInt*)this;
  SocketHolder* holder = (SocketHolder *)oml_malloc(sizeof(SocketHolder));
  memset(holder, 0, sizeof(SocketHolder));
  holder->socket = socket;
  holder->next = self->first;
  self->first = holder;
}
Socket* socket_group_new (char * name)
Return a new 'instance' structure.
Create an new socket group.
Parameters
name Name used for debugging
Definition at line 130 of file socket_group.c.
References oml_malloc().
  {
  SocketGroupInt* self = (SocketGroupInt *)oml_malloc(sizeof(SocketGroupInt));
  memset(self, 0, sizeof(SocketGroupInt));
  self->name = self->nameBuf;
  strcpy(self->name, name != NULL ? name : "UNKNOWN");
  self->sendto = sg_sendto;
  self->get_sockfd = sg_get_sockfd;
  return (Socket*)self;
}
void socket_group_remove (Socket * this, Socket * socket)
Remove a socket to the group.
Parameters
socket This object Socket to remove
Definition at line 71 of file socket_group.c.
References _sockHolder::next, oml_free(), and _sockHolder::socket.
  {
  SocketGroupInt* self = (SocketGroupInt*)this;
  SocketHolder* prev = NULL;
  SocketHolder* holder = self->first;
  while (holder != NULL) {
    if (socket ==  holder->socket) {
      // remove holder
      if (prev == NULL) {
    self->first = holder->next;
      } else {
    prev->next = holder->next;
      }
      oml_free(holder);
      return;
    }
    prev = holder;
    holder = holder->next;
  }
}