oml2: sqlite_adapter.c File Reference
sqlite_adapter.c File Reference
Adapter code for the SQLite3 database backend.
#include <stdio.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <sqlite3.h>
#include <time.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include "ocomm/o_log.h"
#include "mem.h"
#include "mstring.h"
#include "htonll.h"
#include "json.h"
#include "guid.h"
#include "oml_value.h"
#include "oml_util.h"
#include "schema.h"
#include "database.h"
#include "table_descr.h"
#include "database_adapter.h"
#include "sqlite_adapter.h"
Functions
MString * database_make_sql_insert (Database *db, DbTable *table)
void sq3_dbdir_setup (void)
int sq3_backend_setup (void)
int sq3_create_database (Database *db)
Variables
char * sqlite_database_dir = NULL
Detailed Description
Adapter code for the SQLite3 database backend.
Definition in file sqlite_adapter.c.
Function Documentation
MString* database_make_sql_insert (Database * db, DbTable * table)
Prepare an INSERT statement for a given table
The returned value is to be destroyed by the caller.
Parameters
db Database
table DbTable adapter for the target SQLite3 table
Returns
an MString containing the prepared statement, or NULL on error
See Also
mstring_create, mstring_delete
Definition at line 502 of file database.c.
References Database::prepare.
{
    return db->prepare(db,table);
}
int sq3_backend_setup (void)
Setup the SQLite3 backend.
Returns
0 on success, -1 otherwise
See Also
database_setup_backend
Definition at line 128 of file sqlite_adapter.c.
References logerror(), loginfo(), sq3_dbdir_setup(), and sqlite_database_dir.
Referenced by database_setup_backend().
{
  sq3_dbdir_setup ();
  /*
   * The man page says access(2) should be avoided because it creates
   * a race condition between calls to access(2) and open(2) where an
   * attacker could swap the underlying file for a link to a file that
   * the unprivileged user does not have permissions to access, which
   * the effective user does.  We don't use the access/open sequence
   * here. We check that we can create files in the
   * sqlite_database_dir directory, and fail if not (as the server
   * won't be able to do useful work otherwise).
   *
   * An attacker could potentially change the underlying file to a
   * link and still cause problems if oml2-server is run as root or
   * setuid root, but this check must happen after drop_privileges()
   * is called, so if oml2-server is not run with superuser privileges
   * such an attack would still fail.
   *
   * oml2-server should not be run as root or setuid root in any case.
   */
  if (access (sqlite_database_dir, R_OK | W_OK | X_OK) == -1) {
    logerror ("sqlite: Can't access SQLite database directory %s: %s\n",
         sqlite_database_dir, strerror (errno));
    return -1;
  }
  loginfo ("sqlite: Creating SQLite3 databases in %s\n", sqlite_database_dir);
  return 0;
}
int sq3_create_database (Database * db)
Create an SQLite3 database and adapter structures
See Also
db_adapter_create
Definition at line 229 of file sqlite_adapter.c.
References Database::add_sender_id, Database::backend_name, dba_begin_transaction(), dba_table_create_meta(), Database::get_metadata, Database::get_table_list, Database::get_uri, Database::handle, Database::insert, logerror(), loginfo(), mstring_buf(), mstring_create(), mstring_delete(), mstring_sprintf(), Database::name, Database::o2t, oml_malloc(), Database::prepare, Database::prepared_var, Database::release, Database::set_metadata, sqlite_database_dir, Database::stmt, Database::t2o, Database::table_create, Database::table_create_meta, and Database::table_free.
{
  sqlite3* conn;
  int rc;
  MString *path = mstring_create ();
  if (mstring_sprintf (path, "%s/%s.sq3", sqlite_database_dir, db->name) == -1) {
    logerror ("sqlite:%s: Failed to construct database path string\n", db->name);
    return -1;
  }
  loginfo ("sqlite:%s: Opening database at '%s'\n",
           db->name, mstring_buf (path));
  rc = sqlite3_open(mstring_buf (path), &conn);
  mstring_delete (path);
  if (rc) {
    logerror("sqlite:%s: Can't open database: %s\n", db->name, sqlite3_errmsg(conn));
    return -1;
  }
  Sq3DB* self = oml_malloc(sizeof(Sq3DB));
  self->conn = conn;
  self->last_commit = time (NULL);
  db->backend_name = backend_name;
  db->o2t = sq3_oml_to_type;
  db->t2o = sq3_type_to_oml;
  db->stmt = sq3_stmt;
  db->table_create = sq3_table_create;
  db->table_create_meta = dba_table_create_meta;
  db->table_free = sq3_table_free;
  db->release = sq3_release;
  db->prepared_var = sq3_prepared_var;
  db->prepare = sq3_prepare;
  db->insert = sq3_insert;
  db->add_sender_id = sq3_add_sender_id;
  db->set_metadata = sq3_set_metadata;
  db->get_metadata = sq3_get_metadata;
  db->get_uri = sq3_get_uri;
  db->get_table_list = sq3_get_table_list;
  db->handle = self;
  dba_begin_transaction (db);
  return 0;
}
void sq3_dbdir_setup (void)
Work out which directory to put sqlite databases in, and set sqlite_database_dir to that directory.
This works as follows: if the user specified –data-dir on the command line, we use that value. Otherwise, if OML_SQLITE_DIR environment variable is set, use that dir. Otherwise, use PKG_LOCAL_STATE_DIR, which is a preprocessor macro set by the build system (under Autotools defaults this should be ${prefix}/var/oml2-server, but on a distro it should be something like /var/lib/oml2-server).
Definition at line 109 of file sqlite_adapter.c.
References oml_strndup(), and sqlite_database_dir.
Referenced by sq3_backend_setup().
{
  if (!sqlite_database_dir) {
    const char *oml_sqlite_dir = getenv ("OML_SQLITE_DIR");
    if (oml_sqlite_dir) {
      sqlite_database_dir = oml_strndup (oml_sqlite_dir, strlen (oml_sqlite_dir));
    } else {
      sqlite_database_dir = PKG_LOCAL_STATE_DIR;
    }
  }
}
Variable Documentation
char* sqlite_database_dir = NULL
Definition at line 40 of file sqlite_adapter.c.
Referenced by binary_protocol_suite(), sq3_backend_setup(), sq3_create_database(), sq3_dbdir_setup(), and text_protocol_suite().