oml2: table_descr.c File Reference
table_descr.c File Reference
Functions for managing table description (TableDescr) structures.
#include <stdlib.h>
#include <string.h>
#include "mem.h"
#include "schema.h"
#include "table_descr.h"
Functions
TableDescr * table_descr_new (const char *name, struct schema *schema)
int table_descr_have_table (TableDescr *tables, const char *table_name)
void table_descr_array_free (TableDescr *tables, int n)
void table_descr_list_free (TableDescr *tables)
Detailed Description
Functions for managing table description (TableDescr) structures.
Definition in file table_descr.c.
Function Documentation
void table_descr_array_free (TableDescr * tables, int n)
Deallocate a TableDescr array
Parameters
tables beginning of the array
n size of the array
Definition at line 76 of file table_descr.c.
References name, oml_free(), and schema_free().
{
  int i = 0;
  for (i = 0; i < n; i++) {
      oml_free (tables[i].name);
      if (tables[i].schema) {
        schema_free (tables[i].schema);
      }
  }
  oml_free(tables);
}
int table_descr_have_table (TableDescr * tables, const char * table_name)
Look for a given table in a list of TableDescr
Parameters
tables the head of the TableDescr list
table_name the name of the table to look for
Returns
1 if found, 0 otherwise
Definition at line 59 of file table_descr.c.
References TableDescr::name, and TableDescr::next.
Referenced by database_init().
{
  while (tables) {
      if (strcmp (tables->name, table_name) == 0) {
        return 1;
      }
      tables = tables->next;
  }
  return 0;
}
void table_descr_list_free (TableDescr * tables)
Deallocate a TableDescr linked list
Also free the encapsulated schema structures.
Parameters
tables head of the list
Definition at line 96 of file table_descr.c.
References TableDescr::name, TableDescr::next, oml_free(), TableDescr::schema, and schema_free().
Referenced by database_init().
{
  TableDescr* t = tables;
  while (t) {
      TableDescr* next = t->next;
      oml_free (t->name);
      if (t->schema) {
        schema_free (t->schema);
      }
      oml_free (t);
      t = next;
  }
}
TableDescr* table_descr_new (const char * name, struct schema * schema)
Create a new table description
The caller should oml_free the returned value when no longer needed. The schema argument is kept verbatim (no copy). XXX: It should be copied internally.
Parameters
name name of the table
schema MP schema of the table
Returns
an oml_malloc'd TableDescr, or NULL on error
See Also
oml_malloc, oml_free
Definition at line 31 of file table_descr.c.
References TableDescr::name, TableDescr::next, oml_free(), oml_malloc(), oml_strndup(), schema, and TableDescr::schema.
{
  if (name == NULL)
    return NULL;
  /* schema == NULL means metadata table */
  char *new_name = oml_strndup (name, strlen (name));
  TableDescr* t = oml_malloc (sizeof(TableDescr));
  if (t == NULL) {
    oml_free (new_name);
    return NULL;
  }
  t->name = new_name;
  t->schema = schema;
  t->next = NULL;
  return t;
}