oml2: testclient.c File Reference
testclient.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include "oml2/omlc.h"
#include "oml_value.h"
Data Structures
struct mp
Macros
#define MAX_WORD 256
#define MAX_SAMPLES 10000
Typedefs
typedef enum mp_input mp_input_t
typedef enum perr perr_t
Enumerations
enum mp_input { MP_INPUT_NONE, MP_INPUT_LINEAR, MP_INPUT_SINE, MP_INPUT_GAUSSIAN }
enum perr {
PERR_NONE, PERR_NO_OPERATOR, PERR_WRONG_OPERATOR, PERR_WORD_TOO_LONG,
PERR_EOF, PERR_BAD_MP_DELIMITER, PERR_SYSTEM
}
Functions
void perr_print (const char *s, const char *p)
const char * input_to_s (enum mp_input input)
mp_input_t input_from_s (const char *s)
void set_value (OmlMPDef *def, OmlValueU *v, int value)
int skip_white (FILE *fp)
int is_token_terminator (int c)
char * read_word (FILE *fp)
OmlMPDef * read_mp_def (FILE *fp, int *mp_length)
struct mp * read_mp (FILE *fp)
int main (int argc, const char **argv)
Variables
perr_t perr = 0
Macro Definition Documentation
#define MAX_SAMPLES 10000
Definition at line 70 of file testclient.c.
Referenced by main().
#define MAX_WORD 256
Definition at line 69 of file testclient.c.
Referenced by input_from_s(), read_mp(), read_mp_def(), read_word(), and set_value().
Typedef Documentation
typedef enum mp_input mp_input_t
typedef enum perr perr_t
Enumeration Type Documentation
enum mp_input
Enumerator:
MP_INPUT_NONE
MP_INPUT_LINEAR
MP_INPUT_SINE
MP_INPUT_GAUSSIAN
Definition at line 72 of file testclient.c.
  {
    MP_INPUT_NONE,
    MP_INPUT_LINEAR,
    MP_INPUT_SINE,
    MP_INPUT_GAUSSIAN
  } mp_input_t;
enum perr
Enumerator:
PERR_NONE
PERR_NO_OPERATOR
PERR_WRONG_OPERATOR
PERR_WORD_TOO_LONG
PERR_EOF
PERR_BAD_MP_DELIMITER
PERR_SYSTEM
Definition at line 90 of file testclient.c.
  {
    PERR_NONE,
    PERR_NO_OPERATOR,
    PERR_WRONG_OPERATOR,
    PERR_WORD_TOO_LONG,
    PERR_EOF,
    PERR_BAD_MP_DELIMITER,
    PERR_SYSTEM
  } perr_t;
Function Documentation
mp_input_t input_from_s (const char * s)
Definition at line 152 of file testclient.c.
References MAX_WORD, MP_INPUT_GAUSSIAN, MP_INPUT_LINEAR, MP_INPUT_NONE, and MP_INPUT_SINE.
Referenced by read_mp().
{
  if (strncmp (s, "linear", MAX_WORD) == 0) return MP_INPUT_LINEAR;
  if (strncmp (s, "sine", MAX_WORD) == 0) return MP_INPUT_SINE;
  if (strncmp (s, "gaussian", MAX_WORD) == 0) return MP_INPUT_GAUSSIAN;
  return MP_INPUT_NONE;
}
const char* input_to_s (enum mp_input input)
Definition at line 139 of file testclient.c.
References MP_INPUT_GAUSSIAN, MP_INPUT_LINEAR, MP_INPUT_NONE, and MP_INPUT_SINE.
{
  switch (input)
    {
    case MP_INPUT_LINEAR: return "none";
    case MP_INPUT_SINE: return "sine";
    case MP_INPUT_GAUSSIAN: return "gaussian";
    case MP_INPUT_NONE: return "none";
    default: return "BAD_INPUT_TYPE";
    }
}
int is_token_terminator (int c)
Definition at line 208 of file testclient.c.
Referenced by read_word().
{
  const char *terminators = "{},:;";
  return isspace (c) || (strchr (terminators, c) != NULL);
}
int main (int argc, const char ** argv)
Definition at line 467 of file testclient.c.
References mp::def, mp::length, MAX_SAMPLES, mp::mp, mp::name, OmlMPDef::name, OML_BLOB_VALUE, OML_STRING_VALUE, oml_type_to_s(), omlc_add_mp(), omlc_init(), omlc_inject(), omlc_reset_blob, omlc_reset_string, omlc_start(), omlc_zero_array, OmlMPDef::param_types, read_mp(), and set_value().
{
  int result;
  struct mp *mp = read_mp (stdin);
  if (mp == NULL) exit (EXIT_FAILURE);
  printf ("MP : %s\n", mp->name);
  printf ("LEN : %d\n", mp->length);
  int i, j;
  for (i = 0; i < mp->length; i++) {
      printf ("-> %s : %s\n", mp->def[i].name, oml_type_to_s (mp->def[i].param_types));
  }
  result = omlc_init ("testclient", &argc, argv, NULL);
  if (result == -1)
    {
      fprintf (stderr, "Failed to initialize OML2 library\n");
      exit (EXIT_FAILURE);
    }
  mp->mp = omlc_add_mp (mp->name, mp->def);
  if (mp->mp == NULL)
    {
      fprintf (stderr, "Failed to add OML2 MP %s\n", mp->name);
      exit (EXIT_FAILURE);
    }
  omlc_start ();
  OmlValueU *v = (OmlValueU*) malloc (mp->length * sizeof (OmlValueU));
  omlc_zero_array(v, mp->length);
  for (i = 0; i < MAX_SAMPLES; i++) {
    for (j = 0; j < mp->length; j++) {
      set_value (&mp->def[j], &v[j], i);
    }
    omlc_inject (mp->mp, v);
  }
  /* Reset storage if needed */
  for (j = 0; j < mp->length; j++) {
    if (mp->def[j].param_types == OML_STRING_VALUE)
      omlc_reset_string(v[j]);
    else if (mp->def[j].param_types == OML_BLOB_VALUE)
      omlc_reset_blob(v[j]);
  }
  free(v);
  return 0;
}
void perr_print (const char * s, const char * p)
Definition at line 104 of file testclient.c.
References PERR_EOF, PERR_NO_OPERATOR, PERR_SYSTEM, PERR_WORD_TOO_LONG, and PERR_WRONG_OPERATOR.
Referenced by read_mp(), and read_mp_def().
{
  char *fmt;
  switch (perr)
    {
    case PERR_WORD_TOO_LONG:
      fmt = "%s:  word is too long\n";
      break;
    case PERR_EOF:
      fmt = "%s:  end of file encountered\n";
      break;
    case PERR_NO_OPERATOR:
      fmt = "%s:  unknown operator encountered\n";
      break;
    case PERR_WRONG_OPERATOR:
      fmt = "%s:  incorrect operator encountered\n";
      break;
    case PERR_SYSTEM:
      fprintf (stderr, "%s:  %s\n", s, strerror (errno));
      return;
    default:
      fmt = "%s:  unknown error occurred\n";
      break;
    }
  fprintf (stderr, fmt, s);
  if (p != NULL)
    {
      fprintf (stderr, "Input token: '%s'\n", p);
    }
  return;
}
struct mp* read_mp (FILE * fp) read
Definition at line 378 of file testclient.c.
References mp::def, mp::input, input_from_s(), mp::length, MAX_WORD, mp, MP_INPUT_NONE, mp::name, name, PERR_NO_OPERATOR, perr_print(), PERR_WRONG_OPERATOR, read_mp_def(), read_word(), and skip_white().
Referenced by main().
{
  char *p = NULL;
  char *op = NULL;
  char name[MAX_WORD];
  OmlMPDef *def = NULL;
  int mp_length = 0;
  mp_input_t mp_input = MP_INPUT_NONE;
  if (skip_white (fp))
    {
      perr_print ("read_mp", NULL);
      return NULL;
    }
  op = read_word (fp);
  if (op == NULL)
    {
      perr = PERR_NO_OPERATOR;
      perr_print ("read_mp", NULL);
      return NULL;
    }
  if (strncmp (op, "mp", MAX_WORD) != 0)
    {
      perr = PERR_WRONG_OPERATOR;
      perr_print ("read_mp", op);
      return NULL;
    }
  if (skip_white (fp))
    {
      perr_print ("read_mp: looking for mp name", NULL);
      return NULL;
    }
  p = read_word (fp);
  if (p == NULL)
    {
      perr_print ("read_mp: name not found", NULL);
      return NULL;
    }
  strncpy (name, p, MAX_WORD);
  def = read_mp_def (fp, &mp_length);
  if (def == NULL)
    {
      perr_print ("read_mp: bad MP definition", NULL);
      return NULL;
    }
  if (skip_white (fp))
    {
      perr_print ("read_mp: input type not found", NULL);
      return NULL;
    }
  p = read_word (fp);
  if (p == NULL)
    {
      perr_print ("read_mp: input function not found", NULL);
      return NULL;
    }
  mp_input = input_from_s (p);
  if (mp_input == MP_INPUT_NONE)
    {
      perr_print ("read_mp", p);
      return NULL;
    }
  struct mp *mp = (struct mp*) malloc (sizeof(struct mp));
  if (mp == NULL) return NULL;
  mp->name = (char*) malloc (strlen (name) + 1);
  strncpy (mp->name, name, strlen (name) + 1);
  mp->def = def;
  mp->length = mp_length;
  mp->input = mp_input;
  return mp;
}
OmlMPDef* read_mp_def (FILE * fp, int * mp_length)
Definition at line 258 of file testclient.c.
References MAX_WORD, OmlMPDef::name, name, oml_type_from_s(), OmlMPDef::param_types, PERR_BAD_MP_DELIMITER, PERR_EOF, PERR_NONE, perr_print(), PERR_SYSTEM, read_word(), OmlMPDef::relations, skip_white(), and type.
Referenced by read_mp().
{
  if (skip_white (fp)) return NULL;
  int c = fgetc (fp);
  if (c == EOF)
    {
      perr = feof (fp) ? PERR_EOF : PERR_SYSTEM;
      return NULL;
    }
  if (c != '{')
    {
      char s[2] = { c, '\0' };
      perr = PERR_BAD_MP_DELIMITER;
      perr_print ("read_mp_def", s);
      return NULL;
    }
  int done = 0;
  int elt_count = 0;
  perr = PERR_NONE;
  struct mpelt
  {
    OmlMPDef def;
    struct mpelt *next;
  } *head = NULL, *elt, *new;
  /* eltname : type, */
  do
    {
      int c;
      char *p;
      char name[MAX_WORD];
      char type[MAX_WORD];
      if (skip_white (fp)) break;
      p = read_word (fp);
      if (p == NULL) break;
      if (*p == '\0')
        {
          /* } or , */
          c = fgetc (fp);
          if (c == '}')
            {
              done = 1;
              continue;
            }
          else if (c == ',') continue;
          else
            {
              char s[2] = { c, '\0' };
              perr = PERR_BAD_MP_DELIMITER;
              perr_print ("read_mp_def: got a strange token", s);
              break;
            }
        }
      strncpy (name, p, MAX_WORD);
      if (skip_white (fp)) break;
      /* : */
      c = fgetc (fp);
      if (c != ':')
        {
          char s[2] = { c, '\0' };
          perr = PERR_BAD_MP_DELIMITER;
          perr_print ("read_mp_def: expecting ':', but got something else", s);
          break;
        }
      if (skip_white (fp)) break;
      p = read_word (fp);
      if (p == NULL) break;
      if (*p == '\0')
        {
          char s[2] = { c, '\0' };
          perr = PERR_BAD_MP_DELIMITER;
          perr_print ("read_mp_def: expecting element type, but got something else", s);
          break;
        }
      strncpy (type, p, MAX_WORD);
      new = (struct mpelt*) malloc (sizeof (struct mpelt));
      if (new == NULL) { perr = PERR_SYSTEM; break; }
      p = (char*) malloc (strlen (name) + 1);
      strncpy (p, name, strlen (name));
      new->def.name = p;
      new->def.param_types = oml_type_from_s (type);
      new->next = head;
      head = new;
      elt_count++;
    }
  while (!done);
  if (perr != PERR_NONE)
    return NULL;
  OmlMPDef *def = (OmlMPDef*) malloc ((elt_count+1) * sizeof (OmlMPDef));
  int i;
  for (elt = head, i = elt_count-1; elt != NULL; elt = elt->next, i--)
    {
      def[i].name = elt->def.name;
      def[i].param_types = elt->def.param_types;
      def[i].relations = NULL;
    }
  def[elt_count].name = NULL;
  def[elt_count].param_types = 0;
  def[elt_count].relations = NULL;
  *mp_length = elt_count;
  return def;
}
char* read_word (FILE * fp)
Definition at line 215 of file testclient.c.
References is_token_terminator(), MAX_WORD, PERR_EOF, PERR_SYSTEM, and PERR_WORD_TOO_LONG.
Referenced by read_mp(), and read_mp_def().
{
  int c = -1;
  static char buf[MAX_WORD];
  char *p = buf;
  do
    {
      c = fgetc (fp);
      if (c != EOF && !is_token_terminator (c))
        *p++ = c;
    }
  while (c != EOF && !is_token_terminator (c) && (p - buf) < MAX_WORD - 1);
  if (is_token_terminator (c))
    {
      *p = '\0';
      if (!isspace (c))
        ungetc (c, fp);
      return buf;
    }
  else
    {
      if (c == EOF)
        {
          if (feof (fp))
            perr = PERR_EOF;
          else
            perr = PERR_SYSTEM;
          return NULL;
        }
      else
        {
          perr = PERR_WORD_TOO_LONG;
          return NULL;
        }
    }
}
void set_value (OmlMPDef * def, OmlValueU * v, int value)
Definition at line 161 of file testclient.c.
References MAX_WORD, OML_BLOB_VALUE, OML_DOUBLE_VALUE, OML_INT32_VALUE, OML_INT64_VALUE, OML_LONG_VALUE, OML_STRING_VALUE, OML_UINT32_VALUE, OML_UINT64_VALUE, omlc_set_blob, omlc_set_double, omlc_set_int32, omlc_set_int64, omlc_set_long, omlc_set_string_copy, omlc_set_uint32, omlc_set_uint64, OmlMPDef::param_types, and str.
Referenced by main().
{
  char str[MAX_WORD];
  switch (def->param_types)
    {
    case OML_LONG_VALUE:    omlc_set_long(*v,   value); break;
    case OML_INT32_VALUE:   omlc_set_int32(*v,  value); break;
    case OML_UINT32_VALUE:  omlc_set_uint32(*v, value); break;
    case OML_INT64_VALUE:   omlc_set_int64(*v,  value); break;
    case OML_UINT64_VALUE:  omlc_set_uint64(*v, value); break;
    case OML_DOUBLE_VALUE:  omlc_set_double(*v, value); break;
    case OML_STRING_VALUE:
                            snprintf (str, MAX_WORD, "%d", value);
                            omlc_set_string_copy(*v, str, strlen(str));
                            break;
    case OML_BLOB_VALUE:
                            snprintf (str, MAX_WORD, "%d", value);
                            omlc_set_blob(*v, str, strlen(str));
                            break;
    default: omlc_set_long(*v, -1); break;
    }
}
int skip_white (FILE * fp)
Definition at line 186 of file testclient.c.
References PERR_SYSTEM.
{
  int c = -1;
  do
    {
      c = fgetc (fp);
    }
  while (c != EOF && isspace (c));
  if (c == EOF)
    {
      perr = PERR_SYSTEM;
      return -1;
    }
  else
    {
      ungetc (c, fp);
      return 0;
    }
}
Variable Documentation
perr_t perr = 0
Definition at line 101 of file testclient.c.