oml2: text_writer.c File Reference
text_writer.c File Reference
An implementation of the OmlWriter interface functions (see oml2/oml_writer.h) that serializes measurement tuples using the OML text protocol OMSP Text Protocol.
#include <assert.h>
#include <float.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "oml2/omlc.h"
#include "oml2/oml_filter.h"
#include "oml2/oml_writer.h"
#include "ocomm/o_log.h"
#include "oml_value.h"
#include "client.h"
#include "buffered_writer.h"
#include "string_utils.h"
#include "base64.h"
Data Structures
struct OmlTextWriter
Typedefs
typedef struct OmlTextWriter OmlTextWriter
Functions
OmlWriter * text_writer_new (OmlOutStream *out_stream)
Detailed Description
An implementation of the OmlWriter interface functions (see oml2/oml_writer.h) that serializes measurement tuples using the OML text protocol OMSP Text Protocol.
Tests behaviour and issues related to the text protocol.
Definition in file text_writer.c.
Typedef Documentation
typedef struct OmlTextWriter OmlTextWriter
Function Documentation
OmlWriter* text_writer_new (OmlOutStream * out_stream)
Create a new OmlTextWriter
Parameters
out_stream OmlOutStream into which the data should be written
Returns
a pointer to the new OmlTextWriter cast as an OmlWriter
See Also
BufferedWriter
Definition at line 83 of file text_writer.c.
References bw_create(), OmlClient::max_queue, oml_malloc(), and omlc_instance.
Referenced by create_writer().
{
  assert(out_stream != NULL);
  OmlTextWriter* self = (OmlTextWriter *)oml_malloc(sizeof(OmlTextWriter));
  memset(self, 0, sizeof(OmlTextWriter));
  self->bufferedWriter = bw_create(out_stream, omlc_instance->max_queue, 0);
  self->out_stream = out_stream;
  self->meta = owt_meta;
  self->header_done = owt_header_done;
  self->row_start = owt_row_start;
  self->row_end = owt_row_end;
  self->out = owt_row_cols;
  self->close = owt_close;
  return (OmlWriter*)self;
}