oml2: text.c File Reference
text.c File Reference
Text mode OMSP (OML Measurement Stream Protocol (OMSP) OMSP Text Protocol) serialisation of OML tuples.
#include "mbuf.h"
#include "marshal.h"
#include "oml_value.h"
#include "schema.h"
#include "message.h"
Functions
int text_read_msg_start (struct oml_message *msg, MBuffer *mbuf)
int text_read_msg_values (struct oml_message *msg, MBuffer *mbuf, struct schema *schema, OmlValue *values)
Read a vector of values matching schema from mbuf.
Detailed Description
Text mode OMSP (OML Measurement Stream Protocol (OMSP) OMSP Text Protocol) serialisation of OML tuples.
Definition in file text.c.
Function Documentation
int text_read_msg_start (struct oml_message * msg, MBuffer * mbuf)
Definition at line 142 of file text.c.
References oml_message::length, mbuf_find(), OML_DOUBLE_VALUE, OML_UINT32_VALUE, oml_value_get_value, oml_value_init(), oml_value_reset(), oml_value_set_type(), omlc_get_double, omlc_get_uint32, oml_message::seqno, oml_message::stream, and oml_message::timestamp.
Referenced by proxy_message_loop(), and START_TEST().
{
  int len = mbuf_find (mbuf, '\n'); // Find length of line
  OmlValue value;
  int bytes = 0;
  oml_value_init(&value);
  if (len == -1)
    return 0; // Haven't got a full line
  msg->length = (uint32_t)len + 1;
  /* Read the timestamp first */
  oml_value_set_type(&value, OML_DOUBLE_VALUE);
  bytes = text_read_value (mbuf, &value, len);
  if (bytes == -1)
    return -1;
  else
    len -= bytes;
  msg->timestamp = omlc_get_double(*oml_value_get_value(&value));
  /* Read the stream index */
  oml_value_set_type(&value, OML_UINT32_VALUE);
  bytes = text_read_value (mbuf, &value, len);
  if (bytes == -1)
    return -1;
  else
    len -= bytes;
  msg->stream = omlc_get_uint32(*oml_value_get_value(&value));
  /* Read the sequence number */
  oml_value_set_type(&value, OML_UINT32_VALUE);
  bytes = text_read_value (mbuf, &value, len);
  if (bytes == -1)
    return -1;
  else
    len -= bytes;
  msg->seqno = omlc_get_uint32(*oml_value_get_value(&value));
  oml_value_reset(&value);
  return msg->length;
}
int text_read_msg_values (struct oml_message * msg, MBuffer * mbuf, struct schema * schema, OmlValue * values)
Read a vector of values matching schema from mbuf.
Reads as many values as required to match the schema from the mbuf, and stores them in the values vector.
Definition at line 198 of file text.c.
References oml_message::count, schema::fields, oml_message::length, mp::length, mbuf_consume_message(), mbuf_message_index(), schema::nfields, oml_value_set_type(), and schema_field::type.
Referenced by START_TEST().
{
  int length = msg->length;
  int index = mbuf_message_index (mbuf);
  int msg_remaining = length - index;
  int i = 0;
  length = msg_remaining;
  for (i = 0; i < schema->nfields; i++) {
    int bytes;
    oml_value_set_type(&values[i], schema->fields[i].type);
    bytes = text_read_value (mbuf, &values[i], length);
    if (bytes == -1)
      return -1;
    else
      length -= bytes;
  }
  msg->count = schema->nfields;
  // rdptr now points to start of next line/message
  mbuf_consume_message (mbuf);
  return 0;
}