oml2: validate.c File Reference
validate.c File Reference
Implements the validation of OML identifiers.
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include "validate.h"
Functions
int validate_name (const char *name)
Detailed Description
Implements the validation of OML identifiers.
Definition in file validate.c.
Function Documentation
int validate_name (const char * name)
Validate the name of an OML identifier (schema name, schema column, measurement point, application.)
The only valid characters for the name of an identifier are letters [A-Za-z], numbers, and the underscore character. The first character must not be a digit.
Parameters
name the name to validate.
Returns
If the name is valid, returns 1, otherwise returns 0.
Definition at line 36 of file validate.c.
References name.
Referenced by omlc_add_mp(), omlc_inject_metadata(), START_TEST(), and validate_app_name().
{
  size_t len = strlen (name);
  const char* p = name;
  if (!p || *p == '\0' || isdigit (*p))
    return 0;
  do {
    if (!valid_name_char (*p))
      return 0;
  } while ((size_t)(++p - name) < len);
  return 1;
}