oml2: virtuoso_adapter.c File Reference
virtuoso_adapter.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include <string.h>
#include <inttypes.h>
#include <time.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include <curl/curl.h>
#include <oml2/omlc.h>
#include <oml2/oml_filter.h>
#include <oml2/oml_writer.h>
#include "ocomm/o_log.h"
#include "mem.h"
#include "mstring.h"
#include "htonll.h"
#include "json.h"
#include "guid.h"
#include "oml_value.h"
#include "oml_util.h"
#include "schema.h"
#include "database.h"
#include "table_descr.h"
#include "database_adapter.h"
#include "virtuoso_adapter.h"
Macros
#define HEADER_INSERT "prefix afn: <http://jena.hpl.hp.com/ARQ/function#> \ prefix fn: <http://www.w3.org/2005/xpath-functions#> \ prefix owl: <http://www.w3.org/2002/07/owl#> \ prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> \ prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> \ prefix time: <http://www.w3.org/2006/time#> \ prefix xsd: <http://www.w3.org/2001/XMLSchema#> \ prefix MD: <http://www.etsi.org/isg/moi/data.owl#> \ prefix MM: <http://www.etsi.org/isg/moi/Metadata.owl#> \ prefix MGC: <http://www.etsi.org/isg/moi/GeneralConcepts.owl#> \ prefix MU: <http://www.etsi.org/isg/moi/Units.owl#>"
#define MAXLINE 4096
#define MAXSUB 2000
#define REPLACE_SEQ "#?#value_seq#?#"
#define REPLACE_TS "#?#value_ts#?#"
#define REPLACE_TC "#?#value_tc#?#"
Functions
char * str_replace (const char *string, const char *substr, const char *replacement)
int virtuoso_backend_setup (void)
size_t logwrite_vir (char *ptr, size_t size, size_t nmemb, void *userdata)
int virtuoso_create_database (Database *db)
Variables
char * vir_host = DEFAULT_VIR_HOST
char * vir_port = DEFAULT_VIR_PORT
char * vir_user = DEFAULT_VIR_USER
char * vir_pass = DEFAULT_VIR_PASS
Macro Definition Documentation
#define HEADER_INSERT "prefix afn: <http://jena.hpl.hp.com/ARQ/function#> \ prefix fn: <http://www.w3.org/2005/xpath-functions#> \ prefix owl: <http://www.w3.org/2002/07/owl#> \ prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> \ prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> \ prefix time: <http://www.w3.org/2006/time#> \ prefix xsd: <http://www.w3.org/2001/XMLSchema#> \ prefix MD: <http://www.etsi.org/isg/moi/data.owl#> \ prefix MM: <http://www.etsi.org/isg/moi/Metadata.owl#> \ prefix MGC: <http://www.etsi.org/isg/moi/GeneralConcepts.owl#> \ prefix MU: <http://www.etsi.org/isg/moi/Units.owl#>"
Definition at line 63 of file virtuoso_adapter.c.
#define MAXLINE 4096
Definition at line 110 of file virtuoso_adapter.c.
#define MAXSUB 2000
Definition at line 111 of file virtuoso_adapter.c.
#define REPLACE_SEQ "#?#value_seq#?#"
Definition at line 113 of file virtuoso_adapter.c.
#define REPLACE_TC "#?#value_tc#?#"
Definition at line 117 of file virtuoso_adapter.c.
#define REPLACE_TS "#?#value_ts#?#"
Definition at line 115 of file virtuoso_adapter.c.
Function Documentation
size_t logwrite_vir (char * ptr, size_t size, size_t nmemb, void * userdata)
Definition at line 129 of file virtuoso_adapter.c.
Referenced by virtuoso_create_database().
{
   return size * nmemb;
}
char* str_replace (const char * string, const char * substr, const char * replacement)
int virtuoso_backend_setup (void)
This function generates a new socket that connects with virtuoso backend and send some data
Returns
int - 0 (OK) -1 (KO)
Definition at line 123 of file virtuoso_adapter.c.
Referenced by database_setup_backend().
{
    return 0;
}
int virtuoso_create_database (Database * db)
Create an SQLite3 database and adapter structures
See Also
db_adapter_create
Definition at line 140 of file virtuoso_adapter.c.
References Database::add_sender_id, Database::backend_name, dba_begin_transaction(), dba_table_create_meta(), Database::get_metadata, Database::get_table_list, Database::get_uri, Database::handle, Database::insert, logwrite_vir(), mstring_buf(), mstring_create(), mstring_delete(), mstring_sprintf(), Database::o2t, oml_malloc(), Database::prepare, Database::prepared_var, Database::release, Database::semantic, Database::set_metadata, Database::stmt, Database::t2o, Database::table_create, Database::table_create_meta, Database::table_free, vir_host, vir_pass, vir_port, and vir_user.
{
  MString* mstr = mstring_create ();
  MString* userpw = mstring_create ();
  CURL *curl;
  curl_global_init(CURL_GLOBAL_ALL);
  if (!(curl = curl_easy_init())) return -1;
  mstring_sprintf(mstr,"http://%s:%s/sparql/",vir_host, vir_port);
  mstring_sprintf(userpw,"%s:%s",vir_user,vir_pass);
  curl_easy_setopt(curl, CURLOPT_URL, mstring_buf(mstr));
  curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, &logwrite_vir);
  curl_easy_setopt(curl, CURLOPT_USERPWD, mstring_buf(userpw));
  mstring_delete (mstr);
  mstring_delete (userpw);
  VirDB* self = oml_malloc(sizeof(VirDB));
  self->conn = curl;//conn;
  self->last_commit = time (NULL);
  db->semantic = 1;
  db->backend_name = backend_name;
  db->o2t = sem_oml_to_type;
  db->t2o = sem_type_to_oml;
  db->stmt = sem_stmt;
  db->table_create = sem_table_create;
  db->table_create_meta = dba_table_create_meta;
  db->table_free = sem_table_free;
  db->release = sem_release;
  db->prepared_var = sem_prepared_var;
  db->prepare = sem_prepare;
  db->insert = sem_insert;
  db->add_sender_id = sem_add_sender_id;
  db->set_metadata = sem_set_metadata;
  db->get_metadata = sem_get_metadata;
  db->get_uri = sem_get_uri;
  db->get_table_list = sem_get_table_list;
  db->handle = self;
  dba_begin_transaction (db);
  return 0;
}
Variable Documentation
char* vir_host = DEFAULT_VIR_HOST
Definition at line 104 of file virtuoso_adapter.c.
Referenced by main(), and virtuoso_create_database().
char* vir_pass = DEFAULT_VIR_PASS
Definition at line 107 of file virtuoso_adapter.c.
Referenced by main(), and virtuoso_create_database().
char* vir_port = DEFAULT_VIR_PORT
Definition at line 105 of file virtuoso_adapter.c.
Referenced by main(), and virtuoso_create_database().
char* vir_user = DEFAULT_VIR_USER
Definition at line 106 of file virtuoso_adapter.c.
Referenced by main(), and virtuoso_create_database().