'\" t
.\"     Title: omlc_close
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 2015-04-16
.\"    Manual: The OML Manual
.\"    Source: OML 2.12.0pre.79-58cf-dirty
.\"  Language: English
.\"
.TH "OMLC_CLOSE" "3" "2015\-04\-16" "OML 2\&.12\&.0pre\&.79\-58cf\-" "The OML Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
omlc_close \- shutdown the OML client library
.SH "SYNOPSIS"
.sp
.nf
\fB#include <oml2/omlc\&.h>\fR
.fi
.sp
.nf
\fIint\fR \fBomlc_close\fR(\fIvoid\fR);
.fi
.SH "DESCRIPTION"
.sp
\fBomlc_close\fR() shuts down the OML client library, and stops all measurement processes\&. It also flushes all measurement streams to try to ensure that all measurements are stored correctly before the application terminates\&. The application should call \fBomlc_close\fR() if it intends to exit\&.
.sp
If \fBomlc_inject\fR(3) is called after \fBomlc_close\fR() has been called, then it will be ignored and not measurement collection will take place\&. Other API functions will return with an error\&.
.SH "RETURN VALUE"
.sp
\fBomlc_close\fR() returns 0 on success; on error it returns \-1\&.
.SH "ERRORS"
.sp
\fBomlc_close\fR() will succeed unless the API has not already been initialized by a call to \fBomlc_init\fR(3)\&.
.SH "BUGS"
.sp
If a problem you are experiencing is not addressed in the FAQ (http://oml\&.mytestbed\&.net/projects/oml/wiki/FAQ_and_Support) nor already present in the list of know bugs (http://oml\&.mytestbed\&.net/projects/oml/issues)\&. You could discuss it on the mailing list (details and archives at http://oml\&.mytestbed\&.net/tab/show?id=oml)\&.
.sp
It is however advisable to open a ticket on our issue tracker at http://oml\&.mytestbed\&.net/projects/oml/issues/new\&. Don\(cqt forget to include details such as client and server logs (at \fI[\-\-oml\-log\-level|\-d] 2\fR)\&. It also helps if you can share the source code of a (minimal, if possible) example reliably triggering the problem\&.
.SH "SEE ALSO"
.SS "Manual Pages"
.sp
\fBoml2-server\fR(1), \fBliboml2\fR(1), \fBliboml2\fR(3), \fBliboml2.conf\fR(5)
.sp
\fBomlc_init\fR(3), \fBomlc_add_mp\fR(3), \fBomlc_start\fR(3), \fBomlc_inject\fR(3)
.SS "OML User Manual"
.sp
http://oml\&.mytestbed\&.net/projects/oml/wiki/Documentation
