'\" t
.\"     Title: omlc_start
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 2015-04-16
.\"    Manual: The OML Manual
.\"    Source: OML 2.12.0pre.79-58cf-dirty
.\"  Language: English
.\"
.TH "OMLC_START" "3" "2015\-04\-16" "OML 2\&.12\&.0pre\&.79\-58cf\-" "The OML Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
omlc_start \- start measurement outputs
.SH "SYNOPSIS"
.sp
.nf
\fB#include <oml2/omlc\&.h>\fR
.fi
.sp
.nf
\fIint\fR \fBomlc_start\fR(\fIvoid\fR);
.fi
.SH "DESCRIPTION"
.sp
\fBomlc_start\fR() begins the process of measurement sampling and output\&. It must be called after any \fImeasurement points\fR (MPs) have been registered with \fBliboml2\fR using \fBomlc_add_mp\fR(3)\&. Once \fBomlc_start\fR() has been called, it is valid to call \fBomlc_inject\fR(3) to start making measurements, but it is no longer possible to call \fBomlc_add_mp\fR(3)\&.
.sp
The main function of \fBomlc_start\fR() is to set up the internal data structures that determine the filtering configuration\&. It also starts threads to periodically generate filter outputs for measurement streams that are declared using the \fIinterval\fR sampling method (see the \fB\-\-oml\-interval\fR option in \fBliboml2\fR(1) or the \fIinterval\fR attribute in \fBliboml2.conf\fR(5))\&.
.sp
If a configuration file is given using the \fB\-\-oml\-config\fR command line option or the OML_CONFIG environment variable, then \fBomlc_start\fR() reads the configuration file to determine what filters to create\&. Otherwise it creates a set of default filters as follows:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
For each field of each MP, a separate filter is created;
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
If the type of the field is a numeric type, then the filter will be the
\fIavg\fR
averaging filter, unless the
\fIsamples\fR
method is specified and the number of samples per filter output is set to 1, in which case the
\fIfirst\fR
filter is used\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
If the type of the field is not a numeric type, then the
\fIfirst\fR
filter is used\&.
.RE
.sp
For more details on how filter configuration is done, see \fBliboml2\fR(1) and \fBliboml2.conf\fR(5)\&.
.sp
Once \fBomlc_start\fR() has finished establishing the filter configuration, it writes headers to the configured output destinations (local files and/or \fBoml2-server\fR(1) daemons)\&.
.SH "RETURN VALUE"
.sp
\fBomlc_start\fR() returns 0 on success; on error, a negative value is returned\&.
.SH "ERRORS"
.sp
\fBomlc_start\fR() will return < 0 if:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBliboml2\fR
has not yet been initialized via a call to
\fBomlc_init\fR(3);
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
an error occurred parsing the external config file;
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
no config file was given and no output destination was specified on either the command line or using an environment variable (e\&.g\&., no
\fB\-\-oml\-collect\fR
command line option);
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
there was an error in the specification of the output destination;
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
there was an error writing to the output destination stream(s)\&.
.RE
.sp
The last condition can occur during a call to \fBomlc_start\fR() because the function writes the metadata for the current configuration to all of the currently configured output streams, either local files or \fBoml2-server\fR(1) daemons\&.
.SH "BUGS"
.sp
If a problem you are experiencing is not addressed in the FAQ (http://oml\&.mytestbed\&.net/projects/oml/wiki/FAQ_and_Support) nor already present in the list of know bugs (http://oml\&.mytestbed\&.net/projects/oml/issues)\&. You could discuss it on the mailing list (details and archives at http://oml\&.mytestbed\&.net/tab/show?id=oml)\&.
.sp
It is however advisable to open a ticket on our issue tracker at http://oml\&.mytestbed\&.net/projects/oml/issues/new\&. Don\(cqt forget to include details such as client and server logs (at \fI[\-\-oml\-log\-level|\-d] 2\fR)\&. It also helps if you can share the source code of a (minimal, if possible) example reliably triggering the problem\&.
.SH "SEE ALSO"
.SS "Manual Pages"
.sp
\fBoml2-server\fR(1), \fBliboml2\fR(1), \fBliboml2\fR(3), \fBliboml2.conf\fR(5)
.sp
\fBomlc_init\fR(3), \fBomlc_add_mp\fR(3), \fBomlc_inject\fR(3)
.SS "OML User Manual"
.sp
http://oml\&.mytestbed\&.net/projects/oml/wiki/Documentation
